import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Paris Airport Transfer - CDG, Orly & Beauvais',
    subtitle: 'Professional private driver service from all Paris airports to city center, hotels and any destination',
    description: 'Book your reliable Paris airport transfer with professional English-speaking drivers. We provide premium transportation from Charles de Gaulle (CDG), Orly and Beauvais airports to anywhere in Paris and surrounding areas. Fixed prices, flight monitoring, meet and greet service with personalized name sign at arrivals. Whether you arrive at Terminal 1, 2 or 3 at CDG, any Orly terminal, or Beauvais, your driver is waiting.',
    description2: 'Paris welcomes over 100 million visitors per year across its three airports. Skip the long taxi queues, confusing RER trains, and overpriced meters. Our professional chauffeurs monitor your flight in real-time and meet you directly at the arrivals hall. Door-to-door service in premium Mercedes and BMW vehicles, with complimentary 60 minutes waiting time for any flight delays.',
    whyChoose: 'Why Choose Our Paris Airport Transfer?',
    feature1Title: 'Meet & Greet Service', feature1Desc: 'Driver waits at arrivals with personalized name sign. Free 60 minutes waiting time for delays.',
    feature2Title: 'Flight Monitoring', feature2Desc: 'We track your flight in real-time at CDG, Orly and Beauvais. No extra charge for delays.',
    feature3Title: 'Premium Vehicles', feature3Desc: 'Mercedes E-Class, BMW 5 Series. Clean, air-conditioned, less than 3 years old.',
    feature4Title: 'Fixed Prices', feature4Desc: 'Price confirmed at booking. No hidden fees, tolls included. No surge pricing.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class or BMW 7 Series',
    minivan: 'Minivan', minivanDesc: 'Mercedes V-Class, up to 6 passengers', minibus: 'Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter your flight details and Paris destination. Instant price confirmation.',
    step2: 'Meet Your Driver', step2Desc: 'Driver waits at arrivals hall with personalized sign with your name.',
    step3: 'Relax & Enjoy', step3Desc: 'Sit back in a clean, air-conditioned vehicle. Direct transfer to your destination.',
    popularRoutesTitle: 'Popular Paris Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'CDG Airport \u2192 Paris City Center', price: 65 },
      { name: 'CDG Airport \u2192 Disneyland Paris', price: 75 },
      { name: 'Orly Airport \u2192 Paris City Center', price: 45 },
      { name: 'Beauvais Airport \u2192 Paris City Center', price: 120 },
    ],
    bookingForm: 'Book Your Paris Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Paris CDG Airport',
    otherCitiesTitle: 'We serve 120+ cities across Europe', otherCitiesBtn: 'View All Destinations',
    rating: '4.9/5 (4,500+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Paris - CDG, Orly et Beauvais',
    subtitle: 'Service de chauffeur prive professionnel depuis tous les aeroports parisiens vers le centre-ville, hotels et toute destination',
    description: 'Reservez votre transfert aeroport Paris fiable avec des chauffeurs professionnels francophones. Nous proposons un transport premium depuis Charles de Gaulle (CDG), Orly et Beauvais vers Paris centre et tous les hotels. Prix fixes, suivi des vols en temps reel, service d\'accueil personnalise avec pancarte nominative aux arrivees. Que vous arriviez au Terminal 1, 2 ou 3 de CDG, a n\'importe quel terminal d\'Orly, ou a Beauvais, votre chauffeur vous attend.',
    description2: 'Paris accueille plus de 100 millions de visiteurs par an a travers ses trois aeroports. Evitez les longues files de taxis, les RER bondes et les compteurs excessifs. Nos chauffeurs professionnels suivent votre vol en temps reel et vous accueillent directement au hall des arrivees. Service porte-a-porte en Mercedes et BMW premium, avec 60 minutes d\'attente gratuites.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Paris ?',
    feature1Title: 'Accueil Personnalise', feature1Desc: 'Chauffeur aux arrivees avec pancarte a votre nom. 60 minutes d\'attente gratuites.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Suivi en temps reel a CDG, Orly et Beauvais. Aucun supplement pour retard.',
    feature3Title: 'Vehicules Premium', feature3Desc: 'Mercedes Classe E, BMW Serie 5. Propres, climatises, moins de 3 ans.',
    feature4Title: 'Prix Fixes Garantis', feature4Desc: 'Prix confirme a la reservation. Pas de frais caches, peages inclus.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E, 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S ou BMW Serie 7',
    minivan: 'Monospace', minivanDesc: 'Mercedes Classe V, jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Pour groupes jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez les details de votre vol et destination. Confirmation du prix immediate.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Le chauffeur vous attend aux arrivees avec pancarte a votre nom.',
    step3: 'Detendez-vous', step3Desc: 'Installez-vous dans un vehicule propre et climatise. Transfert direct.',
    popularRoutesTitle: 'Trajets Populaires Transfert Aeroport Paris', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport CDG \u2192 Centre de Paris', price: 65 },
      { name: 'Aeroport CDG \u2192 Disneyland Paris', price: 75 },
      { name: 'Aeroport Orly \u2192 Centre de Paris', price: 45 },
      { name: 'Aeroport Beauvais \u2192 Centre de Paris', price: 120 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Paris',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Paris CDG',
    otherCitiesTitle: 'Nous desservons plus de 120 villes en Europe', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.9/5 (4 500+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Парижа - CDG, Орли и Бове',
    subtitle: 'Профессиональный частный водитель из всех аэропортов Парижа в центр города, отели и любые направления',
    description: 'Забронируйте трансфер из аэропорта Парижа с профессиональными русскоговорящими водителями. Премиум-транспорт из Шарль де Голль (CDG), Орли и Бове в любую точку Парижа. Фиксированные цены, отслеживание рейсов, встреча с именной табличкой.',
    description2: 'Париж принимает более 100 миллионов гостей через три аэропорта. Пропустите очереди на такси и переполненные RER. Наши водители отслеживают ваш рейс и встречают в зале прилета.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Парижа?',
    feature1Title: 'Встреча с Табличкой', feature1Desc: 'Водитель ждет с именной табличкой. 60 минут бесплатного ожидания.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мониторинг в реальном времени CDG, Орли и Бове. Без доплаты.',
    feature3Title: 'Премиум Автомобили', feature3Desc: 'Mercedes E-Class, BMW 5 серии. Чистые, с кондиционером.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Цена при бронировании. Без скрытых платежей.',
    sedan: 'Премиум Седан', sedanDesc: 'Mercedes E-Class, 1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes S-Class или BMW 7',
    minivan: 'Минивэн', minivanDesc: 'Mercedes V-Class, до 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Введите данные рейса и адрес назначения.',
    step2: 'Встретьте Водителя', step2Desc: 'Водитель ждет в зале прилета с табличкой.',
    step3: 'Расслабьтесь', step3Desc: 'Комфортная поездка в премиум автомобиле.',
    popularRoutesTitle: 'Популярные Маршруты из Аэропорта Парижа', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт CDG \u2192 Центр Парижа', price: 65 },
      { name: 'Аэропорт CDG \u2192 Диснейленд Париж', price: 75 },
      { name: 'Аэропорт Орли \u2192 Центр Парижа', price: 45 },
      { name: 'Аэропорт Бове \u2192 Центр Парижа', price: 120 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Парижа',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Париж CDG',
    otherCitiesTitle: 'Мы обслуживаем 120+ городов Европы', otherCitiesBtn: 'Все Направления',
    rating: '4.9/5 (4 500+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 65, luxury: 95, minivan: 130, minibus: 190 };

const ParisAirportTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} />;
export default ParisAirportTransfer;
