import B2BPage from '@/components/B2BPage';

const content = {
  en: {
    seoTitle: 'Business Transport Partnership Opportunities | Zont B2B',
    seoDesc: 'Strategic transport partnerships with Zont. Referral programs, white-label solutions, recurring collaborations. Grow together with a premium European transfer network.',
    badge: 'Strategic Business Partnership',
    heroTitle: 'Business Transport Partnership Opportunities',
    heroSub: 'Beyond a simple supplier relationship — Zont offers strategic transport partnerships designed for long-term growth. From referral programs to white-label solutions, we build collaborations that create mutual value across the European market.',
    ctaPartner: 'Explore Partnership',
    ctaQuote: 'Discuss Opportunities',
    heroStats: [
      { value: '16', label: 'Cities Network' },
      { value: 'Custom', label: 'Partnership Models' },
      { value: 'Win-Win', label: 'Revenue Sharing' },
      { value: 'API', label: 'Integration Ready' },
    ],
    benefitsTitle: 'Partnership Models That Drive Growth',
    benefitsSub: 'Flexible collaboration structures tailored to your business model',
    benefits: [
      { title: 'Referral Partnership', desc: 'Earn commission on every booking you refer. Simple tracking, transparent reporting and monthly payouts. No minimum volume required.' },
      { title: 'White-Label Solutions', desc: 'Offer airport transfers under your own brand. We handle operations, vehicles and drivers. You maintain full client relationship.' },
      { title: 'API Integration', desc: 'Connect your platform directly to our booking system. Real-time availability, pricing and booking confirmation via REST API.' },
      { title: 'Volume Agreements', desc: 'Committed volume? Unlock premium rates, priority dispatch and dedicated account management for your organization.' },
      { title: 'Co-Marketing Opportunities', desc: 'Joint marketing campaigns, cross-promotion and shared content. Leverage each other\'s audience and brand strength.' },
      { title: 'Revenue Sharing', desc: 'Transparent revenue share model for strategic partners. Growing together means earning together.' },
    ],
    servicesTitle: 'What Partners Access',
    servicesSub: 'Tools and resources for successful collaboration',
    services: [
      { title: 'Partner Booking Portal', desc: 'Dedicated platform for managing bookings, tracking transfers and generating reports.' },
      { title: 'Branded Booking Widget', desc: 'Embed our booking engine on your website with your branding. Seamless integration.' },
      { title: 'Dedicated Account Manager', desc: 'A single point of contact who understands your business and ensures smooth operations.' },
      { title: 'Marketing & Sales Support', desc: 'Co-branded materials, sales training and marketing resources to help you sell transfer services.' },
    ],
    howTitle: 'How Business Partnership Works',
    howSteps: [
      { title: 'Discovery Call', desc: 'We learn about your business model and goals.' },
      { title: 'Custom Proposal', desc: 'We design a partnership model that fits your needs.' },
      { title: 'Onboarding & Launch', desc: 'Technical setup, training and partnership go-live.' },
      { title: 'Grow Together', desc: 'Regular reviews, optimization and scaling.' },
    ],
    trustTitle: 'A Network Worth Joining',
    trustSub: '',
    trustPoints: [
      { value: '16', label: 'Cities in Network' },
      { value: '1000+', label: 'Active Partners' },
      { value: '15+', label: 'Countries' },
      { value: 'EUR 2M+', label: 'Partner Revenue/yr' },
    ],
    relatedTitle: 'Related Partnership Options',
    contactTitle: 'Let\'s Build Something Together',
    contactSub: 'Tell us about your business, your audience and how you envision our partnership. We will come back with a tailored proposal.',
    formSubmit: 'Start Partnership Discussion',
    backToPartners: 'Back to All Professional Solutions',
  },
  fr: {
    seoTitle: 'Opportunites de Partenariat Transport Business | Zont B2B',
    seoDesc: 'Partenariats transport strategiques avec Zont. Programmes de parrainage, solutions marque blanche, collaborations recurrentes. Grandissez avec le reseau de transfert europeen.',
    badge: 'Partenariat Commercial Strategique',
    heroTitle: 'Opportunites de Partenariat Transport Business',
    heroSub: 'Au-dela d\'une simple relation fournisseur — Zont propose des partenariats strategiques concus pour une croissance a long terme. Programmes de parrainage, marque blanche, collaborations qui creent de la valeur mutuelle.',
    ctaPartner: 'Explorer le Partenariat',
    ctaQuote: 'Discuter des Opportunites',
    heroStats: [
      { value: '16', label: 'Reseau de Villes' },
      { value: 'Sur Mesure', label: 'Modeles de Partenariat' },
      { value: 'Win-Win', label: 'Partage de Revenus' },
      { value: 'API', label: 'Integration Prete' },
    ],
    benefitsTitle: 'Des Modeles de Partenariat qui Generent la Croissance',
    benefitsSub: 'Structures de collaboration flexibles adaptees a votre modele economique',
    benefits: [
      { title: 'Parrainage', desc: 'Gagnez une commission sur chaque reservation referee. Suivi simple, reporting transparent et paiements mensuels.' },
      { title: 'Solutions Marque Blanche', desc: 'Proposez des transferts sous votre propre marque. Nous gerons les operations, vehicules et chauffeurs.' },
      { title: 'Integration API', desc: 'Connectez votre plateforme a notre systeme de reservation. Disponibilite, tarifs et confirmation en temps reel.' },
      { title: 'Accords de Volume', desc: 'Volume engage ? Debloquez des tarifs premium, dispatch prioritaire et gestion de compte dediee.' },
      { title: 'Co-Marketing', desc: 'Campagnes marketing conjointes, cross-promotion et contenus partages.' },
      { title: 'Partage de Revenus', desc: 'Modele transparent de partage de revenus pour partenaires strategiques.' },
    ],
    servicesTitle: 'Ce que les Partenaires Obtiennent',
    servicesSub: 'Outils et ressources pour une collaboration reussie',
    services: [
      { title: 'Portail Partenaire', desc: 'Plateforme dediee pour gerer les reservations, suivre les transferts et generer des rapports.' },
      { title: 'Widget de Reservation Brande', desc: 'Integrez notre moteur de reservation sur votre site avec votre identite visuelle.' },
      { title: 'Gestionnaire de Compte Dedie', desc: 'Un interlocuteur unique qui comprend votre business.' },
      { title: 'Support Marketing & Ventes', desc: 'Materiaux co-brandes, formation commerciale et ressources marketing.' },
    ],
    howTitle: 'Comment Fonctionne le Partenariat Business',
    howSteps: [
      { title: 'Appel Decouverte', desc: 'Nous decouvrons votre modele et vos objectifs.' },
      { title: 'Proposition Sur Mesure', desc: 'Nous concevons un modele de partenariat adapte.' },
      { title: 'Integration & Lancement', desc: 'Configuration technique, formation et lancement.' },
      { title: 'Croissance Mutuelle', desc: 'Reviews regulieres, optimisation et scaling.' },
    ],
    trustTitle: 'Un Reseau qui Vaut le Coup', trustSub: '',
    trustPoints: [{ value: '16', label: 'Villes dans le Reseau' }, { value: '1 000+', label: 'Partenaires Actifs' }, { value: '15+', label: 'Pays' }, { value: '2M EUR+', label: 'Revenus Partenaires/an' }],
    contactTitle: 'Construisons Ensemble',
    contactSub: 'Parlez-nous de votre business et de votre vision du partenariat.',
    formSubmit: 'Demarrer la Discussion', backToPartners: 'Retour aux Solutions Professionnelles',
  },
  ru: {
    seoTitle: 'Возможности Бизнес-Партнерства в Транспорте | Zont B2B',
    seoDesc: 'Стратегические транспортные партнерства с Zont. Реферальные программы, white-label решения, регулярные коллаборации.',
    badge: 'Стратегическое Бизнес-Партнерство',
    heroTitle: 'Возможности Транспортного Бизнес-Партнерства',
    heroSub: 'Больше чем просто поставщик — Zont предлагает стратегические партнерства для долгосрочного роста. Реферальные программы, white-label решения и коллаборации.',
    ctaPartner: 'Изучить Партнерство', ctaQuote: 'Обсудить Возможности',
    heroStats: [{ value: '16', label: 'Городов' }, { value: 'Кастом', label: 'Модели' }, { value: 'Win-Win', label: 'Доход' }, { value: 'API', label: 'Интеграция' }],
    benefitsTitle: 'Модели Партнерства для Роста', benefitsSub: 'Гибкие структуры под ваш бизнес',
    benefits: [
      { title: 'Реферальная Программа', desc: 'Получайте комиссию за каждое бронирование. Простое отслеживание и ежемесячные выплаты.' },
      { title: 'White-Label Решения', desc: 'Предлагайте трансферы под вашим брендом. Мы управляем операциями.' },
      { title: 'API Интеграция', desc: 'Подключите вашу платформу к нашей системе бронирования через REST API.' },
      { title: 'Объемные Соглашения', desc: 'Гарантированный объем — премиальные тарифы и приоритетная диспетчеризация.' },
      { title: 'Совместный Маркетинг', desc: 'Совместные кампании и кросс-промоция.' },
      { title: 'Разделение Дохода', desc: 'Прозрачная модель для стратегических партнеров.' },
    ],
    servicesTitle: 'Что Получают Партнеры', servicesSub: 'Инструменты для успешного сотрудничества',
    services: [
      { title: 'Партнерский Портал', desc: 'Платформа для управления бронированиями и отчетами.' },
      { title: 'Брендированный Виджет', desc: 'Встройте наш движок бронирования на ваш сайт.' },
      { title: 'Выделенный Менеджер', desc: 'Единый контакт, понимающий ваш бизнес.' },
      { title: 'Маркетинговая Поддержка', desc: 'Ко-брендированные материалы и обучение продажам.' },
    ],
    howTitle: 'Как Работает Партнерство', howSteps: [
      { title: 'Ознакомительный Звонок', desc: 'Мы узнаем о вашей модели и целях.' },
      { title: 'Индивидуальное Предложение', desc: 'Модель партнерства под ваши потребности.' },
      { title: 'Запуск', desc: 'Техническая настройка и обучение.' },
      { title: 'Совместный Рост', desc: 'Регулярные обзоры и масштабирование.' },
    ],
    trustTitle: 'Сеть, к Которой Стоит Присоединиться', trustSub: '',
    trustPoints: [{ value: '16', label: 'Городов' }, { value: '1000+', label: 'Партнеров' }, { value: '15+', label: 'Стран' }, { value: '2М EUR+', label: 'Доход Партнеров/год' }],
    contactTitle: 'Давайте Построим Вместе',
    contactSub: 'Расскажите о бизнесе и видении партнерства.',
    formSubmit: 'Начать Обсуждение', backToPartners: 'Назад ко Всем Решениям',
  },
  hy: {
    heroTitle: 'Բիզնես Գործընկերների Համար',
    heroSub: 'Պարզեցրեք ձեր բիզնեսի տրանսպորտը Zont-ի հետ:',
    heroBtn: 'Ստանալ Առաջարկություն',
    ctaPartner: 'Դառնալ Գորցընկեր',
    ctaQuote: 'Հարցում Առաջարկություն',
    benefits: [
      { title: 'Սպասարկում Սպասեմ', desc: 'Ձեր հաճախորդներին պատրաստենք հանգիստ տրանսֆեր ամեն տեղ:' },
      { title: 'Պրեմիում Մեքենաներ', desc: 'Mercedes, BMW, Վաններ և մինիբուսներ:' },
      { title: 'Պարզ API Ինտեգրացիա', desc: 'Ավտոմատացրեք ձեր ամրագրումները մեր API-ի միջոցով:' },
      { title: 'Հատուկ Կոմիսիա', desc: 'Առանձին միջնորդավար տոկոսադրույք:' },
    ],
    trustTitle: 'Բիզնես Գործընկերները Վստահում Են',
    trustSub: '',
    trustPoints: [
      { v: '500+', l: 'Գործընկեր Գործակալություններ' },
      { v: '16', l: 'Քաղաքներ' },
      { v: '24/7', l: 'Աջակցություն' },
      { v: '98%', l: 'Գոհունակություն' },
    ],
    formTitle: 'Ստանալ Առաջարկություն',
    formSub: 'Լրացրեք ստորև ձևը և մենք կկապվենք 24 ժամվա ընթացքում:',
    name: 'Անուն *', company: 'Ընկերություն *', email: 'Email *', phone: 'Հեռախոս *',
    message: 'Հաղորդագրություն',
    messagePh: 'Պատմեք ձեր կարիքները...',
    submit: 'Ուղարկել Հարցումը', sending: 'Ուղարկվում է...',
    successTitle: 'Հաղորդագրությունը ուղարկվեց!',
    successDesc: 'Մեր թիմը կկապվի ձեզ:',
    seoTitle: 'Բիզնես Գործընկերների Համար | Zont',
    seoDesc: 'Պրեմիում տրանսպորտ բիզնես գործընկերների համար:',
    relatedTitle: 'Կապված Էջեր',
  },
};

const seoUrls = { en: '/business-partners', fr: '/business-partners', ru: '/business-partners' };
const relatedPages = [
  { path: '/corporate-clients', name: 'Corporate Clients', tagline: 'Business travel services' },
  { path: '/travel-agencies', name: 'Travel Agencies', tagline: 'Airport transfer partnership' },
  { path: '/tour-operators', name: 'Tour Operators', tagline: 'Tour logistics partner' },
];

const BusinessPartners = () => <B2BPage content={content} seoUrls={seoUrls} relatedPages={relatedPages} />;
export default BusinessPartners;
