import B2BPage from '@/components/B2BPage';

const content = {
  en: {
    seoTitle: 'Premium Chauffeur Services for Concierge Professionals | Zont B2B',
    seoDesc: 'Luxury chauffeur and VIP transport for concierge services. Discretion, punctuality, premium vehicles. Reliable partner for high-end concierge professionals.',
    badge: 'Concierge Transport Partner',
    heroTitle: 'Premium Chauffeur Services for Concierge Professionals',
    heroSub: 'Your clients expect perfection. Zont delivers luxury-level ground transportation with absolute discretion, impeccable punctuality and vehicles that match the standards of the most demanding concierge clientele.',
    ctaPartner: 'Become a Concierge Partner',
    ctaQuote: 'Request VIP Rates',
    heroStats: [
      { value: 'VIP', label: 'Service Standard' },
      { value: '100%', label: 'Discretion' },
      { value: 'S-Class', label: 'Vehicle Level' },
      { value: '<15min', label: 'Response Time' },
    ],
    benefitsTitle: 'Designed for Concierge Excellence',
    benefitsSub: 'Transportation that upholds the highest standards of personal service',
    benefits: [
      { title: 'Absolute Discretion', desc: 'Your clients\' privacy is paramount. Our chauffeurs are trained in confidentiality, NDA-compliant, and accustomed to serving high-profile individuals.' },
      { title: 'Luxury Vehicle Fleet', desc: 'Mercedes S-Class, BMW 7 Series, premium SUVs. Vehicles that match the lifestyle of your clientele.' },
      { title: 'On-Demand Availability', desc: 'Last-minute requests are our specialty. Rapid response for urgent bookings, schedule changes and spontaneous requirements.' },
      { title: 'Personalized Service', desc: 'Preferred vehicle temperature, newspaper selection, specific water brand. We remember and deliver individual preferences.' },
      { title: 'Multi-City Coordination', desc: 'Your client flies to Paris, continues to Monaco, returns via Nice. We coordinate seamlessly across all touchpoints.' },
      { title: 'Direct Line to Dispatch', desc: 'Priority phone line for concierge partners. No waiting, no menus. Direct human contact for every request.' },
    ],
    servicesTitle: 'VIP Transport Solutions',
    servicesSub: 'Bespoke ground transportation for discerning clientele',
    services: [
      { title: 'Private Airport Meet & Greet', desc: 'Discreet landside or airside welcome. Fast-track assistance available at select airports.' },
      { title: 'Full-Day Chauffeur Service', desc: 'Dedicated driver at disposal for shopping, appointments, events. Flexible itinerary throughout the day.' },
      { title: 'Event & Gala Transport', desc: 'Coordinated arrivals and departures for private events, galas, premieres and exclusive gatherings.' },
      { title: 'Long-Distance Luxury Transfers', desc: 'Comfortable intercity travel in premium vehicles. Paris-Deauville, Nice-Saint-Tropez, any route.' },
    ],
    howTitle: 'How We Support Concierge Partners',
    howSteps: [
      { title: 'Dedicated Account', desc: 'Personal account manager who knows your standards.' },
      { title: 'Instant Booking', desc: 'Priority booking via direct phone line or WhatsApp.' },
      { title: 'Flawless Execution', desc: 'Vetted chauffeur delivers a bespoke experience.' },
      { title: 'Client Satisfaction', desc: 'Your reputation is enhanced with every transfer.' },
    ],
    trustTitle: 'Trusted by Luxury Concierge Services',
    trustSub: '',
    trustPoints: [
      { value: '100%', label: 'Discretion Guaranteed' },
      { value: 'VIP', label: 'Trained Chauffeurs' },
      { value: '<15min', label: 'Booking Response' },
      { value: '5-Star', label: 'Service Rating' },
    ],
    relatedTitle: 'Related Premium Solutions',
    contactTitle: 'Elevate Your Concierge Offering',
    contactSub: 'Tell us about your concierge service and the standard your clients expect. We will create a bespoke transport partnership.',
    formSubmit: 'Request Concierge Partnership',
    backToPartners: 'Back to All Professional Solutions',
  },
  fr: {
    seoTitle: 'Services Chauffeur Premium pour Conciergeries | Zont B2B',
    seoDesc: 'Chauffeur de luxe et transport VIP pour conciergeries. Discretion, ponctualite, vehicules premium. Partenaire fiable pour professionnels de la conciergerie haut de gamme.',
    badge: 'Partenaire Transport Conciergerie',
    heroTitle: 'Services Chauffeur Premium pour Conciergeries',
    heroSub: 'Vos clients exigent la perfection. Zont offre un transport terrestre de niveau luxe avec une discretion absolue, une ponctualite impeccable et des vehicules au niveau des conciergeries les plus exigeantes.',
    ctaPartner: 'Devenir Partenaire Conciergerie',
    ctaQuote: 'Demander les Tarifs VIP',
    heroStats: [
      { value: 'VIP', label: 'Standard Service' },
      { value: '100%', label: 'Discretion' },
      { value: 'Classe S', label: 'Niveau Vehicule' },
      { value: '<15min', label: 'Temps de Reponse' },
    ],
    benefitsTitle: 'Concu pour l\'Excellence en Conciergerie',
    benefitsSub: 'Un transport qui respecte les standards les plus eleves du service personnel',
    benefits: [
      { title: 'Discretion Absolue', desc: 'La vie privee de vos clients est primordiale. Chauffeurs formes a la confidentialite, habitues aux personnalites.' },
      { title: 'Flotte de Luxe', desc: 'Mercedes Classe S, BMW Serie 7, SUV premium. Des vehicules au niveau du style de vie de votre clientele.' },
      { title: 'Disponibilite a la Demande', desc: 'Les demandes de derniere minute sont notre specialite. Reponse rapide pour reservations urgentes.' },
      { title: 'Service Personnalise', desc: 'Temperature preferee, journal, marque d\'eau specifique. Nous memorisons les preferences individuelles.' },
      { title: 'Coordination Multi-Villes', desc: 'Votre client vole a Paris, continue a Monaco, rentre par Nice. Coordination fluide a chaque etape.' },
      { title: 'Ligne Directe Dispatch', desc: 'Ligne telephonique prioritaire pour partenaires conciergerie. Contact humain direct pour chaque demande.' },
    ],
    servicesTitle: 'Solutions Transport VIP',
    servicesSub: 'Transport sur mesure pour une clientele exigeante',
    services: [
      { title: 'Accueil Prive Aeroport', desc: 'Accueil discret cote piste ou arrivees. Assistance fast-track dans certains aeroports.' },
      { title: 'Chauffeur a la Journee', desc: 'Chauffeur dedie pour shopping, rendez-vous, evenements. Itineraire flexible toute la journee.' },
      { title: 'Transport Evenements & Galas', desc: 'Arrivees et departs coordonnes pour evenements prives, galas et soirees exclusives.' },
      { title: 'Transferts Luxe Longue Distance', desc: 'Voyages interurbains confortables en vehicules premium. Paris-Deauville, Nice-Saint-Tropez.' },
    ],
    howTitle: 'Comment Nous Accompagnons les Conciergeries',
    howSteps: [
      { title: 'Compte Dedie', desc: 'Gestionnaire personnel qui connait vos standards.' },
      { title: 'Reservation Instantanee', desc: 'Reservation prioritaire par ligne directe ou WhatsApp.' },
      { title: 'Execution Parfaite', desc: 'Un chauffeur selectionne offre une experience sur mesure.' },
      { title: 'Satisfaction Client', desc: 'Votre reputation est renforcee a chaque transfert.' },
    ],
    trustTitle: 'La Confiance des Conciergeries de Luxe', trustSub: '',
    trustPoints: [{ value: '100%', label: 'Discretion Garantie' }, { value: 'VIP', label: 'Chauffeurs Formes' }, { value: '<15min', label: 'Reponse Reservation' }, { value: '5 Etoiles', label: 'Note Service' }],
    contactTitle: 'Sublimez Votre Offre de Conciergerie',
    contactSub: 'Parlez-nous de votre service et des standards attendus par vos clients.',
    formSubmit: 'Demander le Partenariat Conciergerie', backToPartners: 'Retour aux Solutions Professionnelles',
  },
  ru: {
    seoTitle: 'Премиальный Шофер для Консьерж-Служб | Zont B2B',
    seoDesc: 'Люксовый шофер и VIP транспорт для консьерж-служб. Дискретность, пунктуальность, премиальные авто.',
    badge: 'Транспорт для Консьержей',
    heroTitle: 'Премиальные Услуги Шофера для Консьерж-Служб',
    heroSub: 'Ваши клиенты ожидают совершенства. Zont обеспечивает люксовый наземный транспорт с абсолютной дискретностью и безупречной пунктуальностью.',
    ctaPartner: 'Стать Партнером', ctaQuote: 'Запросить VIP Тарифы',
    heroStats: [{ value: 'VIP', label: 'Стандарт' }, { value: '100%', label: 'Дискретность' }, { value: 'S-Class', label: 'Уровень Авто' }, { value: '<15мин', label: 'Время Ответа' }],
    benefitsTitle: 'Создано для Консьерж-Совершенства', benefitsSub: 'Транспорт, соответствующий высочайшим стандартам',
    benefits: [
      { title: 'Абсолютная Дискретность', desc: 'Конфиденциальность ваших клиентов — приоритет. Шоферы обучены работе с VIP-персонами.' },
      { title: 'Люксовый Автопарк', desc: 'Mercedes S-Class, BMW 7 Series, премиальные SUV.' },
      { title: 'Доступность по Запросу', desc: 'Срочные запросы — наша специальность. Быстрый отклик на любые бронирования.' },
      { title: 'Персональный Сервис', desc: 'Предпочтительная температура, газеты, марка воды. Мы запоминаем индивидуальные предпочтения.' },
      { title: 'Мульти-Городская Координация', desc: 'Париж, Монако, Ницца — бесшовная координация на всех этапах.' },
      { title: 'Прямая Линия Диспетчера', desc: 'Приоритетный телефон для консьерж-партнеров. Прямой человеческий контакт.' },
    ],
    servicesTitle: 'VIP Транспортные Решения', servicesSub: 'Транспорт на заказ для взыскательной клиентуры',
    services: [
      { title: 'Частная Встреча в Аэропорту', desc: 'Дискретная встреча. Содействие fast-track.' },
      { title: 'Шофер на День', desc: 'Выделенный водитель для шоппинга, встреч, мероприятий.' },
      { title: 'Транспорт для Мероприятий', desc: 'Координация для частных событий и гала-вечеров.' },
      { title: 'Люксовые Дальние Трансферы', desc: 'Комфортные междугородние поездки в премиальных авто.' },
    ],
    howTitle: 'Как Мы Поддерживаем Консьержей', howSteps: [
      { title: 'Выделенный Аккаунт', desc: 'Персональный менеджер.' },
      { title: 'Мгновенное Бронирование', desc: 'Приоритетное бронирование через прямую линию.' },
      { title: 'Безупречное Исполнение', desc: 'Проверенный шофер обеспечивает индивидуальный опыт.' },
      { title: 'Удовлетворенность Клиентов', desc: 'Ваша репутация усиливается с каждым трансфером.' },
    ],
    trustTitle: 'Доверие Люксовых Консьержей', trustSub: '',
    trustPoints: [{ value: '100%', label: 'Дискретность' }, { value: 'VIP', label: 'Шоферы' }, { value: '<15мин', label: 'Ответ' }, { value: '5 Звезд', label: 'Рейтинг' }],
    contactTitle: 'Улучшите Ваше Консьерж-Предложение',
    contactSub: 'Расскажите о вашей службе и ожиданиях клиентов.',
    formSubmit: 'Запросить Партнерство', backToPartners: 'Назад ко Всем Решениям',
  },
};

const seoUrls = { en: '/concierge-services', fr: '/concierge-services', ru: '/concierge-services' };
const relatedPages = [
  { path: '/hotels', name: 'Hotels', tagline: 'Guest transfer services' },
  { path: '/corporate-clients', name: 'Corporate Clients', tagline: 'Business travel services' },
  { path: '/event-agencies', name: 'Event Agencies', tagline: 'Event transportation' },
];

const ConciergeServices = () => <B2BPage content={content} seoUrls={seoUrls} relatedPages={relatedPages} />;
export default ConciergeServices;
