import B2BPage from '@/components/B2BPage';

const content = {
  en: {
    seoTitle: 'Corporate Chauffeur and Airport Transfer Services | Zont B2B',
    seoDesc: 'Executive airport transfers and corporate chauffeur services. Punctual, professional transport for teams, guests and business travelers. Recurring business bookings.',
    badge: 'Corporate Transport Solutions',
    heroTitle: 'Corporate Chauffeur and Airport Transfer Services',
    heroSub: 'Professional ground transportation for the modern enterprise. From executive airport pickups to team mobility, Zont delivers punctual, premium service that aligns with your corporate standards and travel policies.',
    ctaPartner: 'Open Corporate Account',
    ctaQuote: 'Request Corporate Rates',
    heroStats: [
      { value: '300+', label: 'Corporate Clients' },
      { value: 'Fixed', label: 'Transparent Rates' },
      { value: '99.5%', label: 'On-Time Record' },
      { value: 'Monthly', label: 'Consolidated Billing' },
    ],
    benefitsTitle: 'Built for Corporate Efficiency',
    benefitsSub: 'Transport that integrates with your business operations',
    benefits: [
      { title: 'Corporate Travel Policy Compliant', desc: 'Fixed rates and transparent invoicing that align with your company travel policies. No surprises on expense reports.' },
      { title: 'Consolidated Monthly Billing', desc: 'One invoice per month for all company transfers. Detailed reporting by department, project or cost center.' },
      { title: 'Executive-Level Service', desc: 'Premium vehicles, professional chauffeurs in formal attire. First impressions matter when meeting clients and investors.' },
      { title: 'Guest & Client Transport', desc: 'Impress visiting clients, partners and board members with professional airport pickups and office transfers.' },
      { title: 'Team Event Mobility', desc: 'Team offsites, conferences, client dinners. Reliable group transport that keeps your team moving.' },
      { title: 'Admin Portal & Reporting', desc: 'Self-service booking portal for office managers. Real-time tracking and detailed usage analytics.' },
    ],
    servicesTitle: 'Corporate Transport Services',
    servicesSub: 'Professional mobility for every business scenario',
    services: [
      { title: 'Executive Airport Transfers', desc: 'C-suite pickups and drop-offs at all airports. Meet & greet, luggage assistance, direct to office or hotel.' },
      { title: 'Client & Investor Transport', desc: 'Professional ground transportation for visiting clients, investors and partners. Premium vehicles on every occasion.' },
      { title: 'Recurring Employee Transfers', desc: 'Regular commute or weekly travel patterns. Consistent service at negotiated corporate rates.' },
      { title: 'Corporate Event Transport', desc: 'Board meetings, team events, annual conferences. Coordinated multi-vehicle logistics.' },
    ],
    howTitle: 'How Corporate Partnership Works',
    howSteps: [
      { title: 'Open Account', desc: 'Quick corporate onboarding, no minimum commitment.' },
      { title: 'Set Up Access', desc: 'Admin portal for office managers and travel coordinators.' },
      { title: 'Book Seamlessly', desc: 'Portal, email, phone or integrated booking system.' },
      { title: 'Monthly Settlement', desc: 'Consolidated invoice with detailed reporting.' },
    ],
    trustTitle: 'Trusted by Leading Companies',
    trustSub: '',
    trustPoints: [
      { value: '300+', label: 'Corporate Accounts' },
      { value: '99.5%', label: 'On-Time Arrivals' },
      { value: '10K+', label: 'Executive Transfers/mo' },
      { value: '<1h', label: 'Booking Response' },
    ],
    relatedTitle: 'Related Business Solutions',
    contactTitle: 'Open Your Corporate Account',
    contactSub: 'Tell us about your company, travel volume and transport needs. We will set up your corporate account with tailored rates.',
    formSubmit: 'Request Corporate Account',
    backToPartners: 'Back to All Professional Solutions',
  },
  fr: {
    seoTitle: 'Service Chauffeur et Transfert Aeroport Entreprise | Zont B2B',
    seoDesc: 'Transferts aeroport executifs et services chauffeur entreprise. Transport ponctuel et professionnel pour equipes, clients et voyageurs d\'affaires.',
    badge: 'Solutions Transport Entreprise',
    heroTitle: 'Service Chauffeur et Transfert Aeroport Entreprise',
    heroSub: 'Transport terrestre professionnel pour l\'entreprise moderne. Des transferts executifs aux deplacements d\'equipe, Zont offre un service ponctuel et premium aligne sur vos standards et politiques de voyage.',
    ctaPartner: 'Ouvrir un Compte Entreprise',
    ctaQuote: 'Demander les Tarifs Corporate',
    heroStats: [
      { value: '300+', label: 'Clients Corporate' },
      { value: 'Fixes', label: 'Tarifs Transparents' },
      { value: '99,5%', label: 'Ponctualite' },
      { value: 'Mensuelle', label: 'Facturation Consolidee' },
    ],
    benefitsTitle: 'Concu pour l\'Efficacite Corporate',
    benefitsSub: 'Un transport qui s\'integre a vos operations commerciales',
    benefits: [
      { title: 'Conforme a la Politique Voyage', desc: 'Tarifs fixes et facturation transparente alignes sur vos politiques de voyage d\'entreprise.' },
      { title: 'Facturation Mensuelle Consolidee', desc: 'Une facture par mois pour tous les transferts. Reporting detaille par departement ou centre de cout.' },
      { title: 'Service Niveau Executif', desc: 'Vehicules premium, chauffeurs en tenue formelle. La premiere impression compte.' },
      { title: 'Transport Clients & Invites', desc: 'Impressionnez vos clients et partenaires visiteurs avec des transferts professionnels.' },
      { title: 'Mobilite Evenements d\'Equipe', desc: 'Offsites, conferences, diners clients. Transport groupe fiable.' },
      { title: 'Portail Admin & Reporting', desc: 'Portail de reservation en libre-service. Suivi en temps reel et analyses detaillees.' },
    ],
    servicesTitle: 'Services Transport Corporate',
    servicesSub: 'Mobilite professionnelle pour chaque scenario business',
    services: [
      { title: 'Transferts Aeroport Executifs', desc: 'Prises en charge direction dans tous les aeroports. Accueil, assistance bagages, transfert direct.' },
      { title: 'Transport Clients & Investisseurs', desc: 'Transport professionnel pour clients et partenaires visiteurs. Vehicules premium.' },
      { title: 'Transferts Employes Recurrents', desc: 'Trajets reguliers ou patterns hebdomadaires. Service constant a tarifs negocies.' },
      { title: 'Transport Evenements Corporate', desc: 'Reunions CA, evenements equipe, conferences. Logistique multi-vehicules.' },
    ],
    howTitle: 'Comment Fonctionne le Partenariat Corporate',
    howSteps: [
      { title: 'Ouvrir un Compte', desc: 'Integration rapide, sans engagement minimum.' },
      { title: 'Configurer les Acces', desc: 'Portail admin pour office managers et coordinateurs.' },
      { title: 'Reservez Facilement', desc: 'Portail, email, telephone ou systeme integre.' },
      { title: 'Reglement Mensuel', desc: 'Facture consolidee avec reporting detaille.' },
    ],
    trustTitle: 'La Confiance des Grandes Entreprises', trustSub: '',
    trustPoints: [{ value: '300+', label: 'Comptes Corporate' }, { value: '99,5%', label: 'Ponctualite' }, { value: '10 000+', label: 'Transferts Exec/mois' }, { value: '<1h', label: 'Reponse Reservation' }],
    contactTitle: 'Ouvrez Votre Compte Entreprise',
    contactSub: 'Parlez-nous de votre entreprise, volume de deplacements et besoins transport.',
    formSubmit: 'Demander un Compte Corporate', backToPartners: 'Retour aux Solutions Professionnelles',
  },
  ru: {
    seoTitle: 'Корпоративный Шофер и Трансферы из Аэропорта | Zont B2B',
    seoDesc: 'Представительские трансферы и корпоративные услуги шофера. Пунктуальный, профессиональный транспорт для команд и бизнес-путешественников.',
    badge: 'Корпоративные Транспортные Решения',
    heroTitle: 'Корпоративный Шофер и Трансферы из Аэропорта',
    heroSub: 'Профессиональный наземный транспорт для современного предприятия. Пунктуальный премиальный сервис, соответствующий вашим корпоративным стандартам.',
    ctaPartner: 'Открыть Корпоративный Счет', ctaQuote: 'Запросить Тарифы',
    heroStats: [{ value: '300+', label: 'Корп. Клиентов' }, { value: 'Фикс.', label: 'Прозрачные Тарифы' }, { value: '99,5%', label: 'Пунктуальность' }, { value: 'Месяц', label: 'Сводный Счет' }],
    benefitsTitle: 'Создано для Корпоративной Эффективности', benefitsSub: 'Транспорт, интегрированный в бизнес-операции',
    benefits: [
      { title: 'Соответствие Политике Поездок', desc: 'Фиксированные тарифы и прозрачная отчетность.' },
      { title: 'Ежемесячная Консолидированная Оплата', desc: 'Один счет за все трансферы компании с детализацией.' },
      { title: 'Представительский Сервис', desc: 'Премиальные авто, шоферы в деловой одежде.' },
      { title: 'Транспорт для Клиентов', desc: 'Произведите впечатление на клиентов и партнеров профессиональными трансферами.' },
      { title: 'Мобильность Команды', desc: 'Выездные мероприятия, конференции, деловые ужины.' },
      { title: 'Портал и Аналитика', desc: 'Портал самообслуживания для офис-менеджеров. Аналитика использования.' },
    ],
    servicesTitle: 'Корпоративные Транспортные Услуги', servicesSub: 'Мобильность для бизнеса',
    services: [
      { title: 'Представительские Трансферы', desc: 'Встреча руководства в аэропортах. Прямой трансфер в офис или отель.' },
      { title: 'Транспорт для Клиентов', desc: 'Профессиональный транспорт для клиентов и инвесторов.' },
      { title: 'Регулярные Трансферы', desc: 'Стабильный сервис по корпоративным тарифам.' },
      { title: 'Корпоративные Мероприятия', desc: 'Заседания, мероприятия, конференции. Мульти-авто логистика.' },
    ],
    howTitle: 'Как Работает Корпоративное Партнерство', howSteps: [
      { title: 'Открытие Счета', desc: 'Быстрый онбординг без минимальных обязательств.' },
      { title: 'Настройка Доступа', desc: 'Портал для офис-менеджеров и координаторов.' },
      { title: 'Простое Бронирование', desc: 'Портал, email, телефон или интегрированная система.' },
      { title: 'Месячный Расчет', desc: 'Консолидированный счет с отчетностью.' },
    ],
    trustTitle: 'Доверие Ведущих Компаний', trustSub: '',
    trustPoints: [{ value: '300+', label: 'Корп. Счетов' }, { value: '99,5%', label: 'Пунктуальность' }, { value: '10 000+', label: 'Трансферов/мес' }, { value: '<1ч', label: 'Ответ' }],
    contactTitle: 'Откройте Корпоративный Счет',
    contactSub: 'Расскажите о компании, объемах и потребностях в транспорте.',
    formSubmit: 'Запросить Корп. Счет', backToPartners: 'Назад ко Всем Решениям',
  },
  hy: {
    heroTitle: 'Կորպորատիվ Հաճախորդների Համար',
    heroSub: 'Պարզեցրեք ձեր թիմի բիզնես տրանսպորտը Zont-ի հետ: Գործուղային ուղևորություններ, VIP վարորդներ:',
    heroBtn: 'Ստանալ Առաջարկություն',
    benefits: [
      { title: 'Սպասարկում Սպասեմ', desc: 'Ձեր հաճախորդներին պատրաստենք հանգիստ տրանսֆեր ամեն տեղ:' },
      { title: 'Պրեմիում Մեքենաներ', desc: 'Mercedes, BMW, Վաններ և մինիբուսներ:' },
      { title: 'Պարզ API Ինտեգրացիա', desc: 'Ավտոմատացրեք ձեր ամրագրումները մեր API-ի միջոցով:' },
      { title: 'Հատուկ Կոմիսիա', desc: 'Առանձին միջնորդավար տոկոսադրույք:' },
    ],
    trustTitle: 'Կորպորատիվ Հաճախորդները Վստահում Են',
    trustSub: '',
    trustPoints: [
      { v: '500+', l: 'Գործընկեր Գործակալություններ' },
      { v: '120+', l: 'Քաղաքներ' },
      { v: '24/7', l: 'Աջակցություն' },
      { v: '98%', l: 'Գոհունակություն' },
    ],
    formTitle: 'Ստանալ Առաջարկություն',
    formSub: 'Լրացրեք ստորև ձևը և մենք կկապվենք 24 ժամվա ընթացքում:',
    name: 'Անուն *', company: 'Ընկերություն *', email: 'Email *', phone: 'Հեռախոս *',
    message: 'Հաղորդագրություն',
    messagePh: 'Պատմեք ձեր կարիքները...',
    submit: 'Ուղարկել Հարցումը', sending: 'Ուղարկվում է...',
    successTitle: 'Հաղորդագրությունը ուղարկվեց!',
    successDesc: 'Մեր թիմը կկապվի ձեզ:',
    seoTitle: 'Կորպորատիվ Հաճախորդների Համար | Zont',
    seoDesc: 'Պրեմիում բիզնես տրանսպորտ կորպորատիվ հաճախորդների համար:',
    relatedTitle: 'Կապված Էջեր',
  },
};

const seoUrls = { en: '/corporate-clients', fr: '/corporate-clients', ru: '/corporate-clients' };
const relatedPages = [
  { path: '/business-partners', name: 'Business Partners', tagline: 'Strategic partnerships' },
  { path: '/event-agencies', name: 'Event Agencies', tagline: 'Event transportation' },
  { path: '/concierge-services', name: 'Concierge Services', tagline: 'VIP chauffeur solutions' },
];

const CorporateClients = () => <B2BPage content={content} seoUrls={seoUrls} relatedPages={relatedPages} />;
export default CorporateClients;
