import B2BPage from '@/components/B2BPage';

const content = {
  en: {
    seoTitle: 'Transport Solutions for Event Agencies | Zont B2B',
    seoDesc: 'Reliable guest transportation for events, seminars and corporate gatherings. Airport pickups, group mobility, VIP transport. Zont event transportation partner.',
    badge: 'Event Transport Partner',
    heroTitle: 'Transport Solutions for Event Agencies',
    heroSub: 'From international conferences to private galas, Zont provides reliable guest transportation that keeps your events running on schedule. Airport pickups, group mobility and VIP transport — all coordinated from a single partner.',
    ctaPartner: 'Become an Event Partner',
    ctaQuote: 'Request Event Quote',
    heroStats: [
      { value: '500+', label: 'Events Supported' },
      { value: '16', label: 'Max Per Vehicle' },
      { value: '99%', label: 'On-Time Rate' },
      { value: '1', label: 'Point of Contact' },
    ],
    benefitsTitle: 'Why Event Agencies Choose Zont',
    benefitsSub: 'Guest logistics that make your events seamless',
    benefits: [
      { title: 'Centralized Coordination', desc: 'One dedicated coordinator manages all transport logistics for your event. Multiple arrivals, venues and schedules handled from a single point.' },
      { title: 'Scalable Fleet', desc: 'From 5 to 500 guests, our fleet scales to your event size. Sedans, minivans, minibuses and coaches available on demand.' },
      { title: 'Airport Guest Collection', desc: 'Organized airport pickups for event attendees arriving on different flights. Name signs, luggage help, direct transfer to venue.' },
      { title: 'Real-Time Event Dashboard', desc: 'Track all guest movements in real time. Know who has arrived, who is en route and who needs assistance.' },
      { title: 'Multi-Venue Shuttling', desc: 'Conference center, hotel, dinner venue, airport. Continuous shuttle service between event locations.' },
      { title: 'VIP Speaker Transport', desc: 'Premium vehicles and dedicated chauffeurs for keynote speakers, executives and VIP guests.' },
    ],
    servicesTitle: 'Event Transport Services',
    servicesSub: 'Complete ground transportation for every event format',
    services: [
      { title: 'Conference & Seminar Transport', desc: 'Coordinated airport-venue-hotel transfers for attendees. Timed pickups and departures.' },
      { title: 'Corporate Event Logistics', desc: 'Team building events, offsites, product launches. Reliable group mobility throughout.' },
      { title: 'Wedding & Private Event Transport', desc: 'Elegant vehicle options for private celebrations. Guest shuttles between ceremony and reception.' },
      { title: 'Festival & Exhibition Transport', desc: 'High-volume guest movement for large-scale events. Multi-day coordination available.' },
    ],
    howTitle: 'How Event Partnership Works',
    howSteps: [
      { title: 'Share Event Details', desc: 'Guest count, schedule, venues and special requirements.' },
      { title: 'Custom Transport Plan', desc: 'We design a logistics plan tailored to your event.' },
      { title: 'Seamless Execution', desc: 'Our team manages all guest movements on event day.' },
      { title: 'Successful Event', desc: 'Guests arrive on time. Your event runs smoothly.' },
    ],
    trustTitle: 'Trusted for Event Logistics',
    trustSub: '',
    trustPoints: [
      { value: '500+', label: 'Events Supported' },
      { value: '50K+', label: 'Guests Transported' },
      { value: '99%', label: 'On-Time Delivery' },
      { value: '4.9/5', label: 'Organizer Rating' },
    ],
    relatedTitle: 'Related Professional Solutions',
    contactTitle: 'Plan Your Event Transport',
    contactSub: 'Share your event details — dates, guest count, venues, schedule. We will create a comprehensive transport plan.',
    formSubmit: 'Request Event Transport Plan',
    backToPartners: 'Back to All Professional Solutions',
  },
  fr: {
    seoTitle: 'Solutions de Transport pour Agences Evenementielles | Zont B2B',
    seoDesc: 'Transport d\'invites fiable pour evenements, seminaires et rassemblements. Transferts aeroport, mobilite de groupe, transport VIP. Partenaire transport evenementiel.',
    badge: 'Partenaire Transport Evenementiel',
    heroTitle: 'Solutions de Transport pour Agences Evenementielles',
    heroSub: 'Des conferences internationales aux galas prives, Zont assure un transport d\'invites fiable qui maintient vos evenements dans les temps. Transferts aeroport, mobilite groupe et transport VIP coordonnes par un seul partenaire.',
    ctaPartner: 'Devenir Partenaire Evenementiel',
    ctaQuote: 'Demander un Devis Evenement',
    heroStats: [
      { value: '500+', label: 'Evenements Geres' },
      { value: '16', label: 'Max Par Vehicule' },
      { value: '99%', label: 'Taux Ponctualite' },
      { value: '1', label: 'Point de Contact' },
    ],
    benefitsTitle: 'Pourquoi les Agences Choisissent Zont',
    benefitsSub: 'Une logistique invites qui rend vos evenements fluides',
    benefits: [
      { title: 'Coordination Centralisee', desc: 'Un coordinateur dedie gere toute la logistique transport. Arrivees multiples, lieux et horaires geres depuis un seul point.' },
      { title: 'Flotte Evolutive', desc: 'De 5 a 500 invites, notre flotte s\'adapte. Berlines, minivans, minibus et autocars disponibles.' },
      { title: 'Collecte Aeroport', desc: 'Transferts organises pour les participants arrivant sur differents vols. Panneaux nominatifs, assistance bagages.' },
      { title: 'Suivi en Temps Reel', desc: 'Suivez tous les mouvements des invites en temps reel. Sachez qui est arrive et qui est en route.' },
      { title: 'Navettes Multi-Lieux', desc: 'Centre de conference, hotel, lieu de diner, aeroport. Navette continue entre les lieux.' },
      { title: 'Transport VIP Intervenants', desc: 'Vehicules premium et chauffeurs dedies pour keynotes, dirigeants et invites VIP.' },
    ],
    servicesTitle: 'Services Transport Evenementiel',
    servicesSub: 'Transport terrestre complet pour chaque format d\'evenement',
    services: [
      { title: 'Transport Conferences & Seminaires', desc: 'Transferts coordonnes aeroport-lieu-hotel pour participants.' },
      { title: 'Logistique Evenements Corporate', desc: 'Team building, offsites, lancements produits. Mobilite groupe fiable.' },
      { title: 'Transport Mariages & Evenements Prives', desc: 'Options de vehicules elegants. Navettes entre ceremonie et reception.' },
      { title: 'Transport Festivals & Expositions', desc: 'Deplacement d\'invites a grand volume. Coordination multi-jours disponible.' },
    ],
    howTitle: 'Comment Fonctionne le Partenariat',
    howSteps: [
      { title: 'Partagez les Details', desc: 'Nombre d\'invites, programme, lieux et besoins speciaux.' },
      { title: 'Plan Transport Sur Mesure', desc: 'Nous concevons un plan logistique adapte.' },
      { title: 'Execution Fluide', desc: 'Notre equipe gere tous les mouvements le jour J.' },
      { title: 'Evenement Reussi', desc: 'Les invites arrivent a l\'heure. Votre evenement se deroule parfaitement.' },
    ],
    trustTitle: 'La Confiance pour la Logistique Evenementielle', trustSub: '',
    trustPoints: [{ value: '500+', label: 'Evenements Geres' }, { value: '50 000+', label: 'Invites Transportes' }, { value: '99%', label: 'Ponctualite' }, { value: '4.9/5', label: 'Note Organisateurs' }],
    contactTitle: 'Planifiez le Transport de Votre Evenement',
    contactSub: 'Partagez les details — dates, nombre d\'invites, lieux. Nous creerons un plan transport complet.',
    formSubmit: 'Demander un Plan Transport', backToPartners: 'Retour aux Solutions Professionnelles',
  },
  ru: {
    seoTitle: 'Транспорт для Ивент-Агентств | Zont B2B',
    seoDesc: 'Надежный транспорт для мероприятий, семинаров и корпоративных событий. Трансферы из аэропорта, групповая мобильность, VIP транспорт.',
    badge: 'Партнер по Транспорту для Мероприятий',
    heroTitle: 'Транспортные Решения для Ивент-Агентств',
    heroSub: 'От международных конференций до частных гала-вечеров — Zont обеспечивает надежный транспорт гостей, поддерживая расписание ваших мероприятий.',
    ctaPartner: 'Стать Партнером', ctaQuote: 'Запросить Предложение',
    heroStats: [{ value: '500+', label: 'Мероприятий' }, { value: '16', label: 'Макс на Авто' }, { value: '99%', label: 'Пунктуальность' }, { value: '1', label: 'Контакт' }],
    benefitsTitle: 'Почему Ивент-Агентства Выбирают Zont', benefitsSub: 'Логистика гостей для безупречных мероприятий',
    benefits: [
      { title: 'Централизованная Координация', desc: 'Один координатор управляет всей логистикой транспорта для вашего мероприятия.' },
      { title: 'Масштабируемый Автопарк', desc: 'От 5 до 500 гостей. Седаны, минивэны, микроавтобусы по запросу.' },
      { title: 'Сбор Гостей в Аэропорту', desc: 'Организованные встречи для участников, прибывающих разными рейсами.' },
      { title: 'Панель в Реальном Времени', desc: 'Отслеживайте перемещения всех гостей в реальном времени.' },
      { title: 'Шаттлы между Площадками', desc: 'Непрерывный шаттл между местами проведения.' },
      { title: 'VIP Транспорт Спикеров', desc: 'Премиальные авто и выделенные шоферы для ключевых гостей.' },
    ],
    servicesTitle: 'Транспорт для Мероприятий', servicesSub: 'Полный наземный транспорт для любого формата',
    services: [
      { title: 'Конференции и Семинары', desc: 'Координированные трансферы аэропорт-площадка-отель.' },
      { title: 'Корпоративные Мероприятия', desc: 'Тимбилдинги, выездные мероприятия, презентации.' },
      { title: 'Свадьбы и Частные Мероприятия', desc: 'Элегантные авто и шаттлы для гостей.' },
      { title: 'Фестивали и Выставки', desc: 'Массовое перемещение гостей. Многодневная координация.' },
    ],
    howTitle: 'Как Работает Партнерство', howSteps: [
      { title: 'Детали Мероприятия', desc: 'Количество гостей, расписание, площадки.' },
      { title: 'Транспортный План', desc: 'Мы разрабатываем индивидуальный план логистики.' },
      { title: 'Бесшовное Исполнение', desc: 'Наша команда управляет всеми перемещениями в день мероприятия.' },
      { title: 'Успешное Мероприятие', desc: 'Гости прибывают вовремя.' },
    ],
    trustTitle: 'Доверие в Ивент-Логистике', trustSub: '',
    trustPoints: [{ value: '500+', label: 'Мероприятий' }, { value: '50 000+', label: 'Гостей' }, { value: '99%', label: 'Пунктуальность' }, { value: '4.9/5', label: 'Рейтинг' }],
    contactTitle: 'Спланируйте Транспорт для Мероприятия',
    contactSub: 'Поделитесь деталями — даты, количество гостей, площадки.',
    formSubmit: 'Запросить План', backToPartners: 'Назад ко Всем Решениям',
  },
  hy: {
    heroTitle: 'Միջոցառումների Կազմակերպիչների Համար',
    heroSub: 'Տրանսպորտային ծառայություն ձեր միջոցառումների համար:',
    heroBtn: 'Ստանալ Առաջարկություն',
    benefits: [
      { title: 'Սպասարկում Սպասեմ', desc: 'Ձեր հաճախորդներին պատրաստենք հանգիստ տրանսֆեր ամեն տեղ:' },
      { title: 'Պրեմիում Մեքենաներ', desc: 'Mercedes, BMW, Վաններ և մինիբուսներ:' },
      { title: 'Պարզ API Ինտեգրացիա', desc: 'Ավտոմատացրեք ձեր ամրագրումները մեր API-ի միջոցով:' },
      { title: 'Հատուկ Կոմիսիա', desc: 'Առանձին միջնորդավար տոկոսադրույք:' },
    ],
    trustTitle: 'Կազմակերպիչները Վստահում Են',
    trustSub: '',
    trustPoints: [
      { v: '500+', l: 'Գործընկեր Գործակալություններ' },
      { v: '120+', l: 'Քաղաքներ' },
      { v: '24/7', l: 'Աջակցություն' },
      { v: '98%', l: 'Գոհունակություն' },
    ],
    formTitle: 'Ստանալ Առաջարկություն',
    formSub: 'Լրացրեք ստորև ձևը և մենք կկապվենք 24 ժամվա ընթացքում:',
    name: 'Անուն *', company: 'Ընկերություն *', email: 'Email *', phone: 'Հեռախոս *',
    message: 'Հաղորդագրություն',
    messagePh: 'Պատմեք ձեր կարիքները...',
    submit: 'Ուղարկել Հարցումը', sending: 'Ուղարկվում է...',
    successTitle: 'Հաղորդագրությունը ուղարկվեց!',
    successDesc: 'Մեր թիմը կկապվի ձեզ:',
    seoTitle: 'Միջոցառումների Կազմակերպիչների Համար | Zont',
    seoDesc: 'Տրանսպորտ ձեր միջոցառումների համար Zont-ի հետ:',
    relatedTitle: 'Կապված Էջեր',
  },
};

const seoUrls = { en: '/event-agencies', fr: '/event-agencies', ru: '/event-agencies' };
const relatedPages = [
  { path: '/corporate-clients', name: 'Corporate Clients', tagline: 'Business travel services' },
  { path: '/concierge-services', name: 'Concierge Services', tagline: 'VIP chauffeur solutions' },
  { path: '/hotels', name: 'Hotels', tagline: 'Guest transfer services' },
];

const EventAgencies = () => <B2BPage content={content} seoUrls={seoUrls} relatedPages={relatedPages} />;
export default EventAgencies;
