import B2BPage from '@/components/B2BPage';

const content = {
  en: {
    seoTitle: 'Chauffeur and Transfer Services for Hotels | Zont B2B',
    seoDesc: 'Premium airport transfer and chauffeur services for hotels. Meet & greet, guest pickups, concierge-level transport. Elevate your hotel guest experience with Zont.',
    badge: 'Hotel Transport Partner',
    heroTitle: 'Chauffeur and Transfer Services for Hotels',
    heroSub: 'Elevate your guest experience from the moment they land. Zont provides seamless airport-to-hotel transfers, chauffeur services and guest transportation that reflects the quality of your establishment.',
    ctaPartner: 'Become a Hotel Partner',
    ctaQuote: 'Request Hotel Rates',
    heroStats: [
      { value: '200+', label: 'Hotel Partners' },
      { value: '5-Star', label: 'Service Level' },
      { value: '60min', label: 'Free Wait Time' },
      { value: '24/7', label: 'Front Desk Support' },
    ],
    benefitsTitle: 'Why Hotels Trust Zont',
    benefitsSub: 'Guest transportation that reflects your hotel standards',
    benefits: [
      { title: 'Guest-Centric Service', desc: 'Every transfer is an extension of your hospitality. Professional chauffeurs trained to deliver hotel-level courtesy and discretion.' },
      { title: 'Concierge Integration', desc: 'Book transfers directly through your concierge or front desk. Simple process that integrates with your existing guest services workflow.' },
      { title: 'Brand-Consistent Experience', desc: 'Premium vehicles, impeccable presentation, multilingual drivers. The transport matches your hotel reputation.' },
      { title: 'Automated Guest Arrivals', desc: 'Share guest flight details and we handle the rest. Real-time flight tracking ensures your guest is met on time, every time.' },
      { title: 'Flexible Billing', desc: 'Monthly invoicing, per-transfer billing, or guest-pays options. Choose what works best for your hotel accounting.' },
      { title: 'VIP & Suite Guests', desc: 'Luxury vehicles available for your most distinguished guests. Mercedes S-Class, BMW 7 Series and premium SUVs on request.' },
    ],
    servicesTitle: 'Transport Services for Your Guests',
    servicesSub: 'Every ground transportation need covered',
    services: [
      { title: 'Airport-to-Hotel Transfers', desc: 'Professional meet & greet at arrivals. Driver with name sign, luggage assistance, direct transfer to your hotel.' },
      { title: 'Hotel-to-Airport Departures', desc: 'On-time pickup from your hotel. Flight-time optimized scheduling ensures guests arrive relaxed and on time.' },
      { title: 'Guest Excursions', desc: 'Chauffeur at disposal for shopping trips, restaurant visits, sightseeing. Hourly or daily booking.' },
      { title: 'Inter-Hotel Transfers', desc: 'For hotel groups: seamless transfers between your properties or partner hotels.' },
    ],
    howTitle: 'How Hotel Partnership Works',
    howSteps: [
      { title: 'Onboard Your Hotel', desc: 'Quick setup with dedicated hotel liaison.' },
      { title: 'Share Guest Details', desc: 'Send flight info and guest preferences.' },
      { title: 'We Handle Transport', desc: 'Professional chauffeur meets your guest.' },
      { title: 'Elevate Guest Reviews', desc: 'Seamless arrival boosts guest satisfaction.' },
    ],
    trustTitle: 'The Hotel Industry Trusts Zont',
    trustSub: '',
    trustPoints: [
      { value: '200+', label: 'Hotel Partners' },
      { value: '50K+', label: 'Guest Transfers' },
      { value: '4.5/5', label: 'Guest Rating' },
      { value: '99.5%', label: 'On-Time Arrivals' },
    ],
    relatedTitle: 'Solutions for Related Hospitality Sectors',
    contactTitle: 'Elevate Your Hotel Guest Experience',
    contactSub: 'Tell us about your hotel, average guest volume and transfer needs. We will create a tailored partnership proposal.',
    formSubmit: 'Request Hotel Partnership',
    backToPartners: 'Back to All Professional Solutions',
  },
  fr: {
    seoTitle: 'Services Chauffeur et Transfert pour Hotels | Zont B2B',
    seoDesc: 'Transferts aeroport premium et services chauffeur pour hotels. Accueil personnalise, transport client de niveau conciergerie. Sublimez l\'experience de vos clients.',
    badge: 'Partenaire Transport Hotelier',
    heroTitle: 'Services Chauffeur et Transfert pour Hotels',
    heroSub: 'Sublimez l\'experience de vos clients des leur atterrissage. Zont propose des transferts aeroport-hotel fluides et des services chauffeur qui refletent la qualite de votre etablissement.',
    ctaPartner: 'Devenir Partenaire Hotel',
    ctaQuote: 'Demander les Tarifs Hotels',
    heroStats: [
      { value: '200+', label: 'Hotels Partenaires' },
      { value: '5 Etoiles', label: 'Niveau de Service' },
      { value: '60min', label: 'Attente Gratuite' },
      { value: '24/7', label: 'Support Reception' },
    ],
    benefitsTitle: 'Pourquoi les Hotels Font Confiance a Zont',
    benefitsSub: 'Un transport client qui reflete les standards de votre hotel',
    benefits: [
      { title: 'Service Centre sur le Client', desc: 'Chaque transfert est une extension de votre hospitalite. Chauffeurs formes a la courtoisie hoteliere.' },
      { title: 'Integration Conciergerie', desc: 'Reservez directement via votre conciergerie. Processus simple integre a vos services clients.' },
      { title: 'Experience Coherente avec la Marque', desc: 'Vehicules premium, presentation impeccable, chauffeurs multilingues. Le transport correspond a votre reputation.' },
      { title: 'Arrivees Automatisees', desc: 'Partagez les details de vol et nous gerons le reste. Suivi en temps reel pour chaque client.' },
      { title: 'Facturation Flexible', desc: 'Facturation mensuelle, par transfert ou paiement par le client. Choisissez ce qui convient.' },
      { title: 'Clients VIP & Suites', desc: 'Vehicules de luxe pour vos clients les plus distingues. Mercedes Classe S, BMW Serie 7.' },
    ],
    servicesTitle: 'Services de Transport pour Vos Clients',
    servicesSub: 'Tous les besoins de transport terrestre couverts',
    services: [
      { title: 'Transferts Aeroport-Hotel', desc: 'Accueil professionnel aux arrivees. Chauffeur avec panneau, assistance bagages, transfert direct.' },
      { title: 'Departs Hotel-Aeroport', desc: 'Prise en charge ponctuelle depuis votre hotel. Horaires optimises selon les vols.' },
      { title: 'Excursions Clients', desc: 'Chauffeur a disposition pour shopping, restaurants, visites touristiques.' },
      { title: 'Transferts Inter-Hotels', desc: 'Pour groupes hoteliers : transferts fluides entre vos etablissements.' },
    ],
    howTitle: 'Comment Fonctionne le Partenariat Hotel',
    howSteps: [
      { title: 'Integration de Votre Hotel', desc: 'Mise en place rapide avec interlocuteur dedie.' },
      { title: 'Partagez les Details', desc: 'Envoyez les infos de vol et preferences.' },
      { title: 'Nous Gerons le Transport', desc: 'Un chauffeur professionnel accueille votre client.' },
      { title: 'Ameliorez les Avis', desc: 'Une arrivee fluide booste la satisfaction client.' },
    ],
    trustTitle: 'L\'Hotellerie Fait Confiance a Zont', trustSub: '',
    trustPoints: [{ value: '200+', label: 'Hotels Partenaires' }, { value: '50 000+', label: 'Transferts Clients' }, { value: '4.5/5', label: 'Note Clients' }, { value: '99,5%', label: 'Ponctualite' }],
    contactTitle: 'Sublimez l\'Experience de Vos Clients',
    contactSub: 'Parlez-nous de votre hotel, volume moyen de clients et besoins de transfert.',
    formSubmit: 'Demander le Partenariat Hotel', backToPartners: 'Retour aux Solutions Professionnelles',
  },
  ru: {
    seoTitle: 'Шофер и Трансферы для Отелей | Zont B2B',
    seoDesc: 'Премиальные трансферы и услуги шофера для отелей. Встреча гостей, транспорт уровня консьержа. Улучшите впечатления гостей с Zont.',
    badge: 'Транспортный Партнер Отелей',
    heroTitle: 'Услуги Шофера и Трансферов для Отелей',
    heroSub: 'Улучшите впечатления гостей с момента прилета. Zont обеспечивает бесшовные трансферы аэропорт-отель и услуги шофера, соответствующие качеству вашего заведения.',
    ctaPartner: 'Стать Партнером', ctaQuote: 'Запросить Тарифы',
    heroStats: [{ value: '200+', label: 'Отелей-Партнеров' }, { value: '5 Звезд', label: 'Уровень Сервиса' }, { value: '60мин', label: 'Бесплатное Ожидание' }, { value: '24/7', label: 'Поддержка Ресепшн' }],
    benefitsTitle: 'Почему Отели Доверяют Zont', benefitsSub: 'Транспорт гостей, соответствующий стандартам отеля',
    benefits: [
      { title: 'Гостеориентированный Сервис', desc: 'Каждый трансфер — продолжение вашего гостеприимства. Шоферы обучены отельной вежливости.' },
      { title: 'Интеграция с Консьержем', desc: 'Бронируйте через консьержа или ресепшн. Простой процесс.' },
      { title: 'Опыт, Соответствующий Бренду', desc: 'Премиальные авто, безупречная презентация, многоязычные водители.' },
      { title: 'Автоматизация Прибытий', desc: 'Поделитесь данными рейсов — мы позаботимся обо всем остальном.' },
      { title: 'Гибкая Оплата', desc: 'Ежемесячная, потрансферная или оплата гостем.' },
      { title: 'VIP Гости', desc: 'Люксовые авто для самых требовательных гостей. Mercedes S-Class, BMW 7.' },
    ],
    servicesTitle: 'Транспорт для Ваших Гостей', servicesSub: 'Все потребности наземного транспорта покрыты',
    services: [
      { title: 'Трансферы Аэропорт-Отель', desc: 'Встреча в зоне прилета с табличкой, помощь с багажом.' },
      { title: 'Отправление Отель-Аэропорт', desc: 'Пунктуальная подача из отеля.' },
      { title: 'Экскурсии для Гостей', desc: 'Шофер в распоряжении для шоппинга и достопримечательностей.' },
      { title: 'Межотельные Трансферы', desc: 'Для сетей: бесшовные трансферы между отелями.' },
    ],
    howTitle: 'Как Работает Партнерство', howSteps: [
      { title: 'Подключение Отеля', desc: 'Быстрая настройка с выделенным менеджером.' },
      { title: 'Данные Гостей', desc: 'Отправьте информацию о рейсах и предпочтениях.' },
      { title: 'Мы Организуем', desc: 'Профессиональный шофер встречает гостя.' },
      { title: 'Лучшие Отзывы', desc: 'Бесшовный прилет повышает удовлетворенность.' },
    ],
    trustTitle: 'Доверие Отельной Индустрии', trustSub: '',
    trustPoints: [{ value: '200+', label: 'Отелей' }, { value: '50 000+', label: 'Трансферов' }, { value: '4.5/5', label: 'Рейтинг' }, { value: '99,5%', label: 'Пунктуальность' }],
    contactTitle: 'Улучшите Впечатления Гостей',
    contactSub: 'Расскажите о вашем отеле и потребностях в трансферах.',
    formSubmit: 'Запросить Партнерство', backToPartners: 'Назад ко Всем Решениям',
  },
  hy: {
    heroTitle: 'Հյուրանոցների Համար',
    heroSub: 'Առաջարկեք պրեմիում տրանսֆերներ ձեր հյուրերին: Պրեմիում ծառայություն, գինն ընդգրկված է:',
    heroBtn: 'Ստանալ Առաջարկություն',
    ctaPartner: 'Դառնալ Գորցընկեր',
    ctaQuote: 'Հարցում Առաջարկություն',
    benefits: [
      { title: 'Սպասարկում Սպասեմ', desc: 'Ձեր հաճախորդներին պատրաստենք հանգիստ տրանսֆեր ամեն տեղ:' },
      { title: 'Պրեմիում Մեքենաներ', desc: 'Mercedes, BMW, Վաններ և մինիբուսներ:' },
      { title: 'Պարզ API Ինտեգրացիա', desc: 'Ավտոմատացրեք ձեր ամրագրումները մեր API-ի միջոցով:' },
      { title: 'Հատուկ Կոմիսիա', desc: 'Առանձին միջնորդավար տոկոսադրույք:' },
    ],
    trustTitle: 'Թվեր Որոնց Հյուրանոցները Վստահում Են',
    trustSub: '',
    trustPoints: [
      { v: '500+', l: 'Գործընկեր Գործակալություններ' },
      { v: '16', l: 'Քաղաքներ' },
      { v: '24/7', l: 'Աջակցություն' },
      { v: '98%', l: 'Գոհունակություն' },
    ],
    formTitle: 'Ստանալ Առաջարկություն',
    formSub: 'Լրացրեք ստորև ձևը և մենք կկապվենք 24 ժամվա ընթացքում:',
    name: 'Անուն *', company: 'Ընկերություն *', email: 'Email *', phone: 'Հեռախոս *',
    message: 'Հաղորդագրություն',
    messagePh: 'Պատմեք ձեր կարիքները...',
    submit: 'Ուղարկել Հարցումը', sending: 'Ուղարկվում է...',
    successTitle: 'Հաղորդագրությունը ուղարկվեց!',
    successDesc: 'Մեր թիմը կկապվի ձեզ:',
    seoTitle: 'Հյուրանոցների Համար | Zont',
    seoDesc: 'Պրեմիում տրանսպորտ հյուրանոցների համար:',
    relatedTitle: 'Կապված Էջեր',
  },
};

const seoUrls = { en: '/hotels', fr: '/hotels', ru: '/hotels' };
const relatedPages = [
  { path: '/concierge-services', name: 'Concierge Services', tagline: 'VIP chauffeur solutions' },
  { path: '/tourism-agencies', name: 'Tourism Agencies', tagline: 'Private transport solutions' },
  { path: '/event-agencies', name: 'Event Agencies', tagline: 'Event transportation' },
];

const Hotels = () => <B2BPage content={content} seoUrls={seoUrls} relatedPages={relatedPages} />;
export default Hotels;
