import B2BPage from '@/components/B2BPage';

const content = {
  en: {
    seoTitle: 'Private Transfer Services for Tour Operators | Zont B2B',
    seoDesc: 'Airport transfers and private transport for tour operators. Reliable logistics for organized tours, travel programs and group itineraries across Europe.',
    badge: 'Tour Operator Partnership',
    heroTitle: 'Private Transfer Services for Tour Operators',
    heroSub: 'The ground transportation backbone for your tour programs. Zont ensures every transfer in your itinerary runs smoothly — from first airport pickup to final departure. Reliable logistics across 16 European cities for individual travelers and groups.',
    ctaPartner: 'Become a Tour Partner',
    ctaQuote: 'Request Operator Rates',
    heroStats: [
      { value: '16', label: 'European Cities' },
      { value: '1-16', label: 'Passengers/Vehicle' },
      { value: 'Multi-Day', label: 'Programs Supported' },
      { value: '99%', label: 'Schedule Adherence' },
    ],
    benefitsTitle: 'Why Tour Operators Partner With Zont',
    benefitsSub: 'Ground transport that strengthens every tour itinerary',
    benefits: [
      { title: 'Itinerary-Integrated Transport', desc: 'We plan transfers around your tour schedule. Airport arrivals, hotel changes, excursion pickups — all synchronized with your program timing.' },
      { title: 'Multi-Day Program Support', desc: '3-day city tours, 7-day European circuits, 14-day grand tours. We support the full duration with consistent service quality.' },
      { title: 'Group & FIT Flexibility', desc: 'Solo travelers, couples, families or groups of 30+. Our fleet adapts from premium sedans to minibuses and coaches.' },
      { title: 'Destination Expertise', desc: 'Our drivers know Paris, the Riviera, Tuscany, Bavaria. Local knowledge that adds value to your tour experience.' },
      { title: 'Operational Reliability', desc: '99% schedule adherence. Real-time flight tracking, driver backup protocols and 24/7 operations center. Your tours stay on track.' },
      { title: 'Seasonal Scalability', desc: 'High season, low season — our capacity scales with your demand. No overbooking, no shortages, consistent availability.' },
    ],
    servicesTitle: 'Transport for Every Tour Format',
    servicesSub: 'Comprehensive logistics for organized travel',
    services: [
      { title: 'Airport Meet & Transfer', desc: 'Professional welcome for tour participants at airports. Coordinated pickups even when guests arrive on different flights.' },
      { title: 'Inter-City Tour Transfers', desc: 'Paris-Loire Valley, Nice-Monaco, Rome-Florence. Comfortable long-distance transfers between tour destinations.' },
      { title: 'Daily Excursion Transport', desc: 'Chauffeur at disposal for wine tours, cultural visits, shopping trips. Flexible daily scheduling.' },
      { title: 'Cruise Port Transfers', desc: 'Reliable transfers between cruise terminals and city centers or airports. Timed to ship schedules.' },
    ],
    howTitle: 'How Tour Operator Partnership Works',
    howSteps: [
      { title: 'Share Your Programs', desc: 'Send us your tour itineraries, dates and passenger counts.' },
      { title: 'Route-Based Pricing', desc: 'We price each leg of your tour with transparent, fixed rates.' },
      { title: 'Coordinated Execution', desc: 'Drivers assigned per tour, schedules confirmed 48h in advance.' },
      { title: 'Seamless Tour Experience', desc: 'Your guests enjoy premium transfers at every stage of the journey.' },
    ],
    trustTitle: 'Tour Operators Trust Zont',
    trustSub: '',
    trustPoints: [
      { value: '16', label: 'Cities Covered' },
      { value: '5K+', label: 'Tour Programs Served' },
      { value: '99%', label: 'Schedule Adherence' },
      { value: '15+', label: 'European Countries' },
    ],
    relatedTitle: 'Related Tourism Solutions',
    contactTitle: 'Partner With Zont for Your Tours',
    contactSub: 'Share your upcoming tour programs, destinations and group sizes. We will create a comprehensive transport proposal with route-based pricing.',
    formSubmit: 'Request Tour Operator Partnership',
    backToPartners: 'Back to All Professional Solutions',
  },
  fr: {
    seoTitle: 'Services de Transfert Prive pour Tour-Operateurs | Zont B2B',
    seoDesc: 'Transferts aeroport et transport prive pour tour-operateurs. Logistique fiable pour circuits organises et programmes de voyage en Europe.',
    badge: 'Partenariat Tour-Operateurs',
    heroTitle: 'Services de Transfert Prive pour Tour-Operateurs',
    heroSub: 'L\'epine dorsale du transport terrestre pour vos programmes de circuits. Zont garantit que chaque transfert de votre itineraire se deroule sans accroc — du premier accueil aeroport au dernier depart. Logistique fiable dans 16 villes europeennes.',
    ctaPartner: 'Devenir Partenaire Tour',
    ctaQuote: 'Demander les Tarifs Operateur',
    heroStats: [
      { value: '16', label: 'Villes Europeennes' },
      { value: '1-16', label: 'Passagers/Vehicule' },
      { value: 'Multi-Jours', label: 'Programmes Geres' },
      { value: '99%', label: 'Respect du Programme' },
    ],
    benefitsTitle: 'Pourquoi les Tour-Operateurs Choisissent Zont',
    benefitsSub: 'Un transport terrestre qui renforce chaque itineraire de circuit',
    benefits: [
      { title: 'Transport Integre a l\'Itineraire', desc: 'Nous planifions les transferts autour de votre programme. Arrivees aeroport, changements d\'hotel, excursions — tout synchronise.' },
      { title: 'Support Programmes Multi-Jours', desc: 'Circuits de 3 jours, 7 jours, 14 jours. Qualite de service constante sur toute la duree.' },
      { title: 'Flexibilite Groupes & FIT', desc: 'Voyageurs individuels, couples, familles ou groupes de 30+. Notre flotte s\'adapte.' },
      { title: 'Expertise Destination', desc: 'Nos chauffeurs connaissent Paris, la Riviera, la Toscane, la Baviere. Connaissance locale qui enrichit le circuit.' },
      { title: 'Fiabilite Operationnelle', desc: '99% de respect du programme. Suivi de vols, protocoles de backup, centre operationnel 24/7.' },
      { title: 'Scalabilite Saisonniere', desc: 'Haute et basse saison — notre capacite s\'adapte a votre demande. Disponibilite constante.' },
    ],
    servicesTitle: 'Transport pour Chaque Format de Circuit',
    servicesSub: 'Logistique complete pour voyages organises',
    services: [
      { title: 'Accueil & Transfert Aeroport', desc: 'Accueil professionnel des participants. Prises en charge coordonnees meme sur differents vols.' },
      { title: 'Transferts Inter-Villes', desc: 'Paris-Loire, Nice-Monaco, Rome-Florence. Transferts confortables longue distance.' },
      { title: 'Transport Excursions', desc: 'Chauffeur a disposition pour visites culturelles, degustation, shopping.' },
      { title: 'Transferts Ports de Croisiere', desc: 'Transferts fiables entre terminaux de croisiere et centres-villes ou aeroports.' },
    ],
    howTitle: 'Comment Fonctionne le Partenariat',
    howSteps: [
      { title: 'Partagez Vos Programmes', desc: 'Envoyez vos itineraires, dates et nombre de participants.' },
      { title: 'Tarification par Route', desc: 'Nous tarifons chaque etape avec des prix fixes transparents.' },
      { title: 'Execution Coordonnee', desc: 'Chauffeurs assignes par circuit, horaires confirmes 48h a l\'avance.' },
      { title: 'Experience de Circuit Fluide', desc: 'Vos clients profitent de transferts premium a chaque etape.' },
    ],
    trustTitle: 'Les Tour-Operateurs Font Confiance a Zont', trustSub: '',
    trustPoints: [{ value: '16', label: 'Villes Couvertes' }, { value: '5 000+', label: 'Programmes Geres' }, { value: '99%', label: 'Respect Programme' }, { value: '15+', label: 'Pays Europeens' }],
    contactTitle: 'Partenariat Transport pour Vos Circuits',
    contactSub: 'Partagez vos programmes, destinations et tailles de groupes. Nous creerons une proposition avec tarification par route.',
    formSubmit: 'Demander le Partenariat Tour', backToPartners: 'Retour aux Solutions Professionnelles',
  },
  ru: {
    seoTitle: 'Частные Трансферы для Туроператоров | Zont B2B',
    seoDesc: 'Трансферы из аэропорта и частный транспорт для туроператоров. Надежная логистика для организованных туров по Европе.',
    badge: 'Партнерство для Туроператоров',
    heroTitle: 'Услуги Частного Трансфера для Туроператоров',
    heroSub: 'Основа наземного транспорта для ваших турпрограмм. Zont обеспечивает бесперебойную работу каждого трансфера — от первой встречи в аэропорту до последнего отъезда.',
    ctaPartner: 'Стать Партнером', ctaQuote: 'Запросить Тарифы',
    heroStats: [{ value: '16', label: 'Городов' }, { value: '1-16', label: 'Пассажиров/Авто' }, { value: 'Много-Дн.', label: 'Программы' }, { value: '99%', label: 'Соблюдение Расписания' }],
    benefitsTitle: 'Почему Туроператоры Выбирают Zont', benefitsSub: 'Наземный транспорт, усиливающий каждый маршрут',
    benefits: [
      { title: 'Транспорт по Маршруту', desc: 'Планируем трансферы вокруг вашего расписания. Прилеты, смена отелей, экскурсии — всё синхронизировано.' },
      { title: 'Многодневные Программы', desc: '3-дневные туры, 7-дневные, 14-дневные. Стабильное качество на всей протяженности.' },
      { title: 'Группы и FIT', desc: 'Индивидуальные путешественники или группы 30+. Автопарк адаптируется.' },
      { title: 'Знание Направлений', desc: 'Водители знают Париж, Ривьеру, Тоскану. Местные знания обогащают тур.' },
      { title: 'Операционная Надежность', desc: '99% соблюдение расписания. Отслеживание рейсов, резервные протоколы.' },
      { title: 'Сезонная Масштабируемость', desc: 'Высокий и низкий сезон — мощности адаптируются к спросу.' },
    ],
    servicesTitle: 'Транспорт для Каждого Формата', servicesSub: 'Комплексная логистика для организованных путешествий',
    services: [
      { title: 'Встреча и Трансфер', desc: 'Профессиональная встреча участников тура в аэропортах.' },
      { title: 'Междугородние Трансферы', desc: 'Комфортные переезды между городами маршрута.' },
      { title: 'Экскурсионный Транспорт', desc: 'Шофер в распоряжении для культурных визитов и дегустаций.' },
      { title: 'Круизные Терминалы', desc: 'Трансферы между круизными терминалами и городами.' },
    ],
    howTitle: 'Как Работает Партнерство', howSteps: [
      { title: 'Поделитесь Программами', desc: 'Отправьте маршруты, даты и количество участников.' },
      { title: 'Тарификация по Маршруту', desc: 'Прозрачные фиксированные цены за каждый этап.' },
      { title: 'Координированное Исполнение', desc: 'Водители назначены, расписание подтверждено за 48ч.' },
      { title: 'Бесшовный Тур', desc: 'Гости наслаждаются трансферами на каждом этапе.' },
    ],
    trustTitle: 'Доверие Туроператоров', trustSub: '',
    trustPoints: [{ value: '16', label: 'Городов' }, { value: '5000+', label: 'Программ' }, { value: '99%', label: 'Расписание' }, { value: '15+', label: 'Стран' }],
    contactTitle: 'Партнерство для Ваших Туров',
    contactSub: 'Поделитесь программами и размерами групп. Мы создадим предложение с тарификацией по маршруту.',
    formSubmit: 'Запросить Партнерство', backToPartners: 'Назад ко Всем Решениям',
  },
  hy: {
    heroTitle: 'Տուրիզմի Գործակալությունների Համար',
    heroSub: 'Տրանսպորտային ծառայություն տուրիստական փաթեթների համար:',
    heroBtn: 'Ստանալ Առաջարկություն',
    ctaPartner: 'Դառնալ Գորցընկեր',
    ctaQuote: 'Հարցում Առաջարկություն',
    benefits: [
      { title: 'Սպասարկում Սպասեմ', desc: 'Ձեր հաճախորդներին պատրաստենք հանգիստ տրանսֆեր ամեն տեղ:' },
      { title: 'Պրեմիում Մեքենաներ', desc: 'Mercedes, BMW, Վաններ և մինիբուսներ:' },
      { title: 'Պարզ API Ինտեգրացիա', desc: 'Ավտոմատացրեք ձեր ամրագրումները մեր API-ի միջոցով:' },
      { title: 'Հատուկ Կոմիսիա', desc: 'Առանձին միջնորդավար տոկոսադրույք:' },
    ],
    trustTitle: 'Տուրիզմի Գործակալությունները Վստահում Են',
    trustSub: '',
    trustPoints: [
      { v: '500+', l: 'Գործընկեր Գործակալություններ' },
      { v: '16', l: 'Քաղաքներ' },
      { v: '24/7', l: 'Աջակցություն' },
      { v: '98%', l: 'Գոհունակություն' },
    ],
    formTitle: 'Ստանալ Առաջարկություն',
    formSub: 'Լրացրեք ստորև ձևը և մենք կկապվենք 24 ժամվա ընթացքում:',
    name: 'Անուն *', company: 'Ընկերություն *', email: 'Email *', phone: 'Հեռախոս *',
    message: 'Հաղորդագրություն',
    messagePh: 'Պատմեք ձեր կարիքները...',
    submit: 'Ուղարկել Հարցումը', sending: 'Ուղարկվում է...',
    successTitle: 'Հաղորդագրությունը ուղարկվեց!',
    successDesc: 'Մեր թիմը կկապվի ձեզ:',
    seoTitle: 'Տուրիզմի Գործակալությունների Համար | Zont',
    seoDesc: 'Տրանսպորտային ծառայություն տուրիստական գործակալությունների համար:',
    relatedTitle: 'Կապված Էջեր',
  },
};

const seoUrls = { en: '/tour-operators', fr: '/tour-operators', ru: '/tour-operators' };
const relatedPages = [
  { path: '/travel-agencies', name: 'Travel Agencies', tagline: 'Airport transfer partnership' },
  { path: '/tourism-agencies', name: 'Tourism Agencies', tagline: 'Private transport solutions' },
  { path: '/hotels', name: 'Hotels', tagline: 'Guest transfer services' },
];

const TourOperators = () => <B2BPage content={content} seoUrls={seoUrls} relatedPages={relatedPages} />;
export default TourOperators;
