import B2BPage from '@/components/B2BPage';

const content = {
  en: {
    seoTitle: 'Private Transport Solutions for Tourism Agencies | Zont B2B',
    seoDesc: 'Zont provides private transport solutions for tourism agencies. Airport transfers, city tours, intercity travel for tourists visiting Paris, France and Europe.',
    badge: 'Tourism Agency Solutions',
    heroTitle: 'Private Transport Solutions for Tourism Agencies',
    heroSub: 'Deliver unforgettable travel experiences with premium ground transportation. From airport pickups to city-to-city transfers, Zont handles the logistics so you can focus on crafting exceptional tours.',
    ctaPartner: 'Become a Partner',
    ctaQuote: 'Request Tourism Rates',
    heroStats: [
      { value: '15+', label: 'Countries Covered' },
      { value: '24/7', label: 'Booking Available' },
      { value: '16', label: 'Max Passengers' },
      { value: '60min', label: 'Free Wait Time' },
    ],
    benefitsTitle: 'Built for Tourism Professionals',
    benefitsSub: 'Ground transportation that enhances every tourist experience',
    benefits: [
      { title: 'Tourist-Friendly Drivers', desc: 'Multilingual chauffeurs who understand tourism. They know the best routes, local tips and how to welcome international visitors.' },
      { title: 'Flexible Scheduling', desc: 'Tourism plans change. Our booking system adapts to last-minute modifications, additional stops and schedule shifts.' },
      { title: 'Multi-Destination Coordination', desc: 'Manage transfers across multiple cities and countries from a single point of contact. Paris today, Nice tomorrow, Monaco next.' },
      { title: 'Airport Meet & Greet', desc: 'Professional welcome with name sign at arrivals. Luggage assistance and smooth handoff to comfortable vehicle.' },
      { title: 'Diverse Vehicle Fleet', desc: 'Sedans for couples, minivans for families, minibuses for groups. Every tourist profile covered with the right vehicle.' },
      { title: 'Volume Discounts', desc: 'Competitive rates that improve with volume. The more you book, the more you save for your tourism business.' },
    ],
    servicesTitle: 'Transport for Every Tourism Scenario',
    servicesSub: 'Comprehensive mobility solutions for your tourism operations',
    services: [
      { title: 'Airport Arrival Transfers', desc: 'Welcome tourists from day one with professional airport pickups across Europe.' },
      { title: 'Sightseeing Transportation', desc: 'Chauffeur at disposal for city tours, wine regions, historical sites and cultural experiences.' },
      { title: 'Intercity Transfers', desc: 'Comfortable long-distance transfers between cities: Paris-Versailles, Nice-Monaco, Rome-Florence.' },
      { title: 'Hotel-to-Station Transfers', desc: 'Reliable transfers between hotels and train stations for multi-city European tours.' },
    ],
    howTitle: 'How We Support Tourism Agencies',
    howSteps: [
      { title: 'Share Your Programs', desc: 'Tell us about your tour itineraries and transport needs.' },
      { title: 'Custom Quote', desc: 'Receive tailored pricing for your specific routes and volumes.' },
      { title: 'Seamless Coordination', desc: 'We assign drivers, track flights and manage all logistics.' },
      { title: 'Happy Tourists', desc: 'Your tourists enjoy premium transfers at every touchpoint.' },
    ],
    trustTitle: 'Trusted by Tourism Professionals',
    trustSub: '',
    trustPoints: [
      { value: '120+', label: 'European Cities' },
      { value: '15+', label: 'Countries' },
      { value: '6', label: 'Languages Spoken' },
      { value: '99%', label: 'Satisfaction Rate' },
    ],
    relatedTitle: 'Explore Related Solutions',
    contactTitle: 'Partner With Zont for Tourism Transport',
    contactSub: 'Describe your tourism programs, destinations and expected passenger volumes. We will prepare a comprehensive proposal.',
    formSubmit: 'Request Tourism Partnership',
    backToPartners: 'Back to All Professional Solutions',
  },
  fr: {
    seoTitle: 'Solutions de Transport Prive pour Agences de Tourisme | Zont B2B',
    seoDesc: 'Zont fournit des solutions de transport prive pour les agences de tourisme. Transferts aeroport, circuits, voyages interurbains pour touristes en France et en Europe.',
    badge: 'Solutions Agences de Tourisme',
    heroTitle: 'Solutions de Transport Prive pour Agences de Tourisme',
    heroSub: 'Offrez des experiences de voyage inoubliables avec un transport terrestre premium. Des transferts aeroport aux trajets interurbains, Zont gere la logistique pour que vous puissiez creer des circuits exceptionnels.',
    ctaPartner: 'Devenir Partenaire',
    ctaQuote: 'Demander les Tarifs Tourisme',
    heroStats: [
      { value: '15+', label: 'Pays Couverts' },
      { value: '24/7', label: 'Reservation Disponible' },
      { value: '16', label: 'Passagers Max' },
      { value: '60min', label: 'Attente Gratuite' },
    ],
    benefitsTitle: 'Concu pour les Professionnels du Tourisme',
    benefitsSub: 'Un transport terrestre qui sublime chaque experience touristique',
    benefits: [
      { title: 'Chauffeurs Orientes Tourisme', desc: 'Chauffeurs multilingues qui comprennent le tourisme. Ils connaissent les meilleurs itineraires et accueillent les visiteurs internationaux.' },
      { title: 'Planification Flexible', desc: 'Les plans touristiques changent. Notre systeme s\'adapte aux modifications de derniere minute et arrets supplementaires.' },
      { title: 'Coordination Multi-Destinations', desc: 'Gerez les transferts dans plusieurs villes et pays depuis un seul interlocuteur. Paris aujourd\'hui, Nice demain.' },
      { title: 'Accueil Aeroport', desc: 'Accueil professionnel avec panneau nominatif aux arrivees. Assistance bagages et transfert confortable.' },
      { title: 'Flotte Diversifiee', desc: 'Berlines pour couples, minivans pour familles, minibus pour groupes. Chaque profil touristique couvert.' },
      { title: 'Remises Volume', desc: 'Tarifs competitifs qui s\'ameliorent avec le volume. Plus vous reservez, plus vous economisez.' },
    ],
    servicesTitle: 'Transport pour Chaque Scenario Touristique',
    servicesSub: 'Solutions de mobilite completes pour vos operations touristiques',
    services: [
      { title: 'Transferts Arrivee Aeroport', desc: 'Accueillez les touristes des le premier jour avec des transferts professionnels.' },
      { title: 'Transport Touristique', desc: 'Chauffeur a disposition pour circuits, regions viticoles, sites historiques.' },
      { title: 'Transferts Interurbains', desc: 'Transferts confortables entre villes : Paris-Versailles, Nice-Monaco.' },
      { title: 'Transferts Hotel-Gare', desc: 'Transferts fiables entre hotels et gares pour circuits europeens multi-villes.' },
    ],
    howTitle: 'Comment Nous Accompagnons les Agences',
    howSteps: [
      { title: 'Partagez Vos Programmes', desc: 'Parlez-nous de vos itineraires et besoins de transport.' },
      { title: 'Devis Personnalise', desc: 'Recevez des tarifs adaptes a vos routes et volumes specifiques.' },
      { title: 'Coordination Fluide', desc: 'Nous assignons les chauffeurs et gerons toute la logistique.' },
      { title: 'Touristes Satisfaits', desc: 'Vos touristes profitent de transferts premium a chaque etape.' },
    ],
    trustTitle: 'La Confiance des Professionnels du Tourisme',
    trustSub: '',
    trustPoints: [
      { value: '120+', label: 'Villes Europeennes' },
      { value: '15+', label: 'Pays' },
      { value: '6', label: 'Langues Parlees' },
      { value: '99%', label: 'Taux de Satisfaction' },
    ],
    contactTitle: 'Partenariat Transport Touristique',
    contactSub: 'Decrivez vos programmes touristiques et volumes attendus. Nous preparerons une proposition complete.',
    formSubmit: 'Demander le Partenariat Tourisme',
    backToPartners: 'Retour aux Solutions Professionnelles',
  },
  ru: {
    seoTitle: 'Частный Транспорт для Туристических Агентств | Zont B2B',
    seoDesc: 'Zont предоставляет решения частного транспорта для туристических агентств. Трансферы, экскурсии, междугородние поездки по Франции и Европе.',
    badge: 'Решения для Турагентств',
    heroTitle: 'Решения Частного Транспорта для Туристических Агентств',
    heroSub: 'Создавайте незабываемые впечатления от путешествий с премиальным наземным транспортом. Zont берет на себя логистику.',
    ctaPartner: 'Стать Партнером', ctaQuote: 'Запросить Тарифы',
    heroStats: [{ value: '15+', label: 'Стран' }, { value: '24/7', label: 'Бронирование' }, { value: '16', label: 'Макс. Пассажиров' }, { value: '60мин', label: 'Бесплатное Ожидание' }],
    benefitsTitle: 'Создано для Профессионалов Туризма', benefitsSub: 'Наземный транспорт, улучшающий каждый туристический опыт',
    benefits: [
      { title: 'Водители для Туристов', desc: 'Многоязычные шоферы, знающие лучшие маршруты и умеющие встречать международных гостей.' },
      { title: 'Гибкое Планирование', desc: 'Система адаптируется к изменениям, дополнительным остановкам и корректировкам расписания.' },
      { title: 'Мульти-Направления', desc: 'Управляйте трансферами в нескольких городах и странах через одного координатора.' },
      { title: 'Встреча в Аэропорту', desc: 'Профессиональная встреча с табличкой. Помощь с багажом.' },
      { title: 'Разнообразный Автопарк', desc: 'Седаны для пар, минивэны для семей, микроавтобусы для групп.' },
      { title: 'Скидки за Объем', desc: 'Тарифы улучшаются с ростом объемов бронирований.' },
    ],
    servicesTitle: 'Транспорт для Туризма', servicesSub: 'Комплексные решения мобильности',
    services: [
      { title: 'Трансферы из Аэропорта', desc: 'Встречайте туристов профессиональными трансферами.' },
      { title: 'Экскурсионный Транспорт', desc: 'Шофер в распоряжении для городских туров и культурных объектов.' },
      { title: 'Междугородние Трансферы', desc: 'Комфортные поездки между городами.' },
      { title: 'Отель-Вокзал', desc: 'Надежные трансферы для мультигородских туров.' },
    ],
    howTitle: 'Как Мы Помогаем Агентствам',
    howSteps: [
      { title: 'Поделитесь Программами', desc: 'Расскажите об итинерарах и потребностях.' },
      { title: 'Персональное Предложение', desc: 'Индивидуальные тарифы для ваших маршрутов.' },
      { title: 'Координация', desc: 'Мы назначаем водителей и управляем логистикой.' },
      { title: 'Довольные Туристы', desc: 'Премиальные трансферы на каждом этапе.' },
    ],
    trustTitle: 'Доверие Профессионалов Туризма', trustSub: '',
    trustPoints: [{ value: '120+', label: 'Городов' }, { value: '15+', label: 'Стран' }, { value: '6', label: 'Языков' }, { value: '99%', label: 'Удовлетворенность' }],
    contactTitle: 'Партнерство для Туристического Транспорта',
    contactSub: 'Опишите ваши программы и ожидаемые объемы.',
    formSubmit: 'Запросить Партнерство', backToPartners: 'Назад ко Всем Решениям',
  },
};

const seoUrls = { en: '/tourism-agencies', fr: '/tourism-agencies', ru: '/tourism-agencies' };
const relatedPages = [
  { path: '/travel-agencies', name: 'Travel Agencies', tagline: 'Airport transfer partnership' },
  { path: '/tour-operators', name: 'Tour Operators', tagline: 'Tour logistics partner' },
  { path: '/hotels', name: 'Hotels', tagline: 'Guest transfer services' },
];

const TourismAgencies = () => <B2BPage content={content} seoUrls={seoUrls} relatedPages={relatedPages} />;
export default TourismAgencies;
