import B2BPage from '@/components/B2BPage';

const content = {
  en: {
    seoTitle: 'Airport Transfer Partner for Travel Agencies | Zont B2B',
    seoDesc: 'Partner with Zont for reliable airport transfers for your travel agency clients. Fixed rates, flight tracking, meet & greet. Dedicated B2B support for agencies.',
    badge: 'Travel Agency Partnership',
    heroTitle: 'Airport Transfer Partner for Travel Agencies',
    heroSub: 'Enhance your travel packages with premium airport transfers. Zont provides reliable, fixed-price chauffeur services that seamlessly integrate into your agency offerings across 120+ European cities.',
    ctaPartner: 'Become a Partner',
    ctaQuote: 'Request Agency Rates',
    heroStats: [
      { value: '120+', label: 'Cities in Europe' },
      { value: '24h', label: 'Quote Response' },
      { value: '4.9/5', label: 'Traveler Rating' },
      { value: '0', label: 'Hidden Fees' },
    ],
    benefitsTitle: 'Why Agencies Choose Zont',
    benefitsSub: 'A transport partner that strengthens your travel packages and client satisfaction',
    benefits: [
      { title: 'Seamless Package Integration', desc: 'Add premium airport transfers to your travel packages effortlessly. One booking, one invoice, zero complications for your team.' },
      { title: 'Competitive B2B Rates', desc: 'Exclusive partner pricing that lets you maintain healthy margins while offering clients premium service.' },
      { title: 'Reliable Client Handoff', desc: 'Your clients are greeted by name at arrivals. Professional meet & greet ensures a smooth transition from airport to destination.' },
      { title: 'Real-Time Flight Monitoring', desc: 'We track every flight automatically. Early arrivals or delays are handled seamlessly with no extra cost.' },
      { title: 'Bulk & Recurring Bookings', desc: 'Streamlined booking process for high-volume agencies. Manage multiple transfers from a single dashboard.' },
      { title: 'White-Glove Client Experience', desc: 'Premium vehicles, professional chauffeurs, complimentary water. Every transfer reinforces your agency brand.' },
    ],
    servicesTitle: 'Transfer Solutions for Agencies',
    servicesSub: 'Everything your agency needs to offer world-class ground transportation',
    services: [
      { title: 'Airport-to-Hotel Transfers', desc: 'Reliable point-to-point transfers from all major airports to client accommodations.' },
      { title: 'Return Airport Transfers', desc: 'On-time pickups from hotels to airports. Flight-time adjusted scheduling.' },
      { title: 'Multi-Leg Itineraries', desc: 'Complex routing for travel packages: airport, hotel, sightseeing, return. All coordinated.' },
      { title: 'Group Travel Logistics', desc: 'Vehicles from sedans to minibuses. Coordinated transport for groups of any size.' },
    ],
    howTitle: 'How Agency Partnership Works',
    howSteps: [
      { title: 'Register as Partner', desc: 'Quick onboarding with dedicated account manager.' },
      { title: 'Get B2B Rates', desc: 'Receive competitive pricing for all destinations.' },
      { title: 'Book for Clients', desc: 'Easy booking via portal, email or phone.' },
      { title: 'Clients Travel in Style', desc: 'Premium experience that reflects on your agency.' },
    ],
    trustTitle: 'Numbers That Agencies Trust',
    trustSub: '',
    trustPoints: [
      { value: '50K+', label: 'Transfers Completed' },
      { value: '500+', label: 'Agency Partners' },
      { value: '99.2%', label: 'On-Time Rate' },
      { value: '<2h', label: 'Support Response' },
    ],
    relatedTitle: 'Solutions for Related Industries',
    relatedSub: 'Discover how Zont serves other professional sectors',
    contactTitle: 'Partner With Zont for Your Agency',
    contactSub: 'Tell us about your agency, travel destinations, and expected booking volume. We will prepare tailored B2B rates.',
    formSubmit: 'Request Agency Partnership',
    backToPartners: 'Back to All Professional Solutions',
  },
  fr: {
    seoTitle: 'Partenaire Transfert Aeroport pour Agences de Voyage | Zont B2B',
    seoDesc: 'Devenez partenaire Zont pour des transferts aeroport fiables pour les clients de votre agence de voyage. Tarifs fixes, suivi de vol, accueil personnalise.',
    badge: 'Partenariat Agences de Voyage',
    heroTitle: 'Partenaire Transfert Aeroport pour Agences de Voyage',
    heroSub: 'Enrichissez vos packages de voyage avec des transferts aeroport premium. Zont propose des services chauffeur fiables et a prix fixe qui s\'integrent parfaitement a vos offres dans plus de 120 villes europeennes.',
    ctaPartner: 'Devenir Partenaire',
    ctaQuote: 'Demander les Tarifs Agence',
    heroStats: [
      { value: '120+', label: 'Villes en Europe' },
      { value: '24h', label: 'Reponse Devis' },
      { value: '4.9/5', label: 'Note Voyageurs' },
      { value: '0', label: 'Frais Caches' },
    ],
    benefitsTitle: 'Pourquoi les Agences Choisissent Zont',
    benefitsSub: 'Un partenaire transport qui renforce vos packages et la satisfaction client',
    benefits: [
      { title: 'Integration Sans Effort', desc: 'Ajoutez des transferts premium a vos packages voyage sans complication. Une reservation, une facture.' },
      { title: 'Tarifs B2B Competitifs', desc: 'Prix exclusifs partenaire qui vous permettent de maintenir des marges saines tout en offrant un service premium.' },
      { title: 'Accueil Client Fiable', desc: 'Vos clients sont accueillis par leur nom a l\'arrivee. Service d\'accueil professionnel pour une transition fluide.' },
      { title: 'Suivi de Vol en Temps Reel', desc: 'Nous suivons chaque vol automatiquement. Arrivees anticipees ou retards geres sans cout supplementaire.' },
      { title: 'Reservations en Volume', desc: 'Processus simplifie pour les agences a fort volume. Gerez plusieurs transferts depuis un seul tableau de bord.' },
      { title: 'Experience Client Premium', desc: 'Vehicules premium, chauffeurs professionnels. Chaque transfert renforce l\'image de votre agence.' },
    ],
    servicesTitle: 'Solutions de Transfert pour Agences',
    servicesSub: 'Tout ce dont votre agence a besoin pour un transport terrestre de classe mondiale',
    services: [
      { title: 'Transferts Aeroport-Hotel', desc: 'Transferts fiables point a point depuis tous les grands aeroports vers les hebergements clients.' },
      { title: 'Transferts Retour Aeroport', desc: 'Prises en charge ponctuelles des hotels vers les aeroports. Horaires ajustes selon les vols.' },
      { title: 'Itineraires Multi-Etapes', desc: 'Routage complexe pour packages : aeroport, hotel, visites, retour. Tout coordonne.' },
      { title: 'Logistique Groupes', desc: 'Berlines aux minibus. Transport coordonne pour groupes de toute taille.' },
    ],
    howTitle: 'Comment Fonctionne le Partenariat',
    howSteps: [
      { title: 'Inscrivez-vous', desc: 'Integration rapide avec gestionnaire de compte dedie.' },
      { title: 'Obtenez les Tarifs B2B', desc: 'Recevez des prix competitifs pour toutes les destinations.' },
      { title: 'Reservez pour vos Clients', desc: 'Reservation facile via portail, email ou telephone.' },
      { title: 'Vos Clients Voyagent en Style', desc: 'Experience premium qui rejaillit sur votre agence.' },
    ],
    trustTitle: 'Des Chiffres qui Inspirent Confiance',
    trustSub: '',
    trustPoints: [
      { value: '50 000+', label: 'Transferts Realises' },
      { value: '500+', label: 'Agences Partenaires' },
      { value: '99,2%', label: 'Taux de Ponctualite' },
      { value: '<2h', label: 'Reponse Support' },
    ],
    relatedTitle: 'Solutions pour Secteurs Connexes',
    relatedSub: 'Decouvrez comment Zont sert d\'autres secteurs professionnels',
    contactTitle: 'Partenariat Zont pour Votre Agence',
    contactSub: 'Parlez-nous de votre agence, destinations et volume de reservations attendu. Nous preparerons des tarifs B2B personnalises.',
    formSubmit: 'Demander le Partenariat Agence',
    backToPartners: 'Retour aux Solutions Professionnelles',
  },
  ru: {
    seoTitle: 'Партнер по Трансферам для Туристических Агентств | Zont B2B',
    seoDesc: 'Станьте партнером Zont для надежных трансферов из аэропорта для клиентов вашего турагентства. Фиксированные тарифы, отслеживание рейсов, встреча.',
    badge: 'Партнерство для Турагентств',
    heroTitle: 'Партнер по Трансферам для Туристических Агентств',
    heroSub: 'Усильте ваши турпакеты премиальными трансферами из аэропорта. Zont предоставляет надежные услуги шофера по фиксированным ценам в 120+ европейских городах.',
    ctaPartner: 'Стать Партнером',
    ctaQuote: 'Запросить Тарифы для Агентств',
    heroStats: [
      { value: '120+', label: 'Городов в Европе' },
      { value: '24ч', label: 'Ответ на Запрос' },
      { value: '4.9/5', label: 'Рейтинг Путешественников' },
      { value: '0', label: 'Скрытых Комиссий' },
    ],
    benefitsTitle: 'Почему Агентства Выбирают Zont',
    benefitsSub: 'Транспортный партнер, который укрепляет ваши турпакеты',
    benefits: [
      { title: 'Бесшовная Интеграция', desc: 'Добавляйте трансферы в турпакеты без сложностей. Одно бронирование, один счет.' },
      { title: 'Конкурентные B2B Тарифы', desc: 'Эксклюзивные партнерские цены с сохранением здоровой маржи.' },
      { title: 'Надежная Встреча Клиентов', desc: 'Ваших клиентов встречают по имени в зоне прилета. Профессиональный сервис встречи.' },
      { title: 'Мониторинг Рейсов', desc: 'Автоматическое отслеживание всех рейсов. Ранние прилеты и задержки без доплат.' },
      { title: 'Массовые Бронирования', desc: 'Упрощенный процесс для агентств с большим объемом. Управление через единую панель.' },
      { title: 'Премиальный Клиентский Опыт', desc: 'Премиальные авто, профессиональные шоферы. Каждый трансфер укрепляет бренд агентства.' },
    ],
    servicesTitle: 'Решения для Агентств',
    servicesSub: 'Всё для наземного транспорта мирового класса',
    services: [
      { title: 'Трансферы Аэропорт-Отель', desc: 'Надежные трансферы из аэропортов к размещению клиентов.' },
      { title: 'Обратные Трансферы', desc: 'Пунктуальные подачи из отелей в аэропорты.' },
      { title: 'Многоэтапные Маршруты', desc: 'Сложная маршрутизация: аэропорт, отель, экскурсии, возврат.' },
      { title: 'Групповая Логистика', desc: 'От седанов до микроавтобусов. Координация для групп любого размера.' },
    ],
    howTitle: 'Как Работает Партнерство',
    howSteps: [
      { title: 'Регистрация', desc: 'Быстрый онбординг с выделенным менеджером.' },
      { title: 'B2B Тарифы', desc: 'Конкурентные цены для всех направлений.' },
      { title: 'Бронирование для Клиентов', desc: 'Простое бронирование через портал, email или телефон.' },
      { title: 'Клиенты Путешествуют с Комфортом', desc: 'Премиальный опыт, отражающий качество вашего агентства.' },
    ],
    trustTitle: 'Цифры, Которым Доверяют Агентства',
    trustSub: '',
    trustPoints: [
      { value: '50 000+', label: 'Трансферов' },
      { value: '500+', label: 'Агентств-Партнеров' },
      { value: '99,2%', label: 'Пунктуальность' },
      { value: '<2ч', label: 'Ответ Поддержки' },
    ],
    relatedTitle: 'Решения для Смежных Отраслей',
    contactTitle: 'Партнерство Zont для Вашего Агентства',
    contactSub: 'Расскажите о вашем агентстве и ожидаемых объемах бронирований.',
    formSubmit: 'Запросить Партнерство',
    backToPartners: 'Назад ко Всем Решениям',
  },
  hy: {
    heroTitle: 'Տուրիստական Գործակալությունների Համար',
    heroSub: 'Առաջարկեք պրեմիում տրանսֆերներ ձեր հաճախորդներին: Հաստատ գներ, պրեմիում մեքենաներ 120+ քաղաքներում:',
    heroBtn: 'Ստանալ Առաջարկություն',
    benefits: [
      { title: 'Սպասարկում Սպասեմ', desc: 'Ձեր հաճախորդներին պատրաստենք հանգիստ օդանավակայանի տրանսֆեր ամեն տեղ:' },
      { title: 'Պրեմիում Մեքենաներ', desc: 'Վերջին կարգի Mercedes, BMW, Վաններ և մինիբուսներ:' },
      { title: 'Պարզ API Ինտեգրացիա', desc: 'Ավտոմատացրեք ձեր ամրագրումները մեր API-ի միջոցով:' },
      { title: 'Հատուկ Կոմիսիա', desc: 'Առանձին միջնորդավար տոկոսադրույք յուրաքանչյուր վաճառքին համար:' },
    ],
    trustTitle: 'Թվեր Որոնց Գործակալությունները Վստահում Են',
    trustSub: '',
    trustPoints: [
      { v: '500+', l: 'Գործընկեր Գործակալություններ' },
      { v: '120+', l: 'Քաղաքներ' },
      { v: '24/7', l: 'Աջակցություն' },
      { v: '98%', l: 'Գոհունակություն' },
    ],
    formTitle: 'Ստանալ Առաջարկություն',
    formSub: 'Լրացրեք ստորև ձևը և մենք կկապվենք 24 ժամվա ընթացքում:',
    name: 'Անուն *', company: 'Ընկերություն *', email: 'Email *', phone: 'Հեռախոս *',
    message: 'Հաղորդագրություն',
    messagePh: 'Պատմեք ձեր կարիքները...',
    submit: 'Ուղարկել Հարցումը', sending: 'Ուղարկվում է...',
    successTitle: 'Հաղորդագրությունը ուղարկվեց!',
    successDesc: 'Մեր թիմը կկապվի ձեզ:',
    seoTitle: 'Տուրիստական Գործակալությունների Համար | Zont',
    seoDesc: 'Պրեմիում տրանսպորտային ծառայություն տուրիստական գործակալությունների համար:',
    relatedTitle: 'Կապված Էջեր',
  },
};

const seoUrls = { en: '/travel-agencies', fr: '/travel-agencies', ru: '/travel-agencies' };

const relatedPages = [
  { path: '/tourism-agencies', name: 'Tourism Agencies', tagline: 'Private transport for tourism' },
  { path: '/tour-operators', name: 'Tour Operators', tagline: 'Logistics for tour programs' },
  { path: '/corporate-clients', name: 'Corporate Clients', tagline: 'Business travel services' },
];

const TravelAgencies = () => <B2BPage content={content} seoUrls={seoUrls} relatedPages={relatedPages} />;
export default TravelAgencies;
