// Driver At Disposal — Vehicle catalogue + multilingual content
// Pricing left as TBD placeholders — to be filled by the user later.

export const DURATIONS = ['4h', '8h', '12h'];

// Slug map per language, used for URL routing & internal links.
export const VEHICLE_SLUGS = {
  'mercedes-s-class': {
    en: 'mercedes-s-class',
    fr: 'mercedes-classe-s',
    ru: 'mercedes-s-class',
    hy: 'mercedes-s-class',
  },
  'mercedes-e-class': {
    en: 'mercedes-e-class',
    fr: 'mercedes-classe-e',
    ru: 'mercedes-e-class',
    hy: 'mercedes-e-class',
  },
  'mercedes-v-class': {
    en: 'mercedes-v-class',
    fr: 'mercedes-classe-v',
    ru: 'mercedes-v-class',
    hy: 'mercedes-v-class',
  },
  'renault-trafic': {
    en: 'renault-trafic',
    fr: 'renault-trafic',
    ru: 'renault-trafic',
    hy: 'renault-trafic',
  },
};

export const DISPOSAL_BASE_PATH = {
  en: '/driver-at-disposal',
  fr: '/chauffeur-mis-a-disposition',
  ru: '/voditel-s-avtomobilem',
  hy: '/varorde-tramadrutyamb',
};

export const VEHICLES = [
  {
    id: 'mercedes-s-class',
    image: '/images/mercedes-classe-s-chauffeur-prive-paris.webp',
    pax: 3,
    luggage: 3,
    tier: 'flagship',
    badge: { en: 'Flagship', fr: 'Vaisseau amiral', ru: 'Флагман', hy: 'Դրոշակակիր' },
    name: { en: 'Mercedes-Benz S-Class', fr: 'Mercedes Classe S', ru: 'Mercedes S-Class', hy: 'Mercedes S-Class' },
    tagline: {
      en: 'The ultimate executive limousine for VIP & diplomatic travel in Paris.',
      fr: 'La limousine executive ultime pour voyages VIP & diplomatiques a Paris.',
      ru: 'Премиальный седан для VIP и дипломатических поездок в Париже.',
      hy: 'Բարձրակարգ լիմուզին VIP և դիվանագիտական ուղևորությունների համար Փարիզում.',
    },
    pricing: { '4h': null, '8h': null, '12h': null }, // TBD — user will provide
  },
  {
    id: 'mercedes-e-class',
    image: '/images/mercedes-classe-e-chauffeur-prive-paris.webp',
    pax: 3,
    luggage: 3,
    tier: 'business',
    badge: { en: 'Business', fr: 'Affaires', ru: 'Бизнес', hy: 'Բիզնես' },
    name: { en: 'Mercedes-Benz E-Class', fr: 'Mercedes Classe E', ru: 'Mercedes E-Class', hy: 'Mercedes E-Class' },
    tagline: {
      en: 'The reference business sedan for executives, meetings and city tours.',
      fr: 'La berline business de reference pour cadres, rendez-vous et tours de ville.',
      ru: 'Эталонный бизнес-седан для деловых встреч и поездок по городу.',
      hy: 'Բիզնես սեդանի չափանիշը գործնական հանդիպումների և քաղաքային ուղևորությունների համար.',
    },
    pricing: { '4h': null, '8h': null, '12h': null },
  },
  {
    id: 'mercedes-v-class',
    image: '/images/mercedes-classe-v-chauffeur-prive-paris.webp',
    pax: 7,
    luggage: 7,
    tier: 'premium-van',
    badge: { en: 'Premium Van', fr: 'Van Premium', ru: 'Премиум Вэн', hy: 'Պրեմիում Վեն' },
    name: { en: 'Mercedes-Benz V-Class', fr: 'Mercedes Classe V', ru: 'Mercedes V-Class', hy: 'Mercedes V-Class' },
    tagline: {
      en: 'Spacious 7-seat luxury van — ideal for families, delegations and city tours.',
      fr: 'Van de luxe 7 places — ideal pour familles, delegations et tours de ville.',
      ru: 'Просторный люксовый вэн на 7 мест — для семей, делегаций и экскурсий.',
      hy: 'Ընդարձակ 7 տեղանոց պրեմիում վեն ընտանիքների ու պատվիրակությունների համար.',
    },
    pricing: { '4h': null, '8h': null, '12h': null },
  },
  {
    id: 'renault-trafic',
    image: '/images/renault-trafic-minibus-chauffeur-paris.webp',
    pax: 8,
    luggage: 8,
    tier: 'minibus',
    badge: { en: 'Minibus 8', fr: 'Minibus 8', ru: 'Минибус 8', hy: 'Մինիբուս 8' },
    name: { en: 'Renault Trafic', fr: 'Renault Trafic', ru: 'Renault Trafic', hy: 'Renault Trafic' },
    tagline: {
      en: 'The smart eco van — comfort, capacity and fixed pricing for groups up to 8.',
      fr: 'Le van eco intelligent — confort, capacite et prix fixe pour groupes jusqu\'a 8.',
      ru: 'Умный эко-вэн — комфорт и фиксированная цена для групп до 8 человек.',
      hy: 'Խելացի էկո վեն՝ հարմարավետություն և ֆիքսված գին մինչև 8 հոգու համար.',
    },
    pricing: { '4h': null, '8h': null, '12h': null },
  },
];

// Long-form SEO copy per vehicle, per language.
// Each entry contains hero claims and SEO-rich body paragraphs.
export const VEHICLE_COPY = {
  'mercedes-s-class': {
    en: {
      h1: 'Mercedes S-Class — Private Chauffeur Service in Paris',
      hero: 'Hourly chauffeur rental in a flagship Mercedes-Benz S-Class. The benchmark of automotive luxury for executives, diplomats, weddings and red-carpet evenings across Paris and Ile-de-France.',
      p1: 'The Mercedes S-Class is the unspoken language of business success. Behind its sculpted silhouette and signature three-pointed star, you find Burmester sound, Magic Body Control suspension that scans the road ahead, reclining rear seats with massage function, and a cabin so quiet you can close a deal over the phone between place Vendome and La Defense without raising your voice. Our chauffeur-driven Mercedes S-Class fleet is reserved for clients who refuse compromise: every vehicle is the latest long-wheelbase generation, polished daily, equipped with chilled bottled water, on-board Wi-Fi, and rear privacy glass.',
      p2: 'Hire a Mercedes S-Class with private driver in Paris by the hour, half-day or full day. Whether you need a discreet transfer from Le Bourget to a private meeting at the Plaza Athenee, a multi-stop investor roadshow through the 8th and 16th arrondissements, or a wedding car with a chauffeur in tailcoat from your hotel to the Mairie, the S-Class is the only answer worth giving. Our drivers are licensed VTC (chauffeur prive) professionals, multilingual, trained to anticipate — they will open the door before you reach it, hold an umbrella above your shoulder, and know which stairwell at Roland-Garros gets you to the players\' box without crossing the public.',
      p3: 'Pricing is transparent and confirmed at booking — no surge, no waiting fees, no kilometre caps within the city. The S-Class hourly rate includes fuel, tolls, parking, water, Wi-Fi and a fully insured licensed driver. We accept Stripe online payment, corporate billing on account, and direct invoicing for travel agencies and hotel concierges. Premium business clients can request the same driver across multiple days for full discretion. Booking takes less than two minutes — pick your date, your duration (4h, 8h, or 12h), and we confirm by email and SMS within minutes.',
      faq: [
        { q: 'How many passengers can fit in an S-Class?', a: 'Up to 3 passengers with full comfort and 3 suitcases. For larger groups choose the V-Class.' },
        { q: 'Is the driver multilingual?', a: 'Yes — all our S-Class drivers speak French and English, with Russian, Spanish or Arabic available on request.' },
        { q: 'Can I book the same driver for several days?', a: 'Absolutely — return clients on multi-day disposal benefit from priority driver continuity.' },
      ],
    },
    fr: {
      h1: 'Mercedes Classe S — Chauffeur prive mis a disposition a Paris',
      hero: 'Location de chauffeur prive a l\'heure avec une Mercedes-Benz Classe S, vaisseau amiral de la marque. La reference du luxe automobile pour dirigeants, diplomates, mariages et grandes soirees a Paris et en Ile-de-France.',
      p1: 'La Mercedes Classe S est le langage non-dit de la reussite. Derriere sa silhouette sculptee et son etoile a trois branches, on trouve le son Burmester, la suspension Magic Body Control qui scanne la route, des sieges arriere inclinables avec fonction massage, et un habitacle si silencieux qu\'on peut conclure un contrat au telephone entre la place Vendome et La Defense sans elever la voix. Notre flotte de Mercedes Classe S avec chauffeur prive est reservee aux clients qui refusent le compromis : chaque vehicule est de la derniere generation longue, lave quotidiennement, equipe d\'eau minerale fraiche, Wi-Fi a bord et vitres arriere teintees.',
      p2: 'Louez une Mercedes Classe S avec chauffeur prive a Paris a l\'heure, en demi-journee ou journee complete. Que vous ayez besoin d\'un transfert discret du Bourget vers un rendez-vous prive au Plaza Athenee, d\'un roadshow investisseurs multi-arrets dans les 8e et 16e arrondissements, ou d\'une voiture de mariage avec chauffeur en habit jusqu\'a la Mairie : la Classe S est la seule reponse qui vaille. Nos chauffeurs sont des professionnels VTC agrees, multilingues, formes a anticiper — ils ouvriront la portiere avant que vous ne l\'atteigniez, tiendront un parapluie au-dessus de votre epaule, et connaissent l\'entree de Roland-Garros qui mene a la loge des joueurs sans passer par le public.',
      p3: 'Le tarif est transparent et confirme a la reservation — pas de surge, pas de frais d\'attente, pas de plafond kilometrique en ville. Le tarif horaire Classe S comprend le carburant, les peages, le stationnement, l\'eau, le Wi-Fi et un chauffeur agree integralement assure. Nous acceptons le paiement en ligne Stripe, la facturation entreprise sur compte, et la facturation directe pour agences de voyage et concierges hoteliers. Les clients premium peuvent demander le meme chauffeur sur plusieurs jours pour une discretion totale. La reservation prend moins de deux minutes — choisissez votre date, votre duree (4h, 8h ou 12h), nous confirmons par email et SMS en quelques minutes.',
      faq: [
        { q: 'Combien de passagers dans une Classe S ?', a: 'Jusqu\'a 3 passagers en plein confort avec 3 valises. Pour les groupes plus importants, choisissez la Classe V.' },
        { q: 'Le chauffeur est-il multilingue ?', a: 'Oui — tous nos chauffeurs Classe S parlent francais et anglais, russe, espagnol ou arabe sur demande.' },
        { q: 'Puis-je reserver le meme chauffeur plusieurs jours ?', a: 'Bien sur — les clients en mise a disposition multi-jours beneficient d\'une continuite chauffeur prioritaire.' },
      ],
    },
    ru: {
      h1: 'Mercedes S-Class — Услуга личного водителя в Париже',
      hero: 'Почасовая аренда водителя на флагманском Mercedes-Benz S-Class. Эталон автомобильной роскоши для руководителей, дипломатов, свадеб и торжественных вечеров в Париже и Иль-де-Франс.',
      p1: 'Mercedes S-Class — это негласный язык успеха. За скульптурным силуэтом и трёхлучевой звездой скрыты акустика Burmester, подвеска Magic Body Control, сканирующая дорогу, откидные задние кресла с функцией массажа и салон настолько тихий, что вы можете обсудить сделку по телефону между Place Vendome и La Defense, не повышая голоса. Наш парк Mercedes S-Class с водителем зарезервирован для клиентов, не идущих на компромисс: только самое новое поколение длинной базы, ежедневная мойка, охлаждённая минеральная вода, бортовой Wi-Fi и тонированные задние стёкла.',
      p2: 'Арендуйте Mercedes S-Class с личным водителем в Париже на час, на полдня или на день. Будь то трансфер из Ле-Бурже на закрытую встречу в Plaza Athenee, road-show для инвесторов с множеством остановок в 8-м и 16-м округах, или свадебный автомобиль с водителем во фраке до мэрии — S-Class остаётся единственным достойным ответом. Наши водители — лицензированные VTC, многоязычные, профессионально обученные предугадывать каждое ваше движение.',
      p3: 'Цена прозрачна и подтверждается при бронировании — без скачков, без платы за ожидание, без лимита километров в черте города. В часовой тариф входят топливо, дороги, парковка, вода, Wi-Fi и водитель с полной страховкой. Принимаем оплату Stripe, корпоративные счета, прямой биллинг для турагентств и консьерж-сервисов. Бронирование занимает менее двух минут — выберите дату, длительность (4ч, 8ч или 12ч), мы подтвердим по e-mail и SMS.',
      faq: [
        { q: 'Сколько пассажиров вмещает S-Class?', a: 'До 3 пассажиров с максимальным комфортом и 3 чемоданами. Для больших групп выбирайте V-Class.' },
        { q: 'Водитель говорит на иностранных языках?', a: 'Да — все водители S-Class говорят по-французски и по-английски, русский, испанский или арабский — по запросу.' },
        { q: 'Можно ли заказать одного водителя на несколько дней?', a: 'Да, постоянным клиентам мы гарантируем приоритетную преемственность водителя.' },
      ],
    },
  },
  'mercedes-e-class': {
    en: {
      h1: 'Mercedes E-Class — Business Chauffeur Hire in Paris',
      hero: 'The most-booked business sedan in Paris. Hourly chauffeur rental in a Mercedes-Benz E-Class — refined, discreet, irreproachable for executives, lawyers and short-list candidates.',
      p1: 'The Mercedes E-Class is the standard of the European business world. Where the S-Class makes a statement, the E-Class quietly does the job — and that\'s precisely why it has been the favorite of executives, in-house counsel, M&A bankers and senior managers for two decades. Our chauffeur-driven E-Class fleet is composed of the latest long-wheelbase generation, all-LED matrix headlamps, soft Nappa leather, three-zone climate, and an interior whisper-quiet enough to hold a confidential call from Charles de Gaulle to the office without leaking a syllable.',
      p2: 'Hire a Mercedes E-Class with private driver in Paris by the hour. Typical missions include morning pick-up at your hotel, multiple meetings across La Defense, lunch at Costes, a 15h press call near the Champs-Elysees, dropping off at Gare du Nord for the 18:13 to Brussels — the driver waits for you, repositions the car between stops, handles the parking, and never bills extra. The same driver from start to finish means you can leave a laptop, a portfolio or a coat in the car between stops without a second thought.',
      p3: 'The E-Class is also the obvious choice for half-day Paris city tours: comfortable for 1 to 3 passengers, perfect for navigating the narrow streets of the Marais, the cobblestones of Montmartre, and the wider boulevards of the 16th. Our chauffeurs hold professional photography spots ready in advance — Pont Bir-Hakeim with the Eiffel Tower behind, the Trocadero esplanade at sunset, the Pont Alexandre III. Combine your tour with a 30-minute stop at Laduree for the perfect souvenir.',
      faq: [
        { q: 'How is the E-Class different from the S-Class?', a: 'Both are luxury sedans. E-Class is the business standard; S-Class is the executive flagship with extra interior length, massage seats and the highest level of refinement.' },
        { q: 'Can I split the day across multiple addresses?', a: 'Yes — the disposal package allows unlimited stops within your chosen duration.' },
      ],
    },
    fr: {
      h1: 'Mercedes Classe E — Chauffeur business mis a disposition a Paris',
      hero: 'La berline business la plus reservee de Paris. Location de chauffeur a l\'heure en Mercedes-Benz Classe E — raffinement, discretion et irreprochabilite pour cadres, avocats et candidats short-list.',
      p1: 'La Mercedes Classe E est le standard du monde des affaires europeen. La ou la Classe S affirme, la Classe E execute discretement — et c\'est precisement pour cela qu\'elle est le choix favori des dirigeants, juristes d\'entreprise, banquiers M&A et cadres superieurs depuis deux decennies. Notre flotte de Classe E avec chauffeur prive se compose de la derniere generation longue : phares matriciels LED, cuir Nappa souple, climatisation trois zones, et un habitacle suffisamment silencieux pour passer un appel confidentiel de Roissy au bureau sans qu\'une syllabe ne s\'echappe.',
      p2: 'Louez une Mercedes Classe E avec chauffeur prive a l\'heure a Paris. Missions typiques : prise en charge matinale a l\'hotel, rendez-vous successifs a La Defense, dejeuner au Costes, point presse a 15h pres des Champs-Elysees, depose Gare du Nord pour le 18h13 vers Bruxelles — le chauffeur vous attend, repositionne le vehicule entre les arrets, gere le stationnement, et ne facture rien de plus. Le meme chauffeur du debut a la fin signifie que vous pouvez laisser un ordinateur, un portfolio ou un manteau dans la voiture entre deux arrets sans une seconde d\'hesitation.',
      p3: 'La Classe E est aussi le choix evident pour un tour de Paris en demi-journee : confortable pour 1 a 3 passagers, parfaite pour traverser les rues etroites du Marais, les paves de Montmartre et les larges boulevards du 16e. Nos chauffeurs tiennent en reserve les meilleurs spots photo : Pont Bir-Hakeim avec la Tour Eiffel en arriere-plan, esplanade du Trocadero au coucher du soleil, Pont Alexandre III. Combinez votre tour avec un arret de 30 minutes chez Laduree pour le souvenir parfait.',
      faq: [
        { q: 'Quelle difference entre Classe E et Classe S ?', a: 'Les deux sont des berlines de luxe. La Classe E est le standard business ; la Classe S est le vaisseau amiral avec habitacle allonge, sieges massants et raffinement maximal.' },
        { q: 'Puis-je faire plusieurs arrets dans la journee ?', a: 'Oui — la mise a disposition permet un nombre illimite d\'arrets dans la duree choisie.' },
      ],
    },
    ru: {
      h1: 'Mercedes E-Class — Бизнес-водитель с автомобилем в Париже',
      hero: 'Самый востребованный бизнес-седан в Париже. Почасовая аренда водителя на Mercedes-Benz E-Class — изящество, сдержанность и безупречность для руководителей и юристов.',
      p1: 'Mercedes E-Class — стандарт европейского бизнес-мира. Если S-Class заявляет о себе, то E-Class тихо делает работу — именно поэтому он остаётся фаворитом руководителей и инхаус-юристов уже два десятилетия. Наш парк E-Class представлен новейшим поколением long-wheelbase: матричные LED-фары, мягкая кожа Nappa, трёхзонный климат-контроль и салон, настолько тихий, что вы можете говорить из Шарль-де-Голль с офисом, не опасаясь утечки ни единого слога.',
      p2: 'Арендуйте Mercedes E-Class с водителем в Париже на час. Типичные сценарии: утренний пикап в отеле, несколько встреч в La Defense, обед у Costes, пресс-конференция в 15:00 у Елисейских полей, высадка на Gare du Nord к 18:13 на Брюссель — водитель ждёт, перепарковывается между остановками, оплачивает стоянку и не выставляет дополнительных счетов.',
      p3: 'E-Class — очевидный выбор для полудневной экскурсии по Парижу: комфортно для 1–3 пассажиров, идеален для узких улочек Маре, брусчатки Монмартра и широких бульваров 16-го округа. Наши водители держат наготове лучшие фотоспоты: мост Бир-Хакейм с Эйфелевой башней, площадь Трокадеро на закате, мост Александра III.',
      faq: [
        { q: 'Чем E-Class отличается от S-Class?', a: 'Оба — премиум-седаны. E-Class — бизнес-стандарт; S-Class — флагман с увеличенным салоном и массажными креслами.' },
        { q: 'Можно ли делать много остановок?', a: 'Да — пакет «в распоряжении» позволяет неограниченное число остановок в пределах выбранного времени.' },
      ],
    },
  },
  'mercedes-v-class': {
    en: {
      h1: 'Mercedes V-Class — Luxury 7-Seat Chauffeur Van in Paris',
      hero: 'Hire a Mercedes-Benz V-Class with private driver by the hour in Paris. The flagship 7-seat luxury van — for families, delegations, weddings, film crews and small VIP groups.',
      p1: 'The Mercedes V-Class is the only van that has crossed into the luxury category. Inside, you discover Captain seats facing each other around a folding table, tinted privacy windows, three-zone climate, USB-C in every row, ambient lighting that adapts to the time of day, and electric sliding doors that open at the press of a button. Compared to the standard 7-seat minivan, the V-Class is wider, longer, taller and twice as quiet — which is why it has become the official vehicle of music tours, fashion houses, embassies, and luxury wedding planners.',
      p2: 'Book a Mercedes V-Class with chauffeur in Paris by the hour or full day. Up to 7 passengers travel in absolute comfort, with luggage space for 7 hard-shell cases, or alternatively 2 large flight cases for equipment. The V-Class is the obvious choice for a CEO travelling with their executive committee, a family with grandparents and small children visiting the Louvre, a film crew transferring between locations, or a wedding party moving from church to reception. With over 5 metres of cabin length and individually reclining rear seats, even an 8-hour day from Versailles to Giverny passes without fatigue.',
      p3: 'Our V-Class chauffeurs are senior drivers — minimum 5 years professional experience, English-speaking, trained in luxury hospitality. They will help children with car seats (provided free on request), assist elderly passengers in and out, secure musical instruments and camera equipment, and never refuse a last-minute stop at a pharmacy or a souvenir shop. The V-Class disposal package is the highest-rated service in our entire fleet — 4.9/5 over 400 bookings.',
      faq: [
        { q: 'How many passengers fit in a V-Class?', a: 'Up to 7 passengers plus the driver, with luggage space for 7 large suitcases.' },
        { q: 'Are child seats included?', a: 'Yes — baby seats, child seats and booster seats are available free on request.' },
        { q: 'Can the V-Class handle a long day trip to Mont-Saint-Michel or Champagne?', a: 'Absolutely — the 12-hour disposal is designed exactly for that scenario.' },
      ],
    },
    fr: {
      h1: 'Mercedes Classe V — Van de luxe 7 places avec chauffeur a Paris',
      hero: 'Louez une Mercedes-Benz Classe V avec chauffeur prive a l\'heure a Paris. Le van de luxe 7 places vaisseau amiral — pour familles, delegations, mariages, equipes de tournage et petits groupes VIP.',
      p1: 'La Mercedes Classe V est le seul van a avoir bascule dans la categorie luxe. A l\'interieur : sieges Captain face a face autour d\'une table escamotable, vitres teintees, climatisation trois zones, USB-C dans chaque rangee, eclairage d\'ambiance qui s\'adapte a l\'heure de la journee, portes coulissantes electriques qui s\'ouvrent au bouton. Comparee au minivan 7 places standard, la Classe V est plus large, plus longue, plus haute, et deux fois plus silencieuse — raison pour laquelle elle est devenue le vehicule officiel des tournees musicales, des maisons de couture, des ambassades et des wedding planners de luxe.',
      p2: 'Reservez une Mercedes Classe V avec chauffeur a Paris a l\'heure ou en journee complete. Jusqu\'a 7 passagers voyagent dans un confort absolu, avec un coffre pour 7 valises rigides, ou alternativement 2 grands flightcases d\'equipement. La Classe V est le choix evident pour un PDG voyageant avec son comite executif, une famille avec grands-parents et jeunes enfants visitant le Louvre, une equipe de tournage transferant entre lieux, ou un mariage entre l\'eglise et la reception. Avec plus de 5 metres d\'habitacle et des sieges arriere individuellement inclinables, meme une journee de 8h entre Versailles et Giverny se passe sans fatigue.',
      p3: 'Nos chauffeurs Classe V sont des chauffeurs seniors — 5 ans minimum d\'experience professionnelle, anglophones, formes a l\'hospitalite de luxe. Ils aideront les enfants avec les sieges auto (fournis gratuitement sur demande), aideront les passagers ages a monter et descendre, securiseront instruments de musique et materiel photo, et ne refuseront jamais un arret de derniere minute en pharmacie ou en boutique souvenir. La mise a disposition Classe V est le service le mieux note de toute notre flotte — 4,9/5 sur 400+ reservations.',
      faq: [
        { q: 'Combien de passagers tiennent en Classe V ?', a: 'Jusqu\'a 7 passagers plus le chauffeur, avec un coffre pour 7 grandes valises.' },
        { q: 'Les sieges enfant sont-ils inclus ?', a: 'Oui — sieges bebe, sieges enfant et rehausseurs disponibles gratuitement sur demande.' },
        { q: 'La Classe V peut-elle faire une journee complete au Mont-Saint-Michel ou en Champagne ?', a: 'Absolument — la mise a disposition 12h est conçue exactement pour ce scenario.' },
      ],
    },
    ru: {
      h1: 'Mercedes V-Class — Премиум вэн 7 мест с водителем в Париже',
      hero: 'Аренда Mercedes-Benz V-Class с водителем почасово в Париже. Флагманский 7-местный люкс-вэн — для семей, делегаций, свадеб, съёмочных групп и VIP-компаний.',
      p1: 'Mercedes V-Class — единственный вэн, перешедший в премиум-сегмент. Внутри — кресла Captain напротив друг друга вокруг откидного столика, тонированные стёкла, трёхзонный климат, USB-C в каждом ряду, амбиентная подсветка, электрические сдвижные двери. По сравнению с обычным 7-местным минивэном V-Class шире, длиннее, выше и вдвое тише — поэтому он стал официальным выбором гастролирующих музыкантов, домов моды, посольств и люкс-вэддинг-плэннеров.',
      p2: 'Забронируйте Mercedes V-Class с водителем в Париже на час или на день. До 7 пассажиров — в максимальном комфорте, багажник на 7 жёстких чемоданов. V-Class — идеальный выбор для CEO с командой, семьи с бабушками и детьми в Лувре, съёмочной группы, свадебной процессии. 5+ метров салона и индивидуально откидывающиеся задние кресла — даже 8 часов в дороге Версаль–Живерни проходят без усталости.',
      p3: 'Наши водители V-Class — старшие водители: минимум 5 лет опыта, английский язык, обучение люкс-сервису. Помогут с детскими креслами (бесплатно по запросу), поддержат пожилых пассажиров, обеспечат сохранность инструментов и фотооборудования, никогда не откажут в остановке у аптеки или сувенирной лавки.',
      faq: [
        { q: 'Сколько пассажиров вмещает V-Class?', a: 'До 7 пассажиров плюс водитель, багажник на 7 крупных чемоданов.' },
        { q: 'Детские кресла включены?', a: 'Да — детские и бустерные кресла бесплатно по запросу.' },
        { q: 'Подходит ли V-Class для целого дня (Мон-Сен-Мишель, Шампань)?', a: 'Безусловно — 12-часовой пакет создан именно для таких поездок.' },
      ],
    },
  },
  'renault-trafic': {
    en: {
      h1: 'Renault Trafic — 8-Seat Eco Minibus with Driver in Paris',
      hero: 'Hourly chauffeur rental in a Renault Trafic 8-seater. The smart eco van — generous space, large boot, fixed price, professional driver — for families, tour groups and budget-aware corporate travel.',
      p1: 'The Renault Trafic 8-seater is the workhorse of intelligent group travel. Where the V-Class delivers luxury, the Trafic delivers volume and value: eight individually-mounted forward-facing seats, climbing space for travellers of all ages, a boot deep enough to swallow 8 large suitcases without playing Tetris, and modern Euro 6 diesel or e-Tech hybrid engines that cut both fuel costs and city centre emissions. The Trafic is the vehicle most family travel agencies, tour operators, school excursions and small-business team outings book first — because the math simply works.',
      p2: 'Hire a Renault Trafic with private driver in Paris by the hour, half-day or full day. Up to 8 passengers travel together — no second taxi, no group splitting at airport arrivals, no second meeting point at the hotel. The driver waits between stops, repositions the vehicle, handles tolls and parking, and adapts the itinerary live to your group\'s rhythm. Whether your day is Roissy CDG to Eurodisney, a day-trip from Paris to Champagne with a vineyard tasting, an airport transfer for a sports team, or a multi-stop ceremony for a wedding party, the Trafic 8-seater is the answer that combines comfort, capacity and fair pricing.',
      p3: 'Our Trafic vehicles are not the entry-level workhorses you might rent at a budget rental agency. They are equipped with full climate control across all rows, captain-style individual seats, large panoramic side windows, USB charging, and child seat anchorages. Each Trafic is professionally cleaned daily and inspected weekly. Drivers are licensed VTC professionals — the same training, the same insurance, the same hospitality standard as our S-Class drivers; the only thing that changes is the vehicle.',
      faq: [
        { q: 'How many passengers fit in a Trafic 8-seater?', a: 'Exactly 8 passengers plus the driver, with luggage space for 8 large suitcases.' },
        { q: 'Is the Trafic the same as a V-Class with cheaper paint?', a: 'No — the Trafic is a different category. It offers more capacity (8 vs 7) and a lower hourly rate, but the V-Class delivers luxury appointments the Trafic does not.' },
      ],
    },
    fr: {
      h1: 'Renault Trafic — Minibus 8 places avec chauffeur a Paris',
      hero: 'Location de chauffeur a l\'heure en Renault Trafic 8 places. Le van eco intelligent — espace genereux, grand coffre, prix fixe, chauffeur professionnel — pour familles, groupes touristiques et voyages d\'affaires maitrises.',
      p1: 'Le Renault Trafic 8 places est le cheval de trait du voyage de groupe intelligent. La ou la Classe V delivre du luxe, le Trafic delivre du volume et de la valeur : huit sieges individuels orientes vers l\'avant, un espace en hauteur pour les voyageurs de tous ages, un coffre suffisamment profond pour engloutir 8 grandes valises sans jouer a Tetris, et des moteurs diesel Euro 6 ou hybride e-Tech qui reduisent les couts de carburant et les emissions en centre-ville. Le Trafic est le vehicule que reservent en premier la plupart des agences voyage famille, les tour-operateurs, les sorties scolaires et les seminaires de PME — parce que les maths fonctionnent.',
      p2: 'Louez un Renault Trafic avec chauffeur prive a Paris a l\'heure, en demi-journee ou en journee. Jusqu\'a 8 passagers voyagent ensemble — pas de second taxi, pas de groupe scinde aux arrivees aeroport, pas de second point de rendez-vous a l\'hotel. Le chauffeur attend entre les arrets, repositionne le vehicule, gere peages et stationnement, et adapte l\'itineraire en temps reel au rythme du groupe. Que votre journee soit Roissy CDG vers Eurodisney, Paris vers la Champagne avec degustation, transfert aeroport d\'une equipe sportive, ou ceremonie multi-arrets pour un mariage, le Trafic 8 places est la reponse qui combine confort, capacite et juste prix.',
      p3: 'Nos Trafic ne sont pas les utilitaires d\'entree de gamme que vous loueriez chez un loueur low cost. Ils sont equipes de climatisation complete sur toutes les rangees, sieges individuels type Captain, larges vitres panoramiques, recharge USB et fixations sieges enfant. Chaque Trafic est nettoye professionnellement chaque jour et inspecte chaque semaine. Les chauffeurs sont des VTC professionnels — meme formation, meme assurance, meme standard d\'hospitalite que nos chauffeurs Classe S ; seul le vehicule change.',
      faq: [
        { q: 'Combien de passagers en Trafic 8 places ?', a: 'Exactement 8 passagers plus le chauffeur, avec un coffre pour 8 grandes valises.' },
        { q: 'Le Trafic est-il une Classe V moins chere ?', a: 'Non — le Trafic est une categorie differente. Il offre plus de capacite (8 vs 7) et un tarif horaire plus bas, mais la Classe V offre des prestations luxe que le Trafic n\'a pas.' },
      ],
    },
    ru: {
      h1: 'Renault Trafic — Минибус 8 мест с водителем в Париже',
      hero: 'Почасовая аренда водителя на Renault Trafic 8 мест. Умный эко-вэн — просторный салон, большой багажник, фиксированная цена для семей и групп.',
      p1: 'Renault Trafic 8 мест — рабочая лошадка умного группового путешествия. Если V-Class даёт люкс, то Trafic даёт объём и ценность: 8 индивидуальных кресел, багажник на 8 крупных чемоданов, Euro 6 дизель или e-Tech гибрид. Trafic — вэн, который чаще всего бронируют семейные тураагентства, туроператоры и школьные экскурсии — потому что математика сходится.',
      p2: 'Арендуйте Renault Trafic с водителем в Париже почасово или на день. До 8 пассажиров вместе — без второго такси, без разделения группы. Водитель ждёт, перепарковывается, оплачивает дороги и парковку.',
      p3: 'Наши Trafic — не бюджетные коммерческие фургоны. Кондиционер во всех рядах, индивидуальные кресла, панорамные окна, USB-зарядка, крепления детских кресел. Водители — лицензированные VTC, та же подготовка, что и у водителей S-Class.',
      faq: [
        { q: 'Сколько пассажиров вмещает Trafic 8 мест?', a: '8 пассажиров плюс водитель, багажник на 8 крупных чемоданов.' },
        { q: 'Trafic — это дешёвый V-Class?', a: 'Нет. Trafic — другая категория: больше мест (8 vs 7), ниже цена, но без премиум-салона V-Class.' },
      ],
    },
  },
};

// Generic strings (UI labels) for the disposal pages.
export const UI = {
  en: {
    pageTitle: 'Driver at Disposal Paris — Hourly Chauffeur Rental',
    pageSubtitle: 'Hire a private driver in Paris by the hour. Mercedes S-Class, E-Class, V-Class or Renault Trafic — 4h, 8h or 12h. Fixed pricing, professional chauffeur, all included.',
    durations: 'Durations',
    duration4h: '4 hours',
    duration8h: '8 hours',
    duration12h: '12 hours',
    perDuration: 'duration',
    passengers: 'passengers',
    luggage: 'luggage',
    discoverVehicle: 'Discover this vehicle',
    bookNow: 'Book Now',
    bookThisVehicle: 'Book this vehicle',
    pricingTBD: 'On request',
    pricingFrom: 'From',
    fleetTitle: 'Our chauffeur-driven fleet',
    fleetSubtitle: 'Four flagship vehicles. One promise: refinement, punctuality and discretion. Choose the car that fits the day.',
    whatsIncluded: 'What\'s included',
    inc1: 'Licensed VTC chauffeur (fully insured)',
    inc2: 'Fuel, tolls, parking — all included',
    inc3: 'Bottled water, Wi-Fi, USB chargers',
    inc4: 'Multilingual driver on request',
    inc5: 'Free meet & greet at airports & stations',
    inc6: 'Unlimited stops within Paris & Ile-de-France',
    useCasesTitle: 'When to book a Driver at Disposal',
    useCases: [
      { t: 'Business roadshows', d: 'Multiple meetings, single driver, total discretion.' },
      { t: 'Family city tours', d: 'Visit Paris at your own pace with kids and grandparents.' },
      { t: 'Wedding day', d: 'Hotel, mairie, church, reception — one car, one driver.' },
      { t: 'Press & film shoots', d: 'Equipment-friendly, location-flexible, multilingual crew comms.' },
      { t: 'Group excursions', d: 'Champagne, Giverny, Versailles, Mont-Saint-Michel — at your tempo.' },
      { t: 'Diplomatic & VIP', d: 'Senior driver, encrypted scheduling, on-call extension.' },
    ],
    faqTitle: 'Frequently asked questions',
    faqs: [
      { q: 'What does "Driver at Disposal" mean?', a: 'A private chauffeur with a luxury vehicle is dedicated to you for a fixed duration (4, 8 or 12 hours). You set the itinerary; the driver follows.' },
      { q: 'Can I extend on the day?', a: 'Yes — same-day extension is possible subject to driver availability and billed prorata.' },
      { q: 'Do you operate outside Paris?', a: 'Yes — Ile-de-France, regional day-trips (Champagne, Loire, Normandy) and cross-border missions on request.' },
      { q: 'Is the pricing all-inclusive?', a: 'Yes — fuel, tolls, parking and water are included. The only extras are optional child seats (free on request) and out-of-Paris regional toll surcharges, both transparent at booking.' },
    ],
    backToMainTitle: 'See all our chauffeur-driven vehicles',
    backToMainLink: 'View the full fleet',
  },
  fr: {
    pageTitle: 'Chauffeur Mis a Disposition Paris — Location de Chauffeur Privé a l\'Heure',
    pageSubtitle: 'Louez un chauffeur prive a l\'heure a Paris. Mercedes Classe S, Classe E, Classe V ou Renault Trafic — 4h, 8h ou 12h. Tarif fixe, chauffeur professionnel, tout inclus.',
    durations: 'Durees',
    duration4h: '4 heures',
    duration8h: '8 heures',
    duration12h: '12 heures',
    perDuration: 'duree',
    passengers: 'passagers',
    luggage: 'bagages',
    discoverVehicle: 'Decouvrir ce vehicule',
    bookNow: 'Reserver',
    bookThisVehicle: 'Reserver ce vehicule',
    pricingTBD: 'Sur demande',
    pricingFrom: 'A partir de',
    fleetTitle: 'Notre flotte avec chauffeur',
    fleetSubtitle: 'Quatre vehicules vaisseaux amiraux. Une promesse : raffinement, ponctualite, discretion. Choisissez la voiture adaptee a la journee.',
    whatsIncluded: 'Inclus dans le tarif',
    inc1: 'Chauffeur VTC agree (integralement assure)',
    inc2: 'Carburant, peages, stationnement — tout inclus',
    inc3: 'Eau minerale, Wi-Fi, chargeurs USB',
    inc4: 'Chauffeur multilingue sur demande',
    inc5: 'Accueil aeroports & gares offert',
    inc6: 'Arrets illimites dans Paris & Ile-de-France',
    useCasesTitle: 'Quand reserver un chauffeur mis a disposition',
    useCases: [
      { t: 'Roadshows affaires', d: 'Rendez-vous successifs, meme chauffeur, discretion totale.' },
      { t: 'Tour de Paris en famille', d: 'Visitez Paris a votre rythme avec enfants et grands-parents.' },
      { t: 'Mariage', d: 'Hotel, mairie, eglise, reception — une voiture, un chauffeur.' },
      { t: 'Presse & tournages', d: 'Materiel charge facile, lieux flexibles, equipe multilingue.' },
      { t: 'Excursions groupe', d: 'Champagne, Giverny, Versailles, Mont-Saint-Michel — a votre tempo.' },
      { t: 'Diplomatie & VIP', d: 'Chauffeur senior, planning crypte, extension a la demande.' },
    ],
    faqTitle: 'Questions frequentes',
    faqs: [
      { q: 'Que signifie "chauffeur mis a disposition" ?', a: 'Un chauffeur prive avec un vehicule de luxe vous est dedie pour une duree fixe (4, 8 ou 12 heures). Vous fixez l\'itineraire ; le chauffeur suit.' },
      { q: 'Puis-je prolonger le jour meme ?', a: 'Oui — extension le jour meme possible selon disponibilite du chauffeur, facturee au prorata.' },
      { q: 'Operez-vous hors Paris ?', a: 'Oui — Ile-de-France, excursions regionales (Champagne, Loire, Normandie) et missions transfrontalieres sur demande.' },
      { q: 'Le tarif est-il tout inclus ?', a: 'Oui — carburant, peages, stationnement et eau inclus. Seuls extras possibles : sieges enfant (gratuits sur demande) et peages regionaux hors Paris, tous transparents a la reservation.' },
    ],
    backToMainTitle: 'Voir tous nos vehicules avec chauffeur',
    backToMainLink: 'Voir la flotte complete',
  },
  ru: {
    pageTitle: 'Водитель в Распоряжении Париж — Почасовая Аренда Водителя',
    pageSubtitle: 'Арендуйте частного водителя в Париже почасово. Mercedes S-Class, E-Class, V-Class или Renault Trafic — 4ч, 8ч или 12ч. Фиксированная цена, всё включено.',
    durations: 'Длительность',
    duration4h: '4 часа',
    duration8h: '8 часов',
    duration12h: '12 часов',
    perDuration: 'длительность',
    passengers: 'пассажиры',
    luggage: 'багаж',
    discoverVehicle: 'Подробнее',
    bookNow: 'Забронировать',
    bookThisVehicle: 'Забронировать авто',
    pricingTBD: 'По запросу',
    pricingFrom: 'От',
    fleetTitle: 'Наш парк с водителем',
    fleetSubtitle: 'Четыре флагманских автомобиля. Одно обещание: изысканность, пунктуальность и сдержанность. Выберите авто под задачу дня.',
    whatsIncluded: 'Что включено',
    inc1: 'Лицензированный VTC водитель (с полной страховкой)',
    inc2: 'Топливо, дороги, парковка — всё включено',
    inc3: 'Минеральная вода, Wi-Fi, USB-зарядка',
    inc4: 'Многоязычный водитель по запросу',
    inc5: 'Бесплатная встреча в аэропортах и вокзалах',
    inc6: 'Безлимитные остановки в Париже и Иль-де-Франс',
    useCasesTitle: 'Когда заказывать водителя в распоряжение',
    useCases: [
      { t: 'Деловые road-show', d: 'Цепочка встреч, один водитель, полная конфиденциальность.' },
      { t: 'Семейная экскурсия', d: 'Гуляйте по Парижу в своём темпе с детьми и старшими.' },
      { t: 'Свадебный день', d: 'Отель, мэрия, церковь, банкет — одна машина, один водитель.' },
      { t: 'Пресса и киносъёмки', d: 'Удобно для оборудования, гибкость локаций, многоязычная команда.' },
      { t: 'Групповые экскурсии', d: 'Шампань, Живерни, Версаль, Мон-Сен-Мишель — в вашем темпе.' },
      { t: 'Дипломатия и VIP', d: 'Старший водитель, защищённое расписание, продление по запросу.' },
    ],
    faqTitle: 'Часто задаваемые вопросы',
    faqs: [
      { q: 'Что значит «водитель в распоряжение»?', a: 'Личный водитель и люкс-авто закреплены за вами на фиксированное время (4, 8 или 12 часов). Вы задаёте маршрут — водитель его выполняет.' },
      { q: 'Можно ли продлить в тот же день?', a: 'Да — продление возможно при наличии водителя, оплата pro-rata.' },
      { q: 'Работаете ли за пределами Парижа?', a: 'Да — Иль-де-Франс, региональные поездки (Шампань, Луара, Нормандия) и трансграничные миссии.' },
      { q: 'Тариф всё включено?', a: 'Да — топливо, дороги, парковка и вода включены. Дополнительно — детские кресла (бесплатно) и региональные дороги вне Парижа.' },
    ],
    backToMainTitle: 'Смотреть все авто с водителем',
    backToMainLink: 'Открыть полный парк',
  },
  hy: {
    pageTitle: 'Վարորդ Տրամադրությամբ Փարիզում — Ժամային Վարձույթ',
    pageSubtitle: 'Վարձեք մասնավոր վարորդ Փարիզում ժամային սկզբունքով՝ Mercedes S, E, V դասի կամ Renault Trafic — 4ժ, 8ժ կամ 12ժ։ Ֆիքսված գին, ամեն ինչ ներառված է։',
    durations: 'Տևողություն',
    duration4h: '4 ժամ',
    duration8h: '8 ժամ',
    duration12h: '12 ժամ',
    perDuration: 'տևողություն',
    passengers: 'ուղևորներ',
    luggage: 'ուղեբեռ',
    discoverVehicle: 'Բացել մեքենան',
    bookNow: 'Ամրագրել',
    bookThisVehicle: 'Ամրագրել մեքենան',
    pricingTBD: 'Ըստ պահանջի',
    pricingFrom: 'Սկսած',
    fleetTitle: 'Մեր մեքենաների պարկը՝ վարորդով',
    fleetSubtitle: 'Չորս դրոշակակիր մեքենա, մեկ խոստում՝ նրբություն, ճշտապահություն և գաղտնիություն։',
    whatsIncluded: 'Ինչ է ներառված',
    inc1: 'Լիցենզավորված VTC վարորդ (ապահովագրությամբ)',
    inc2: 'Վառելիք, մաքսերն ու կայանումը՝ ներառված',
    inc3: 'Շիշ ջուր, Wi-Fi, USB լիցքավորիչներ',
    inc4: 'Բազմալեզու վարորդ ըստ պահանջի',
    inc5: 'Անվճար ընդունելություն օդանավակայանում',
    inc6: 'Անսահմանափակ կանգառներ Փարիզում',
    useCasesTitle: 'Երբ ամրագրել վարորդ տրամադրությամբ',
    useCases: [
      { t: 'Բիզնես հանդիպումներ', d: 'Մի քանի կանգառ, մեկ վարորդ, ամբողջական գաղտնիություն։' },
      { t: 'Ընտանեկան էքսկուրսիա', d: 'Շրջեք Փարիզով ձեր տեմպով՝ երեխաների ու տատիկ-պապիկների հետ։' },
      { t: 'Հարսանիք', d: 'Հյուրանոց, քաղաքապետարան, եկեղեցի, ընդունելություն՝ մեկ մեքենա, մեկ վարորդ։' },
      { t: 'Մամուլ և նկարահանումներ', d: 'Սարքավորման համար հարմար, ճկուն երթուղի։' },
      { t: 'Խմբային էքսկուրսիաներ', d: 'Շամպայն, Ժիվերնի, Վերսալ, Մոն-Սեն-Միշել։' },
      { t: 'Դիվանագիտություն և VIP', d: 'Ավագ վարորդ, գաղտնի ժամանակացույց։' },
    ],
    faqTitle: 'Հաճախ տրվող հարցեր',
    faqs: [
      { q: 'Ինչ է նշանակում «վարորդ տրամադրությամբ»?', a: 'Անձնական վարորդ ու լյուքս մեքենա՝ ֆիքսված տևողությամբ։' },
      { q: 'Կարո՞ղ եմ երկարաձգել նույն օրը', a: 'Այո — ենթակա է վարորդի առկայության։' },
      { q: 'Աշխատու՞մ եք Փարիզից դուրս', a: 'Այո — Իլ-դե-Ֆրանս ու տարածաշրջանային էքսկուրսիաներ։' },
      { q: 'Գինը ամեն ինչ ներառո՞ւմ է', a: 'Այո — վառելիք, մաքսեր, կայանում, ջուր։' },
    ],
    backToMainTitle: 'Տեսնել մեր ամբողջ պարկը',
    backToMainLink: 'Բացել պարկը',
  },
};
