import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  fr: {
    title: 'VTC 7 Places - Van avec Chauffeur Prive | Zont.cab',
    subtitle: 'Service VTC 7 places pour familles, groupes et transferts aeroport. Mercedes Classe V, Volkswagen Caravelle ou similaire avec chauffeur professionnel.',
    description: 'Reservez un VTC 7 places pour vos trajets en famille ou en groupe. Notre service de van avec chauffeur prive est la solution ideale pour les transferts aeroport, les deplacements en ville, les evenements et les circuits touristiques. Nos vehicules 7 places de type Mercedes Classe V, Volkswagen Caravelle ou Toyota Proace Verso offrent un espace genereux pour 6 a 7 passagers avec leurs bagages. Confort premium garanti : sieges en cuir, climatisation, Wi-Fi, prises USB et un chauffeur professionnel agree VTC. Prix fixe sans surprise, reserve en quelques clics.',
    description2: 'Le VTC 7 places represente le compromis parfait entre confort et capacite. Plus spacieux qu\'une berline classique, il accueille confortablement jusqu\'a 7 passagers tout en offrant un large coffre pour les valises et bagages volumineux. Ideal pour les familles avec enfants (sieges bebe disponibles sur demande), les groupes d\'amis en week-end ou les equipes professionnelles en deplacement. Nos chauffeurs VTC assurent un service premium : accueil a l\'aeroport avec pancarte nominative, aide aux bagages, itineraire optimise et conduite souple pour un trajet agreable. Disponible pour les transferts depuis Paris CDG, Orly, Beauvais et toutes les gares parisiennes, ainsi que pour les circuits touristiques dans Paris et en Ile-de-France.',
    whyChoose: 'Pourquoi Choisir un VTC 7 Places ?',
    feature1Title: 'Confort pour 7 Passagers', feature1Desc: 'Van spacieux type Mercedes Classe V. Sieges en cuir, espace jambes genereux et grand coffre pour tous vos bagages.',
    feature2Title: 'Ideal pour les Familles', feature2Desc: 'Sieges bebe et rehausseurs disponibles sur demande. Parfait pour voyager avec enfants en toute securite.',
    feature3Title: 'Chauffeur Agree VTC', feature3Desc: 'Chauffeurs professionnels, experimentes et ponctuels. Accueil personnalise avec pancarte a l\'aeroport.',
    feature4Title: 'Tarif Fixe Tout Compris', feature4Desc: 'Prix confirme a la reservation sans supplement. Peages, parking et attente a l\'aeroport inclus dans le tarif.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E, 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S ou BMW Serie 7',
    minivan: 'Van 7 Places', minivanDesc: 'Mercedes Classe V, jusqu\'a 7 passagers', minibus: 'Minibus 8 Places', minibusDesc: 'Renault Trafic ou similaire, 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER MAINTENANT', allInclusive: 'Tout compris',
    vehiclesTitle: 'Nos Vehicules VTC 7 Places',
    howItWorks: 'Comment Reserver Votre VTC 7 Places', step1: 'Reservez en Ligne', step1Desc: 'Indiquez votre adresse de prise en charge, votre destination, la date et l\'heure souhaitees. Recevez un devis instantane.',
    step2: 'Chauffeur Attribue', step2Desc: 'Un chauffeur professionnel vous est assigne. Il vous contacte pour confirmer les details de votre trajet.',
    step3: 'Profitez du Trajet', step3Desc: 'Installez-vous confortablement dans votre van 7 places. Detendez-vous et profitez du voyage avec votre groupe.',
    popularRoutesTitle: 'Trajets Populaires en VTC 7 Places', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport CDG → Paris Centre (7 places)', price: 130 },
      { name: 'Aeroport Orly → Paris Centre (7 places)', price: 110 },
      { name: 'Paris → Disneyland Paris (7 places)', price: 140 },
      { name: 'Paris → Chateau de Versailles (7 places)', price: 125 },
      { name: 'Paris → Aeroport Beauvais (7 places)', price: 220 },
    ],
    bookingForm: 'Reservez Votre VTC 7 Places',
    pickupLabel: 'Adresse de depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: '',
    otherCitiesTitle: 'Besoin de plus de places ? Decouvrez notre VTC 8 places', otherCitiesBtn: 'Voir Toutes Nos Destinations',
    rating: '4.9/5 (3 200+ avis)',
  },
  en: {
    title: 'VTC 7 Seats - Van with Private Driver | Zont.cab',
    subtitle: '7-seat VTC service for families, groups, and airport transfers. Mercedes V-Class, VW Caravelle or similar with professional driver.',
    description: 'Book a 7-seat VTC for family or group travel. Our private driver van service is perfect for airport transfers, city trips, events, and tours. Mercedes V-Class, VW Caravelle or Toyota Proace Verso with premium comfort: leather seats, AC, Wi-Fi. Fixed price, no hidden fees.',
    description2: 'The 7-seat VTC is the perfect balance between comfort and capacity. More spacious than a standard sedan, it comfortably accommodates up to 7 passengers with generous luggage space. Ideal for families with children (baby seats available on request), friend groups, or business teams. Available for transfers from Paris CDG, Orly, Beauvais airports and all Paris train stations.',
    whyChoose: 'Why Choose a 7-Seat VTC?',
    feature1Title: 'Comfort for 7 Passengers', feature1Desc: 'Spacious van like Mercedes V-Class. Leather seats and generous luggage space.',
    feature2Title: 'Perfect for Families', feature2Desc: 'Baby seats and boosters available on request. Safe travel with children.',
    feature3Title: 'Licensed VTC Driver', feature3Desc: 'Professional, experienced, and punctual drivers. Meet and greet at the airport.',
    feature4Title: 'All-Inclusive Fixed Price', feature4Desc: 'Price confirmed at booking. Tolls, parking, and airport waiting included.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class or BMW 7 Series',
    minivan: 'Van 7 Seats', minivanDesc: 'Mercedes V-Class, up to 7 passengers', minibus: 'Minibus 8 Seats', minibusDesc: 'Renault Trafic or similar, 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Our 7-Seat VTC Vehicles',
    howItWorks: 'How to Book Your 7-Seat VTC', step1: 'Book Online', step1Desc: 'Enter your pickup, destination, date & time. Get an instant quote.',
    step2: 'Driver Assigned', step2Desc: 'A professional driver is assigned and contacts you to confirm details.',
    step3: 'Enjoy the Ride', step3Desc: 'Settle comfortably in your 7-seat van. Relax and enjoy the journey.',
    popularRoutesTitle: 'Popular 7-Seat VTC Routes', fromLabel: 'From',
    routes: [
      { name: 'CDG Airport → Paris Center (7 seats)', price: 130 },
      { name: 'Orly Airport → Paris Center (7 seats)', price: 110 },
      { name: 'Paris → Disneyland Paris (7 seats)', price: 140 },
      { name: 'Paris → Palace of Versailles (7 seats)', price: 125 },
    ],
    bookingForm: 'Book Your 7-Seat VTC',
    pickupLabel: 'Pickup address', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: '',
    otherCitiesTitle: 'Need more seats? Discover our 8-seat VTC', otherCitiesBtn: 'View All Destinations',
    rating: '4.9/5 (3,200+ reviews)',
  },
  ru: {
    title: 'VTC 7 Мест - Вэн с Частным Водителем | Zont.cab',
    subtitle: 'Услуга VTC 7 мест для семей, групп и трансферов. Mercedes V-Class с профессиональным водителем.',
    description: 'Закажите VTC на 7 мест для семейных или групповых поездок. Mercedes V-Class, VW Caravelle. Кожаные сидения, кондиционер, Wi-Fi. Фиксированная цена.',
    description2: 'VTC на 7 мест - идеальный баланс комфорта и вместимости. Доступны детские кресла. Трансферы из аэропортов CDG, Орли, Бове.',
    whyChoose: 'Почему VTC на 7 Мест?',
    feature1Title: 'Комфорт для 7 Пассажиров', feature1Desc: 'Просторный вэн Mercedes V-Class.',
    feature2Title: 'Для Семей', feature2Desc: 'Детские кресла по запросу.',
    feature3Title: 'Лицензированный Водитель', feature3Desc: 'Профессиональные водители VTC.',
    feature4Title: 'Фиксированная Цена', feature4Desc: 'Без скрытых платежей.',
    sedan: 'Премиум Седан', sedanDesc: 'Mercedes E-Class, 1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes S-Class или BMW 7',
    minivan: 'Вэн 7 мест', minivanDesc: 'Mercedes V-Class, до 7 пассажиров', minibus: 'Минибус 8 мест', minibusDesc: 'Renault Trafic, 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Наши VTC 7 мест',
    howItWorks: 'Как Забронировать', step1: 'Бронируйте Онлайн', step1Desc: 'Укажите адрес и получите цену.',
    step2: 'Водитель Назначен', step2Desc: 'Профессиональный водитель назначен.',
    step3: 'Наслаждайтесь Поездкой', step3Desc: 'Комфортная поездка для всей группы.',
    popularRoutesTitle: 'Популярные Маршруты', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт CDG → Центр Парижа (7 мест)', price: 130 },
      { name: 'Аэропорт Орли → Центр Парижа (7 мест)', price: 110 },
    ],
    bookingForm: 'Забронируйте VTC 7 Мест',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: '',
    otherCitiesTitle: 'Также: VTC 8 мест, седаны и минибусы', otherCitiesBtn: 'Все Направления',
    rating: '4.9/5 (3 200+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 65, luxury: 95, minivan: 130, minibus: 190 };
const seoUrls = { en: '/vtc-7-seats', fr: '/vtc-7-places', ru: '/vtc-7-mest' };

const VTC7Places = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default VTC7Places;
