import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  fr: {
    title: 'VTC 7 Places - Van avec Chauffeur Prive | Zont.cab',
    subtitle: 'Service VTC 7 places pour familles, groupes et transferts aeroport. Mercedes Classe V, Volkswagen Caravelle ou similaire avec chauffeur professionnel.',
    description: 'Voyager a plusieurs ne devrait jamais signifier renoncer au confort. Notre VTC 7 places est concu precisement pour les familles qui refusent de s\'entasser dans deux taxis avec des valises debordantes, les groupes d\'amis qui arrivent a Roissy apres un vol et veulent partager le meme vehicule, ou les equipes professionnelles en route vers un seminaire. Le Mercedes Classe V, avec ses portes coulissantes electriques, son interieur cuir et ses 5 a 6 metres de longueur, transforme un simple transfert en veritable moment de detente. Chaque siege dispose de sa propre ventilation, de prises USB pour recharger telephones et tablettes, et l\'espace coffre engloutit aisement 7 valises rigides sans compromettre le confort des passagers. Un chauffeur prive agree VTC conduit, tandis que votre groupe discute, planifie la soiree, ou tout simplement respire apres un long vol.',
    description2: 'Au-dela de l\'aeroport, le VTC 7 places est devenu le vehicule de choix pour des usages que beaucoup de voyageurs n\'imaginent pas. Les familles recomposees emmenent enfants et grands-parents pour un week-end a Deauville ou au Mont-Saint-Michel — sans louer deux voitures. Les organisateurs d\'enterrements de vie de garcon et de vie de jeune fille reservent un van pour parcourir les vignobles de Champagne avec un conducteur sobre. Les societes envoient des delegations de CDG a la Porte de Versailles pour le Salon de l\'Agriculture ou au Bourget pour le Salon de l\'Aeronautique. Dans chaque cas, le prix fixe confirme a la reservation elimine les discussions et les compteurs : vous savez exactement ce que le trajet coute avant de monter a bord.',
    description3: 'Nos vehicules 7 places sont egalement equipes de sieges enfant et rehausseurs disponibles gratuitement sur demande — un detail qui transforme un transfert aeroportuaire avec des bambins de corvee epuisante en promenade tranquille. Le chauffeur vous attend avec une pancarte a votre nom, installe les sieges enfant avant votre sortie de l\'aeroport, et charge poussettes et bagages dans le coffre pendant que vous attachez vos enfants. Du terminal CDG 2E a votre appartement Airbnb du Marais, du TGV Gare de Lyon a votre hotel a Fontainebleau, ou d\'Orly a un mariage en Sologne : le VTC 7 places vous y conduit sans compromis. Reservez en deux minutes, payez en ligne, et laissez le chauffeur s\'occuper du reste.',
    whyChoose: 'Pourquoi Choisir un VTC 7 Places ?',
    feature1Title: 'Confort pour 7 Passagers', feature1Desc: 'Van spacieux type Mercedes Classe V. Sieges en cuir, espace jambes genereux et grand coffre pour tous vos bagages.',
    feature2Title: 'Ideal pour les Familles', feature2Desc: 'Sieges bebe et rehausseurs disponibles sur demande. Parfait pour voyager avec enfants en toute securite.',
    feature3Title: 'Chauffeur Agree VTC', feature3Desc: 'Chauffeurs professionnels, experimentes et ponctuels. Accueil personnalise avec pancarte a l\'aeroport.',
    feature4Title: 'Tarif Fixe Tout Compris', feature4Desc: 'Prix confirme a la reservation sans supplement. Peages, parking et attente a l\'aeroport inclus dans le tarif.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E, 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S ou BMW Serie 7',
    minivan: 'Van 7 Places', minivanDesc: 'Mercedes Classe V, jusqu\'a 7 passagers', minibus: 'Minibus 8 Places', minibusDesc: 'Renault Trafic ou similaire, 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER MAINTENANT', allInclusive: 'Tout compris',
    vehiclesTitle: 'Nos Vehicules VTC 7 Places',
    howItWorks: 'Comment Reserver Votre VTC 7 Places', step1: 'Reservez en Ligne', step1Desc: 'Indiquez votre adresse de prise en charge, votre destination, la date et l\'heure souhaitees. Recevez un devis instantane.',
    step2: 'Chauffeur Attribue', step2Desc: 'Un chauffeur professionnel vous est assigne. Il vous contacte pour confirmer les details de votre trajet.',
    step3: 'Profitez du Trajet', step3Desc: 'Installez-vous confortablement dans votre van 7 places. Detendez-vous et profitez du voyage avec votre groupe.',
    popularRoutesTitle: 'Trajets Populaires en VTC 7 Places', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport CDG → Paris Centre (7 places)', price: 130 },
      { name: 'Aeroport Orly → Paris Centre (7 places)', price: 110 },
      { name: 'Paris → Disneyland Paris (7 places)', price: 140 },
      { name: 'Paris → Chateau de Versailles (7 places)', price: 125 },
      { name: 'Paris → Aeroport Beauvais (7 places)', price: 220 },
    ],
    bookingForm: 'Reservez Votre VTC 7 Places',
    pickupLabel: 'Adresse de depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: '',
    otherCitiesTitle: 'Besoin de plus de places ? Decouvrez notre VTC 8 places', otherCitiesBtn: 'Voir Toutes Nos Destinations',
    rating: '4.5/5 Tripadvisor (29 avis)',
  },
  en: {
    title: 'VTC 7 Seats - Van with Private Driver | Zont.cab',
    subtitle: '7-seat VTC service for families, groups, and airport transfers. Mercedes V-Class, VW Caravelle or similar with professional driver.',
    description: 'Traveling in a group should never mean sacrificing comfort. Our 7-seat VTC is designed for families who refuse to split into two taxis with overflowing suitcases, friend groups arriving at CDG who want to share one vehicle, or corporate teams heading to a conference. The Mercedes V-Class, with electric sliding doors, leather interior, and over 5 metres of cabin length, transforms a simple transfer into a genuine moment of relaxation. Each seat has its own ventilation, USB charging ports, and the boot swallows 7 hard-shell suitcases without compromising passenger comfort. A licensed VTC driver handles the road while your group chats, plans dinner, or simply decompresses after a long flight.',
    description2: 'Beyond airport runs, the 7-seat VTC has become the vehicle of choice for uses many travelers never consider. Blended families take children and grandparents to Deauville or Mont-Saint-Michel — without renting two cars. Bachelor and bachelorette parties book a van to tour the Champagne vineyards with a sober driver. Companies send delegations from CDG to Porte de Versailles for trade shows. In every case, the fixed price confirmed at booking eliminates haggling and meters: you know exactly what the trip costs before you board.',
    description3: 'Our 7-seat vehicles are also equipped with child seats and boosters available free on request — a detail that transforms an airport transfer with toddlers from an exhausting ordeal into a peaceful ride. The driver waits with a name board, installs child seats before you exit the terminal, and loads strollers and bags while you buckle in your children. From CDG Terminal 2E to your Marais Airbnb, from Gare de Lyon to your Fontainebleau hotel, or from Orly to a wedding in Sologne: the 7-seat VTC takes you there without compromise. Book in two minutes, pay online, and let the driver handle the rest.',
    whyChoose: 'Why Choose a 7-Seat VTC?',
    feature1Title: 'Comfort for 7 Passengers', feature1Desc: 'Spacious van like Mercedes V-Class. Leather seats and generous luggage space.',
    feature2Title: 'Perfect for Families', feature2Desc: 'Baby seats and boosters available on request. Safe travel with children.',
    feature3Title: 'Licensed VTC Driver', feature3Desc: 'Professional, experienced, and punctual drivers. Meet and greet at the airport.',
    feature4Title: 'All-Inclusive Fixed Price', feature4Desc: 'Price confirmed at booking. Tolls, parking, and airport waiting included.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class or BMW 7 Series',
    minivan: 'Van 7 Seats', minivanDesc: 'Mercedes V-Class, up to 7 passengers', minibus: 'Minibus 8 Seats', minibusDesc: 'Renault Trafic or similar, 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Our 7-Seat VTC Vehicles',
    howItWorks: 'How to Book Your 7-Seat VTC', step1: 'Book Online', step1Desc: 'Enter your pickup, destination, date & time. Get an instant quote.',
    step2: 'Driver Assigned', step2Desc: 'A professional driver is assigned and contacts you to confirm details.',
    step3: 'Enjoy the Ride', step3Desc: 'Settle comfortably in your 7-seat van. Relax and enjoy the journey.',
    popularRoutesTitle: 'Popular 7-Seat VTC Routes', fromLabel: 'From',
    routes: [
      { name: 'CDG Airport → Paris Center (7 seats)', price: 130 },
      { name: 'Orly Airport → Paris Center (7 seats)', price: 110 },
      { name: 'Paris → Disneyland Paris (7 seats)', price: 140 },
      { name: 'Paris → Palace of Versailles (7 seats)', price: 125 },
    ],
    bookingForm: 'Book Your 7-Seat VTC',
    pickupLabel: 'Pickup address', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: '',
    otherCitiesTitle: 'Need more seats? Discover our 8-seat VTC', otherCitiesBtn: 'View All Destinations',
    rating: '4.5/5 Tripadvisor (29 reviews)',
  },
  ru: {
    title: 'VTC 7 Мест - Вэн с Частным Водителем | Zont.cab',
    subtitle: 'Услуга VTC 7 мест для семей, групп и трансферов. Mercedes V-Class с профессиональным водителем.',
    description: 'Путешествовать группой не значит жертвовать комфортом. Наш VTC на 7 мест создан для семей, которые не хотят разделяться на два такси с горой чемоданов, для компаний друзей, прилетающих в CDG и желающих ехать вместе, для корпоративных команд на пути к конференции. Mercedes V-Class с электрическими сдвижными дверями, кожаным салоном и 5-метровой кабиной превращает обычный трансфер в момент расслабления. У каждого кресла — вентиляция и USB-зарядка, а багажник вмещает 7 жёстких чемоданов без ущерба для пассажиров. Лицензированный VTC-водитель ведёт, пока ваша группа общается или просто приходит в себя после долгого перелёта.',
    description2: 'Помимо аэропортов, VTC на 7 мест стал идеальным решением для многих ситуаций: семьи едут с детьми и бабушками в Довиль или на Мон-Сен-Мишель без аренды двух машин, мальчишники и девичники отправляются в Шампань с трезвым водителем, компании перевозят делегации из CDG на выставки. Фиксированная цена при бронировании — никаких счётчиков. Детские кресла и бустеры бесплатно по запросу. От CDG до Airbnb в Марэ, от Гар-де-Лион до отеля в Фонтенбло, от Орли на свадьбу в Солонь — без компромиссов. Бронируйте за 2 минуты.',
    whyChoose: 'Почему VTC на 7 Мест?',
    feature1Title: 'Комфорт для 7 Пассажиров', feature1Desc: 'Просторный вэн Mercedes V-Class.',
    feature2Title: 'Для Семей', feature2Desc: 'Детские кресла по запросу.',
    feature3Title: 'Лицензированный Водитель', feature3Desc: 'Профессиональные водители VTC.',
    feature4Title: 'Фиксированная Цена', feature4Desc: 'Без скрытых платежей.',
    sedan: 'Премиум Седан', sedanDesc: 'Mercedes E-Class, 1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes S-Class или BMW 7',
    minivan: 'Вэн 7 мест', minivanDesc: 'Mercedes V-Class, до 7 пассажиров', minibus: 'Минибус 8 мест', minibusDesc: 'Renault Trafic, 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Наши VTC 7 мест',
    howItWorks: 'Как Забронировать', step1: 'Бронируйте Онлайн', step1Desc: 'Укажите адрес и получите цену.',
    step2: 'Водитель Назначен', step2Desc: 'Профессиональный водитель назначен.',
    step3: 'Наслаждайтесь Поездкой', step3Desc: 'Комфортная поездка для всей группы.',
    popularRoutesTitle: 'Популярные Маршруты', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт CDG → Центр Парижа (7 мест)', price: 130 },
      { name: 'Аэропорт Орли → Центр Парижа (7 мест)', price: 110 },
    ],
    bookingForm: 'Забронируйте VTC 7 Мест',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: '',
    otherCitiesTitle: 'Также: VTC 8 мест, седаны и минибусы', otherCitiesBtn: 'Все Направления',
    rating: '4.5/5 Tripadvisor (29 отзывов)',
  },
  hy: {
    title: 'VTC 7 տեղ - Մինիվեն վարորդով',
    subtitle: 'Ընտանիքների և խմբերի համար մինիվեն',
    description: 'Mercedes V-Class-ով 7 տեղ ընտանիքների և խմբերի համար: Էլեկտրական սղուն դռներ՝ կաշվե սալոն՝ USB լիցքավորիչներ: Մանկական նստատեղերը անվճար են: Deauville՝ Mont-Saint-Michel՝ Շամպանյայի գինեգործարաններ՝ հարսանիքներ:',
    description2: 'Ֆիքս գինը մեքենայի համար է՝ ոչ մեկ անձի:',
    whyChoose: 'Ինչու ընտրել մեր vtc 7 տեղ - մինիվեն վարորդով',
    feature1Title: 'Դիմավորում', feature1Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով: 60 րոպե անվճար սպասման ժամանակ:',
    feature2Title: 'Թռիչքի հետևում', feature2Desc: 'Իրական ժամանակում թռիչքի հետևում: Անվճար:',
    feature3Title: 'Պրեմիում մեքենաներ', feature3Desc: 'Mercedes E-Class, BMW 5: Մաքուր, կլիմատիզացիա:',
    feature4Title: 'Ֆիքս գներ', feature4Desc: 'Գինը հաստատված է ամրագրման ժամանակ: Թաքնված վճարներ չկան:',
    sedan: 'Պրեմիում սեդան', sedanDesc: 'Mercedes E-Class, 1-3 ուղևոր',
    luxury: 'Լյուքս սեդան', luxuryDesc: 'Mercedes S-Class կամ BMW 7',
    minivan: 'Մինիվեն', minivanDesc: 'Mercedes V-Class, մինչև 6 ուղևոր',
    minibus: 'Մինիբուս', minibusDesc: 'Մինչև 8 ուղևոր',
    passengers: 'Ուղևորներ', luggage: 'Ուղեբարան',
    bookNow: 'ԱՄՏԱԳՏՎԵԼ', allInclusive: 'Ամեն ինչ ներառված է',
    vehiclesTitle: 'Ընտրեք մեքենան',
    howItWorks: 'Ինչպես է աշխատում',
    step1: 'Ամրագրեք օնլայն', step1Desc: 'Մուտքագրեք ձեր տվյալները և հասցեն: Ակնթարթ գնի հաստատում:',
    step2: 'Հանդիպեք վարորդին', step2Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով:',
    step3: 'Հանգստացեք', step3Desc: 'Հարմարավետ ուղևորություն պրեմիում մեքենայում:',
    popularRoutesTitle: 'Սկսած', fromLabel: 'Սկսած',
    bookingForm: 'ԱՄՏԱԳՏՎԵԼ',
    pickupLabel: 'Վերցնում', dropoffLabel: 'Իջնում',
    dateLabel: 'Ամսաթիվ', timeLabel: 'Ժամ',
    defaultPickup: '',
    otherCitiesTitle: 'Սպասարկում ենք 120+ քաղաքներ Եվրոպայում',
    otherCitiesBtn: 'Բոլոր ուղղությունները',
    rating: '4.5/5 Tripadvisor',
  },
};

const vehiclesPrices = { sedan: 65, luxury: 95, minivan: 130, minibus: 190 };
const seoUrls = { en: '/vtc-7-seats', fr: '/vtc-7-places', ru: '/vtc-7-mest', hy: '/vtc-7-tegh' };

const VTC7Places = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default VTC7Places;
