import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  fr: {
    title: 'VTC 8 Places - Minibus avec Chauffeur Prive | Zont.cab',
    subtitle: 'Service VTC 8 places pour groupes, familles et transferts aeroport. Minibus Renault Trafic, Mercedes Vito ou similaire avec chauffeur professionnel.',
    description: 'Reservez un VTC 8 places pour vos deplacements en groupe, en famille ou entre collegues. Notre service de minibus avec chauffeur prive est ideal pour les transferts aeroport, les evenements, les sorties en groupe ou les trajets longue distance. Nos vehicules de type Renault Trafic, Mercedes Vito ou Ford Tourneo Custom offrent un espace genereux pour 7 a 8 passagers avec leurs bagages. Profitez d\'un confort optimal, de la climatisation, du Wi-Fi et d\'un chauffeur professionnel qui vous prend en charge a l\'adresse de votre choix. Prix fixe confirme a la reservation, pas de frais caches.',
    description2: 'Le VTC 8 places est la solution ideale quand vous voyagez en grand groupe. Que ce soit pour un transfert depuis l\'aeroport Paris CDG, Orly ou Beauvais, un deplacement vers une gare, un hotel ou un lieu d\'evenement, notre flotte de minibus est a votre disposition 24h/24, 7j/7. Nos chauffeurs sont tous professionnels agrees VTC, avec une excellente connaissance des itineraires. Chaque vehicule est equipe de sieges confortables, d\'un large espace bagages et de toutes les commodites pour un trajet agreable. Nous proposons egalement des services pour les mariages, seminaires, circuits touristiques et toute occasion necessitant un transport de groupe fiable et confortable.',
    whyChoose: 'Pourquoi Choisir un VTC 8 Places ?',
    feature1Title: 'Espace pour 8 Passagers', feature1Desc: 'Minibus spacieux type Renault Trafic ou Mercedes Vito. Sieges confortables et espace bagages genereux pour tout le groupe.',
    feature2Title: 'Chauffeur Professionnel', feature2Desc: 'Chauffeurs agrees VTC, ponctuels et courtois. Accueil personnalise avec pancarte a l\'aeroport ou a la gare.',
    feature3Title: 'Disponible 24h/24', feature3Desc: 'Reservez votre minibus a toute heure. Ideal pour les vols tot le matin ou tard le soir. Suivi de vol en temps reel.',
    feature4Title: 'Prix Fixe Garanti', feature4Desc: 'Tarif confirme a la reservation. Aucun supplement, peages et parking inclus. Paiement securise en ligne.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E, 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S ou BMW Serie 7',
    minivan: 'Van 6 Places', minivanDesc: 'Mercedes Classe V, jusqu\'a 6 passagers', minibus: 'Minibus 8 Places', minibusDesc: 'Renault Trafic ou similaire, 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER MAINTENANT', allInclusive: 'Tout compris',
    vehiclesTitle: 'Nos Vehicules VTC 8 Places et Plus',
    howItWorks: 'Comment Reserver Votre VTC 8 Places', step1: 'Reservez en Ligne', step1Desc: 'Indiquez votre adresse de depart, destination, date et heure. Recevez un prix fixe instantanement.',
    step2: 'Chauffeur Confirme', step2Desc: 'Un chauffeur professionnel vous est attribue. Il vous attend avec pancarte a l\'adresse convenue.',
    step3: 'Voyagez en Groupe', step3Desc: 'Montez a bord de votre minibus confortable. Profitez du trajet avec tout votre groupe, sans stress.',
    popularRoutesTitle: 'Trajets Populaires en VTC 8 Places', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport CDG → Paris Centre (8 places)', price: 190 },
      { name: 'Aeroport Orly → Paris Centre (8 places)', price: 170 },
      { name: 'Paris → Disneyland Paris (8 places)', price: 195 },
      { name: 'Paris → Versailles (8 places)', price: 180 },
      { name: 'Paris → Aeroport Beauvais (8 places)', price: 280 },
    ],
    bookingForm: 'Reservez Votre VTC 8 Places',
    pickupLabel: 'Adresse de depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: '',
    otherCitiesTitle: 'Egalement disponible : VTC 7 places, berlines et vans', otherCitiesBtn: 'Voir Toutes Nos Destinations',
    rating: '4.9/5 (3 200+ avis)',
  },
  en: {
    title: 'VTC 8 Seats - Minibus with Private Driver | Zont.cab',
    subtitle: '8-seat VTC service for groups, families, and airport transfers. Renault Trafic, Mercedes Vito or similar minibus with professional driver.',
    description: 'Book an 8-seat VTC for your group, family, or business travel. Our minibus private driver service is perfect for airport transfers, events, group outings, or long-distance trips. Vehicles like Renault Trafic, Mercedes Vito, or Ford Tourneo Custom offer generous space for 7-8 passengers with luggage. Enjoy optimal comfort, air conditioning, Wi-Fi, and a professional driver. Fixed price confirmed at booking, no hidden fees.',
    description2: 'The 8-seat VTC is the ideal solution for large group travel. Whether for a transfer from Paris CDG, Orly, or Beauvais airport, or to a train station, hotel, or event venue, our minibus fleet is at your disposal 24/7. All our drivers are licensed VTC professionals with excellent route knowledge. We also offer services for weddings, seminars, tourist circuits, and any occasion requiring reliable and comfortable group transport.',
    whyChoose: 'Why Choose an 8-Seat VTC?',
    feature1Title: 'Space for 8 Passengers', feature1Desc: 'Spacious minibus like Renault Trafic or Mercedes Vito. Comfortable seats and generous luggage space.',
    feature2Title: 'Professional Driver', feature2Desc: 'Licensed VTC drivers, punctual and courteous. Personalized meet and greet at the airport.',
    feature3Title: 'Available 24/7', feature3Desc: 'Book your minibus at any time. Ideal for early morning or late night flights.',
    feature4Title: 'Fixed Price Guaranteed', feature4Desc: 'Price confirmed at booking. No surcharges, tolls and parking included.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class or BMW 7 Series',
    minivan: 'Van 6 Seats', minivanDesc: 'Mercedes V-Class, up to 6 passengers', minibus: 'Minibus 8 Seats', minibusDesc: 'Renault Trafic or similar, 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Our 8-Seat VTC Vehicles',
    howItWorks: 'How to Book Your 8-Seat VTC', step1: 'Book Online', step1Desc: 'Enter your pickup address, destination, date, and time. Get an instant fixed price.',
    step2: 'Driver Confirmed', step2Desc: 'A professional driver is assigned. They wait with a name sign at the agreed address.',
    step3: 'Travel as a Group', step3Desc: 'Board your comfortable minibus. Enjoy the ride stress-free with your group.',
    popularRoutesTitle: 'Popular 8-Seat VTC Routes', fromLabel: 'From',
    routes: [
      { name: 'CDG Airport → Paris Center (8 seats)', price: 190 },
      { name: 'Orly Airport → Paris Center (8 seats)', price: 170 },
      { name: 'Paris → Disneyland Paris (8 seats)', price: 195 },
      { name: 'Paris → Versailles (8 seats)', price: 180 },
      { name: 'Paris → Beauvais Airport (8 seats)', price: 280 },
    ],
    bookingForm: 'Book Your 8-Seat VTC',
    pickupLabel: 'Pickup address', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: '',
    otherCitiesTitle: 'Also available: 7-seat VTC, sedans, and vans', otherCitiesBtn: 'View All Destinations',
    rating: '4.9/5 (3,200+ reviews)',
  },
  ru: {
    title: 'VTC 8 Мест - Минибус с Частным Водителем | Zont.cab',
    subtitle: 'Услуга VTC 8 мест для групп, семей и трансферов. Renault Trafic, Mercedes Vito с профессиональным водителем.',
    description: 'Закажите VTC на 8 мест для групповых, семейных или деловых поездок. Наш минибус идеален для трансферов, мероприятий и дальних поездок. Renault Trafic, Mercedes Vito или аналогичные. Фиксированная цена при бронировании.',
    description2: 'VTC на 8 мест - идеальное решение для больших групп. Трансферы из аэропортов CDG, Орли, Бове. Водители с лицензией VTC, комфортные автомобили. Также предлагаем услуги для свадеб, семинаров и туров.',
    whyChoose: 'Почему Выбрать VTC на 8 Мест?',
    feature1Title: '8 Пассажиров', feature1Desc: 'Просторный минибус Renault Trafic или Mercedes Vito.',
    feature2Title: 'Профессиональный Водитель', feature2Desc: 'Лицензированные VTC водители.',
    feature3Title: 'Доступно 24/7', feature3Desc: 'Бронируйте в любое время.',
    feature4Title: 'Фиксированная Цена', feature4Desc: 'Цена подтверждается при бронировании.',
    sedan: 'Премиум Седан', sedanDesc: 'Mercedes E-Class, 1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes S-Class или BMW 7',
    minivan: 'Минивэн 6 мест', minivanDesc: 'Mercedes V-Class, до 6 пассажиров', minibus: 'Минибус 8 мест', minibusDesc: 'Renault Trafic, 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Наши VTC 8 мест',
    howItWorks: 'Как Забронировать', step1: 'Бронируйте Онлайн', step1Desc: 'Укажите адрес и получите цену.',
    step2: 'Водитель Подтвержден', step2Desc: 'Профессиональный водитель назначен.',
    step3: 'Путешествуйте Группой', step3Desc: 'Комфортная поездка для всей группы.',
    popularRoutesTitle: 'Популярные Маршруты', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт CDG → Центр Парижа (8 мест)', price: 190 },
      { name: 'Аэропорт Орли → Центр Парижа (8 мест)', price: 170 },
      { name: 'Париж → Диснейленд (8 мест)', price: 195 },
    ],
    bookingForm: 'Забронируйте VTC 8 Мест',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: '',
    otherCitiesTitle: 'Также: VTC 7 мест, седаны и вэны', otherCitiesBtn: 'Все Направления',
    rating: '4.9/5 (3 200+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 65, luxury: 95, minivan: 150, minibus: 190 };
const seoUrls = { en: '/vtc-8-seats', fr: '/vtc-8-places', ru: '/vtc-8-mest' };

const VTC8Places = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default VTC8Places;
