import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  fr: {
    title: 'VTC 8 Places - Minibus avec Chauffeur Prive | Zont.cab',
    subtitle: 'Service VTC 8 places pour groupes, familles et transferts aeroport. Minibus Renault Trafic, Mercedes Vito ou similaire avec chauffeur professionnel.',
    description: 'Quand sept places ne suffisent pas, notre VTC 8 places prend le relais. Pensez au groupe de collegues qui atterrit ensemble pour un seminaire a La Defense, a la famille elargie reunissant trois generations pour un week-end au chateau de la Loire, ou a l\'equipe sportive arrivant avec sacs et equipements pour un tournoi en Ile-de-France. Le Renault Trafic, le Mercedes Vito Tourer ou le Ford Tourneo Custom Long offrent un volume interieur que meme les monospaces haut de gamme ne peuvent egaler : 8 sieges individuels avec accoudoirs, une hauteur sous plafond qui permet de se tenir debout en entrant, et un coffre avalant valises, sacs de golf, poussettes et cartons de materiel sans effort. Un chauffeur VTC professionnel conduit, vous n\'avez qu\'a profiter.',
    description2: 'Le VTC 8 places n\'est pas simplement un taxi plus grand — c\'est un espace mobile qui s\'adapte a vos besoins. Pour les mariages, il transporte le cortege de la mairie a l\'eglise puis au lieu de reception, evitant le chaos de huit voitures individuelles cherchant un parking. Pour les congres, il navette entre l\'hotel et le Palais des Congres avec toute l\'equipe et les presentoirs. Pour les excursions — Versailles, Giverny, Champagne, les chateaux de la Loire — il offre une experience partagee plutot qu\'un trajet isole. Le prix fixe par course couvre le vehicule entier, pas par personne : a huit, c\'est souvent moins cher qu\'un Uber par tete.',
    description3: 'Disponible 24h/24, 7j/7, nos minibus VTC 8 places servent aussi aux transferts nocturnes entre les aeroports parisiens. Un vol tardif a Beauvais qui atterrit a 23h30 avec huit amis en vacances ? Notre chauffeur est la, moteur allume, coffre ouvert. Un depart matinal a CDG Terminal 1 a 4h du matin ? Il passe vous chercher a l\'hotel avec une ponctualite militaire. Chaque vehicule est assure, climatise, equipe de Wi-Fi et regulierement desinfecte. Nos chauffeurs detiennent la licence VTC, maitrisent le francais, l\'anglais et souvent le russe ou l\'armenien. Reservez votre VTC 8 places en ligne, recevez la confirmation instantanee, et laissez-nous nous occuper de la logistique du groupe.',
    whyChoose: 'Pourquoi Choisir un VTC 8 Places ?',
    feature1Title: 'Espace pour 8 Passagers', feature1Desc: 'Minibus spacieux type Renault Trafic ou Mercedes Vito. Sieges confortables et espace bagages genereux pour tout le groupe.',
    feature2Title: 'Chauffeur Professionnel', feature2Desc: 'Chauffeurs agrees VTC, ponctuels et courtois. Accueil personnalise avec pancarte a l\'aeroport ou a la gare.',
    feature3Title: 'Disponible 24h/24', feature3Desc: 'Reservez votre minibus a toute heure. Ideal pour les vols tot le matin ou tard le soir. Suivi de vol en temps reel.',
    feature4Title: 'Prix Fixe Garanti', feature4Desc: 'Tarif confirme a la reservation. Aucun supplement, peages et parking inclus. Paiement securise en ligne.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E, 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S ou BMW Serie 7',
    minivan: 'Van 6 Places', minivanDesc: 'Mercedes Classe V, jusqu\'a 6 passagers', minibus: 'Minibus 8 Places', minibusDesc: 'Renault Trafic ou similaire, 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER MAINTENANT', allInclusive: 'Tout compris',
    vehiclesTitle: 'Nos Vehicules VTC 8 Places et Plus',
    howItWorks: 'Comment Reserver Votre VTC 8 Places', step1: 'Reservez en Ligne', step1Desc: 'Indiquez votre adresse de depart, destination, date et heure. Recevez un prix fixe instantanement.',
    step2: 'Chauffeur Confirme', step2Desc: 'Un chauffeur professionnel vous est attribue. Il vous attend avec pancarte a l\'adresse convenue.',
    step3: 'Voyagez en Groupe', step3Desc: 'Montez a bord de votre minibus confortable. Profitez du trajet avec tout votre groupe, sans stress.',
    popularRoutesTitle: 'Trajets Populaires en VTC 8 Places', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport CDG → Paris Centre (8 places)', price: 190 },
      { name: 'Aeroport Orly → Paris Centre (8 places)', price: 170 },
      { name: 'Paris → Disneyland Paris (8 places)', price: 195 },
      { name: 'Paris → Versailles (8 places)', price: 180 },
      { name: 'Paris → Aeroport Beauvais (8 places)', price: 280 },
    ],
    bookingForm: 'Reservez Votre VTC 8 Places',
    pickupLabel: 'Adresse de depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: '',
    otherCitiesTitle: 'Egalement disponible : VTC 7 places, berlines et vans', otherCitiesBtn: 'Voir Toutes Nos Destinations',
    rating: '4.5/5 Tripadvisor (29 avis)',
  },
  en: {
    title: 'VTC 8 Seats - Minibus with Private Driver | Zont.cab',
    subtitle: '8-seat VTC service for groups, families, and airport transfers. Renault Trafic, Mercedes Vito or similar minibus with professional driver.',
    description: 'When seven seats are not enough, our 8-seat VTC steps in. Think of the colleague group landing together for a seminar in La Defense, the extended family uniting three generations for a Loire Valley chateau weekend, or the sports team arriving with kit bags for a tournament. The Renault Trafic, Mercedes Vito Tourer, or Ford Tourneo Custom Long offers interior volume that even premium MPVs cannot match: 8 individual seats with armrests, standing headroom on entry, and a boot that swallows suitcases, golf bags, pushchairs, and equipment boxes effortlessly. A professional VTC driver handles the road — you simply enjoy the ride.',
    description2: 'The 8-seat VTC is not just a bigger taxi — it is a mobile space that adapts to your needs. For weddings, it ferries the party from city hall to church to reception, avoiding the chaos of eight individual cars hunting for parking. For conferences, it shuttles between the hotel and Palais des Congres with the whole team. For day trips — Versailles, Giverny, Champagne, Loire castles — it provides a shared experience. The fixed price per trip covers the entire vehicle, not per person: split between eight, it is often cheaper per head than an Uber. Book your 8-seat VTC online and let us handle the group logistics.',
    whyChoose: 'Why Choose an 8-Seat VTC?',
    feature1Title: 'Space for 8 Passengers', feature1Desc: 'Spacious minibus like Renault Trafic or Mercedes Vito. Comfortable seats and generous luggage space.',
    feature2Title: 'Professional Driver', feature2Desc: 'Licensed VTC drivers, punctual and courteous. Personalized meet and greet at the airport.',
    feature3Title: 'Available 24/7', feature3Desc: 'Book your minibus at any time. Ideal for early morning or late night flights.',
    feature4Title: 'Fixed Price Guaranteed', feature4Desc: 'Price confirmed at booking. No surcharges, tolls and parking included.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class or BMW 7 Series',
    minivan: 'Van 6 Seats', minivanDesc: 'Mercedes V-Class, up to 6 passengers', minibus: 'Minibus 8 Seats', minibusDesc: 'Renault Trafic or similar, 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Our 8-Seat VTC Vehicles',
    howItWorks: 'How to Book Your 8-Seat VTC', step1: 'Book Online', step1Desc: 'Enter your pickup address, destination, date, and time. Get an instant fixed price.',
    step2: 'Driver Confirmed', step2Desc: 'A professional driver is assigned. They wait with a name sign at the agreed address.',
    step3: 'Travel as a Group', step3Desc: 'Board your comfortable minibus. Enjoy the ride stress-free with your group.',
    popularRoutesTitle: 'Popular 8-Seat VTC Routes', fromLabel: 'From',
    routes: [
      { name: 'CDG Airport → Paris Center (8 seats)', price: 190 },
      { name: 'Orly Airport → Paris Center (8 seats)', price: 170 },
      { name: 'Paris → Disneyland Paris (8 seats)', price: 195 },
      { name: 'Paris → Versailles (8 seats)', price: 180 },
      { name: 'Paris → Beauvais Airport (8 seats)', price: 280 },
    ],
    bookingForm: 'Book Your 8-Seat VTC',
    pickupLabel: 'Pickup address', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: '',
    otherCitiesTitle: 'Also available: 7-seat VTC, sedans, and vans', otherCitiesBtn: 'View All Destinations',
    rating: '4.5/5 Tripadvisor (29 reviews)',
  },
  ru: {
    title: 'VTC 8 Мест - Минибус с Частным Водителем | Zont.cab',
    subtitle: 'Услуга VTC 8 мест для групп, семей и трансферов. Renault Trafic, Mercedes Vito с профессиональным водителем.',
    description: 'Когда семи мест недостаточно, наш VTC на 8 мест приходит на помощь. Команда коллег на семинар в Ла-Дефанс, большая семья из трёх поколений на уикенд в замке Луары, спортивная команда с экипировкой. Renault Trafic, Mercedes Vito Tourer, Ford Tourneo Custom Long — 8 индивидуальных кресел с подлокотниками, стоячая высота и багажник для чемоданов, гольф-сумок и колясок. Профессиональный VTC-водитель ведёт — вы отдыхаете.',
    description2: 'VTC на 8 мест — мобильное пространство для любых задач. Свадебный кортеж от ЗАГСа до ресторана, шаттл между отелем и Дворцом конгрессов, экскурсии в Версаль, Живерни, Шампань. Фиксированная цена за машину — на восьмерых часто дешевле Uber на каждого. 24/7, Wi-Fi, кондиционер, детские кресла бесплатно. Водители с лицензией VTC говорят на французском, английском, русском.',
    whyChoose: 'Почему Выбрать VTC на 8 Мест?',
    feature1Title: '8 Пассажиров', feature1Desc: 'Просторный минибус Renault Trafic или Mercedes Vito.',
    feature2Title: 'Профессиональный Водитель', feature2Desc: 'Лицензированные VTC водители.',
    feature3Title: 'Доступно 24/7', feature3Desc: 'Бронируйте в любое время.',
    feature4Title: 'Фиксированная Цена', feature4Desc: 'Цена подтверждается при бронировании.',
    sedan: 'Премиум Седан', sedanDesc: 'Mercedes E-Class, 1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes S-Class или BMW 7',
    minivan: 'Минивэн 6 мест', minivanDesc: 'Mercedes V-Class, до 6 пассажиров', minibus: 'Минибус 8 мест', minibusDesc: 'Renault Trafic, 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Наши VTC 8 мест',
    howItWorks: 'Как Забронировать', step1: 'Бронируйте Онлайн', step1Desc: 'Укажите адрес и получите цену.',
    step2: 'Водитель Подтвержден', step2Desc: 'Профессиональный водитель назначен.',
    step3: 'Путешествуйте Группой', step3Desc: 'Комфортная поездка для всей группы.',
    popularRoutesTitle: 'Популярные Маршруты', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт CDG → Центр Парижа (8 мест)', price: 190 },
      { name: 'Аэропорт Орли → Центр Парижа (8 мест)', price: 170 },
      { name: 'Париж → Диснейленд (8 мест)', price: 195 },
    ],
    bookingForm: 'Забронируйте VTC 8 Мест',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: '',
    otherCitiesTitle: 'Также: VTC 7 мест, седаны и вэны', otherCitiesBtn: 'Все Направления',
    rating: '4.5/5 Tripadvisor (29 отзывов)',
  },
  hy: {
    title: 'VTC 8 տեղ - Մինիբուս վարորդով',
    subtitle: 'Մեծ խմբերի համար մինիբուս',
    description: 'Renault Trafic, Mercedes Vito կամ Ford Tourneo Custom՝ 8 անհատական նստատեղ: Հարսանիքների՝ սեմինարների՝ եկեղեցական շրջանակների համար: Վերսալ՝ Giverny՝ Շամպանյա՝ Լուարի դղյակներ: Ֆիքս գինը մեքենայի համար է: 24/7՝ Wi-Fi՝ կլիմատիզացիա:',
    description2: 'Ը ութի մեկ անձի իջնում է Uber-ից էժան:',
    whyChoose: 'Ինչու ընտրել մեր vtc 8 տեղ - մինիբուս վարորդով',
    feature1Title: 'Դիմավորում', feature1Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով: 60 րոպե անվճար սպասման ժամանակ:',
    feature2Title: 'Թռիչքի հետևում', feature2Desc: 'Իրական ժամանակում թռիչքի հետևում: Անվճար:',
    feature3Title: 'Պրեմիում մեքենաներ', feature3Desc: 'Mercedes E-Class, BMW 5: Մաքուր, կլիմատիզացիա:',
    feature4Title: 'Ֆիքս գներ', feature4Desc: 'Գինը հաստատված է ամրագրման ժամանակ: Թաքնված վճարներ չկան:',
    sedan: 'Պրեմիում սեդան', sedanDesc: 'Mercedes E-Class, 1-3 ուղևոր',
    luxury: 'Լյուքս սեդան', luxuryDesc: 'Mercedes S-Class կամ BMW 7',
    minivan: 'Մինիվեն', minivanDesc: 'Mercedes V-Class, մինչև 6 ուղևոր',
    minibus: 'Մինիբուս', minibusDesc: 'Մինչև 8 ուղևոր',
    passengers: 'Ուղևորներ', luggage: 'Ուղեբարան',
    bookNow: 'ԱՄՏԱԳՏՎԵԼ', allInclusive: 'Ամեն ինչ ներառված է',
    vehiclesTitle: 'Ընտրեք մեքենան',
    howItWorks: 'Ինչպես է աշխատում',
    step1: 'Ամրագրեք օնլայն', step1Desc: 'Մուտքագրեք ձեր տվյալները և հասցեն: Ակնթարթ գնի հաստատում:',
    step2: 'Հանդիպեք վարորդին', step2Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով:',
    step3: 'Հանգստացեք', step3Desc: 'Հարմարավետ ուղևորություն պրեմիում մեքենայում:',
    popularRoutesTitle: 'Սկսած', fromLabel: 'Սկսած',
    bookingForm: 'ԱՄՏԱԳՏՎԵԼ',
    pickupLabel: 'Վերցնում', dropoffLabel: 'Իջնում',
    dateLabel: 'Ամսաթիվ', timeLabel: 'Ժամ',
    defaultPickup: '',
    otherCitiesTitle: 'Սպասարկում ենք 120+ քաղաքներ Եվրոպայում',
    otherCitiesBtn: 'Բոլոր ուղղությունները',
    rating: '4.5/5 Tripadvisor',
  },
};

const vehiclesPrices = { sedan: 65, luxury: 95, minivan: 150, minibus: 190 };
const seoUrls = { en: '/vtc-8-seats', fr: '/vtc-8-places', ru: '/vtc-8-mest', hy: '/vtc-8-tegh' };

const VTC8Places = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default VTC8Places;
