import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Alicante Airport Transfer - Private Car Service',
    subtitle: 'Professional private driver from Alicante-Elche Airport to Costa Blanca hotels, Benidorm and all destinations',
    description: 'Book your Alicante airport transfer with professional drivers. Alicante-Elche Miguel Hernandez Airport (ALC) is the gateway to Spain\'s stunning Costa Blanca. We provide premium private transfers from ALC Airport to Alicante city center, Benidorm, Torrevieja, Denia, Javea, and all Costa Blanca resorts. Fixed prices, flight monitoring, meet and greet at arrivals.',
    description2: 'The Costa Blanca is one of Europe\'s most popular holiday destinations, with over 300 days of sunshine per year. Whether you are heading to a beachfront hotel in Benidorm, a villa in Javea, or exploring the charming Old Town of Alicante, our drivers ensure a smooth start to your vacation.',
    whyChoose: 'Why Choose Our Alicante Airport Transfer?',
    feature1Title: 'Airport Meet & Greet', feature1Desc: 'Driver with name sign at ALC arrivals. 60 minutes free waiting time.',
    feature2Title: 'Flight Monitoring', feature2Desc: 'Real-time flight tracking. No extra charge for delays.',
    feature3Title: 'Clean Vehicles', feature3Desc: 'Air-conditioned premium vehicles. Comfortable for the Costa Blanca heat.',
    feature4Title: 'Fixed Prices', feature4Desc: 'No surprises. Price confirmed at booking.',
    sedan: 'Premium Sedan', sedanDesc: '1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes E-Class or similar',
    minivan: 'Minivan', minivanDesc: 'Up to 6 passengers, perfect for families', minibus: 'Minibus', minibusDesc: 'Up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter flight details and Costa Blanca address.',
    step2: 'Meet Your Driver', step2Desc: 'Professional driver at ALC arrivals with your name.',
    step3: 'Start Your Holiday', step3Desc: 'Direct transfer to your resort or hotel.',
    popularRoutesTitle: 'Popular Alicante Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'ALC Airport → Alicante City Center', price: 30 },
      { name: 'ALC Airport → Benidorm', price: 65 },
      { name: 'ALC Airport → Torrevieja', price: 45 },
      { name: 'ALC Airport → Denia / Javea', price: 95 },
    ],
    bookingForm: 'Book Your Alicante Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Alicante-Elche Airport (ALC)',
    otherCitiesTitle: 'We serve other European cities', otherCitiesBtn: 'View All Destinations',
    rating: '4.8/5 (750+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Alicante - Voiture Privee',
    subtitle: 'Chauffeur prive professionnel depuis l\'aeroport d\'Alicante vers la Costa Blanca, Benidorm et toutes destinations',
    description: 'Reservez votre transfert aeroport Alicante avec des chauffeurs professionnels. L\'aeroport d\'Alicante-Elche Miguel Hernandez (ALC) est la porte d\'entree de la Costa Blanca espagnole. Transferts prives premium depuis ALC vers Alicante centre, Benidorm, Torrevieja, Denia, Javea et toutes les stations de la Costa Blanca. Prix fixes, suivi de vol, accueil personnalise.',
    description2: 'La Costa Blanca est l\'une des destinations de vacances les plus populaires d\'Europe, avec plus de 300 jours de soleil par an. Nos chauffeurs assurent un debut de vacances sans stress.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Alicante ?',
    feature1Title: 'Accueil a l\'Aeroport', feature1Desc: 'Chauffeur avec pancarte aux arrivees ALC. 60 min d\'attente gratuites.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Suivi en temps reel. Pas de supplement pour retard.',
    feature3Title: 'Vehicules Climatises', feature3Desc: 'Vehicules premium climatises. Confort garanti sous le soleil.',
    feature4Title: 'Prix Fixes', feature4Desc: 'Pas de surprises. Prix confirme a la reservation.',
    sedan: 'Berline Premium', sedanDesc: '1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe E ou similaire',
    minivan: 'Monospace', minivanDesc: 'Jusqu\'a 6 passagers, ideal pour familles', minibus: 'Minibus', minibusDesc: 'Jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez vol et adresse Costa Blanca.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Chauffeur professionnel aux arrivees ALC.',
    step3: 'Commencez Vos Vacances', step3Desc: 'Transfert direct vers votre hotel ou resort.',
    popularRoutesTitle: 'Trajets Populaires Transfert Alicante', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport ALC → Centre d\'Alicante', price: 30 },
      { name: 'Aeroport ALC → Benidorm', price: 65 },
      { name: 'Aeroport ALC → Torrevieja', price: 45 },
      { name: 'Aeroport ALC → Denia / Javea', price: 95 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Alicante',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Alicante-Elche (ALC)',
    otherCitiesTitle: 'Nous desservons d\'autres villes europeennes', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.8/5 (750+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Аликанте - Частный Автомобиль',
    subtitle: 'Частный водитель из аэропорта Аликанте на Коста Бланку, Бенидорм и все направления',
    description: 'Забронируйте трансфер из аэропорта Аликанте. Аэропорт Аликанте-Эльче (ALC) - ворота на испанское побережье Коста Бланка. Премиум-трансферы из ALC в центр Аликанте, Бенидорм, Торревьеху, Дению, Хавею и все курорты.',
    description2: 'Коста Бланка - одно из популярнейших направлений в Европе с 300+ солнечными днями в году.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Аликанте?',
    feature1Title: 'Встреча в Аэропорту', feature1Desc: 'Водитель с табличкой в зале прилета ALC. 60 минут бесплатно.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мониторинг в реальном времени.',
    feature3Title: 'Кондиционированные Авто', feature3Desc: 'Премиум автомобили с кондиционером.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Цена при бронировании. Без сюрпризов.',
    sedan: 'Премиум Седан', sedanDesc: '1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes E-Class',
    minivan: 'Минивэн', minivanDesc: 'До 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте', step1Desc: 'Введите рейс и адрес на Коста Бланке.',
    step2: 'Встреча', step2Desc: 'Водитель в зале прилета ALC.',
    step3: 'Начните Отдых', step3Desc: 'Прямой трансфер в отель.',
    popularRoutesTitle: 'Популярные Маршруты из Аэропорта Аликанте', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт ALC → Центр Аликанте', price: 30 },
      { name: 'Аэропорт ALC → Бенидорм', price: 65 },
      { name: 'Аэропорт ALC → Торревьеха', price: 45 },
      { name: 'Аэропорт ALC → Дения / Хавея', price: 95 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Аликанте',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Аликанте-Эльче (ALC)',
    otherCitiesTitle: 'Другие города', otherCitiesBtn: 'Все Направления',
    rating: '4.8/5 (750+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 30, luxury: 50, minivan: 75, minibus: 120 };

const seoUrls = { en: '/alicante-airport-transfer', fr: '/transfert-aeroport-alicante', ru: '/taksi-iz-aeroporta-alikante' };
const AlicanteTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default AlicanteTransfer;
