import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Alicante Airport Transfer - Private Car Service',
    subtitle: 'Professional private driver from Alicante-Elche Airport to Costa Blanca hotels, Benidorm and all destinations',
    description: 'The Costa Blanca stretches like a white sand ribbon along 200 kilometres of Spain\'s southeastern Mediterranean coast — and Alicante-Elche Miguel Hernandez Airport (ALC) is its front door. Over 15 million passengers pass through this modern airport each year, the vast majority heading to the string of resort towns that have made this coast a European byword for sunshine, golf, and affordable luxury. But while the airport is efficient, the onward journey is where most holiday plans stumble: car rental queues can exceed an hour in July, the local bus runs infrequently to Benidorm, and taxis have no fixed pricing to destinations beyond the city. Our private Alicante airport transfer solves this: a professional driver waits at arrivals, loads your suitcases and golf clubs into a spacious vehicle, and drives you directly to your hotel, villa, or apartment — anywhere on the Costa Blanca.',
    description2: 'Alicante itself is often overlooked by tourists racing to Benidorm, yet the city\'s charms rival any on the coast. The Castillo de Santa Barbara, perched 166 metres above the harbour on Mount Benacantil, offers panoramic views from Tabarca Island to the mountain ranges of the interior. The Explanada de Espana, a mosaic-tiled promenade shaded by palm trees, leads to the old fishing quarter of Santa Cruz with its whitewashed houses and bougainvillea. The Mercado Central, built in 1920, sells turrón (the city\'s famous nougat), fresh seafood, and local wines from the Alicante DO appellation.',
    description3: 'Beyond Alicante city, the Costa Blanca unfolds like a travel brochure come to life. Benidorm (40 minutes north) offers two crescent beaches backed by a Manhattan-like skyline of hotels. Javea and Denia (70 minutes north) attract a quieter crowd with rocky coves, Montgo Natural Park, and ferry connections to Ibiza. Torrevieja (30 minutes south) is home to pink salt lakes and one of the largest expatriate communities in Spain. For golf enthusiasts, La Manga Club and Las Colinas are within a 90-minute drive. Many of our clients book return transfers — airport to villa on arrival, villa to airport on departure — locking in the same fixed price. Book your Alicante transfer and let the Spanish sun do the rest.',
    whyChoose: 'Why Choose Our Alicante Airport Transfer?',
    feature1Title: 'Airport Meet & Greet', feature1Desc: 'Driver with name sign at ALC arrivals. 60 minutes free waiting time.',
    feature2Title: 'Flight Monitoring', feature2Desc: 'Real-time flight tracking. No extra charge for delays.',
    feature3Title: 'Clean Vehicles', feature3Desc: 'Air-conditioned premium vehicles. Comfortable for the Costa Blanca heat.',
    feature4Title: 'Fixed Prices', feature4Desc: 'No surprises. Price confirmed at booking.',
    sedan: 'Premium Sedan', sedanDesc: '1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes E-Class or similar',
    minivan: 'Minivan', minivanDesc: 'Up to 6 passengers, perfect for families', minibus: 'Minibus', minibusDesc: 'Up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter flight details and Costa Blanca address.',
    step2: 'Meet Your Driver', step2Desc: 'Professional driver at ALC arrivals with your name.',
    step3: 'Start Your Holiday', step3Desc: 'Direct transfer to your resort or hotel.',
    popularRoutesTitle: 'Popular Alicante Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'ALC Airport → Alicante City Center', price: 30 },
      { name: 'ALC Airport → Benidorm', price: 65 },
      { name: 'ALC Airport → Torrevieja', price: 45 },
      { name: 'ALC Airport → Denia / Javea', price: 95 },
    ],
    bookingForm: 'Book Your Alicante Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Alicante-Elche Airport (ALC)',
    otherCitiesTitle: 'We serve other European cities', otherCitiesBtn: 'View All Destinations',
    rating: '4.8/5 (750+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Alicante - Voiture Privee',
    subtitle: 'Chauffeur prive professionnel depuis l\'aeroport d\'Alicante vers la Costa Blanca, Benidorm et toutes destinations',
    description: 'Reservez votre transfert aeroport Alicante avec des chauffeurs professionnels. L\'aeroport d\'Alicante-Elche Miguel Hernandez (ALC) est la porte d\'entree de la Costa Blanca espagnole. Transferts prives premium depuis ALC vers Alicante centre, Benidorm, Torrevieja, Denia, Javea et toutes les stations de la Costa Blanca. Prix fixes, suivi de vol, accueil personnalise.',
    description2: 'La Costa Blanca s\'etire sur 200 km de littoral mediterraneen au sud-est de l\'Espagne, et l\'aeroport d\'Alicante-Elche (ALC) en est la porte d\'entree. Plus de 15 millions de passagers par an, la plupart filant vers Benidorm, Javea, Torrevieja ou Denia. Alicante elle-meme recele des tresors : le Castillo de Santa Barbara a 166 m au-dessus du port, l\'Explanada de Espana bordee de palmiers, le quartier Santa Cruz aux maisons blanchies. Notre transfert prive vous depose a votre villa, hotel ou appartement — partout sur la Costa Blanca. Reservez votre transfert Alicante, 300 jours de soleil vous attendent.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Alicante ?',
    feature1Title: 'Accueil a l\'Aeroport', feature1Desc: 'Chauffeur avec pancarte aux arrivees ALC. 60 min d\'attente gratuites.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Suivi en temps reel. Pas de supplement pour retard.',
    feature3Title: 'Vehicules Climatises', feature3Desc: 'Vehicules premium climatises. Confort garanti sous le soleil.',
    feature4Title: 'Prix Fixes', feature4Desc: 'Pas de surprises. Prix confirme a la reservation.',
    sedan: 'Berline Premium', sedanDesc: '1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe E ou similaire',
    minivan: 'Monospace', minivanDesc: 'Jusqu\'a 6 passagers, ideal pour familles', minibus: 'Minibus', minibusDesc: 'Jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez vol et adresse Costa Blanca.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Chauffeur professionnel aux arrivees ALC.',
    step3: 'Commencez Vos Vacances', step3Desc: 'Transfert direct vers votre hotel ou resort.',
    popularRoutesTitle: 'Trajets Populaires Transfert Alicante', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport ALC → Centre d\'Alicante', price: 30 },
      { name: 'Aeroport ALC → Benidorm', price: 65 },
      { name: 'Aeroport ALC → Torrevieja', price: 45 },
      { name: 'Aeroport ALC → Denia / Javea', price: 95 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Alicante',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Alicante-Elche (ALC)',
    otherCitiesTitle: 'Nous desservons d\'autres villes europeennes', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.8/5 (750+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Аликанте - Частный Автомобиль',
    subtitle: 'Частный водитель из аэропорта Аликанте на Коста Бланку, Бенидорм и все направления',
    description: 'Забронируйте трансфер из аэропорта Аликанте. Аэропорт Аликанте-Эльче (ALC) - ворота на испанское побережье Коста Бланка. Премиум-трансферы из ALC в центр Аликанте, Бенидорм, Торревьеху, Дению, Хавею и все курорты.',
    description2: 'Коста-Бланка протянулась на 200 км вдоль средиземноморского побережья юго-востока Испании, а аэропорт Аликанте-Эльче (ALC) — её парадный вход. Более 15 млн пассажиров в год, большинство спешат к Бенидорму, Хавеа, Торревьехе или Дении. Сам Аликанте скрывает сокровища: крепость Санта-Барбара на высоте 166 м, мозаичная Эспланада-де-Эспанья, рыбацкий квартал Санта-Крус. Для гольфистов — La Manga Club и Las Colinas в 90 минутах. Наш трансфер доставит к вилле, отелю или апартаментам на побережье. 300 солнечных дней ждут вас.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Аликанте?',
    feature1Title: 'Встреча в Аэропорту', feature1Desc: 'Водитель с табличкой в зале прилета ALC. 60 минут бесплатно.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мониторинг в реальном времени.',
    feature3Title: 'Кондиционированные Авто', feature3Desc: 'Премиум автомобили с кондиционером.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Цена при бронировании. Без сюрпризов.',
    sedan: 'Премиум Седан', sedanDesc: '1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes E-Class',
    minivan: 'Минивэн', minivanDesc: 'До 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте', step1Desc: 'Введите рейс и адрес на Коста Бланке.',
    step2: 'Встреча', step2Desc: 'Водитель в зале прилета ALC.',
    step3: 'Начните Отдых', step3Desc: 'Прямой трансфер в отель.',
    popularRoutesTitle: 'Популярные Маршруты из Аэропорта Аликанте', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт ALC → Центр Аликанте', price: 30 },
      { name: 'Аэропорт ALC → Бенидорм', price: 65 },
      { name: 'Аэропорт ALC → Торревьеха', price: 45 },
      { name: 'Аэропорт ALC → Дения / Хавея', price: 95 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Аликанте',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Аликанте-Эльче (ALC)',
    otherCitiesTitle: 'Другие города', otherCitiesBtn: 'Все Направления',
    rating: '4.8/5 (750+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 30, luxury: 50, minivan: 75, minibus: 120 };

const seoUrls = { en: '/alicante-airport-transfer', fr: '/transfert-aeroport-alicante', ru: '/taksi-iz-aeroporta-alikante' };
const AlicanteTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default AlicanteTransfer;
