import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Barcelona Airport Transfer - El Prat Airport',
    subtitle: 'Private driver from Barcelona-El Prat Airport to La Rambla, Gothic Quarter, Sagrada Familia and all Barcelona',
    description: 'Book your Barcelona airport transfer with professional drivers. Barcelona-El Prat Josep Tarradellas Airport (BCN) is Spain\'s second busiest airport, located 12 km southwest of the city. We provide premium private transfers from BCN to La Rambla, Gothic Quarter, Eixample, Sagrada Familia, Port Olimpic, and any address in Barcelona. Fixed prices, flight monitoring, personal meet and greet at arrivals.',
    description2: 'Barcelona is a world-class destination blending Gaudi\'s architectural masterpieces, Mediterranean beaches, vibrant nightlife, and Catalan cuisine. Start your Barcelona experience with a stress-free, comfortable airport transfer rather than navigating buses or fighting for a taxi.',
    whyChoose: 'Why Choose Our Barcelona Airport Transfer?',
    feature1Title: 'Meet & Greet at BCN', feature1Desc: 'Driver with name sign at El Prat arrivals. 60 minutes free waiting.',
    feature2Title: 'Flight Tracking', feature2Desc: 'Real-time flight monitoring. No extra charge for delays.',
    feature3Title: 'Premium Vehicles', feature3Desc: 'Mercedes, BMW. Clean, air-conditioned, recent models.',
    feature4Title: 'All-Inclusive Pricing', feature4Desc: 'Fixed price at booking. No hidden fees or surprises.',
    sedan: 'Premium Sedan', sedanDesc: '1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes E-Class or similar',
    minivan: 'Minivan', minivanDesc: 'Up to 6 passengers', minibus: 'Minibus', minibusDesc: 'Up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter flight details and Barcelona address. Instant price.',
    step2: 'Meet Your Driver', step2Desc: 'Driver greets you at El Prat arrivals hall.',
    step3: 'Enjoy Barcelona', step3Desc: 'Direct 20-30 minute ride to central Barcelona.',
    popularRoutesTitle: 'Popular Barcelona Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'BCN Airport → La Rambla / Gothic Quarter', price: 39 },
      { name: 'BCN Airport → Sagrada Familia / Eixample', price: 39 },
      { name: 'BCN Airport → Port Olimpic', price: 42 },
      { name: 'BCN Airport → Sitges', price: 65 },
    ],
    bookingForm: 'Book Your Barcelona Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Barcelona El Prat Airport (BCN)',
    otherCitiesTitle: 'We serve other European cities', otherCitiesBtn: 'View All Destinations',
    rating: '4.9/5 (1,900+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Barcelone - El Prat',
    subtitle: 'Chauffeur prive depuis l\'aeroport de Barcelone-El Prat vers La Rambla, le Quartier Gothique et toute Barcelone',
    description: 'Reservez votre transfert aeroport Barcelone avec des chauffeurs professionnels. L\'aeroport de Barcelone-El Prat (BCN) est le deuxieme aeroport le plus frequente d\'Espagne, situe a 12 km au sud-ouest. Transferts prives premium vers La Rambla, le Quartier Gothique, l\'Eixample, la Sagrada Familia, le Port Olimpic et toute adresse a Barcelone. Prix fixes, suivi de vol, accueil personnalise.',
    description2: 'Barcelone est une destination de classe mondiale melant les chefs-d\'oeuvre architecturaux de Gaudi, les plages mediterraneennes, la vie nocturne et la cuisine catalane. Commencez votre experience barcelonaise avec un transfert confortable.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Barcelone ?',
    feature1Title: 'Accueil a BCN', feature1Desc: 'Chauffeur avec pancarte aux arrivees El Prat. 60 min d\'attente gratuites.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Suivi en temps reel. Pas de supplement pour retard.',
    feature3Title: 'Vehicules Premium', feature3Desc: 'Mercedes, BMW. Propres, climatises, modeles recents.',
    feature4Title: 'Prix Tout Compris', feature4Desc: 'Prix fixe a la reservation. Aucun frais cache.',
    sedan: 'Berline Premium', sedanDesc: '1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe E ou similaire',
    minivan: 'Monospace', minivanDesc: 'Jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez vol et adresse a Barcelone. Prix instantane.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Chauffeur aux arrivees d\'El Prat.',
    step3: 'Profitez de Barcelone', step3Desc: 'Trajet direct de 20-30 minutes vers le centre.',
    popularRoutesTitle: 'Trajets Populaires Transfert Barcelone', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport BCN → La Rambla / Quartier Gothique', price: 39 },
      { name: 'Aeroport BCN → Sagrada Familia / Eixample', price: 39 },
      { name: 'Aeroport BCN → Port Olimpic', price: 42 },
      { name: 'Aeroport BCN → Sitges', price: 65 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Barcelone',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Barcelone El Prat (BCN)',
    otherCitiesTitle: 'Nous desservons d\'autres villes europeennes', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.9/5 (1 900+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Барселоны - Эль-Прат',
    subtitle: 'Частный водитель из аэропорта Барселоны на Рамблу, Готический квартал, Саграда Фамилия',
    description: 'Забронируйте трансфер из аэропорта Барселоны. Аэропорт Барселона-Эль-Прат (BCN) - второй по загруженности в Испании, в 12 км от центра. Премиум-трансферы на Рамблу, в Готический квартал, Эшампле, к Саграда Фамилия и в любую точку Барселоны.',
    description2: 'Барселона - мировая столица архитектуры Гауди, средиземноморских пляжей и каталонской кухни.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Барселоны?',
    feature1Title: 'Встреча в BCN', feature1Desc: 'Водитель с табличкой в Эль-Прат. 60 минут бесплатно.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мониторинг в реальном времени.',
    feature3Title: 'Премиум Автомобили', feature3Desc: 'Mercedes, BMW. Чистые, с кондиционером.',
    feature4Title: 'Все Включено', feature4Desc: 'Фиксированная цена при бронировании.',
    sedan: 'Премиум Седан', sedanDesc: '1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes E-Class',
    minivan: 'Минивэн', minivanDesc: 'До 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте', step1Desc: 'Введите данные рейса и адрес.',
    step2: 'Встреча', step2Desc: 'Водитель в Эль-Прат.',
    step3: 'Наслаждайтесь Барселоной', step3Desc: 'Прямой трансфер 20-30 минут.',
    popularRoutesTitle: 'Популярные Маршруты из Аэропорта Барселоны', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт BCN → Рамбла / Готический квартал', price: 39 },
      { name: 'Аэропорт BCN → Саграда Фамилия', price: 39 },
      { name: 'Аэропорт BCN → Порт Олимпик', price: 42 },
      { name: 'Аэропорт BCN → Ситжес', price: 65 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Барселоны',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Барселона Эль-Прат (BCN)',
    otherCitiesTitle: 'Другие города', otherCitiesBtn: 'Все Направления',
    rating: '4.9/5 (1 900+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 39, luxury: 60, minivan: 85, minibus: 140 };

const seoUrls = { en: '/barcelona-airport-transfer', fr: '/transfert-aeroport-barcelone', ru: '/taksi-iz-aeroporta-barselona' };
const BarcelonaTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default BarcelonaTransfer;
