import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Barcelona Airport Transfer - El Prat Airport',
    subtitle: 'Private driver from Barcelona-El Prat Airport to La Rambla, Gothic Quarter, Sagrada Familia and all Barcelona',
    description: 'Barcelona is where Gaudi\'s impossible architecture meets a 4-kilometre Mediterranean beach and 2,000 years of history coexist with a nightlife scene that starts at midnight. The city\'s airport, El Prat Josep Tarradellas (BCN), sits just 12 kilometres southwest but the final 5 kilometres through the Zona Franca industrial area and onto the congested Ronda del Litoral can double the journey time at peak hours. The Aerobus to Placa Catalunya takes 35 minutes and stops only at two points — neither of which is likely your hotel. Our private Barcelona airport transfer bypasses all of this: your driver collects you at arrivals Terminal 1 or Terminal 2, navigates the Ronda de Dalt ringroad or the coastal C-31, and deposits you at the entrance of your hotel in the Gothic Quarter, Eixample, El Born, Gracia, or Barceloneta in 20 to 40 minutes.',
    description2: 'Barcelona\'s urban layout — conceived by Ildefons Cerda in 1859 — is a grid of octagonal blocks called manzanas, each hiding interior gardens invisible from the street. This elegant geometry means our drivers can reach the Sagrada Familia from El Prat in 25 minutes, the Picasso Museum in 30, and Park Guell in 35. But the city\'s one-way system and pedestrianized zones (Las Ramblas, the Born district, parts of the Gothic Quarter) require a driver who knows which streets allow drop-offs and which parking garages are closest to your hotel. Our chauffeurs do this daily.',
    description3: 'Beyond the city, Barcelona is the gateway to Catalonia\'s remarkable diversity. Montserrat, the jagged mountain monastery where the Black Madonna resides, is an hour northwest. The Penedes wine region, home to cava production, stretches 40 minutes southwest with dozens of wineries offering tastings. The Costa Brava, with its hidden coves, Dali museums in Figueres and Cadaques, and medieval villages like Begur and Pals, begins 90 minutes north. Many of our clients book a Barcelona driver for the day: airport to hotel, hotel to Montserrat, back to the city for dinner at a Michelin-star restaurant in the Gothic Quarter. Book your Barcelona transfer and let Catalonia unfold before you.',
    whyChoose: 'Why Choose Our Barcelona Airport Transfer?',
    feature1Title: 'Meet & Greet at BCN', feature1Desc: 'Driver with name sign at El Prat arrivals. 60 minutes free waiting.',
    feature2Title: 'Flight Tracking', feature2Desc: 'Real-time flight monitoring. No extra charge for delays.',
    feature3Title: 'Premium Vehicles', feature3Desc: 'Mercedes, BMW. Clean, air-conditioned, recent models.',
    feature4Title: 'All-Inclusive Pricing', feature4Desc: 'Fixed price at booking. No hidden fees or surprises.',
    sedan: 'Premium Sedan', sedanDesc: '1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes E-Class or similar',
    minivan: 'Minivan', minivanDesc: 'Up to 6 passengers', minibus: 'Minibus', minibusDesc: 'Up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter flight details and Barcelona address. Instant price.',
    step2: 'Meet Your Driver', step2Desc: 'Driver greets you at El Prat arrivals hall.',
    step3: 'Enjoy Barcelona', step3Desc: 'Direct 20-30 minute ride to central Barcelona.',
    popularRoutesTitle: 'Popular Barcelona Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'BCN Airport → La Rambla / Gothic Quarter', price: 39 },
      { name: 'BCN Airport → Sagrada Familia / Eixample', price: 39 },
      { name: 'BCN Airport → Port Olimpic', price: 42 },
      { name: 'BCN Airport → Sitges', price: 65 },
    ],
    bookingForm: 'Book Your Barcelona Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Barcelona El Prat Airport (BCN)',
    otherCitiesTitle: 'We serve other European cities', otherCitiesBtn: 'View All Destinations',
    rating: '4.9/5 (1,900+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Barcelone - El Prat',
    subtitle: 'Chauffeur prive depuis l\'aeroport de Barcelone-El Prat vers La Rambla, le Quartier Gothique et toute Barcelone',
    description: 'Barcelone est la ou l\'architecture impossible de Gaudi rencontre 4 km de plage mediterraneenne et ou 2 000 ans d\'histoire cohabitent avec une vie nocturne qui commence a minuit. L\'aeroport El Prat (BCN) est a 12 km mais les 5 derniers km a travers la Zona Franca peuvent doubler le temps de trajet aux heures de pointe. L\'Aerobus met 35 minutes et ne s\'arrete qu\'en deux points. Notre transfert prive vous depose au Quartier Gothique, Eixample, El Born, Gracia ou Barceloneta en 20-40 minutes.',
    description2: 'Au-dela de la ville, Barcelone est la porte de la Catalogne : Montserrat et sa Vierge noire (1h), la region viticole du Penedes avec ses caves de cava (40 min), la Costa Brava avec ses criques, les musees Dali a Figueres et les villages medievaux de Begur et Pals (90 min). Nos chauffeurs connaissent le systeme de sens uniques et les zones pietonnisees des Ramblas et du Born. Beaucoup de clients reservent un chauffeur a la journee. Reservez votre transfert Barcelone.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Barcelone ?',
    feature1Title: 'Accueil a BCN', feature1Desc: 'Chauffeur avec pancarte aux arrivees El Prat. 60 min d\'attente gratuites.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Suivi en temps reel. Pas de supplement pour retard.',
    feature3Title: 'Vehicules Premium', feature3Desc: 'Mercedes, BMW. Propres, climatises, modeles recents.',
    feature4Title: 'Prix Tout Compris', feature4Desc: 'Prix fixe a la reservation. Aucun frais cache.',
    sedan: 'Berline Premium', sedanDesc: '1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe E ou similaire',
    minivan: 'Monospace', minivanDesc: 'Jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez vol et adresse a Barcelone. Prix instantane.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Chauffeur aux arrivees d\'El Prat.',
    step3: 'Profitez de Barcelone', step3Desc: 'Trajet direct de 20-30 minutes vers le centre.',
    popularRoutesTitle: 'Trajets Populaires Transfert Barcelone', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport BCN → La Rambla / Quartier Gothique', price: 39 },
      { name: 'Aeroport BCN → Sagrada Familia / Eixample', price: 39 },
      { name: 'Aeroport BCN → Port Olimpic', price: 42 },
      { name: 'Aeroport BCN → Sitges', price: 65 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Barcelone',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Barcelone El Prat (BCN)',
    otherCitiesTitle: 'Nous desservons d\'autres villes europeennes', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.9/5 (1 900+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Барселоны - Эль-Прат',
    subtitle: 'Частный водитель из аэропорта Барселоны на Рамблу, Готический квартал, Саграда Фамилия',
    description: 'Барселона — где невозможная архитектура Гауди встречает 4 км средиземноморского пляжа, а 2000 лет истории соседствуют с ночной жизнью, начинающейся в полночь. Аэропорт Эль-Прат (BCN) в 12 км, но последние 5 км через промзону могут удвоить время в пик. Аэробус едет 35 мин с двумя остановками. Наш частный трансфер доставляет в Готический квартал, Эшампле, Эль-Борн, Грасию или Барселонету за 20-40 минут.',
    description2: 'За городом — каталонское разнообразие: Монтсеррат (1 час), винодельческий Пенедес с кавой (40 мин), Коста-Брава с бухтами, музеями Дали в Фигерасе и средневековыми деревнями Бегур и Пальс (90 мин). Водители знают односторонние улицы и пешеходные зоны Рамблас и Борна. Многие клиенты бронируют водителя на весь день: аэропорт-отель, Монтсеррат, ужин в мишленовском ресторане Готического квартала. Забронируйте трансфер из аэропорта Барселоны.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Барселоны?',
    feature1Title: 'Встреча в BCN', feature1Desc: 'Водитель с табличкой в Эль-Прат. 60 минут бесплатно.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мониторинг в реальном времени.',
    feature3Title: 'Премиум Автомобили', feature3Desc: 'Mercedes, BMW. Чистые, с кондиционером.',
    feature4Title: 'Все Включено', feature4Desc: 'Фиксированная цена при бронировании.',
    sedan: 'Премиум Седан', sedanDesc: '1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes E-Class',
    minivan: 'Минивэн', minivanDesc: 'До 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте', step1Desc: 'Введите данные рейса и адрес.',
    step2: 'Встреча', step2Desc: 'Водитель в Эль-Прат.',
    step3: 'Наслаждайтесь Барселоной', step3Desc: 'Прямой трансфер 20-30 минут.',
    popularRoutesTitle: 'Популярные Маршруты из Аэропорта Барселоны', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт BCN → Рамбла / Готический квартал', price: 39 },
      { name: 'Аэропорт BCN → Саграда Фамилия', price: 39 },
      { name: 'Аэропорт BCN → Порт Олимпик', price: 42 },
      { name: 'Аэропорт BCN → Ситжес', price: 65 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Барселоны',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Барселона Эль-Прат (BCN)',
    otherCitiesTitle: 'Другие города', otherCitiesBtn: 'Все Направления',
    rating: '4.9/5 (1 900+ отзывов)',
  },
  hy: {
    title: 'Տրանսֆեր Բարսելոնայի օդանավայանից',
    subtitle: 'Մասնավոր վարորդ El Prat-ից Բարսելոնա',
    description: 'Բարսելոնան գտնվում է այնտեղ՝ որտեղ Գաուդիի անհնար ճարտարապետությունը հանդիպում է 4 կմ լողավայրին: El Prat-ը 12 կմ՝ 20-40 րոպե: Գոթական թաղամաս՝ Eixample՝ El Born՝ Gràcia: Montserrat (1 ժամ)՝ Penedès (40 րոպե)՝ Costa Brava (90 րոպե) Dalí թանգարաններով:',
    description2: 'Կատալոնիան բացվում է:',
    whyChoose: 'Ինչու ընտրել մեր տրանսֆեր բարսելոնայի օդանավայանից',
    feature1Title: 'Դիմավորում', feature1Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով: 60 րոպե անվճար սպասման ժամանակ:',
    feature2Title: 'Թռիչքի հետևում', feature2Desc: 'Իրական ժամանակում թռիչքի հետևում: Անվճար:',
    feature3Title: 'Պրեմիում մեքենաներ', feature3Desc: 'Mercedes E-Class, BMW 5: Մաքուր, կլիմատիզացիա:',
    feature4Title: 'Ֆիքս գներ', feature4Desc: 'Գինը հաստատված է ամրագրման ժամանակ: Թաքնված վճարներ չկան:',
    sedan: 'Պրեմիում սեդան', sedanDesc: 'Mercedes E-Class, 1-3 ուղևոր',
    luxury: 'Լյուքս սեդան', luxuryDesc: 'Mercedes S-Class կամ BMW 7',
    minivan: 'Մինիվեն', minivanDesc: 'Mercedes V-Class, մինչև 6 ուղևոր',
    minibus: 'Մինիբուս', minibusDesc: 'Մինչև 8 ուղևոր',
    passengers: 'Ուղևորներ', luggage: 'Ուղեբարան',
    bookNow: 'ԱՄՏԱԳՏՎԵԼ', allInclusive: 'Ամեն ինչ ներառված է',
    vehiclesTitle: 'Ընտրեք մեքենան',
    howItWorks: 'Ինչպես է աշխատում',
    step1: 'Ամրագրեք օնլայն', step1Desc: 'Մուտքագրեք ձեր տվյալները և հասցեն: Ակնթարթ գնի հաստատում:',
    step2: 'Հանդիպեք վարորդին', step2Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով:',
    step3: 'Հանգստացեք', step3Desc: 'Հարմարավետ ուղևորություն պրեմիում մեքենայում:',
    popularRoutesTitle: 'Սկսած', fromLabel: 'Սկսած',
    bookingForm: 'ԱՄՏԱԳՏՎԵԼ',
    pickupLabel: 'Վերցնում', dropoffLabel: 'Իջնում',
    dateLabel: 'Ամսաթիվ', timeLabel: 'Ժամ',
    defaultPickup: '',
    otherCitiesTitle: 'Սպասարկում ենք 120+ քաղաքներ Եվրոպայում',
    otherCitiesBtn: 'Բոլոր ուղղությունները',
    rating: '4.9/5',
  },
};

const vehiclesPrices = { sedan: 39, luxury: 60, minivan: 85, minibus: 140 };

const seoUrls = { en: '/barcelona-airport-transfer', fr: '/transfert-aeroport-barcelone', ru: '/taksi-iz-aeroporta-barselona', hy: '/barselona-odanavakayani-transfer' };
const BarcelonaTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default BarcelonaTransfer;
