import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Beauvais Airport Transfer - Private Driver from 99\u20AC',
    subtitle: 'Professional private driver from Beauvais-Tille Airport to Paris city center, hotels and all destinations. Fixed prices from 99\u20AC',
    description: 'Beauvais-Tille Airport sits 85 kilometres north of Paris — a distance that surprises many budget travelers who chose a cheap Ryanair or Wizz Air fare without checking the map. The official shuttle bus costs around 17 euros but takes 75 to 90 minutes, drops you only at Porte Maillot, and does not wait if your flight is delayed. A Beauvais taxi to central Paris can exceed 200 euros with no guarantee of comfort. Our private Beauvais airport transfer solves every one of these problems: a fixed price agreed in advance, a professional driver who monitors your landing time, and a direct door-to-door ride in a clean, air-conditioned Mercedes or BMW. No changes, no crowds, no surprises.',
    description2: 'The drive from Beauvais follows the A16 motorway south, merging onto the Peripherique to reach any Paris neighbourhood. To the Marais: about 80 minutes. To Montmartre or Opera: 75 minutes. To the Eiffel Tower: 85 minutes. Traffic on the A16 is typically lighter than the A1 from CDG, meaning journey times are more predictable. Our drivers also know alternative routes through Meru, Chambly, and L\'Isle-Adam that bypass motorway congestion on Friday evenings and holiday weekends. For travelers continuing beyond Paris, we can take you directly to Disneyland Paris (about 100 minutes), Versailles, or even Reims in the Champagne region.',
    description3: 'Beauvais itself is a hidden gem of northern France. Its Saint-Pierre cathedral has the tallest Gothic choir in the world — 48 metres of soaring stone that rivals Notre-Dame de Paris. The medieval town centre and the astronomical clock are worth a visit if your schedule allows a stopover. Many of our passengers flying into Beauvais are heading to events in Paris: concerts at the Stade de France, conferences at the Parc des Expositions, or fashion shows during Paris Fashion Week. Whatever your reason for choosing Beauvais, our transfer ensures the savings on your flight are not wasted on a stressful, expensive journey into the capital. Book now, travel smart.',
    whyChoose: 'Why Choose Our Beauvais Airport Transfer?',
    feature1Title: 'Door-to-Door Service', feature1Desc: 'No shuttle to Porte Maillot. Direct to your exact Paris hotel or address.',
    feature2Title: 'Flight Monitoring', feature2Desc: 'We track your Ryanair or Wizz Air flight. Free waiting time for delays.',
    feature3Title: 'Premium Vehicles', feature3Desc: 'Spacious vehicles with room for luggage. Mercedes, BMW or similar.',
    feature4Title: 'Fixed Price from 99\u20AC', feature4Desc: 'Price locked at booking. No meters, no toll surprises. Much cheaper than a taxi.',
    sedan: 'Premium Sedan', sedanDesc: 'Comfortable sedan, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes E-Class or similar',
    minivan: 'Minivan', minivanDesc: 'For families up to 6 passengers', minibus: 'Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter your Beauvais flight number and Paris address. Fixed price confirmed.',
    step2: 'Meet Your Driver', step2Desc: 'Driver waits at Beauvais Airport exit with your name sign.',
    step3: 'Direct to Paris', step3Desc: 'Comfortable ride directly to your Paris hotel. No stops, no changes.',
    popularRoutesTitle: 'Popular Beauvais Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'Beauvais Airport \u2192 Paris City Center', price: 120 },
      { name: 'Beauvais Airport \u2192 Montmartre / Opera', price: 115 },
      { name: 'Beauvais Airport \u2192 Disneyland Paris', price: 160 },
      { name: 'Beauvais Airport \u2192 CDG Airport', price: 140 },
    ],
    bookingForm: 'Book Your Beauvais Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Beauvais-Tille Airport',
    otherCitiesTitle: 'Also available from CDG and Orly airports', otherCitiesBtn: 'View All Destinations',
    rating: '4.5/5 Tripadvisor (29 reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Beauvais - Chauffeur Prive des 99\u20AC',
    subtitle: 'Chauffeur prive professionnel depuis l\'aeroport de Beauvais-Tille vers Paris centre, hotels et toutes destinations. Prix fixes des 99\u20AC',
    description: 'L\'aeroport de Beauvais-Tille se trouve a 85 kilometres au nord de Paris — une distance qui surprend beaucoup de voyageurs ayant choisi un vol Ryanair ou Wizz Air a bas prix sans consulter la carte. La navette officielle coute environ 17 euros mais met 75 a 90 minutes, vous depose uniquement a la Porte Maillot, et ne vous attend pas en cas de retard de vol. Un taxi Beauvais vers Paris centre peut depasser 200 euros sans garantie de confort. Notre transfert prive depuis Beauvais resout chacun de ces problemes : un prix fixe convenu a l\'avance, un chauffeur professionnel qui suit votre heure d\'atterrissage, et un trajet direct porte-a-porte dans une Mercedes ou BMW propre et climatisee. Pas de changement, pas de foule, pas de mauvaise surprise.',
    description2: 'Le trajet depuis Beauvais emprunte l\'autoroute A16 vers le sud, puis rejoint le Peripherique pour atteindre n\'importe quel quartier parisien. Vers le Marais : environ 80 minutes. Vers Montmartre ou l\'Opera : 75 minutes. Vers la Tour Eiffel : 85 minutes. La circulation sur l\'A16 est generalement plus fluide que sur l\'A1 depuis CDG, ce qui rend les temps de trajet plus previsibles. Nos chauffeurs connaissent aussi les alternatives par Meru, Chambly et L\'Isle-Adam pour eviter les bouchons de l\'autoroute le vendredi soir et les weekends de vacances. Pour ceux qui continuent au-dela de Paris, nous pouvons vous conduire directement a Disneyland Paris (environ 100 minutes), Versailles, ou meme Reims en Champagne.',
    description3: 'Beauvais elle-meme est un joyau cache du nord de la France. Sa cathedrale Saint-Pierre possede le choeur gothique le plus haut du monde — 48 metres de pierre vertigineuse qui rivalise avec Notre-Dame de Paris. Le centre medieval et l\'horloge astronomique meritent une visite si votre emploi du temps le permet. Nombre de nos passagers atterrissant a Beauvais se rendent a des evenements parisiens : concerts au Stade de France, salons au Parc des Expositions, defiles pendant la Fashion Week. Quelle que soit votre raison de choisir Beauvais, notre transfert garantit que les economies sur votre billet d\'avion ne seront pas gaspillees dans un trajet stressant et couteux vers la capitale. Reservez maintenant, voyagez malin.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Beauvais ?',
    feature1Title: 'Service Porte-a-Porte', feature1Desc: 'Pas de navette jusqu\'a Porte Maillot. Direct a votre hotel ou adresse a Paris.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Suivi de votre vol Ryanair ou Wizz Air. Attente gratuite en cas de retard.',
    feature3Title: 'Vehicules Premium', feature3Desc: 'Vehicules spacieux avec place pour les bagages. Mercedes, BMW ou similaire.',
    feature4Title: 'Prix Fixe des 99\u20AC', feature4Desc: 'Prix verrouille a la reservation. Pas de compteur. Bien moins cher qu\'un taxi.',
    sedan: 'Berline Premium', sedanDesc: 'Berline confortable, 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe E ou similaire',
    minivan: 'Monospace', minivanDesc: 'Pour familles jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Pour groupes jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez votre vol Beauvais et adresse a Paris. Prix fixe confirme.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Le chauffeur vous attend a la sortie de l\'aeroport de Beauvais.',
    step3: 'Direct vers Paris', step3Desc: 'Trajet confortable directement a votre hotel. Sans arret, sans changement.',
    popularRoutesTitle: 'Trajets Populaires depuis Beauvais', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport Beauvais \u2192 Centre de Paris', price: 120 },
      { name: 'Aeroport Beauvais \u2192 Montmartre / Opera', price: 115 },
      { name: 'Aeroport Beauvais \u2192 Disneyland Paris', price: 160 },
      { name: 'Aeroport Beauvais \u2192 Aeroport CDG', price: 140 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Beauvais',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Beauvais-Tille',
    otherCitiesTitle: 'Egalement depuis CDG et Orly', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.5/5 Tripadvisor (29 avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Бове - Частный Автомобиль до Парижа',
    subtitle: 'Профессиональный водитель из аэропорта Бове-Тийе в центр Парижа, отели и все направления',
    description: 'Аэропорт Бове-Тийе расположен в 85 километрах к северу от Парижа — расстояние, которое удивляет многих бюджетных путешественников, выбравших дешёвый рейс Ryanair или Wizz Air, не заглянув в карту. Официальный автобус-шаттл стоит около 17 евро, но едет 75-90 минут, высаживает только у Порт-Майо и не ждёт при задержке рейса. Такси из Бове в центр Парижа может обойтись дороже 200 евро без гарантии комфорта. Наш частный трансфер из Бове решает все эти проблемы: фиксированная цена, согласованная заранее, профессиональный водитель, отслеживающий время посадки, и прямая поездка от двери до двери в чистом Mercedes или BMW с кондиционером.',
    description2: 'Путь из Бове проходит по автомагистрали A16 на юг, затем по Периферик до любого парижского района. До Марэ — около 80 минут, до Монмартра или Оперы — 75 минут, до Эйфелевой башни — 85 минут. Движение на A16 обычно спокойнее, чем на A1 из CDG, что делает время в пути предсказуемым. Наши водители знают альтернативные маршруты через Меру, Шамбли и Лиль-Адам для обхода пробок в пятницу вечером и праздничные выходные. Для тех, кто едет дальше Парижа — Диснейленд (100 минут), Версаль или даже Реймс в Шампани.',
    description3: 'Сам Бове — скрытая жемчужина северной Франции. Его собор Сен-Пьер имеет самый высокий готический хор в мире — 48 метров парящего камня, соперничающего с Нотр-Дам де Пари. Средневековый центр и астрономические часы заслуживают остановки, если позволяет расписание. Многие наши пассажиры, прилетающие в Бове, направляются на мероприятия в Париже: концерты на Стад-де-Франс, выставки в Parc des Expositions, показы мод. Каким бы ни был повод выбрать Бове, наш трансфер гарантирует, что экономия на авиабилете не будет потрачена на стрессовую дорогу до столицы. Бронируйте сейчас.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Бове?',
    feature1Title: 'От Двери до Двери', feature1Desc: 'Без шаттла до Порт-Майо. Прямо к вашему отелю или адресу в Париже.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мы следим за вашим рейсом Ryanair или Wizz Air. Бесплатное ожидание.',
    feature3Title: 'Премиум Автомобили', feature3Desc: 'Просторные автомобили с местом для багажа. Mercedes, BMW.',
    feature4Title: 'Гарантия Фиксированной Цены', feature4Desc: 'Цена при бронировании. Без счётчиков. Дешевле такси.',
    sedan: 'Премиум Седан', sedanDesc: 'Комфортный седан, 1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes E-Class или аналог',
    minivan: 'Минивэн', minivanDesc: 'Для семей до 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'Для групп до 8 человек',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Укажите рейс из Бове и адрес в Париже. Фиксированная цена.',
    step2: 'Встретьте Водителя', step2Desc: 'Водитель ждёт у выхода аэропорта Бове с табличкой.',
    step3: 'Прямо в Париж', step3Desc: 'Комфортная поездка до вашего отеля. Без остановок и пересадок.',
    popularRoutesTitle: 'Популярные Маршруты из Бове', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт Бове \u2192 Центр Парижа', price: 120 },
      { name: 'Аэропорт Бове \u2192 Монмартр / Опера', price: 115 },
      { name: 'Аэропорт Бове \u2192 Диснейленд', price: 160 },
      { name: 'Аэропорт Бове \u2192 Аэропорт CDG', price: 140 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Бове',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Бове-Тийе',
    otherCitiesTitle: 'Также из CDG и Орли', otherCitiesBtn: 'Все Направления',
    rating: '4.5/5 Tripadvisor (29 отзывов)',
  },
  hy: {
    title: 'Տրանսֆեր Beauvais օդանավայանից',
    subtitle: 'Մասնավոր վարորդ Beauvais-ից Փարիզ',
    description: 'Beauvais-ը գտնվում է 85 կմ Փարիզից հյուս՝ Ryanair-ի և Wizz Air-ի բյուջետային օդանավայան: Պաշտոնական շատլը 90 րոպե է և իջնում է միայն Porte Maillot: Մեր դռից-դուռ մասնավոր տրանսֆերը ձեզ փրկում է այդ բոլոր խնդիրներից: Ֆիքս գին՝ թռիչքի հետևում՝ պրեմիում մեքենա:',
    description2: 'Beauvais-ի տաճարը Հյուսիսային Ֆրանսիայի թաքնված գոհարը է՝ Սեն Պիեռ տաճարը ունի աշխարհի ամենաբարձր գոթական երգչասրահը:',
    whyChoose: 'Ինչու ընտրել մեր տրանսֆեր beauvais օդանավայանից',
    feature1Title: 'Դիմավորում', feature1Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով: 60 րոպե անվճար սպասման ժամանակ:',
    feature2Title: 'Թռիչքի հետևում', feature2Desc: 'Իրական ժամանակում թռիչքի հետևում: Անվճար:',
    feature3Title: 'Պրեմիում մեքենաներ', feature3Desc: 'Mercedes E-Class, BMW 5: Մաքուր, կլիմատիզացիա:',
    feature4Title: 'Ֆիքս գներ', feature4Desc: 'Գինը հաստատված է ամրագրման ժամանակ: Թաքնված վճարներ չկան:',
    sedan: 'Պրեմիում սեդան', sedanDesc: 'Mercedes E-Class, 1-3 ուղևոր',
    luxury: 'Լյուքս սեդան', luxuryDesc: 'Mercedes S-Class կամ BMW 7',
    minivan: 'Մինիվեն', minivanDesc: 'Mercedes V-Class, մինչև 6 ուղևոր',
    minibus: 'Մինիբուս', minibusDesc: 'Մինչև 8 ուղևոր',
    passengers: 'Ուղևորներ', luggage: 'Ուղեբարան',
    bookNow: 'ԱՄՏԱԳՏՎԵԼ', allInclusive: 'Ամեն ինչ ներառված է',
    vehiclesTitle: 'Ընտրեք մեքենան',
    howItWorks: 'Ինչպես է աշխատում',
    step1: 'Ամրագրեք օնլայն', step1Desc: 'Մուտքագրեք ձեր տվյալները և հասցեն: Ակնթարթ գնի հաստատում:',
    step2: 'Հանդիպեք վարորդին', step2Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով:',
    step3: 'Հանգստացեք', step3Desc: 'Հարմարավետ ուղևորություն պրեմիում մեքենայում:',
    popularRoutesTitle: 'Սկսած', fromLabel: 'Սկսած',
    bookingForm: 'ԱՄՏԱԳՏՎԵԼ',
    pickupLabel: 'Վերցնում', dropoffLabel: 'Իջնում',
    dateLabel: 'Ամսաթիվ', timeLabel: 'Ժամ',
    defaultPickup: '',
    otherCitiesTitle: 'Սպասարկում ենք 16 քաղաքներ Եվրոպայում',
    otherCitiesBtn: 'Բոլոր ուղղությունները',
    rating: '4.5/5 Tripadvisor',
  },
};

const vehiclesPrices = { sedan: 120, luxury: 165, minivan: 200, minibus: 280 };

const seoUrls = { en: '/beauvais-airport-transfer', fr: '/transfert-aeroport-beauvais', ru: '/taksi-iz-aeroporta-bove', hy: '/bove-odanavakayani-transfer' };
const BeauvaisTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default BeauvaisTransfer;
