import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Beauvais Airport Transfer - Private Car to Paris',
    subtitle: 'Professional private driver from Beauvais-Tille Airport to Paris city center, hotels and all destinations',
    description: 'Book your Beauvais airport transfer with professional English-speaking drivers. Beauvais-Tille Airport (BVA) is located 85 km north of Paris and is a major hub for low-cost airlines like Ryanair and Wizz Air. We provide premium private car transfers from Beauvais Airport directly to central Paris, your hotel, or any address. Fixed prices with no surprises - no extra charges for traffic or delays. The journey takes approximately 75-90 minutes depending on traffic conditions.',
    description2: 'Many travelers choose Beauvais for affordable flights but are surprised by the distance to Paris. The official shuttle bus takes over 90 minutes and drops you at Porte Maillot only. Our private transfer takes you door-to-door, directly to your hotel or any Paris address. Travel in comfort after your flight, with a professional driver who monitors your arrival in real-time.',
    whyChoose: 'Why Choose Our Beauvais Airport Transfer?',
    feature1Title: 'Door-to-Door Service', feature1Desc: 'Direct to your Paris hotel or address. No bus changes, no metro, no hassle.',
    feature2Title: 'Flight Monitoring', feature2Desc: 'We track your Ryanair or Wizz Air flight. No surcharge for delays.',
    feature3Title: 'Comfortable Ride', feature3Desc: 'Relax in a premium vehicle for the 75-90 minute journey to Paris.',
    feature4Title: 'Fixed Price', feature4Desc: 'Price confirmed at booking. Cheaper than a taxi, more comfortable than the bus.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class or similar',
    minivan: 'Minivan', minivanDesc: 'Mercedes V-Class, up to 6 passengers', minibus: 'Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter your flight details and Paris address. Instant price confirmation.',
    step2: 'Meet at Beauvais', step2Desc: 'Driver waits at Beauvais arrivals with your name sign. Help with luggage.',
    step3: 'Direct to Paris', step3Desc: 'Comfortable 75-90 minute ride directly to your Paris destination.',
    popularRoutesTitle: 'Popular Beauvais Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'Beauvais Airport → Paris City Center', price: 120 },
      { name: 'Beauvais Airport → Gare du Nord', price: 115 },
      { name: 'Beauvais Airport → Champs-Elysees', price: 125 },
      { name: 'Beauvais Airport → Disneyland Paris', price: 160 },
    ],
    bookingForm: 'Book Your Beauvais Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Beauvais-Tille Airport (BVA)',
    otherCitiesTitle: 'Also available from other Paris airports', otherCitiesBtn: 'View All Destinations',
    rating: '4.8/5 (1,400+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Beauvais - Voiture Privee vers Paris',
    subtitle: 'Chauffeur prive professionnel depuis l\'aeroport Beauvais-Tille vers Paris centre, hotels et toutes destinations',
    description: 'Reservez votre transfert aeroport Beauvais avec des chauffeurs professionnels. L\'aeroport Beauvais-Tille (BVA) est situe a 85 km au nord de Paris et est un hub majeur pour les compagnies low-cost comme Ryanair et Wizz Air. Nous proposons des transferts en voiture privee premium depuis Beauvais directement vers Paris centre, votre hotel ou toute adresse. Prix fixes sans surprises - aucun supplement pour le trafic ou les retards. Le trajet dure environ 75-90 minutes selon la circulation.',
    description2: 'Beaucoup de voyageurs choisissent Beauvais pour les vols pas chers mais sont surpris par la distance avec Paris. La navette officielle prend plus de 90 minutes et vous depose a Porte Maillot uniquement. Notre transfert prive vous emmene de porte a porte, directement a votre hotel ou toute adresse parisienne.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Beauvais ?',
    feature1Title: 'Service Porte-a-Porte', feature1Desc: 'Direct vers votre hotel ou adresse a Paris. Pas de bus, pas de metro.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Nous suivons votre vol Ryanair ou Wizz Air. Pas de supplement pour retard.',
    feature3Title: 'Trajet Confortable', feature3Desc: 'Detendez-vous dans un vehicule premium pendant les 75-90 minutes vers Paris.',
    feature4Title: 'Prix Fixe', feature4Desc: 'Prix confirme a la reservation. Moins cher qu\'un taxi, plus confortable que le bus.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E, 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S ou similaire',
    minivan: 'Monospace', minivanDesc: 'Mercedes Classe V, jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Pour groupes jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez les details de votre vol et adresse a Paris. Prix instantane.',
    step2: 'Rendez-vous a Beauvais', step2Desc: 'Chauffeur aux arrivees de Beauvais avec pancarte nominative. Aide aux bagages.',
    step3: 'Direct vers Paris', step3Desc: 'Trajet confortable de 75-90 minutes vers votre destination parisienne.',
    popularRoutesTitle: 'Trajets Populaires depuis Beauvais', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport Beauvais → Paris Centre', price: 120 },
      { name: 'Aeroport Beauvais → Gare du Nord', price: 115 },
      { name: 'Aeroport Beauvais → Champs-Elysees', price: 125 },
      { name: 'Aeroport Beauvais → Disneyland Paris', price: 160 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Beauvais',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Beauvais-Tille (BVA)',
    otherCitiesTitle: 'Egalement disponible depuis les autres aeroports parisiens', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.8/5 (1 400+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Бове - Частный Автомобиль в Париж',
    subtitle: 'Профессиональный водитель из аэропорта Бове-Тийе в центр Парижа, отели и все направления',
    description: 'Забронируйте трансфер из аэропорта Бове с профессиональными водителями. Аэропорт Бове-Тийе (BVA) расположен в 85 км к северу от Парижа и является хабом для лоукостеров Ryanair и Wizz Air. Мы обеспечиваем премиум-трансферы из Бове прямо в центр Парижа, ваш отель или любой адрес. Фиксированные цены без сюрпризов. Поездка занимает 75-90 минут.',
    description2: 'Многие выбирают Бове из-за дешевых рейсов, но удивляются расстоянию до Парижа. Официальный автобус идет более 90 минут и привозит только на Порт Майо. Наш трансфер - от двери до двери, прямо в отель.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Бове?',
    feature1Title: 'Сервис Дверь-в-Дверь', feature1Desc: 'Прямо до вашего отеля в Париже. Без автобусов и метро.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мониторинг рейсов Ryanair и Wizz Air. Без доплаты.',
    feature3Title: 'Комфортная Поездка', feature3Desc: 'Расслабьтесь в премиум авто на протяжении 75-90 минут до Парижа.',
    feature4Title: 'Фиксированная Цена', feature4Desc: 'Цена при бронировании. Дешевле такси, комфортнее автобуса.',
    sedan: 'Премиум Седан', sedanDesc: 'Mercedes E-Class, 1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes S-Class',
    minivan: 'Минивэн', minivanDesc: 'Mercedes V-Class, до 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Введите данные рейса и адрес в Париже.',
    step2: 'Встреча в Бове', step2Desc: 'Водитель ждет с табличкой. Помощь с багажом.',
    step3: 'Прямо в Париж', step3Desc: 'Комфортная поездка 75-90 минут.',
    popularRoutesTitle: 'Популярные Маршруты из Бове', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт Бове → Центр Парижа', price: 120 },
      { name: 'Аэропорт Бове → Северный Вокзал', price: 115 },
      { name: 'Аэропорт Бове → Елисейские Поля', price: 125 },
      { name: 'Аэропорт Бове → Диснейленд Париж', price: 160 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Бове',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Бове-Тийе (BVA)',
    otherCitiesTitle: 'Также из других парижских аэропортов', otherCitiesBtn: 'Все Направления',
    rating: '4.8/5 (1 400+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 120, luxury: 160, minivan: 200, minibus: 280 };

const seoUrls = { en: '/beauvais-airport-transfer', fr: '/transfert-aeroport-beauvais', ru: '/taksi-iz-aeroporta-bove' };
const BeauvaisTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default BeauvaisTransfer;
