import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Berlin Airport Transfer - BER Brandenburg',
    subtitle: 'Professional private driver from Berlin Brandenburg Airport to city center, hotels and all Berlin destinations',
    description: 'Book your Berlin airport transfer with experienced drivers. Berlin Brandenburg Airport (BER) is the main international gateway to Germany\'s capital. We provide reliable private car service from BER Airport to Berlin city center, Potsdamer Platz, Alexanderplatz, Brandenburg Gate area, Mitte, and all Berlin districts. Fixed prices, flight tracking, meet and greet at arrivals.',
    description2: 'Berlin is Europe\'s vibrant capital of culture and history. From the Brandenburg Gate to Museum Island, from Kreuzberg to Charlottenburg, our drivers know every corner of the city. Skip the taxi queues and public transport hassle - enjoy a comfortable, direct transfer to your destination.',
    whyChoose: 'Why Choose Our Berlin Airport Transfer?',
    feature1Title: 'Meet & Greet at BER', feature1Desc: 'Driver with name sign at BER arrivals. 60 minutes free waiting time.',
    feature2Title: 'Flight Monitoring', feature2Desc: 'Real-time flight tracking. No extra charge for delays.',
    feature3Title: 'Comfortable Vehicles', feature3Desc: 'Clean, air-conditioned Mercedes, BMW or Audi. Less than 3 years old.',
    feature4Title: 'Transparent Pricing', feature4Desc: 'Fixed price at booking. No hidden fees or surge pricing.',
    sedan: 'Premium Sedan', sedanDesc: 'Ideal for 1-3 passengers', luxury: 'Business Sedan', luxuryDesc: 'Mercedes E-Class or BMW 5 Series',
    minivan: 'Minivan', minivanDesc: 'For groups up to 6 passengers', minibus: 'Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter flight number and Berlin address. Instant confirmation.',
    step2: 'Meet at BER', step2Desc: 'Driver greets you at arrivals with name sign and helps with luggage.',
    step3: 'Direct to Berlin', step3Desc: 'Comfortable 30-45 minute ride to central Berlin.',
    popularRoutesTitle: 'Popular Berlin Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'BER Airport → Berlin Mitte', price: 45 },
      { name: 'BER Airport → Potsdamer Platz', price: 45 },
      { name: 'BER Airport → Alexanderplatz', price: 50 },
      { name: 'BER Airport → Charlottenburg', price: 55 },
    ],
    bookingForm: 'Book Your Berlin Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Berlin Brandenburg Airport (BER)',
    otherCitiesTitle: 'We also serve other European cities', otherCitiesBtn: 'View All Destinations',
    rating: '4.8/5 (1,400+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Berlin - BER Brandenburg',
    subtitle: 'Chauffeur prive professionnel depuis l\'aeroport de Berlin Brandenburg vers le centre-ville et tous les quartiers',
    description: 'Reservez votre transfert aeroport Berlin avec des chauffeurs experimentes. L\'aeroport Berlin Brandenburg (BER) est la principale porte d\'entree internationale de la capitale allemande. Nous offrons un service de voiture privee fiable depuis BER vers le centre de Berlin, Potsdamer Platz, Alexanderplatz, la Porte de Brandebourg, Mitte et tous les quartiers. Prix fixes, suivi de vol, accueil aux arrivees.',
    description2: 'Berlin est la vibrante capitale europeenne de la culture et de l\'histoire. De la Porte de Brandebourg a l\'ile aux Musees, nos chauffeurs connaissent chaque recoin de la ville.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Berlin ?',
    feature1Title: 'Accueil a BER', feature1Desc: 'Chauffeur avec pancarte aux arrivees BER. 60 min d\'attente gratuites.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Suivi en temps reel. Pas de supplement pour retard.',
    feature3Title: 'Vehicules Confortables', feature3Desc: 'Mercedes, BMW ou Audi climatises. Moins de 3 ans.',
    feature4Title: 'Prix Transparents', feature4Desc: 'Prix fixe a la reservation. Aucun frais cache.',
    sedan: 'Berline Premium', sedanDesc: 'Ideal pour 1-3 passagers', luxury: 'Berline Business', luxuryDesc: 'Mercedes Classe E ou BMW Serie 5',
    minivan: 'Monospace', minivanDesc: 'Pour groupes jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Pour groupes jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez le numero de vol et adresse a Berlin. Confirmation instantanee.',
    step2: 'Rendez-vous a BER', step2Desc: 'Chauffeur aux arrivees avec pancarte et aide aux bagages.',
    step3: 'Direct vers Berlin', step3Desc: 'Trajet confortable de 30-45 minutes vers le centre de Berlin.',
    popularRoutesTitle: 'Trajets Populaires Transfert Aeroport Berlin', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport BER → Berlin Mitte', price: 45 },
      { name: 'Aeroport BER → Potsdamer Platz', price: 45 },
      { name: 'Aeroport BER → Alexanderplatz', price: 50 },
      { name: 'Aeroport BER → Charlottenburg', price: 55 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Berlin',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Berlin Brandenburg (BER)',
    otherCitiesTitle: 'Nous desservons aussi d\'autres villes europeennes', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.8/5 (1 400+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Берлина - BER Бранденбург',
    subtitle: 'Профессиональный водитель из аэропорта Берлин-Бранденбург в центр города и все районы',
    description: 'Забронируйте трансфер из аэропорта Берлина с опытными водителями. Аэропорт Берлин-Бранденбург (BER) - главные ворота столицы Германии. Мы обеспечиваем надежный трансфер из BER в центр Берлина, Потсдамскую площадь, Александерплац, район Бранденбургских ворот и все районы.',
    description2: 'Берлин - яркая европейская столица культуры и истории. Наши водители знают каждый уголок города.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Берлина?',
    feature1Title: 'Встреча в BER', feature1Desc: 'Водитель с табличкой в зале прилета BER. 60 минут ожидания бесплатно.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мониторинг в реальном времени. Без доплаты.',
    feature3Title: 'Комфортные Автомобили', feature3Desc: 'Mercedes, BMW или Audi с кондиционером. Не старше 3 лет.',
    feature4Title: 'Прозрачные Цены', feature4Desc: 'Фиксированная цена при бронировании.',
    sedan: 'Премиум Седан', sedanDesc: 'Для 1-3 пассажиров', luxury: 'Бизнес Седан', luxuryDesc: 'Mercedes E-Class или BMW 5 серии',
    minivan: 'Минивэн', minivanDesc: 'До 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Введите номер рейса и адрес в Берлине.',
    step2: 'Встреча в BER', step2Desc: 'Водитель встречает вас в зале прилета.',
    step3: 'Прямо в Берлин', step3Desc: 'Комфортная поездка 30-45 минут.',
    popularRoutesTitle: 'Популярные Маршруты из Аэропорта Берлина', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт BER → Берлин Митте', price: 45 },
      { name: 'Аэропорт BER → Потсдамская площадь', price: 45 },
      { name: 'Аэропорт BER → Александерплац', price: 50 },
      { name: 'Аэропорт BER → Шарлоттенбург', price: 55 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Берлина',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Берлин-Бранденбург (BER)',
    otherCitiesTitle: 'Другие города Европы', otherCitiesBtn: 'Все Направления',
    rating: '4.8/5 (1 400+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 45, luxury: 70, minivan: 95, minibus: 150 };

const BerlinTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} />;
export default BerlinTransfer;
