import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Berlin Airport Transfer - BER Brandenburg',
    subtitle: 'Professional private driver from Berlin Brandenburg Airport to city center, hotels and all Berlin destinations',
    description: 'Berlin is a city where history speaks from every street corner. The Brandenburg Gate, the remnants of the Wall, the solemn Holocaust Memorial, the luminous dome of the Reichstag — they form a narrative that draws over 13 million international visitors each year. Since 2020, all flights arrive at Berlin Brandenburg Airport (BER), a modern facility located 18 kilometres south of the city centre in Schonefeld. While the airport-express train exists, it requires a platform change at Hauptbahnhof and does not run after midnight — precisely when many transatlantic and Middle Eastern flights land. Our private Berlin airport transfer eliminates these hassles: your driver meets you at the BER arrivals hall with a name sign, loads your luggage, and delivers you to Mitte, Kreuzberg, Charlottenburg, or Potsdamer Platz in 30 to 45 minutes.',
    description2: 'The drive from BER into Berlin follows the A113 motorway through the leafy southern suburbs, crossing the Teltow Canal before reaching the inner-city Sudkreuz ring. Our drivers know which route works best depending on the hour: the direct motorway approach for early mornings, the scenic Treptower Park route for midday arrivals, and the back streets through Neukolln for Friday evening rush hour. BER also serves as the starting point for excursions to Potsdam and its UNESCO-listed Sanssouci Palace (just 40 minutes west), the Spreewald biosphere reserve (90 minutes south), or even Dresden and its baroque Frauenkirche (two hours).',
    description3: 'Berlin\'s creative energy is unmatched in Europe. From the street art of East Side Gallery to the techno temples of Berghain, from the gourmet food markets of Markthalle Neun to the Michelin-starred restaurants along Unter den Linden, the city caters to every taste. Many of our clients are business travelers attending events at Messe Berlin, the ICC Congress Center, or the tech campuses of Factory Berlin — all locations our drivers navigate daily. For families, a BER pickup with a child seat (free on request) followed by a direct drive to your Airbnb in Prenzlauer Berg beats any combination of trains and trams. Book your Berlin airport transfer and arrive ready to explore.',
    whyChoose: 'Why Choose Our Berlin Airport Transfer?',
    feature1Title: 'Meet & Greet at BER', feature1Desc: 'Driver with name sign at BER arrivals. 60 minutes free waiting time.',
    feature2Title: 'Flight Monitoring', feature2Desc: 'Real-time flight tracking. No extra charge for delays.',
    feature3Title: 'Comfortable Vehicles', feature3Desc: 'Clean, air-conditioned Mercedes, BMW or Audi. Less than 3 years old.',
    feature4Title: 'Transparent Pricing', feature4Desc: 'Fixed price at booking. No hidden fees or surge pricing.',
    sedan: 'Premium Sedan', sedanDesc: 'Ideal for 1-3 passengers', luxury: 'Business Sedan', luxuryDesc: 'Mercedes E-Class or BMW 5 Series',
    minivan: 'Minivan', minivanDesc: 'For groups up to 6 passengers', minibus: 'Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter flight number and Berlin address. Instant confirmation.',
    step2: 'Meet at BER', step2Desc: 'Driver greets you at arrivals with name sign and helps with luggage.',
    step3: 'Direct to Berlin', step3Desc: 'Comfortable 30-45 minute ride to central Berlin.',
    popularRoutesTitle: 'Popular Berlin Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'BER Airport → Berlin Mitte', price: 45 },
      { name: 'BER Airport → Potsdamer Platz', price: 45 },
      { name: 'BER Airport → Alexanderplatz', price: 50 },
      { name: 'BER Airport → Charlottenburg', price: 55 },
    ],
    bookingForm: 'Book Your Berlin Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Berlin Brandenburg Airport (BER)',
    otherCitiesTitle: 'We also serve other European cities', otherCitiesBtn: 'View All Destinations',
    rating: '4.8/5 (1,400+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Berlin - BER Brandenburg',
    subtitle: 'Chauffeur prive professionnel depuis l\'aeroport de Berlin Brandenburg vers le centre-ville et tous les quartiers',
    description: 'Reservez votre transfert aeroport Berlin avec des chauffeurs experimentes. L\'aeroport Berlin Brandenburg (BER) est la principale porte d\'entree internationale de la capitale allemande. Nous offrons un service de voiture privee fiable depuis BER vers le centre de Berlin, Potsdamer Platz, Alexanderplatz, la Porte de Brandebourg, Mitte et tous les quartiers. Prix fixes, suivi de vol, accueil aux arrivees.',
    description2: 'Le trajet depuis BER suit l\'autoroute A113 a travers les banlieues verdoyantes, longe le canal de Teltow avant d\'atteindre le ring Sudkreuz. Nos chauffeurs savent quel itineraire privilegier selon l\'heure. BER est aussi le point de depart pour Potsdam et Sanssouci (40 minutes), la reserve de biosphere de la Spreewald (90 minutes), ou meme Dresde et sa Frauenkirche (deux heures). Berlin regorge d\'energie creative : East Side Gallery, marches gourmets de Markthalle Neun, restaurants etoiles Unter den Linden. Reservez votre transfert Berlin.',
    description3: 'Berlin est une ville ou l\'histoire parle a chaque coin de rue. La Porte de Brandebourg, les vestiges du Mur, le Memorial de l\'Holocauste, le dome lumineux du Reichstag — un recit qui attire plus de 13 millions de visiteurs internationaux par an. Depuis 2020, tous les vols arrivent a BER, a 18 km au sud du centre. Le train express necessite un changement a Hauptbahnhof et ne circule pas apres minuit — precisement quand atterrissent de nombreux vols transatlantiques. Notre transfert prive vous attend aux arrivees avec pancarte, charge vos bagages et vous depose a Mitte, Kreuzberg, Charlottenburg ou Potsdamer Platz en 30-45 minutes.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Berlin ?',
    feature1Title: 'Accueil a BER', feature1Desc: 'Chauffeur avec pancarte aux arrivees BER. 60 min d\'attente gratuites.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Suivi en temps reel. Pas de supplement pour retard.',
    feature3Title: 'Vehicules Confortables', feature3Desc: 'Mercedes, BMW ou Audi climatises. Moins de 3 ans.',
    feature4Title: 'Prix Transparents', feature4Desc: 'Prix fixe a la reservation. Aucun frais cache.',
    sedan: 'Berline Premium', sedanDesc: 'Ideal pour 1-3 passagers', luxury: 'Berline Business', luxuryDesc: 'Mercedes Classe E ou BMW Serie 5',
    minivan: 'Monospace', minivanDesc: 'Pour groupes jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Pour groupes jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez le numero de vol et adresse a Berlin. Confirmation instantanee.',
    step2: 'Rendez-vous a BER', step2Desc: 'Chauffeur aux arrivees avec pancarte et aide aux bagages.',
    step3: 'Direct vers Berlin', step3Desc: 'Trajet confortable de 30-45 minutes vers le centre de Berlin.',
    popularRoutesTitle: 'Trajets Populaires Transfert Aeroport Berlin', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport BER → Berlin Mitte', price: 45 },
      { name: 'Aeroport BER → Potsdamer Platz', price: 45 },
      { name: 'Aeroport BER → Alexanderplatz', price: 50 },
      { name: 'Aeroport BER → Charlottenburg', price: 55 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Berlin',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Berlin Brandenburg (BER)',
    otherCitiesTitle: 'Nous desservons aussi d\'autres villes europeennes', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.8/5 (1 400+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Берлина - BER Бранденбург',
    subtitle: 'Профессиональный водитель из аэропорта Берлин-Бранденбург в центр города и все районы',
    description: 'Забронируйте трансфер из аэропорта Берлина с опытными водителями. Аэропорт Берлин-Бранденбург (BER) - главные ворота столицы Германии. Мы обеспечиваем надежный трансфер из BER в центр Берлина, Потсдамскую площадь, Александерплац, район Бранденбургских ворот и все районы.',
    description2: 'Берлин — город, где история говорит с каждого угла. Бранденбургские ворота, остатки Стены, Мемориал Холокоста, светящийся купол Рейхстага — повествование, привлекающее 13 млн гостей в год. С 2020 года все рейсы прибывают в BER, в 18 км к югу от центра. Наш водитель встречает вас в зале прилёта, загружает багаж и доставляет в Митте, Кройцберг, Шарлоттенбург или на Потсдамер-Плац за 30-45 минут. BER — стартовая точка для Потсдама и Сан-Суси (40 мин), биосферы Шпревальд (90 мин) или Дрездена (2 часа).',
    description3: 'Творческая энергия Берлина не имеет равных в Европе. От стрит-арта East Side Gallery до гастромаркетов Маркт-халле Нойн, от техно-клубов до ресторанов со звёздами Мишлен на Унтер-ден-Линден. Для бизнес-путешественников — Messe Berlin, ICC, Factory Berlin. Для семей — встреча в BER с детским креслом (бесплатно) и прямая поездка до квартиры в Пренцлауэр-Берг. Забронируйте трансфер из аэропорта Берлина.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Берлина?',
    feature1Title: 'Встреча в BER', feature1Desc: 'Водитель с табличкой в зале прилета BER. 60 минут ожидания бесплатно.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мониторинг в реальном времени. Без доплаты.',
    feature3Title: 'Комфортные Автомобили', feature3Desc: 'Mercedes, BMW или Audi с кондиционером. Не старше 3 лет.',
    feature4Title: 'Прозрачные Цены', feature4Desc: 'Фиксированная цена при бронировании.',
    sedan: 'Премиум Седан', sedanDesc: 'Для 1-3 пассажиров', luxury: 'Бизнес Седан', luxuryDesc: 'Mercedes E-Class или BMW 5 серии',
    minivan: 'Минивэн', minivanDesc: 'До 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Введите номер рейса и адрес в Берлине.',
    step2: 'Встреча в BER', step2Desc: 'Водитель встречает вас в зале прилета.',
    step3: 'Прямо в Берлин', step3Desc: 'Комфортная поездка 30-45 минут.',
    popularRoutesTitle: 'Популярные Маршруты из Аэропорта Берлина', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт BER → Берлин Митте', price: 45 },
      { name: 'Аэропорт BER → Потсдамская площадь', price: 45 },
      { name: 'Аэропорт BER → Александерплац', price: 50 },
      { name: 'Аэропорт BER → Шарлоттенбург', price: 55 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Берлина',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Берлин-Бранденбург (BER)',
    otherCitiesTitle: 'Другие города Европы', otherCitiesBtn: 'Все Направления',
    rating: '4.8/5 (1 400+ отзывов)',
  },
  hy: {
    title: 'Տրանսֆեր Բերլինի օդանավայանից',
    subtitle: 'Մասնավոր վարորդ BER-ից Բերլինի կենտրոն',
    description: 'Բերլինը քաղաք է՝ որտեղ պատմությունը խոսում է ամեն փողոցից: Բրանդենբուրգյան դարպասը՝ Պատի մնացորդները՝ Ռայխստագի գմբեթը: BER օդանավայանը 18 կմ հարավից: 13 միլիոն այցելու տարեկան: Պոտսդամ (40 րոպե)՝ Շպրեվալդ (90 րոպե)՝ Դրեզդեն (2 ժամ): East Side Gallery-ից մինչև Markthalle Neun:',
    description2: 'Ստեղծագործական եներգիա և մշակույթ:',
    whyChoose: 'Ինչու ընտրել մեր տրանսֆեր բերլինի օդանավայանից',
    feature1Title: 'Դիմավորում', feature1Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով: 60 րոպե անվճար սպասման ժամանակ:',
    feature2Title: 'Թռիչքի հետևում', feature2Desc: 'Իրական ժամանակում թռիչքի հետևում: Անվճար:',
    feature3Title: 'Պրեմիում մեքենաներ', feature3Desc: 'Mercedes E-Class, BMW 5: Մաքուր, կլիմատիզացիա:',
    feature4Title: 'Ֆիքս գներ', feature4Desc: 'Գինը հաստատված է ամրագրման ժամանակ: Թաքնված վճարներ չկան:',
    sedan: 'Պրեմիում սեդան', sedanDesc: 'Mercedes E-Class, 1-3 ուղևոր',
    luxury: 'Լյուքս սեդան', luxuryDesc: 'Mercedes S-Class կամ BMW 7',
    minivan: 'Մինիվեն', minivanDesc: 'Mercedes V-Class, մինչև 6 ուղևոր',
    minibus: 'Մինիբուս', minibusDesc: 'Մինչև 8 ուղևոր',
    passengers: 'Ուղևորներ', luggage: 'Ուղեբարան',
    bookNow: 'ԱՄՏԱԳՏՎԵԼ', allInclusive: 'Ամեն ինչ ներառված է',
    vehiclesTitle: 'Ընտրեք մեքենան',
    howItWorks: 'Ինչպես է աշխատում',
    step1: 'Ամրագրեք օնլայն', step1Desc: 'Մուտքագրեք ձեր տվյալները և հասցեն: Ակնթարթ գնի հաստատում:',
    step2: 'Հանդիպեք վարորդին', step2Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով:',
    step3: 'Հանգստացեք', step3Desc: 'Հարմարավետ ուղևորություն պրեմիում մեքենայում:',
    popularRoutesTitle: 'Սկսած', fromLabel: 'Սկսած',
    bookingForm: 'ԱՄՏԱԳՏՎԵԼ',
    pickupLabel: 'Վերցնում', dropoffLabel: 'Իջնում',
    dateLabel: 'Ամսաթիվ', timeLabel: 'Ժամ',
    defaultPickup: '',
    otherCitiesTitle: 'Սպասարկում ենք 120+ քաղաքներ Եվրոպայում',
    otherCitiesBtn: 'Բոլոր ուղղությունները',
    rating: '4.9/5',
  },
};

const vehiclesPrices = { sedan: 45, luxury: 70, minivan: 95, minibus: 150 };

const seoUrls = { en: '/berlin-airport-transfer', fr: '/transfert-aeroport-berlin', ru: '/taksi-iz-aeroporta-berlin', hy: '/berlin-odanavakayani-transfer' };
const BerlinTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default BerlinTransfer;
