import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Cannes Airport Transfer - Private Car Service',
    subtitle: 'Premium private driver from Nice Airport to Cannes, La Croisette and all Cannes destinations',
    description: 'Cannes is a name that echoes across red carpets, yacht decks, and boardrooms worldwide. Every May, the Cannes Film Festival transforms this elegant seaside town into the global capital of cinema, while events like MIPIM (the world\'s leading property market), Cannes Lions (the advertising industry\'s Oscars), and the Monaco Yacht Show spillover fill its hotels year-round. Yet Cannes has no airport. The gateway is Nice Cote d\'Azur (NCE), 25 kilometres and 30 to 40 minutes east along the stunning A8 motorway known as La Provencale. Our private Cannes airport transfer collects you at Nice Airport arrivals, loads your luggage into a premium vehicle, and delivers you directly to your hotel on La Croisette, the Palais des Festivals, the old port of Le Suquet, or your private villa in Super-Cannes.',
    description2: 'The drive from Nice to Cannes is one of the most scenic airport transfers in Europe. After leaving the airport, you merge onto the A8 motorway with views of the Baie des Anges, pass through the high-tech hub of Sophia Antipolis, and descend into Cannes along the perfumed hills of Mougins — the village where Picasso spent his final years and where some of the Riviera\'s best restaurants still operate. Our drivers know exactly which exit to take for your specific hotel, whether it\'s the Majestic on the Croisette, the Martinez, or a holiday rental in Cannes La Bocca.',
    description3: 'Beyond the festivals, Cannes offers a Mediterranean lifestyle that rewards year-round visitors: the Lerins Islands (a 15-minute ferry from the old port, where the Man in the Iron Mask was imprisoned), the covered Forville market where locals buy sea bass caught that morning, and the panoramic walk from Le Suquet along the medieval ramparts. Many of our clients use our service for multi-stop itineraries: Nice Airport to Cannes hotel, then Cannes to Monaco for dinner, then back to Cannes — all with the same driver who knows your preferences. For business travelers attending MIPIM at the Palais, arriving by private car with Wi-Fi and space to prepare means you walk into your first meeting calm, not frazzled. Book your Cannes transfer today.',
    whyChoose: 'Why Choose Our Cannes Airport Transfer?',
    feature1Title: 'Meet & Greet', feature1Desc: 'Driver with your name sign at Nice Airport arrivals. 60 min free waiting time.',
    feature2Title: 'Flight Tracking', feature2Desc: 'Real-time flight monitoring. No surcharge for delays.',
    feature3Title: 'Luxury Vehicles', feature3Desc: 'Mercedes, BMW, premium vehicles. Perfect for Cannes elegance.',
    feature4Title: 'Fixed Prices', feature4Desc: 'No surprises. Price confirmed at booking, tolls included.',
    sedan: 'Premium Sedan', sedanDesc: '1-3 passengers, ideal for couples', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes E-Class or similar',
    minivan: 'Minivan', minivanDesc: 'Up to 6 passengers with luggage', minibus: 'Minibus', minibusDesc: 'Up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter flight details and Cannes address. Instant price.',
    step2: 'Meet Your Driver', step2Desc: 'Driver greets you at Nice Airport arrivals hall.',
    step3: 'Direct to Cannes', step3Desc: 'Comfortable 30-minute ride to your Cannes destination.',
    popularRoutesTitle: 'Popular Cannes Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'Nice Airport → Cannes La Croisette', price: 75 },
      { name: 'Nice Airport → Palais des Festivals', price: 75 },
      { name: 'Nice Airport → Cannes Hotels', price: 70 },
      { name: 'Cannes → Monaco', price: 95 },
    ],
    bookingForm: 'Book Your Cannes Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Nice Cote d\'Azur Airport (NCE)',
    otherCitiesTitle: 'We also serve other cities', otherCitiesBtn: 'View All Destinations',
    rating: '4.8/5 (1,200+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Cannes - Voiture Privee',
    subtitle: 'Chauffeur prive premium depuis l\'aeroport de Nice vers Cannes, La Croisette et toutes destinations cannoises',
    description: 'Cannes est un nom qui resonne sur les tapis rouges, les ponts de yachts et dans les salles de conferences du monde entier. Chaque mai, le Festival de Cannes transforme cette elegante ville en capitale mondiale du cinema, tandis que le MIPIM (premier salon immobilier mondial), les Cannes Lions (les Oscars de la publicite) et le debordement du Yacht Show de Monaco remplissent ses hotels toute l\'annee. Pourtant, Cannes n\'a pas d\'aeroport. La porte d\'entree est Nice Cote d\'Azur (NCE), a 25 km et 30-40 minutes a l\'est par la magnifique autoroute A8 dite La Provencale. Notre transfert prive vous recueille aux arrivees de Nice, charge vos bagages dans un vehicule premium et vous depose directement a votre hotel sur La Croisette, au Palais des Festivals, au vieux port du Suquet ou dans votre villa privee de Super-Cannes.',
    description2: 'Le trajet de Nice a Cannes est l\'un des plus sceniques d\'Europe. Apres l\'aeroport, vous empruntez l\'A8 avec vue sur la Baie des Anges, traversez le pole technologique de Sophia Antipolis, et descendez vers Cannes par les collines parfumees de Mougins — le village ou Picasso a passe ses dernieres annees et ou certains des meilleurs restaurants de la Riviera operent encore. Nos chauffeurs savent exactement quelle sortie prendre pour votre hotel, qu\'il s\'agisse du Majestic sur la Croisette, du Martinez ou d\'un appartement a Cannes La Bocca.',
    description3: 'Au-dela des festivals, Cannes offre un art de vivre mediterraneen qui seduit toute l\'annee : les iles de Lerins (15 minutes en ferry, ou le Masque de Fer fut emprisonne), le marche couvert de Forville ou les locaux achetent le loup peche le matin meme, et la promenade panoramique depuis Le Suquet le long des remparts medievaux. Nombre de clients utilisent notre service pour des itineraires multi-etapes : Nice-Cannes, puis Cannes-Monaco pour un diner, puis retour — avec le meme chauffeur qui connait vos preferences. Pour les professionnels du MIPIM au Palais, arriver en voiture privee avec Wi-Fi et espace de preparation signifie entrer dans votre premiere reunion serein, pas stresse. Reservez votre transfert Cannes.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Cannes ?',
    feature1Title: 'Accueil Personnalise', feature1Desc: 'Chauffeur avec pancarte a votre nom aux arrivees de Nice. 60 min d\'attente gratuites.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Suivi en temps reel. Aucun supplement pour retard.',
    feature3Title: 'Vehicules de Luxe', feature3Desc: 'Mercedes, BMW, vehicules premium dignes de l\'elegance cannoise.',
    feature4Title: 'Prix Fixes', feature4Desc: 'Pas de surprises. Prix confirme a la reservation, peages inclus.',
    sedan: 'Berline Premium', sedanDesc: '1-3 passagers, ideal pour couples', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe E ou similaire',
    minivan: 'Monospace', minivanDesc: 'Jusqu\'a 6 passagers avec bagages', minibus: 'Minibus', minibusDesc: 'Jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez les details du vol et adresse a Cannes. Prix instantane.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Votre chauffeur vous accueille aux arrivees de Nice.',
    step3: 'Direct vers Cannes', step3Desc: 'Trajet confortable de 30 minutes vers votre destination a Cannes.',
    popularRoutesTitle: 'Trajets Populaires Transfert Cannes', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport Nice → Cannes La Croisette', price: 75 },
      { name: 'Aeroport Nice → Palais des Festivals', price: 75 },
      { name: 'Aeroport Nice → Hotels Cannes', price: 70 },
      { name: 'Cannes → Monaco', price: 95 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Cannes',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Nice Cote d\'Azur (NCE)',
    otherCitiesTitle: 'Nous desservons aussi d\'autres villes', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.8/5 (1 200+ avis)',
  },
  ru: {
    title: 'Трансфер в Канны из Аэропорта - Частный Автомобиль',
    subtitle: 'Премиум трансфер из аэропорта Ниццы в Канны, Круазетт и все направления Канн',
    description: 'Канны — имя, звучащее на красных ковровых дорожках, палубах яхт и в переговорных залах по всему миру. Каждый май Каннский кинофестиваль превращает этот элегантный приморский городок в мировую столицу кино, а MIPIM, Cannes Lions и Яхт-шоу заполняют отели круглый год. Своего аэропорта у Канн нет — ворота здесь Ницца Лазурный Берег (NCE), 25 км и 30-40 минут по великолепной автомагистрали A8 La Provencale. Наш частный трансфер встречает вас на прилёте в Ницце, загружает багаж в премиальный автомобиль и доставляет прямо к отелю на Круазетт, к Дворцу фестивалей, в старый порт Ле-Сюке или на виллу в Супер-Каннах.',
    description2: 'Путь из Ниццы в Канны — один из самых живописных аэропортовых трансферов Европы. Вы проедете по A8 с видом на бухту Ангелов, через технополис Софи-Антиполис и спуститесь к Каннам по ароматным холмам Мужена — деревни, где Пикассо провёл последние годы и где работают лучшие рестораны Ривьеры. Наши водители знают точный съезд к вашему отелю — будь то Majestic на Круазетт, Martinez или квартира в Канн-ла-Бокка.',
    description3: 'Помимо фестивалей, Канны предлагают средиземноморский образ жизни круглый год: Леринские острова (15 минут на пароме, где был заточён Железная Маска), крытый рынок Форвиль с утренним уловом и панорамная прогулка от Ле-Сюке вдоль средневековых крепостных стен. Многие клиенты заказывают маршруты с несколькими остановками: Ницца-Канны, Канны-Монако на ужин и обратно — с одним водителем. Для участников MIPIM прибытие на частном авто с Wi-Fi означает вход на первую встречу спокойным, а не измотанным. Бронируйте трансфер в Канны сейчас.',
    whyChoose: 'Почему Выбрать Наш Трансфер в Канны?',
    feature1Title: 'Встреча в Аэропорту', feature1Desc: 'Водитель с табличкой в зале прилета Ниццы. 60 минут бесплатного ожидания.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мониторинг в реальном времени. Без доплаты.',
    feature3Title: 'Люкс Автомобили', feature3Desc: 'Mercedes, BMW. Автомобили, достойные Канн.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Цена подтверждена. Дороги включены.',
    sedan: 'Премиум Седан', sedanDesc: '1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes E-Class',
    minivan: 'Минивэн', minivanDesc: 'До 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Введите данные рейса и адрес в Каннах.',
    step2: 'Встретьте Водителя', step2Desc: 'Водитель встречает вас в аэропорту Ниццы.',
    step3: 'Прямо в Канны', step3Desc: 'Комфортная 30-минутная поездка.',
    popularRoutesTitle: 'Популярные Маршруты в Канны', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт Ниццы → Канны Круазетт', price: 75 },
      { name: 'Аэропорт Ниццы → Дворец Фестивалей', price: 75 },
      { name: 'Аэропорт Ниццы → Отели Канн', price: 70 },
      { name: 'Канны → Монако', price: 95 },
    ],
    bookingForm: 'Забронируйте Трансфер в Канны',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Ницца (NCE)',
    otherCitiesTitle: 'Другие города', otherCitiesBtn: 'Все Направления',
    rating: '4.8/5 (1 200+ отзывов)',
  },
  hy: {
    title: 'Տրանսֆեր Կանն',
    subtitle: 'Մասնավոր վարորդ Նիսից Կանն',
    description: 'Կաննը անուն է՝ որը հնչում է կարմիր գորգերիներին՝ զբոսանքներին և բիզնեսին: Ամեն մայիս կինոփառը՝ MIPIM՝ Cannes Lions: Նիսից 25 կմ՝ 30-40 րոպե A8 մագիստրալով: La Croisette-ի հոտելներ՝ Palais des Festivals՝ Le Suquet: Lérins կղզիները 15 րոպե՝ Forville շուկան: Գործարար հաճախորդների համար բազմատեղ երթուղներ:',
    description2: 'Կանն-Մոնակո ընթրիքի համար և նույն վարորդով:',
    whyChoose: 'Ինչու ընտրել մեր տրանսֆեր կանն',
    feature1Title: 'Դիմավորում', feature1Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով: 60 րոպե անվճար սպասման ժամանակ:',
    feature2Title: 'Թռիչքի հետևում', feature2Desc: 'Իրական ժամանակում թռիչքի հետևում: Անվճար:',
    feature3Title: 'Պրեմիում մեքենաներ', feature3Desc: 'Mercedes E-Class, BMW 5: Մաքուր, կլիմատիզացիա:',
    feature4Title: 'Ֆիքս գներ', feature4Desc: 'Գինը հաստատված է ամրագրման ժամանակ: Թաքնված վճարներ չկան:',
    sedan: 'Պրեմիում սեդան', sedanDesc: 'Mercedes E-Class, 1-3 ուղևոր',
    luxury: 'Լյուքս սեդան', luxuryDesc: 'Mercedes S-Class կամ BMW 7',
    minivan: 'Մինիվեն', minivanDesc: 'Mercedes V-Class, մինչև 6 ուղևոր',
    minibus: 'Մինիբուս', minibusDesc: 'Մինչև 8 ուղևոր',
    passengers: 'Ուղևորներ', luggage: 'Ուղեբարան',
    bookNow: 'ԱՄՏԱԳՏՎԵԼ', allInclusive: 'Ամեն ինչ ներառված է',
    vehiclesTitle: 'Ընտրեք մեքենան',
    howItWorks: 'Ինչպես է աշխատում',
    step1: 'Ամրագրեք օնլայն', step1Desc: 'Մուտքագրեք ձեր տվյալները և հասցեն: Ակնթարթ գնի հաստատում:',
    step2: 'Հանդիպեք վարորդին', step2Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով:',
    step3: 'Հանգստացեք', step3Desc: 'Հարմարավետ ուղևորություն պրեմիում մեքենայում:',
    popularRoutesTitle: 'Սկսած', fromLabel: 'Սկսած',
    bookingForm: 'ԱՄՏԱԳՏՎԵԼ',
    pickupLabel: 'Վերցնում', dropoffLabel: 'Իջնում',
    dateLabel: 'Ամսաթիվ', timeLabel: 'Ժամ',
    defaultPickup: '',
    otherCitiesTitle: 'Սպասարկում ենք 120+ քաղաքներ Եվրոպայում',
    otherCitiesBtn: 'Բոլոր ուղղությունները',
    rating: '4.9/5',
  },
};

const vehiclesPrices = { sedan: 70, luxury: 95, minivan: 120, minibus: 170 };

const seoUrls = { en: '/cannes-airport-transfer', fr: '/transfert-aeroport-cannes', ru: '/taksi-iz-aeroporta-kanny', hy: '/kann-odanavakayani-transfer' };
const CannesTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default CannesTransfer;
