import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Cannes Airport Transfer - Private Car Service',
    subtitle: 'Premium private driver from Nice Airport to Cannes, La Croisette and all Cannes destinations',
    description: 'Book your Cannes airport transfer with professional drivers. The nearest major airport to Cannes is Nice Cote d\'Azur Airport (NCE), approximately 25 km away. We provide premium private transfers from Nice Airport directly to your hotel in Cannes, the Palais des Festivals, La Croisette boulevard, or any address. Fixed prices, flight monitoring, meet and greet included.',
    description2: 'Cannes is world-famous for its film festival, luxury boutiques, and beautiful beaches. Whether you are attending the Cannes Film Festival, MIPIM, the Lions festival, or simply enjoying the Mediterranean sun, our transfer service ensures a smooth and elegant arrival.',
    whyChoose: 'Why Choose Our Cannes Airport Transfer?',
    feature1Title: 'Meet & Greet', feature1Desc: 'Driver with your name sign at Nice Airport arrivals. 60 min free waiting time.',
    feature2Title: 'Flight Tracking', feature2Desc: 'Real-time flight monitoring. No surcharge for delays.',
    feature3Title: 'Luxury Vehicles', feature3Desc: 'Mercedes, BMW, premium vehicles. Perfect for Cannes elegance.',
    feature4Title: 'Fixed Prices', feature4Desc: 'No surprises. Price confirmed at booking, tolls included.',
    sedan: 'Premium Sedan', sedanDesc: '1-3 passengers, ideal for couples', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes E-Class or similar',
    minivan: 'Minivan', minivanDesc: 'Up to 6 passengers with luggage', minibus: 'Minibus', minibusDesc: 'Up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter flight details and Cannes address. Instant price.',
    step2: 'Meet Your Driver', step2Desc: 'Driver greets you at Nice Airport arrivals hall.',
    step3: 'Direct to Cannes', step3Desc: 'Comfortable 30-minute ride to your Cannes destination.',
    popularRoutesTitle: 'Popular Cannes Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'Nice Airport → Cannes La Croisette', price: 75 },
      { name: 'Nice Airport → Palais des Festivals', price: 75 },
      { name: 'Nice Airport → Cannes Hotels', price: 70 },
      { name: 'Cannes → Monaco', price: 95 },
    ],
    bookingForm: 'Book Your Cannes Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Nice Cote d\'Azur Airport (NCE)',
    otherCitiesTitle: 'We also serve other cities', otherCitiesBtn: 'View All Destinations',
    rating: '4.8/5 (1,200+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Cannes - Voiture Privee',
    subtitle: 'Chauffeur prive premium depuis l\'aeroport de Nice vers Cannes, La Croisette et toutes destinations cannoises',
    description: 'Reservez votre transfert aeroport Cannes avec des chauffeurs professionnels. L\'aeroport le plus proche de Cannes est Nice Cote d\'Azur (NCE), a environ 25 km. Nous assurons des transferts prives premium depuis l\'aeroport de Nice vers votre hotel a Cannes, le Palais des Festivals, le boulevard de la Croisette ou toute adresse. Prix fixes, suivi de vol, accueil personnalise.',
    description2: 'Cannes est mondialement connue pour son festival du film, ses boutiques de luxe et ses belles plages. Que vous assistiez au Festival de Cannes, au MIPIM, ou profitiez du soleil mediterraneen, notre service de transfert garantit une arrivee elegante.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Cannes ?',
    feature1Title: 'Accueil Personnalise', feature1Desc: 'Chauffeur avec pancarte a votre nom aux arrivees de Nice. 60 min d\'attente gratuites.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Suivi en temps reel. Aucun supplement pour retard.',
    feature3Title: 'Vehicules de Luxe', feature3Desc: 'Mercedes, BMW, vehicules premium dignes de l\'elegance cannoise.',
    feature4Title: 'Prix Fixes', feature4Desc: 'Pas de surprises. Prix confirme a la reservation, peages inclus.',
    sedan: 'Berline Premium', sedanDesc: '1-3 passagers, ideal pour couples', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe E ou similaire',
    minivan: 'Monospace', minivanDesc: 'Jusqu\'a 6 passagers avec bagages', minibus: 'Minibus', minibusDesc: 'Jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez les details du vol et adresse a Cannes. Prix instantane.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Votre chauffeur vous accueille aux arrivees de Nice.',
    step3: 'Direct vers Cannes', step3Desc: 'Trajet confortable de 30 minutes vers votre destination a Cannes.',
    popularRoutesTitle: 'Trajets Populaires Transfert Cannes', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport Nice → Cannes La Croisette', price: 75 },
      { name: 'Aeroport Nice → Palais des Festivals', price: 75 },
      { name: 'Aeroport Nice → Hotels Cannes', price: 70 },
      { name: 'Cannes → Monaco', price: 95 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Cannes',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Nice Cote d\'Azur (NCE)',
    otherCitiesTitle: 'Nous desservons aussi d\'autres villes', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.8/5 (1 200+ avis)',
  },
  ru: {
    title: 'Трансфер в Канны из Аэропорта - Частный Автомобиль',
    subtitle: 'Премиум трансфер из аэропорта Ниццы в Канны, Круазетт и все направления Канн',
    description: 'Забронируйте трансфер в Канны с профессиональными водителями. Ближайший аэропорт - Ницца Лазурный Берег (NCE), около 25 км. Мы обеспечиваем премиум-трансферы из аэропорта Ниццы в ваш отель в Каннах, Дворец Фестивалей, бульвар Круазетт или любой адрес.',
    description2: 'Канны знамениты кинофестивалем, бутиками и пляжами. Наш сервис гарантирует элегантное прибытие.',
    whyChoose: 'Почему Выбрать Наш Трансфер в Канны?',
    feature1Title: 'Встреча в Аэропорту', feature1Desc: 'Водитель с табличкой в зале прилета Ниццы. 60 минут бесплатного ожидания.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мониторинг в реальном времени. Без доплаты.',
    feature3Title: 'Люкс Автомобили', feature3Desc: 'Mercedes, BMW. Автомобили, достойные Канн.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Цена подтверждена. Дороги включены.',
    sedan: 'Премиум Седан', sedanDesc: '1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes E-Class',
    minivan: 'Минивэн', minivanDesc: 'До 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Введите данные рейса и адрес в Каннах.',
    step2: 'Встретьте Водителя', step2Desc: 'Водитель встречает вас в аэропорту Ниццы.',
    step3: 'Прямо в Канны', step3Desc: 'Комфортная 30-минутная поездка.',
    popularRoutesTitle: 'Популярные Маршруты в Канны', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт Ниццы → Канны Круазетт', price: 75 },
      { name: 'Аэропорт Ниццы → Дворец Фестивалей', price: 75 },
      { name: 'Аэропорт Ниццы → Отели Канн', price: 70 },
      { name: 'Канны → Монако', price: 95 },
    ],
    bookingForm: 'Забронируйте Трансфер в Канны',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Ницца (NCE)',
    otherCitiesTitle: 'Другие города', otherCitiesBtn: 'Все Направления',
    rating: '4.8/5 (1 200+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 70, luxury: 95, minivan: 120, minibus: 170 };

const CannesTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} />;
export default CannesTransfer;
