import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'CDG Airport Transfer - Charles de Gaulle Private Car',
    subtitle: 'Premium private driver from Paris Charles de Gaulle Airport to Paris city center, hotels and all destinations',
    description: 'Charles de Gaulle Airport is a city within a city: nine terminals spread across 3,200 hectares, connected by an automated shuttle that can leave even seasoned travelers disoriented. Each year, over 70 million passengers navigate its labyrinthine corridors — and the last thing they need after clearing customs is to figure out which bus stop, which RER platform, or which taxi rank leads to central Paris. That is where our private transfer service transforms your arrival. Your driver monitors your exact flight number, adjusts for any delays, and stands ready at your terminal exit with a clear name board the moment you walk through the arrivals doors.',
    description2: 'Terminal 2 alone has seven sub-terminals (2A through 2G), each with its own arrivals area. Terminal 1 is a futuristic circle that can confuse first-time visitors, and Terminal 3 serves budget airlines with minimal signage. Regardless of where you land, your assigned chauffeur knows the precise pickup point. The drive to central Paris follows the A1 motorway, typically taking 35 minutes to the Opera district, 40 minutes to the Champs-Elysees, and about 50 minutes to the Left Bank — though our drivers also know the back roads through Aubervilliers and Saint-Denis that can shave precious minutes during rush hour.',
    description3: 'CDG is also the departure point for day trips to Chantilly (20 minutes), the royal palace of Versailles (60 minutes via the A86), and even Disneyland Paris (just 35 minutes east). Many of our clients book a round-trip: airport to hotel on arrival, then hotel to airport on departure — locking in the same fixed price both ways. For business travelers heading to the Villepinte exhibition center or Roissy business district, our vehicles double as a mobile office with Wi-Fi, phone chargers, and privacy. Book your CDG transfer now and skip the chaos.',
    whyChoose: 'Why Choose Our CDG Airport Transfer?',
    feature1Title: 'All CDG Terminals', feature1Desc: 'We cover Terminal 1, 2A-2G, and Terminal 3. Driver meets you right at arrivals with name sign.',
    feature2Title: 'Flight Monitoring', feature2Desc: 'Real-time flight tracking. No extra charge for delays. 60 minutes free waiting time.',
    feature3Title: 'Premium Vehicles', feature3Desc: 'Mercedes E-Class, BMW 5 Series. Clean, air-conditioned, less than 3 years old.',
    feature4Title: 'Fixed Prices', feature4Desc: 'Price confirmed at booking. No hidden fees, no surge pricing. Tolls and parking included.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class or BMW 7 Series',
    minivan: 'Minivan', minivanDesc: 'Mercedes V-Class, up to 6 passengers', minibus: 'Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter your CDG terminal, flight number, and Paris address. Instant price confirmation.',
    step2: 'Meet Your Driver', step2Desc: 'Driver waits at your CDG terminal arrivals with a personalized name sign.',
    step3: 'Relax & Enjoy', step3Desc: 'Direct comfortable transfer to central Paris in 35-50 minutes.',
    popularRoutesTitle: 'Popular CDG Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'CDG Airport \u2192 Paris City Center', price: 65 },
      { name: 'CDG Airport \u2192 Champs-Elysees / Arc de Triomphe', price: 65 },
      { name: 'CDG Airport \u2192 Disneyland Paris', price: 75 },
      { name: 'CDG Airport \u2192 La Defense', price: 70 },
    ],
    bookingForm: 'Book Your CDG Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Paris CDG Airport (Terminal 2)',
    otherCitiesTitle: 'Also available from other Paris airports', otherCitiesBtn: 'View All Destinations',
    rating: '4.5/5 Tripadvisor (29 reviews)',
  },
  fr: {
    title: 'Transfert Aeroport CDG - Charles de Gaulle Voiture Privee',
    subtitle: 'Chauffeur prive premium depuis l\'aeroport Paris Charles de Gaulle vers Paris centre, hotels et toutes destinations',
    description: 'L\'aeroport Charles de Gaulle est une ville dans la ville : neuf terminaux repartis sur 3 200 hectares, relies par une navette automatique qui peut desorienter meme les voyageurs les plus experimentes. Chaque annee, plus de 70 millions de passagers arpentent ses couloirs labyrinthiques — et la derniere chose dont ils ont besoin apres la douane, c\'est de chercher quel arret de bus, quel quai de RER ou quelle borne de taxi mene au centre de Paris. C\'est la que notre service de transfert prive change tout. Votre chauffeur surveille votre numero de vol exact, s\'ajuste a tout retard, et vous attend a la sortie de votre terminal avec une pancarte nominative des que vous franchissez les portes des arrivees.',
    description2: 'Le Terminal 2 a lui seul compte sept sous-terminaux (2A a 2G), chacun avec sa propre zone d\'arrivees. Le Terminal 1 est un cercle futuriste qui peut derouter les primo-visiteurs, et le Terminal 3 dessert les compagnies low-cost avec une signaletique minimale. Peu importe ou vous atterrissez, votre chauffeur connait le point de prise en charge exact. Le trajet vers Paris centre emprunte l\'autoroute A1, comptez 35 minutes jusqu\'a l\'Opera, 40 minutes jusqu\'aux Champs-Elysees et environ 50 minutes jusqu\'a la Rive Gauche — nos chauffeurs connaissent aussi les raccourcis par Aubervilliers et Saint-Denis qui font gagner de precieuses minutes aux heures de pointe.',
    description3: 'CDG est aussi le point de depart ideal pour des excursions : Chantilly (20 minutes), le chateau de Versailles (60 minutes par l\'A86), et meme Disneyland Paris (35 minutes a l\'est). Beaucoup de nos clients reservent un aller-retour : aeroport-hotel a l\'arrivee, puis hotel-aeroport au depart — au meme prix fixe garanti dans les deux sens. Pour les voyageurs d\'affaires en direction du parc des expositions de Villepinte ou du quartier d\'affaires de Roissy, nos vehicules se transforment en bureau mobile avec Wi-Fi, chargeurs et confidentialite. Reservez votre transfert CDG maintenant et evitez le chaos.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport CDG ?',
    feature1Title: 'Tous les Terminaux CDG', feature1Desc: 'Nous couvrons Terminal 1, 2A-2G et Terminal 3. Chauffeur aux arrivees avec pancarte.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Suivi en temps reel. Aucun supplement pour retard. 60 minutes d\'attente gratuites.',
    feature3Title: 'Vehicules Premium', feature3Desc: 'Mercedes Classe E, BMW Serie 5. Propres, climatises, moins de 3 ans.',
    feature4Title: 'Prix Fixes', feature4Desc: 'Prix confirme a la reservation. Pas de frais caches, peages et parking inclus.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E, 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S ou BMW Serie 7',
    minivan: 'Monospace', minivanDesc: 'Mercedes Classe V, jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Pour groupes jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez votre terminal CDG, numero de vol et adresse a Paris. Prix instantane.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Le chauffeur vous attend aux arrivees de votre terminal CDG avec pancarte.',
    step3: 'Detendez-vous', step3Desc: 'Transfert direct confortable vers Paris centre en 35-50 minutes.',
    popularRoutesTitle: 'Trajets Populaires depuis CDG', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport CDG \u2192 Paris Centre', price: 65 },
      { name: 'Aeroport CDG \u2192 Champs-Elysees / Arc de Triomphe', price: 65 },
      { name: 'Aeroport CDG \u2192 Disneyland Paris', price: 75 },
      { name: 'Aeroport CDG \u2192 La Defense', price: 70 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport CDG',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Paris CDG (Terminal 2)',
    otherCitiesTitle: 'Egalement disponible depuis les autres aeroports parisiens', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.5/5 Tripadvisor (29 avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта CDG - Шарль де Голль Частный Автомобиль',
    subtitle: 'Премиум трансфер из аэропорта Шарль де Голль в центр Парижа, отели и все направления',
    description: 'Аэропорт Шарль-де-Голль — это город в городе: девять терминалов на 3 200 гектарах, соединённых автоматическим шаттлом, который может дезориентировать даже опытных путешественников. Ежегодно более 70 миллионов пассажиров проходят через его лабиринты — и последнее, что им нужно после прохождения таможни, это разбираться, какая остановка автобуса, какая платформа RER или какая стоянка такси ведёт в центр Парижа. Именно здесь наш частный трансфер меняет правила игры. Ваш водитель отслеживает ваш номер рейса, корректирует время при задержках и встречает вас на выходе из терминала с именной табличкой.',
    description2: 'Только Терминал 2 насчитывает семь подтерминалов (2A-2G), каждый со своей зоной прилёта. Терминал 1 — футуристический круг, сбивающий с толку новичков, а Терминал 3 обслуживает бюджетные авиалинии с минимальными указателями. Где бы вы ни приземлились, ваш водитель знает точное место посадки. Путь до центра Парижа идёт по автомагистрали A1: 35 минут до района Оперы, 40 минут до Елисейских Полей, около 50 минут до Левого берега. Наши водители знают объездные маршруты через Обервилье и Сен-Дени, экономящие драгоценные минуты в час пик.',
    description3: 'CDG — идеальная отправная точка для экскурсий: Шантийи (20 минут), Версаль (60 минут по A86), Диснейленд Париж (35 минут на восток). Многие клиенты бронируют трансфер в обе стороны — из аэропорта в отель и обратно — по одной фиксированной цене. Для бизнес-путешественников, направляющихся в выставочный центр Вильпент или деловой район Руасси, наши автомобили превращаются в мобильный офис с Wi-Fi, зарядками и приватностью. Забронируйте трансфер из CDG сейчас и минуйте хаос.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта CDG?',
    feature1Title: 'Все Терминалы CDG', feature1Desc: 'Терминал 1, 2A-2G и Терминал 3. Водитель встречает с табличкой.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мониторинг в реальном времени. Без доплаты. 60 минут ожидания бесплатно.',
    feature3Title: 'Премиум Автомобили', feature3Desc: 'Mercedes E-Class, BMW 5 серии. Чистые, с кондиционером.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Цена при бронировании. Без скрытых платежей.',
    sedan: 'Премиум Седан', sedanDesc: 'Mercedes E-Class, 1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes S-Class или BMW 7',
    minivan: 'Минивэн', minivanDesc: 'Mercedes V-Class, до 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Введите терминал CDG, номер рейса и адрес в Париже.',
    step2: 'Встретьте Водителя', step2Desc: 'Водитель ждет в зале прилета вашего терминала CDG.',
    step3: 'Расслабьтесь', step3Desc: 'Прямой трансфер в центр Парижа за 35-50 минут.',
    popularRoutesTitle: 'Популярные Маршруты из CDG', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт CDG \u2192 Центр Парижа', price: 65 },
      { name: 'Аэропорт CDG \u2192 Елисейские Поля', price: 65 },
      { name: 'Аэропорт CDG \u2192 Диснейленд Париж', price: 75 },
      { name: 'Аэропорт CDG \u2192 Ла Дефанс', price: 70 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта CDG',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Париж CDG (Терминал 2)',
    otherCitiesTitle: 'Также из других парижских аэропортов', otherCitiesBtn: 'Все Направления',
    rating: '4.5/5 Tripadvisor (29 отзывов)',
  },
  hy: {
    title: 'Տրանսֆեր CDG օդանավայանից - Շարլ դը Գոլի',
    subtitle: 'Մասնավոր վարորդ CDG օդանավայանից Փարիզի կենտրոն',
    description: 'Շարլ դը Գոլի օդանավայանը քաղաք է քաղաքի մեջ՝ 9 տերմինալ տարածված 3200 հեկտարի վրա: Ամեն տարի 70 միլիոնից ավելի ուղևոր անցնում է նրա լաբիրինթներով: Մեր վարորդը գիտի ձեր տերմինալի ելքը և տանում է Փարիզի կենտրոն 35-50 րոպեում:',
    description2: 'CDG-ն նաև ելքի կետ է Շանտիյի (Հարավուսճան 20 րոպե)՝ Վերսալի (60 րոպե) և Դիսնեյլենդի (35 րոպե): Գործարար ճանապարհորդների համար մեքենաները վերածվում են շարժական գրասենյակ Wi-Fi-ով և լիցքավորիչներով:',
    whyChoose: 'Ինչու ընտրել մեր տրանսֆեր cdg օդանավայանից - շարլ դը գոլի',
    feature1Title: 'Դիմավորում', feature1Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով: 60 րոպե անվճար սպասման ժամանակ:',
    feature2Title: 'Թռիչքի հետևում', feature2Desc: 'Իրական ժամանակում թռիչքի հետևում: Անվճար:',
    feature3Title: 'Պրեմիում մեքենաներ', feature3Desc: 'Mercedes E-Class, BMW 5: Մաքուր, կլիմատիզացիա:',
    feature4Title: 'Ֆիքս գներ', feature4Desc: 'Գինը հաստատված է ամրագրման ժամանակ: Թաքնված վճարներ չկան:',
    sedan: 'Պրեմիում սեդան', sedanDesc: 'Mercedes E-Class, 1-3 ուղևոր',
    luxury: 'Լյուքս սեդան', luxuryDesc: 'Mercedes S-Class կամ BMW 7',
    minivan: 'Մինիվեն', minivanDesc: 'Mercedes V-Class, մինչև 6 ուղևոր',
    minibus: 'Մինիբուս', minibusDesc: 'Մինչև 8 ուղևոր',
    passengers: 'Ուղևորներ', luggage: 'Ուղեբարան',
    bookNow: 'ԱՄՏԱԳՏՎԵԼ', allInclusive: 'Ամեն ինչ ներառված է',
    vehiclesTitle: 'Ընտրեք մեքենան',
    howItWorks: 'Ինչպես է աշխատում',
    step1: 'Ամրագրեք օնլայն', step1Desc: 'Մուտքագրեք ձեր տվյալները և հասցեն: Ակնթարթ գնի հաստատում:',
    step2: 'Հանդիպեք վարորդին', step2Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով:',
    step3: 'Հանգստացեք', step3Desc: 'Հարմարավետ ուղևորություն պրեմիում մեքենայում:',
    popularRoutesTitle: 'Սկսած', fromLabel: 'Սկսած',
    bookingForm: 'ԱՄՏԱԳՏՎԵԼ',
    pickupLabel: 'Վերցնում', dropoffLabel: 'Իջնում',
    dateLabel: 'Ամսաթիվ', timeLabel: 'Ժամ',
    defaultPickup: '',
    otherCitiesTitle: 'Սպասարկում ենք 120+ քաղաքներ Եվրոպայում',
    otherCitiesBtn: 'Բոլոր ուղղությունները',
    rating: '4.5/5 Tripadvisor',
  },
};

const vehiclesPrices = { sedan: 65, luxury: 95, minivan: 130, minibus: 190 };

const seoUrls = { en: '/cdg-airport-transfer', fr: '/transfert-aeroport-cdg', ru: '/taksi-iz-aeroporta-cdg', hy: '/cdg-odanavakayani-transfer' };
const CDGTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default CDGTransfer;
