import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'CDG Airport Transfer - Charles de Gaulle Private Car',
    subtitle: 'Premium private driver from Paris Charles de Gaulle Airport to Paris city center, hotels and all destinations',
    description: 'Book your CDG airport transfer with professional English-speaking drivers. Paris Charles de Gaulle Airport (CDG) is France\'s largest airport, located 25 km northeast of Paris. We provide premium private car transfers from all CDG terminals (Terminal 1, 2A-2G, and 3) to central Paris, your hotel, Disneyland Paris, or any address in the Ile-de-France region. Fixed prices, real-time flight monitoring, and personalized meet and greet with name sign at arrivals.',
    description2: 'Charles de Gaulle Airport handles over 70 million passengers annually, making it one of the busiest airports in Europe. Skip the long taxi queues and crowded RER trains. Our professional drivers track your flight in real-time and wait for you at the arrivals hall with a personalized sign. Whether you land at Terminal 1, 2 or 3, we guarantee a smooth, comfortable transfer to your Paris destination.',
    whyChoose: 'Why Choose Our CDG Airport Transfer?',
    feature1Title: 'All CDG Terminals', feature1Desc: 'We cover Terminal 1, 2A-2G, and Terminal 3. Driver meets you right at arrivals with name sign.',
    feature2Title: 'Flight Monitoring', feature2Desc: 'Real-time flight tracking. No extra charge for delays. 60 minutes free waiting time.',
    feature3Title: 'Premium Vehicles', feature3Desc: 'Mercedes E-Class, BMW 5 Series. Clean, air-conditioned, less than 3 years old.',
    feature4Title: 'Fixed Prices', feature4Desc: 'Price confirmed at booking. No hidden fees, no surge pricing. Tolls and parking included.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class or BMW 7 Series',
    minivan: 'Minivan', minivanDesc: 'Mercedes V-Class, up to 6 passengers', minibus: 'Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter your CDG terminal, flight number, and Paris address. Instant price confirmation.',
    step2: 'Meet Your Driver', step2Desc: 'Driver waits at your CDG terminal arrivals with a personalized name sign.',
    step3: 'Relax & Enjoy', step3Desc: 'Direct comfortable transfer to central Paris in 35-50 minutes.',
    popularRoutesTitle: 'Popular CDG Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'CDG Airport → Paris City Center', price: 65 },
      { name: 'CDG Airport → Champs-Elysees / Arc de Triomphe', price: 65 },
      { name: 'CDG Airport → Disneyland Paris', price: 75 },
      { name: 'CDG Airport → La Defense', price: 70 },
    ],
    bookingForm: 'Book Your CDG Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Paris CDG Airport (Terminal 2)',
    otherCitiesTitle: 'Also available from other Paris airports', otherCitiesBtn: 'View All Destinations',
    rating: '4.9/5 (3,200+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport CDG - Charles de Gaulle Voiture Privee',
    subtitle: 'Chauffeur prive premium depuis l\'aeroport Paris Charles de Gaulle vers Paris centre, hotels et toutes destinations',
    description: 'Reservez votre transfert aeroport CDG avec des chauffeurs professionnels francophones. L\'aeroport Paris Charles de Gaulle (CDG) est le plus grand aeroport de France, situe a 25 km au nord-est de Paris. Nous proposons des transferts en voiture privee premium depuis tous les terminaux CDG (Terminal 1, 2A-2G et 3) vers Paris centre, votre hotel, Disneyland Paris ou toute adresse en Ile-de-France. Prix fixes, suivi de vol en temps reel, accueil personnalise avec pancarte nominative.',
    description2: 'L\'aeroport Charles de Gaulle accueille plus de 70 millions de passagers par an. Evitez les longues files de taxis et les RER bondes. Nos chauffeurs professionnels suivent votre vol en temps reel et vous attendent au hall des arrivees avec une pancarte personnalisee.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport CDG ?',
    feature1Title: 'Tous les Terminaux CDG', feature1Desc: 'Nous couvrons Terminal 1, 2A-2G et Terminal 3. Chauffeur aux arrivees avec pancarte.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Suivi en temps reel. Aucun supplement pour retard. 60 minutes d\'attente gratuites.',
    feature3Title: 'Vehicules Premium', feature3Desc: 'Mercedes Classe E, BMW Serie 5. Propres, climatises, moins de 3 ans.',
    feature4Title: 'Prix Fixes', feature4Desc: 'Prix confirme a la reservation. Pas de frais caches, peages et parking inclus.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E, 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S ou BMW Serie 7',
    minivan: 'Monospace', minivanDesc: 'Mercedes Classe V, jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Pour groupes jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez votre terminal CDG, numero de vol et adresse a Paris. Prix instantane.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Le chauffeur vous attend aux arrivees de votre terminal CDG avec pancarte.',
    step3: 'Detendez-vous', step3Desc: 'Transfert direct confortable vers Paris centre en 35-50 minutes.',
    popularRoutesTitle: 'Trajets Populaires depuis CDG', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport CDG → Paris Centre', price: 65 },
      { name: 'Aeroport CDG → Champs-Elysees / Arc de Triomphe', price: 65 },
      { name: 'Aeroport CDG → Disneyland Paris', price: 75 },
      { name: 'Aeroport CDG → La Defense', price: 70 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport CDG',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Paris CDG (Terminal 2)',
    otherCitiesTitle: 'Egalement disponible depuis les autres aeroports parisiens', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.9/5 (3 200+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта CDG - Шарль де Голль Частный Автомобиль',
    subtitle: 'Премиум трансфер из аэропорта Шарль де Голль в центр Парижа, отели и все направления',
    description: 'Забронируйте трансфер из аэропорта CDG с профессиональными русскоговорящими водителями. Аэропорт Париж Шарль де Голль (CDG) - крупнейший аэропорт Франции, расположенный в 25 км к северо-востоку от Парижа. Мы обеспечиваем премиум-трансферы из всех терминалов CDG (Терминал 1, 2A-2G и 3) в центр Парижа, ваш отель, Диснейленд Париж или любой адрес в регионе Иль-де-Франс. Фиксированные цены, отслеживание рейсов, встреча с именной табличкой.',
    description2: 'Аэропорт Шарль де Голль обслуживает более 70 миллионов пассажиров ежегодно. Пропустите очереди на такси и переполненные поезда RER. Наши водители отслеживают ваш рейс и ждут вас в зале прилета.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта CDG?',
    feature1Title: 'Все Терминалы CDG', feature1Desc: 'Терминал 1, 2A-2G и Терминал 3. Водитель встречает с табличкой.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мониторинг в реальном времени. Без доплаты. 60 минут ожидания бесплатно.',
    feature3Title: 'Премиум Автомобили', feature3Desc: 'Mercedes E-Class, BMW 5 серии. Чистые, с кондиционером.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Цена при бронировании. Без скрытых платежей.',
    sedan: 'Премиум Седан', sedanDesc: 'Mercedes E-Class, 1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes S-Class или BMW 7',
    minivan: 'Минивэн', minivanDesc: 'Mercedes V-Class, до 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Введите терминал CDG, номер рейса и адрес в Париже.',
    step2: 'Встретьте Водителя', step2Desc: 'Водитель ждет в зале прилета вашего терминала CDG.',
    step3: 'Расслабьтесь', step3Desc: 'Прямой трансфер в центр Парижа за 35-50 минут.',
    popularRoutesTitle: 'Популярные Маршруты из CDG', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт CDG → Центр Парижа', price: 65 },
      { name: 'Аэропорт CDG → Елисейские Поля', price: 65 },
      { name: 'Аэропорт CDG → Диснейленд Париж', price: 75 },
      { name: 'Аэропорт CDG → Ла Дефанс', price: 70 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта CDG',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Париж CDG (Терминал 2)',
    otherCitiesTitle: 'Также из других парижских аэропортов', otherCitiesBtn: 'Все Направления',
    rating: '4.9/5 (3 200+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 65, luxury: 95, minivan: 130, minibus: 190 };

const seoUrls = { en: '/cdg-airport-transfer', fr: '/transfert-aeroport-cdg', ru: '/taksi-iz-aeroporta-cdg' };
const CDGTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default CDGTransfer;
