import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';
import DisneylandMainSections from '@/components/DisneylandMainSections';

const content = {
  en: {
    title: 'Disneyland Paris Transfer - Private Driver from 49\u20AC',
    subtitle: 'Affordable private car service to Disneyland Paris from airports, hotels and all Paris locations. Fixed prices from 49\u20AC',
    description: 'Every year, over 15 million visitors pass through the gates of Disneyland Paris \u2014 making it the most visited theme park in Europe. Whether you are traveling with excited children counting down the minutes to meet Mickey, a group of friends celebrating a birthday, or a couple enjoying a magical weekend getaway, the last thing you want is to spend an hour navigating RER connections with suitcases and strollers. Our Disneyland Paris transfer service picks you up directly from your Paris hotel, airport terminal or any address, and delivers you to the entrance of Disney Village, the Disneyland Hotel or any resort within the complex. No tickets to buy, no platforms to find, no rain-soaked walks from remote parking lots.',
    description2: 'Disneyland Paris is located in Marne-la-Vallee, approximately 32 kilometres east of central Paris. From CDG Airport, the drive takes 35 to 45 minutes via the A104 motorway. From Orly Airport, allow around 50 minutes through the eastern suburbs. From central Paris \u2014 the Eiffel Tower, Champs-Elysees, or your Marais hotel \u2014 the trip is typically 40 minutes on the A4. Our drivers know every access road to the resort, every drop-off point at each Disney hotel, and the fastest routes to avoid the A4 congestion that plagues weekend mornings. We drop you right at the entrance, not in a distant parking lot where you still need a shuttle.',
    description3: 'What makes our Disneyland transfer truly family-friendly? Child car seats are available at no extra cost \u2014 just request them when booking. Our spacious vehicles comfortably accommodate strollers, souvenirs, and even those giant plush toys your kids will inevitably convince you to buy. The ride back is just as easy: after a full day of rides and parades, your driver is waiting at the agreed time to take you back to your hotel or airport. No surge pricing at closing time, no fighting for a taxi with 15,000 other families. Fixed price, door-to-door, and a smiling professional driver who might just know the best tips for skipping the queues.',
    whyChoose: 'Why Choose Our Disneyland Paris Transfer?',
    feature1Title: 'Door-to-Door Magic', feature1Desc: 'Direct pickup from any Paris address. Drop-off at your exact Disney hotel or park entrance.',
    feature2Title: 'Family Friendly', feature2Desc: 'Free child seats on request. Space for strollers, luggage and Disney souvenirs.',
    feature3Title: 'Fixed Prices from 49\u20AC', feature3Desc: 'Price confirmed at booking. No hidden fees, no surge pricing. Affordable for everyone.',
    feature4Title: 'Return Service', feature4Desc: 'Driver waiting at your chosen time after the fireworks. No taxi hunt at park closing.',
    sedan: 'Comfort Car', sedanDesc: 'Toyota C-HR or similar, 1-3 passengers', luxury: 'Premium Sedan', luxuryDesc: 'Mercedes E-Class or BMW 5 Series',
    minivan: 'Family Van', minivanDesc: 'Mercedes V-Class, up to 6 passengers + strollers', minibus: 'Group Minibus', minibusDesc: 'For large groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Disney Ride',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter your pickup address and Disney destination. Instant price from 49\u20AC.',
    step2: 'Meet Your Driver', step2Desc: 'Driver picks you up at your hotel lobby, airport terminal or any address.',
    step3: 'Arrive in Style', step3Desc: 'Relax during the ride. Arrive at Disney ready for the magic.',
    popularRoutesTitle: 'Popular Disneyland Paris Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'Paris City Center \u2192 Disneyland Paris', price: 59 },
      { name: 'CDG Airport \u2192 Disneyland Paris', price: 75 },
      { name: 'Orly Airport \u2192 Disneyland Paris', price: 90 },
      { name: 'Beauvais Airport \u2192 Disneyland Paris', price: 175 },
      { name: 'Gare du Nord \u2192 Disneyland Paris', price: 59 },
      { name: 'Gare de Lyon \u2192 Disneyland Paris', price: 55 },
    ],
    bookingForm: 'Book Your Disneyland Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: '',
    defaultDropoff: 'Disneyland Paris',
    otherCitiesTitle: 'We serve 16 cities across Europe', otherCitiesBtn: 'View All Destinations',
    rating: '4.5/5 Tripadvisor (29 reviews)',
  },
  fr: {
    title: 'Transfert Disneyland Paris - Chauffeur Prive des 49\u20AC',
    metaDescription: "Transfert vers Disneyland Paris avec chauffeur privé : prix fixes, accueil aéroport, sièges enfants disponibles et minivans confortables pour familles.",
    subtitle: 'VTC et chauffeur prive vers Disneyland Paris depuis les aeroports, hotels et toute adresse. Prix fixes des 49\u20AC',
    description: 'Chaque annee, plus de 15 millions de visiteurs franchissent les portes de Disneyland Paris \u2014 le parc a theme le plus visite d\'Europe. Que vous voyagiez avec des enfants surexcites qui comptent les minutes avant de rencontrer Mickey, un groupe d\'amis qui fete un anniversaire, ou en couple pour un week-end feerique, la derniere chose que vous voulez est de passer une heure a naviguer les correspondances RER avec des valises et des poussettes. Notre service de transfert Disneyland Paris vous prend en charge directement depuis votre hotel parisien, votre terminal d\'aeroport ou toute adresse, et vous depose a l\'entree du Disney Village, du Disneyland Hotel ou de n\'importe quel resort du complexe. Aucun billet a acheter, aucun quai a trouver, aucune marche sous la pluie depuis un parking eloigne.',
    description2: 'Disneyland Paris est situe a Marne-la-Vallee, a environ 32 kilometres a l\'est du centre de Paris. Depuis l\'aeroport CDG, le trajet prend 35 a 45 minutes par l\'autoroute A104. Depuis Orly, comptez environ 50 minutes en traversant la banlieue est. Depuis le centre de Paris \u2014 Tour Eiffel, Champs-Elysees ou votre hotel du Marais \u2014 le trajet est generalement de 40 minutes par l\'A4. Nos chauffeurs connaissent chaque voie d\'acces au resort, chaque point de depose devant les hotels Disney, et les itineraires les plus rapides pour eviter les bouchons de l\'A4 qui plombent les samedis matin. On vous depose directement a l\'entree, pas dans un parking distant ou il faut encore prendre une navette.',
    description3: 'Qu\'est-ce qui rend notre transfert Disneyland vraiment adapte aux familles ? Les sieges enfant sont disponibles gratuitement \u2014 demandez-les a la reservation. Nos vehicules spacieux accueillent confortablement les poussettes, les valises et meme ces enormes peluches que vos enfants vous convaincront inevitablement d\'acheter. Le retour est tout aussi simple : apres une journee complete d\'attractions et de parades, votre chauffeur vous attend a l\'heure convenue pour vous reconduire a votre hotel ou aeroport. Pas de prix gonfle a la fermeture, pas de bataille pour un taxi avec 15 000 autres familles. Prix fixe, porte-a-porte, et un chauffeur professionnel souriant qui connait peut-etre les meilleures astuces pour eviter les files d\'attente.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Disneyland Paris ?',
    feature1Title: 'Porte-a-Porte Magique', feature1Desc: 'Prise en charge depuis n\'importe quelle adresse. Depose a l\'entree de votre hotel Disney.',
    feature2Title: 'Adapte aux Familles', feature2Desc: 'Sieges enfant gratuits. Place pour poussettes, bagages et souvenirs Disney.',
    feature3Title: 'Prix Fixes des 49\u20AC', feature3Desc: 'Prix confirme a la reservation. Pas de frais caches, pas de majoration. Accessible a tous.',
    feature4Title: 'Service Retour', feature4Desc: 'Chauffeur qui attend a l\'heure de votre choix apres le feu d\'artifice.',
    sedan: 'Voiture Confort', sedanDesc: 'Toyota C-HR ou similaire, 1-3 passagers', luxury: 'Berline Premium', luxuryDesc: 'Mercedes Classe E ou BMW Serie 5',
    minivan: 'Van Familial', minivanDesc: 'Mercedes Classe V, jusqu\'a 6 passagers + poussettes', minibus: 'Minibus Groupe', minibusDesc: 'Grands groupes jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule Disney',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez votre adresse et destination Disney. Prix immediat des 49\u20AC.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Le chauffeur vient vous chercher au lobby de l\'hotel, terminal ou toute adresse.',
    step3: 'Arrivez en Beaute', step3Desc: 'Detendez-vous pendant le trajet. Arrivez a Disney pret pour la magie.',
    popularRoutesTitle: 'Trajets Populaires vers Disneyland Paris', fromLabel: 'A partir de',
    routes: [
      { name: 'Centre de Paris \u2192 Disneyland Paris', price: 59 },
      { name: 'Aeroport CDG \u2192 Disneyland Paris', price: 75 },
      { name: 'Aeroport Orly \u2192 Disneyland Paris', price: 90 },
      { name: 'Aeroport Beauvais \u2192 Disneyland Paris', price: 175 },
      { name: 'Gare du Nord \u2192 Disneyland Paris', price: 59 },
      { name: 'Gare de Lyon \u2192 Disneyland Paris', price: 55 },
    ],
    bookingForm: 'Reservez Votre Transfert Disneyland',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: '',
    defaultDropoff: 'Disneyland Paris',
    otherCitiesTitle: 'Nous desservons plus de 120 villes en Europe', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.5/5 Tripadvisor (29 avis)',
  },
  ru: {
    title: 'Трансфер в Диснейленд Париж | ZONT — частный водитель и фиксированные цены',
    metaDescription: 'Трансфер в Диснейленд Париж с частным водителем: фиксированные цены, встреча в аэропорту, детские кресла и комфортные минивэны.',
    h1: 'Трансфер в Диснейленд Париж с частным водителем',
    subtitle: 'Планируете поездку в Disneyland Paris и хотите добраться комфортно, спокойно и без лишнего стресса? ZONT предлагает частные трансферы в Диснейленд Париж из аэропортов, отелей, вокзалов и любых адресов в Париже и регионе Иль-де-Франс.',
    description: 'Наш сервис идеально подходит для семей с детьми, туристических групп, деловых гостей и путешественников, которые хотят заранее знать стоимость поездки и быть уверенными, что водитель приедет вовремя. Диснейленд Париж расположен за пределами центра Парижа, поэтому для многих путешественников самый удобный вариант — заранее заказать частный трансфер. Вам не нужно искать такси, разбираться с общественным транспортом, пересадками, багажом и расписанием поездов. С ZONT водитель заберет вас из аэропорта, отеля или любого другого адреса и доставит прямо к вашему отелю в Disneyland Paris, ко входу в парк или в выбранную точку назначения.',
    description2: 'ZONT выполняет трансферы в Disneyland Paris из всех основных аэропортов Парижа. Трансфер из аэропорта Charles de Gaulle CDG в Disneyland Paris — один из самых популярных пунктов прибытия для гостей Диснейленда. Частный трансфер из CDG в Disneyland Paris позволяет быстро и комфортно добраться до отеля или парка после перелета. Если вы прилетаете в аэропорт Orly, ZONT организует удобный трансфер до Disneyland Paris. Аэропорт Beauvais находится дальше от Парижа, поэтому заранее заказанный трансфер — один из самых комфортных вариантов поездки.',
    description3: 'Вы можете заказать трансфер из Парижа в Disneyland Paris из любого района города. Водитель заберет вас из отеля, апартаментов, вокзала или частного адреса и доставит прямо к месту назначения. ZONT также предлагает обратные трансферы из Disneyland Paris в Париж, аэропорты CDG, Orly, Beauvais, на вокзалы или по любому другому адресу. Для семей и групп доступны просторные минивэны на 7–8 пассажиров. Минивэн особенно удобен, если вы путешествуете с детьми, коляской, чемоданами или большим количеством багажа.',
    whyChoose: 'Почему выбирают ZONT',
    feature1Title: 'Встреча в аэропорту', feature1Desc: 'Водитель встретит вас в зоне прибытия, поможет с багажом и сопроводит до автомобиля. Отслеживание рейса в случае задержки.',
    feature2Title: 'Для семей с детьми', feature2Desc: 'Просторные минивэны для семей с колясками, чемоданами и сувенирами из Диснейленда. Детские кресла по запросу.',
    feature3Title: 'Фиксированные цены', feature3Desc: 'Цена фиксируется при бронировании и не меняется из-за пробок или маршрута. Без скрытых доплат.',
    feature4Title: 'Обратный трансфер', feature4Desc: 'Закажите поездку туда и обратно. Водитель ждёт после фейерверка — никакой охоты за такси.',
    sedan: 'Премиум Седан', sedanDesc: 'Mercedes E-Class, 1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes S-Class или BMW 7',
    minivan: 'Минивэн 7 мест', minivanDesc: 'Mercedes V-Class, до 7 пассажиров + коляски', minibus: 'Минибус 8 мест', minibusDesc: 'Renault Trafic, для семей и групп с багажом',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'Забронировать трансфер', allInclusive: 'Все включено',
    vehiclesTitle: 'Комфортные автомобили и минивэны',
    howItWorks: 'Как забронировать трансфер', step1: 'Укажите детали поездки', step1Desc: 'Адрес отправления, Disneyland Paris или ваш отель, дату и время, количество пассажиров и багаж.',
    step2: 'Получите фиксированную цену', step2Desc: 'Вы увидите стоимость поездки и сможете подтвердить бронирование за 2 минуты.',
    step3: 'Встреча водителя', step3Desc: 'Водитель приедет в назначенное время. Из аэропорта — встретит в зоне прибытия с табличкой.',
    popularRoutesTitle: 'Популярные направления', fromLabel: 'От',
    routes: [
      { name: 'CDG → Disneyland Paris', price: 75 },
      { name: 'Orly → Disneyland Paris', price: 90 },
      { name: 'Beauvais → Disneyland Paris', price: 175 },
      { name: 'Париж → Disneyland Paris', price: 59 },
      { name: 'Disneyland Paris → Париж', price: 59 },
      { name: 'Disneyland → Gare du Nord / Gare de Lyon', price: 65 },
    ],
    bookingForm: 'Заказать трансфер в Disneyland Paris',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: '',
    defaultDropoff: 'Disneyland Paris, France',
    otherCitiesTitle: '16+ городов в Европе', otherCitiesBtn: 'Все Направления',
    rating: '4.5/5 Tripadvisor (29 отзывов)',
  },
  hy: {
    title: 'Disneyland Paris transfer - 49\u20AC-ic',
    subtitle: 'VTC Disneyland Paris. Gner 49\u20AC-ic',
    description: 'Tarekan 15 million aycelu Disneyland Paris. Mer transfery vercenum e dzez hyuranociic yev hascenum Disney Village.',
    description2: 'Disneyland Paris Marne-la-Vallee, 32 km. CDG-ic 35-45 rope. Orly-ic 50 rope. Parizi kentroic 40 rope.',
    description3: 'Mankakan nstateghner ankchar. 24/7 ashkhatum enq. Fix gner.',
    whyChoose: 'Inchu untrel mer transfery',
    feature1Title: 'Dur-dur', feature1Desc: 'Hasceum Disney hyuranociic.',
    feature2Title: 'Yntaniki hamar', feature2Desc: 'Ankchar mankakan nstateghner.',
    feature3Title: 'Gner 49\u20AC-ic', feature3Desc: 'Giny hastatsvats e.',
    feature4Title: 'Hetadardz', feature4Desc: 'Varordyn spasum e.',
    sedan: 'Comfort', sedanDesc: 'Toyota, 1-3', luxury: 'Premium', luxuryDesc: 'Mercedes E-Class',
    minivan: 'Van', minivanDesc: 'Mercedes V-Class, 6', minibus: 'Minibus', minibusDesc: '8',
    passengers: 'Ughevorner', luggage: 'Ughebaranner', bookNow: 'AMRAGREL', allInclusive: 'Amen inch',
    vehiclesTitle: 'Untretsek mekhenan',
    howItWorks: 'Inchpes e ashkhatum', step1: 'Amragreq', step1Desc: 'Giny 49\u20AC-ic.',
    step2: 'Handipeq varordun', step2Desc: 'Varordyn gallis e.',
    step3: 'Hangstatsek', step3Desc: 'Harmaravets ughevoratsutsiun.',
    popularRoutesTitle: 'Disneyland ughghutsiwnner', fromLabel: 'Sksvats',
    routes: [
      { name: 'Pariz \u2192 Disneyland', price: 59 },
      { name: 'CDG \u2192 Disneyland', price: 75 },
      { name: 'Orly \u2192 Disneyland', price: 90 },
      { name: 'Beauvais \u2192 Disneyland', price: 175 },
    ],
    bookingForm: 'Amragreq Disneyland transfer',
    pickupLabel: 'Vertsneloy', dropoffLabel: 'Ijnelov', dateLabel: 'Amsaket', timeLabel: 'Zham',
    defaultPickup: '',
    defaultDropoff: 'Disneyland Paris',
    otherCitiesTitle: '16 qaghaqner', otherCitiesBtn: 'Bolory',
    rating: '4.5/5 Tripadvisor (29)',
  },
  es: {
    title: 'Traslado privado a Disneyland Paris | Desde CDG, Orly y Paris',
    subtitle: 'Reserva un traslado privado a Disneyland Paris desde aeropuertos, hoteles o Paris. Minivan familiar, sillas infantiles, precio fijo y conductor profesional.',
    description: 'ZONT ofrece traslados privados a Disneyland Paris desde los aeropuertos CDG, Orly, Beauvais, estaciones de tren, hoteles de Paris y direcciones privadas. Nuestro servicio es ideal para familias, grupos y viajeros con ninos.',
    description2: 'Disponemos de vehiculos comodos y minivans para pasajeros con equipaje. Bajo solicitud, se pueden anadir sillas infantiles segun disponibilidad. El precio se confirma antes del viaje, sin taximetro ni costes ocultos.',
    description3: 'El conductor puede recibir a los pasajeros en el aeropuerto con cartel de bienvenida, ayudar con las maletas y llevarlos directamente a Disneyland Paris o a los hoteles cercanos como Disney Hotel New York, Newport Bay Club o Sequoia Lodge. Tras un dia largo en el parque, programa tambien tu traslado de vuelta con la misma comodidad.',
    whyChoose: '\u00bfPor que elegir nuestro traslado a Disneyland Paris?',
    feature1Title: 'Vehiculos familiares', feature1Desc: 'Minivans para familias y grupos. Sillas infantiles bajo solicitud.',
    feature2Title: 'Seguimiento de vuelo', feature2Desc: 'Seguimiento en tiempo real. Sin recargo por retrasos. 60 minutos de espera gratis.',
    feature3Title: 'Precio fijo', feature3Desc: 'Precio confirmado al reservar, ida y vuelta a la misma tarifa.',
    feature4Title: 'Conductor profesional', feature4Desc: 'Bilingue. Conoce los hoteles Disney y los puntos de recogida en el parque.',
    sedan: 'Berlina Premium', sedanDesc: 'Mercedes Clase E, 1-3 pasajeros',
    luxury: 'Berlina de Lujo', luxuryDesc: 'Mercedes Clase S o BMW Serie 7',
    minivan: 'Minivan', minivanDesc: 'Mercedes Clase V, hasta 6 pasajeros',
    minibus: 'Microbus', minibusDesc: 'Para grupos de hasta 8 pasajeros',
    passengers: 'Pasajeros', luggage: 'Maletas',
    bookNow: 'RESERVAR', allInclusive: 'Todo incluido',
    vehiclesTitle: 'Elige tu vehiculo',
    howItWorks: 'Como funciona',
    step1: 'Reserva online', step1Desc: 'Indica origen, destino, fecha y numero de pasajeros. Precio instantaneo.',
    step2: 'Encuentra a tu conductor', step2Desc: 'El conductor te espera en el lugar indicado con cartel a tu nombre.',
    step3: 'Llega a Disneyland', step3Desc: 'Traslado directo, comodo y sin estres para empezar la magia.',
    popularRoutesTitle: 'Rutas populares hacia Disneyland Paris', fromLabel: 'Desde',
    routes: [
      { name: 'CDG \u2192 Disneyland Paris', price: 75 },
      { name: 'Orly \u2192 Disneyland Paris', price: 70 },
      { name: 'Beauvais \u2192 Disneyland Paris', price: 165 },
      { name: 'Paris Centro \u2192 Disneyland Paris', price: 85 },
    ],
    bookingForm: 'Reserva tu traslado a Disneyland Paris',
    pickupLabel: 'Recogida', dropoffLabel: 'Destino', dateLabel: 'Fecha', timeLabel: 'Hora',
    defaultPickup: '',
    defaultDropoff: 'Disneyland Paris',
    otherCitiesTitle: 'Tambien disponible desde aeropuertos parisinos', otherCitiesBtn: 'Ver todos los destinos',
    rating: '4.5/5 Tripadvisor',
    meetDriverTitle: 'Donde encontrar a tu conductor para Disneyland Paris',
    meetDriverText: 'El conductor te espera en el lugar indicado al reservar (aeropuerto, hotel o direccion) con un cartel a tu nombre. Te ayuda con el equipaje y te lleva directamente a Disneyland Paris.',
  },
};

const vehiclesPrices = { sedan: 59, luxury: 85, minivan: 110, minibus: 160 };

const seoUrls = { en: '/disneyland-paris-transfer', fr: '/transfert-disneyland-paris', ru: '/transfer-disneyland-parizh', hy: '/disneylend-pariz-transfer', es: '/es/traslado-disneyland-paris' };
const DisneylandTransfer = () => (
  <CityTransferPage
    content={content}
    vehicles={vehiclesPrices}
    seoUrls={seoUrls}
    pageId="disneyland"
    extraSections={<DisneylandMainSections />}
  />
);
export default DisneylandTransfer;
