import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Gare Saint-Lazare Transfer - Private Driver in Paris',
    subtitle: 'Premium private chauffeur to and from Gare Saint-Lazare. Trains from Normandy, Le Havre, Rouen, Deauville.',
    description: 'Gare Saint-Lazare is the second busiest station in Paris, serving over 100 million passengers per year. It connects Paris to Normandy, with trains to Rouen, Le Havre, Caen, Deauville, and the Normandy beaches. Located in the 8th arrondissement near the Opera district and Boulevard Haussmann, the station sits in one of the most congested areas of central Paris. Our private transfer eliminates the stress of navigating narrow streets with luggage.',
    description2: 'Saint-Lazare is surrounded by department stores (Galeries Lafayette, Printemps) and offices, making taxi queues unpredictable. Our driver waits at the main exit on Rue d\'Amsterdam with your name sign.',
    description3: 'Popular for weekend getaways to Deauville and the Normandy coast. Book your return transfer in advance for a seamless trip. Fixed prices from 25 EUR.',
    whyChoose: 'Why Choose Our Saint-Lazare Transfer?',
    feature1Title: 'Train Tracking', feature1Desc: 'We monitor your train arrival.',
    feature2Title: 'Exit Meet', feature2Desc: 'Driver at Rue d\'Amsterdam exit with name sign.',
    feature3Title: 'Fixed Prices', feature3Desc: 'From 25 EUR. No hidden fees.',
    feature4Title: 'Premium Fleet', feature4Desc: 'Mercedes E, S, V-Class.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class',
    minivan: 'Minivan', minivanDesc: 'Mercedes V-Class, up to 6', minibus: 'Minibus', minibusDesc: 'Up to 8',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive', vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Select Saint-Lazare.',
    step2: 'Meet Driver', step2Desc: 'Name sign at exit.', step3: 'Transfer', step3Desc: 'Direct ride.',
    popularRoutesTitle: 'Popular Saint-Lazare Transfers', fromLabel: 'From',
    routes: [{ name: 'Saint-Lazare to Paris Hotel', price: 25 }, { name: 'Saint-Lazare to CDG Airport', price: 65 }],
    bookingForm: 'Book Your Saint-Lazare Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Gare Saint-Lazare, Paris', otherCitiesTitle: 'All Paris stations', otherCitiesBtn: 'View All',
    rating: '4.5/5 Tripadvisor (29 reviews)',
    meetDriverTitle: 'Where to Meet Your Driver at Gare Saint-Lazare',
    meetDriverText: 'After your train arrives, follow the signs to the main exit on Rue d\'Amsterdam. Your chauffeur will be waiting just outside with a sign showing your name. He will help with your luggage and walk you to your waiting vehicle. A smooth start to your Paris stay or a relaxed transfer to the airport.',
  },
  fr: {
    title: 'Transfert Gare Saint-Lazare - Chauffeur Prive a Paris',
    subtitle: 'Chauffeur prive premium depuis et vers Saint-Lazare. Trains de Normandie, Le Havre, Rouen, Deauville.',
    description: 'La Gare Saint-Lazare est la deuxieme gare la plus frequentee de Paris, desservant la Normandie : Rouen, Le Havre, Caen, Deauville. Situee dans le 8e pres de l\'Opera et du Boulevard Haussmann, notre transfert elimine le stress de la circulation dense du quartier.',
    description2: 'Entouree de grands magasins (Galeries Lafayette, Printemps), les files de taxis sont imprevisibles. Notre chauffeur vous attend Rue d\'Amsterdam.',
    description3: 'Ideal pour les week-ends a Deauville. Prix fixes des 25 EUR.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Saint-Lazare ?',
    feature1Title: 'Suivi Train', feature1Desc: 'Surveillance de votre train.',
    feature2Title: 'Accueil Sortie', feature2Desc: 'Chauffeur Rue d\'Amsterdam.',
    feature3Title: 'Prix Fixes', feature3Desc: 'Des 25 EUR.',
    feature4Title: 'Flotte Premium', feature4Desc: 'Mercedes E, S, V-Class.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S',
    minivan: 'Monospace', minivanDesc: 'Mercedes Classe V', minibus: 'Minibus', minibusDesc: 'Jusqu\'a 8',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris', vehiclesTitle: 'Choisissez',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez', step1Desc: 'Saint-Lazare.',
    step2: 'Rencontrez', step2Desc: 'Pancarte a la sortie.', step3: 'Transfert', step3Desc: 'Trajet confortable.',
    popularRoutesTitle: 'Transferts Saint-Lazare', fromLabel: 'A partir de',
    routes: [{ name: 'Saint-Lazare vers Hotel', price: 25 }, { name: 'Saint-Lazare vers CDG', price: 65 }],
    bookingForm: 'Reservez Transfert Saint-Lazare',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Gare Saint-Lazare, Paris', otherCitiesTitle: 'Toutes les gares', otherCitiesBtn: 'Toutes les Gares',
    rating: '4.5/5 Tripadvisor (29 avis)',
    meetDriverTitle: 'Ou retrouver votre chauffeur a Gare Saint-Lazare',
    meetDriverText: 'Apres l\'arrivee de votre train, suivez les panneaux vers la sortie principale Rue d\'Amsterdam. Votre chauffeur vous attend juste dehors avec une pancarte a votre nom. Il prend vos bagages et vous accompagne a votre vehicule.',
  },
  ru: {
    title: 'Трансфер Сен-Лазар', subtitle: 'Премиум трансфер.',
    description: 'Гар Сен-Лазар — поезда в Нормандию. Водитель у выхода.', description2: 'Без очередей на такси.',
    whyChoose: 'Почему?', feature1Title: 'Мониторинг', feature1Desc: '.', feature2Title: 'Встреча', feature2Desc: 'Табличка.',
    feature3Title: 'Цены', feature3Desc: 'От 25.', feature4Title: 'Премиум', feature4Desc: 'Mercedes.',
    sedan: 'Седан', sedanDesc: 'E-Class', luxury: 'Люкс', luxuryDesc: 'S-Class', minivan: 'Минивэн', minivanDesc: 'V-Class', minibus: 'Микроавтобус', minibusDesc: '8',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Включено', vehiclesTitle: 'Авто', howItWorks: 'Как',
    step1: 'Бронируйте', step1Desc: '.', step2: 'Встреча', step2Desc: '.', step3: 'Трансфер', step3Desc: '.',
    popularRoutesTitle: 'Популярные', fromLabel: 'От', routes: [{ name: 'Сен-Лазар → Отель', price: 25 }],
    bookingForm: 'Забронируйте', pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: '', otherCitiesTitle: 'Все', otherCitiesBtn: 'Все', rating: '4.5/5 Tripadvisor',
    meetDriverTitle: 'Где встретить водителя на Сен-Лазар', meetDriverText: 'Водитель ждёт у выхода Rue d\'Amsterdam.',
  },
  hy: {
    title: 'Saint-Lazare delays', subtitle: 'Delays', description: 'Delays.',
    whyChoose: 'Delays', feature1Title: 'Delays', feature1Desc: '.', feature2Title: 'Delays', feature2Desc: '.',
    feature3Title: 'Delays', feature3Desc: '.', feature4Title: 'Delays', feature4Desc: '.',
    sedan: 'Delays', sedanDesc: '.', luxury: 'Delays', luxuryDesc: '.', minivan: 'Delays', minivanDesc: '.', minibus: 'Delays', minibusDesc: '.',
    passengers: 'Delays', luggage: 'Delays', bookNow: 'Delays', allInclusive: 'Delays', vehiclesTitle: 'Delays', howItWorks: 'Delays',
    step1: 'Delays', step1Desc: '.', step2: 'Delays', step2Desc: '.', step3: 'Delays', step3Desc: '.',
    popularRoutesTitle: 'Delays', fromLabel: 'Delays', bookingForm: 'Delays', pickupLabel: 'Delays', dropoffLabel: 'Delays', dateLabel: 'Delays', timeLabel: 'Delays',
    defaultPickup: '', otherCitiesTitle: 'Delays', otherCitiesBtn: 'Delays', rating: '4.5/5 Tripadvisor',
    meetDriverTitle: 'Delays Saint-Lazare', meetDriverText: 'Delays.',
  },
};

const vehiclesPrices = { sedan: 25, luxury: 45, minivan: 60, minibus: 90 };
const seoUrls = { en: '/gare-saint-lazare-transfer', fr: '/transfert-gare-saint-lazare', ru: '/transfer-gar-sen-lazar', hy: '/gar-sen-lazar-transfer' };
const GareSaintLazareTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} meetDriverImage="/images/gare-lazare-driver.webp" pageId="gare-saint-lazare" />;
export default GareSaintLazareTransfer;
