import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Gare du Nord Transfer - Private Driver in Paris',
    subtitle: 'Premium private chauffeur to and from Gare du Nord. Eurostar from London, Thalys from Brussels, ICE from Amsterdam.',
    description: 'Gare du Nord is the busiest train station in Europe, handling over 700,000 passengers per day. It is the arrival point for Eurostar trains from London St Pancras, Thalys from Brussels, and ICE high-speed trains from Amsterdam and Cologne. Located in the 10th arrondissement, the station opens onto a vibrant but sometimes chaotic neighbourhood. Our private transfer meets you at the platform exit with a personalized name sign and takes you directly to your Paris hotel, apartment, or airport.',
    description2: 'The taxi queue at Gare du Nord can stretch for 30 minutes during Eurostar peak arrivals. Our pre-booked chauffeur eliminates the wait. We track your train in real time and adjust to any delay. Your driver is always there when you walk out.',
    description3: 'Gare du Nord is also the starting point for many European journeys. Book a morning pickup from your hotel to catch the 6:30 Eurostar to London or the 7:00 Thalys to Brussels. Fixed prices, no surge pricing.',
    whyChoose: 'Why Choose Our Gare du Nord Transfer?',
    feature1Title: 'Eurostar Tracking', feature1Desc: 'We monitor your Eurostar/Thalys arrival. Driver adjusts automatically.',
    feature2Title: 'Platform Exit Meet', feature2Desc: 'Driver waits right at the platform exit with your name sign.',
    feature3Title: 'Fixed Prices', feature3Desc: 'No hidden fees. From 25 EUR to your Paris hotel.',
    feature4Title: 'Premium Fleet', feature4Desc: 'Mercedes E-Class, S-Class, V-Class. Clean and comfortable.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class or similar',
    minivan: 'Minivan', minivanDesc: 'Mercedes V-Class, up to 6 passengers', minibus: 'Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Select Gare du Nord and your destination.',
    step2: 'Meet Your Driver', step2Desc: 'Driver waits at the exit with your name.',
    step3: 'Direct Transfer', step3Desc: 'Comfortable ride to your destination.',
    popularRoutesTitle: 'Popular Gare du Nord Transfers', fromLabel: 'From',
    routes: [
      { name: 'Gare du Nord to Paris Hotel', price: 25 },
      { name: 'Gare du Nord to CDG Airport', price: 65 },
      { name: 'Gare du Nord to Orly Airport', price: 55 },
      { name: 'Gare du Nord to Disneyland Paris', price: 80 },
    ],
    bookingForm: 'Book Your Gare du Nord Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Gare du Nord, Paris',
    otherCitiesTitle: 'Also available from all Paris stations', otherCitiesBtn: 'View All Stations',
    rating: '4.5/5 Tripadvisor (29 reviews)',
    meetDriverTitle: 'Where to Meet Your Driver at Gare du Nord',
    meetDriverText: 'After your Eurostar or Thalys arrives, follow the signs to the main exit. Your chauffeur will be waiting just outside the arrivals area, holding a sign with your name. He will help you with your luggage and walk you directly to your waiting vehicle. No taxi queues, no confusion — just a smooth, personal welcome to Paris.',
  },
  fr: {
    title: 'Transfert Gare du Nord - Chauffeur Prive a Paris',
    subtitle: 'Chauffeur prive premium depuis et vers la Gare du Nord. Eurostar de Londres, Thalys de Bruxelles, ICE d\'Amsterdam.',
    description: 'La Gare du Nord est la gare la plus frequentee d\'Europe, avec plus de 700 000 passagers par jour. C\'est le point d\'arrivee des Eurostar de Londres, Thalys de Bruxelles et ICE d\'Amsterdam. Notre transfert prive vous attend a la sortie des quais avec une pancarte a votre nom et vous conduit directement a votre hotel, appartement ou aeroport.',
    description2: 'La file de taxis a la Gare du Nord peut atteindre 30 minutes aux heures de pointe Eurostar. Notre chauffeur pre-reserve elimine cette attente. Suivi de votre train en temps reel.',
    description3: 'Point de depart de nombreux voyages europeens. Reservez un transfert matinal pour attraper l\'Eurostar de 6h30 vers Londres. Prix fixes, sans surprises.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Gare du Nord ?',
    feature1Title: 'Suivi Eurostar', feature1Desc: 'Surveillance de votre Eurostar/Thalys. Le chauffeur s\'adapte.',
    feature2Title: 'Accueil aux Quais', feature2Desc: 'Chauffeur a la sortie des quais avec pancarte nominative.',
    feature3Title: 'Prix Fixes', feature3Desc: 'Pas de frais caches. A partir de 25 EUR.',
    feature4Title: 'Flotte Premium', feature4Desc: 'Mercedes E-Class, S-Class, V-Class.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E, 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S ou similaire',
    minivan: 'Monospace', minivanDesc: 'Mercedes Classe V, jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Selectionnez Gare du Nord et votre destination.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Chauffeur a la sortie avec pancarte.',
    step3: 'Transfert Direct', step3Desc: 'Trajet confortable.',
    popularRoutesTitle: 'Transferts Gare du Nord Populaires', fromLabel: 'A partir de',
    routes: [
      { name: 'Gare du Nord vers Hotel Paris', price: 25 },
      { name: 'Gare du Nord vers Aeroport CDG', price: 65 },
      { name: 'Gare du Nord vers Aeroport Orly', price: 55 },
      { name: 'Gare du Nord vers Disneyland Paris', price: 80 },
    ],
    bookingForm: 'Reservez Votre Transfert Gare du Nord',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Gare du Nord, Paris',
    otherCitiesTitle: 'Disponible depuis toutes les gares de Paris', otherCitiesBtn: 'Toutes les Gares',
    rating: '4.5/5 Tripadvisor (29 avis)',
    meetDriverTitle: 'Ou retrouver votre chauffeur a la Gare du Nord',
    meetDriverText: 'Apres l\'arrivee de votre Eurostar ou Thalys, suivez les panneaux vers la sortie principale. Votre chauffeur vous attend juste dehors avec une pancarte a votre nom. Il prend vos bagages et vous accompagne directement a votre vehicule. Pas de file de taxis, pas de confusion — un accueil personnalise a Paris.',
  },
  ru: {
    title: 'Трансфер Гар дю Нор - Частный Водитель в Париже',
    subtitle: 'Премиум трансфер с Гар дю Нор. Eurostar из Лондона, Thalys из Брюсселя.',
    description: 'Гар-дю-Нор — самый загруженный вокзал Европы, 700 000 пассажиров в день. Eurostar из Лондона, Thalys из Брюсселя. Водитель у выхода с табличкой.',
    description2: 'Очередь на такси — до 30 минут. Наш сервис устраняет ожидание. Мониторинг поезда.', description3: 'Фиксированные цены от 25 EUR.',
    whyChoose: 'Почему Наш Трансфер?',
    feature1Title: 'Мониторинг', feature1Desc: 'Отслеживание Eurostar/Thalys.',
    feature2Title: 'Встреча', feature2Desc: 'Водитель с табличкой у выхода.',
    feature3Title: 'Фикс. Цены', feature3Desc: 'От 25 EUR.',
    feature4Title: 'Премиум', feature4Desc: 'Mercedes E, S, V-Class.',
    sedan: 'Премиум Седан', sedanDesc: 'Mercedes E-Class', luxury: 'Люкс', luxuryDesc: 'Mercedes S-Class',
    minivan: 'Минивэн', minivanDesc: 'Mercedes V-Class', minibus: 'Микроавтобус', minibusDesc: 'До 8',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Автомобиль', howItWorks: 'Как Работает',
    step1: 'Бронируйте', step1Desc: 'Выберите вокзал.', step2: 'Встреча', step2Desc: 'Водитель с табличкой.', step3: 'Трансфер', step3Desc: 'Комфортная поездка.',
    popularRoutesTitle: 'Популярные', fromLabel: 'От',
    routes: [{ name: 'Гар дю Нор → Отель', price: 25 }, { name: 'Гар дю Нор → CDG', price: 65 }],
    bookingForm: 'Забронируйте', pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Гар дю Нор, Париж', otherCitiesTitle: 'Все вокзалы', otherCitiesBtn: 'Все', rating: '4.5/5 Tripadvisor',
    meetDriverTitle: 'Где встретить водителя на Гар дю Нор', meetDriverText: 'После прибытия Eurostar следуйте к главному выходу. Водитель ждёт с табличкой.',
  },
  hy: {
    title: 'Գdelays Gare du Nord delays', subtitle: 'Delays', description: 'Delays.',
    whyChoose: 'Delays', feature1Title: 'Delays', feature1Desc: 'Delays', feature2Title: 'Delays', feature2Desc: 'Delays',
    feature3Title: 'Delays', feature3Desc: 'Delays', feature4Title: 'Delays', feature4Desc: 'Delays',
    sedan: 'Delays', sedanDesc: 'Delays', luxury: 'Delays', luxuryDesc: 'Delays', minivan: 'Delays', minivanDesc: 'Delays', minibus: 'Delays', minibusDesc: 'Delays',
    passengers: 'Delays', luggage: 'Delays', bookNow: 'Delays', allInclusive: 'Delays', vehiclesTitle: 'Delays', howItWorks: 'Delays',
    step1: 'Delays', step1Desc: 'Delays', step2: 'Delays', step2Desc: 'Delays', step3: 'Delays', step3Desc: 'Delays',
    popularRoutesTitle: 'Delays', fromLabel: 'Delays', bookingForm: 'Delays', pickupLabel: 'Delays', dropoffLabel: 'Delays', dateLabel: 'Delays', timeLabel: 'Delays',
    defaultPickup: '', otherCitiesTitle: 'Delays', otherCitiesBtn: 'Delays', rating: '4.5/5 Tripadvisor',
    meetDriverTitle: 'Delays Gare du Nord', meetDriverText: 'Delays.',
  },
};

const vehiclesPrices = { sedan: 25, luxury: 45, minivan: 60, minibus: 90 };
const seoUrls = { en: '/gare-du-nord-transfer', fr: '/transfert-gare-du-nord', ru: '/transfer-gar-dyu-nor', hy: '/gar-dyu-nor-transfer' };
const GareDuNordTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} meetDriverImage="/images/gare-nord-driver.webp" pageId="gare-du-nord" />;
export default GareDuNordTransfer;
