import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Gare de Lyon Transfer - Private Driver in Paris',
    subtitle: 'Premium private chauffeur to and from Gare de Lyon, Paris 12th. TGV arrivals from Lyon, Marseille, Nice, and the French Riviera.',
    description: 'Gare de Lyon is the gateway to southern France and the French Riviera, handling TGV high-speed trains to Lyon, Marseille, Nice, Avignon, and Montpellier. With over 148,000 passengers daily, it is one of the busiest stations in Paris. The station sits in the 12th arrondissement, near Bastille and the Seine. Our private transfer service meets you right outside the main hall under the iconic clock tower. Your chauffeur holds a name sign, helps with your luggage, and drives you directly to your hotel, apartment, or Paris CDG / Orly airport.',
    description2: 'Finding a taxi at Gare de Lyon during peak TGV arrivals (Friday evenings, holiday periods) often means 20-30 minutes of queuing in the congested forecourt. Our pre-booked service eliminates the wait entirely. Your driver monitors your train in real time and adjusts to any delays. Whether you arrive from a weekend in Provence or a business trip to Lyon, your ride is ready the moment you step off the platform.',
    description3: 'Gare de Lyon is also a popular departure point. Many travellers book a morning pickup from their Paris hotel to catch the 7:00 TGV to Lyon or the 8:30 to Nice. Our driver arrives 15 minutes early and gets you to the station entrance with time to spare. Fixed prices, no surge, no surprises.',
    whyChoose: 'Why Choose Our Gare de Lyon Transfer?',
    feature1Title: 'TGV Monitoring', feature1Desc: 'We track your TGV arrival. Driver adjusts to any delay automatically.',
    feature2Title: 'Meet at Hall', feature2Desc: 'Driver waits at the main hall exit with your name sign and helps with bags.',
    feature3Title: 'Fixed Prices', feature3Desc: 'No hidden fees. Price confirmed at booking. Station-to-door service.',
    feature4Title: 'Premium Vehicles', feature4Desc: 'Mercedes E-Class, S-Class, V-Class. Clean, air-conditioned, comfortable.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class or similar',
    minivan: 'Minivan', minivanDesc: 'Mercedes V-Class, up to 6 passengers', minibus: 'Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Select Gare de Lyon and your destination.',
    step2: 'Meet Your Driver', step2Desc: 'Driver waits at the station exit with your name sign.',
    step3: 'Direct Transfer', step3Desc: 'Comfortable ride to your hotel, airport, or any Paris destination.',
    popularRoutesTitle: 'Popular Gare de Lyon Transfers', fromLabel: 'From',
    routes: [
      { name: 'Gare de Lyon to Paris Hotel', price: 25 },
      { name: 'Gare de Lyon to CDG Airport', price: 65 },
      { name: 'Gare de Lyon to Orly Airport', price: 50 },
      { name: 'Gare de Lyon to Disneyland Paris', price: 75 },
    ],
    bookingForm: 'Book Your Gare de Lyon Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Gare de Lyon, Paris',
    otherCitiesTitle: 'Also available from all Paris stations', otherCitiesBtn: 'View All Stations',
    rating: '4.5/5 Tripadvisor (29 reviews)',
    meetDriverTitle: 'Where to Meet Your Driver at Gare de Lyon',
    meetDriverText: 'After your TGV arrives, follow the signs to the main hall exit. Your chauffeur will be waiting just outside under the iconic clock tower, holding a sign with your name. He will help you with your luggage and walk you to your vehicle parked nearby. No searching for taxis, no queuing — your transfer starts the moment you step out of the station.',
  },
  fr: {
    title: 'Transfert Gare de Lyon - Chauffeur Prive a Paris',
    subtitle: 'Chauffeur prive premium depuis et vers la Gare de Lyon, Paris 12e. Arrivees TGV de Lyon, Marseille, Nice et la Cote d\'Azur.',
    description: 'La Gare de Lyon est la porte d\'entree du sud de la France et de la Cote d\'Azur, avec des TGV vers Lyon, Marseille, Nice, Avignon et Montpellier. Avec plus de 148 000 passagers par jour, c\'est l\'une des gares les plus frequentees de Paris. Situee dans le 12e arrondissement, pres de Bastille et de la Seine, notre service de transfert prive vous attend a la sortie du hall principal sous la celebre tour de l\'horloge. Votre chauffeur vous accueille avec une pancarte, prend vos bagages et vous conduit directement a votre hotel, appartement ou aeroport CDG / Orly.',
    description2: 'Trouver un taxi a la Gare de Lyon aux heures de pointe TGV (vendredis soirs, periodes de vacances) signifie souvent 20-30 minutes de file. Notre service pre-reserve elimine cette attente. Votre chauffeur surveille votre train en temps reel et s\'adapte aux retards.',
    description3: 'La Gare de Lyon est aussi un point de depart populaire. Beaucoup de voyageurs reservent un transfert matinal depuis leur hotel pour attraper le TGV de 7h vers Lyon ou le 8h30 vers Nice. Prix fixes, sans surprises.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Gare de Lyon ?',
    feature1Title: 'Suivi TGV', feature1Desc: 'Surveillance de l\'arrivee de votre TGV. Le chauffeur s\'adapte aux retards.',
    feature2Title: 'Accueil au Hall', feature2Desc: 'Chauffeur a la sortie du hall principal avec pancarte nominative.',
    feature3Title: 'Prix Fixes', feature3Desc: 'Pas de frais caches. Prix confirme a la reservation.',
    feature4Title: 'Vehicules Premium', feature4Desc: 'Mercedes E-Class, S-Class, V-Class. Propres et climatises.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E, 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S ou similaire',
    minivan: 'Monospace', minivanDesc: 'Mercedes Classe V, jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Selectionnez Gare de Lyon et votre destination.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Chauffeur a la sortie avec pancarte personnalisee.',
    step3: 'Transfert Direct', step3Desc: 'Trajet confortable vers votre destination.',
    popularRoutesTitle: 'Transferts Gare de Lyon Populaires', fromLabel: 'A partir de',
    routes: [
      { name: 'Gare de Lyon vers Hotel Paris', price: 25 },
      { name: 'Gare de Lyon vers Aeroport CDG', price: 65 },
      { name: 'Gare de Lyon vers Aeroport Orly', price: 50 },
      { name: 'Gare de Lyon vers Disneyland Paris', price: 75 },
    ],
    bookingForm: 'Reservez Votre Transfert Gare de Lyon',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Gare de Lyon, Paris',
    otherCitiesTitle: 'Disponible depuis toutes les gares de Paris', otherCitiesBtn: 'Toutes les Gares',
    rating: '4.5/5 Tripadvisor (29 avis)',
    meetDriverTitle: 'Ou retrouver votre chauffeur a la Gare de Lyon',
    meetDriverText: 'Apres l\'arrivee de votre TGV, suivez les panneaux vers la sortie du hall principal. Votre chauffeur vous attend juste dehors sous la celebre tour de l\'horloge, avec une pancarte a votre nom. Il prend vos bagages et vous accompagne jusqu\'a votre vehicule gare a proximite. Pas de recherche de taxi, pas de file d\'attente.',
  },
  ru: {
    title: 'Трансфер Гар де Лион - Частный Водитель в Париже',
    subtitle: 'Премиум трансфер с Гар де Лион. TGV из Лиона, Марселя, Ниццы.',
    description: 'Гар-де-Лион — ворота на юг Франции и Лазурный Берег. TGV в Лион, Марсель, Ниццу, Авиньон. 148 000 пассажиров ежедневно. Наш водитель встречает у выхода из главного зала с табличкой.',
    description2: 'Найти такси в пиковые часы — 20-30 минут очереди. Наш сервис исключает ожидание. Водитель отслеживает ваш поезд.',
    description3: 'Популярный пункт отправления. Утренний трансфер из отеля на TGV в 7:00 до Лиона. Фиксированные цены.',
    whyChoose: 'Почему Наш Трансфер Гар де Лион?',
    feature1Title: 'Мониторинг TGV', feature1Desc: 'Отслеживание прибытия поезда.',
    feature2Title: 'Встреча у Зала', feature2Desc: 'Водитель у выхода с табличкой.',
    feature3Title: 'Фикс. Цены', feature3Desc: 'Цена при бронировании.',
    feature4Title: 'Премиум Авто', feature4Desc: 'Mercedes E, S, V-Class.',
    sedan: 'Премиум Седан', sedanDesc: 'Mercedes E-Class, 1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes S-Class',
    minivan: 'Минивэн', minivanDesc: 'Mercedes V-Class, до 6', minibus: 'Микроавтобус', minibusDesc: 'До 8',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль', howItWorks: 'Как Это Работает',
    step1: 'Бронируйте', step1Desc: 'Выберите Гар де Лион и адрес.',
    step2: 'Встретьте Водителя', step2Desc: 'Водитель с табличкой.',
    step3: 'Прямой Трансфер', step3Desc: 'Комфортная поездка.',
    popularRoutesTitle: 'Популярные Трансферы', fromLabel: 'От',
    routes: [{ name: 'Гар де Лион → Отель', price: 25 }, { name: 'Гар де Лион → CDG', price: 65 }],
    bookingForm: 'Забронируйте', pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Гар де Лион, Париж',
    otherCitiesTitle: 'Все вокзалы Парижа', otherCitiesBtn: 'Все',
    rating: '4.5/5 Tripadvisor',
    meetDriverTitle: 'Где встретить водителя на Гар де Лион',
    meetDriverText: 'После прибытия TGV следуйте указателям к выходу из главного зала. Водитель ждёт снаружи под знаменитой часовой башней с табличкой с вашим именем.',
  },
  hy: {
    title: 'Գdelays Gare de Lyon delays',
    subtitle: 'Delays delays Gare de Lyon delays',
    description: 'Gare de Lyon delays delays delays.',
    whyChoose: 'Delays',
    feature1Title: 'Delays', feature1Desc: 'Delays',
    feature2Title: 'Delays', feature2Desc: 'Delays',
    feature3Title: 'Delays', feature3Desc: 'Delays',
    feature4Title: 'Delays', feature4Desc: 'Delays',
    sedan: 'Delays', sedanDesc: 'Delays', luxury: 'Delays', luxuryDesc: 'Delays',
    minivan: 'Delays', minivanDesc: 'Delays', minibus: 'Delays', minibusDesc: 'Delays',
    passengers: 'Delays', luggage: 'Delays', bookNow: 'Delays', allInclusive: 'Delays',
    vehiclesTitle: 'Delays', howItWorks: 'Delays',
    step1: 'Delays', step1Desc: 'Delays', step2: 'Delays', step2Desc: 'Delays', step3: 'Delays', step3Desc: 'Delays',
    popularRoutesTitle: 'Delays', fromLabel: 'Delays',
    bookingForm: 'Delays', pickupLabel: 'Delays', dropoffLabel: 'Delays', dateLabel: 'Delays', timeLabel: 'Delays',
    defaultPickup: '', otherCitiesTitle: 'Delays', otherCitiesBtn: 'Delays', rating: '4.5/5 Tripadvisor',
    meetDriverTitle: 'Delays Gare de Lyon delays', meetDriverText: 'Delays delays delays.',
  },
};

const vehiclesPrices = { sedan: 25, luxury: 45, minivan: 60, minibus: 90 };
const seoUrls = { en: '/gare-de-lyon-transfer', fr: '/transfert-gare-de-lyon', ru: '/transfer-gar-de-lion', hy: '/gar-de-lion-transfer' };
const GareDeLyonTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} meetDriverImage="/images/gare-lyon-driver.webp" pageId="gare-de-lyon" />;
export default GareDeLyonTransfer;
