import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Gare d\'Austerlitz Transfer - Private Driver in Paris',
    subtitle: 'Premium private chauffeur to and from Gare d\'Austerlitz. Trains from Orleans, Limoges, Toulouse, and overnight services to Spain and Portugal.',
    description: 'Gare d\'Austerlitz is located in the 13th arrondissement along the Seine, serving trains to central and southwestern France including Orleans, Tours, Limoges, and Toulouse. It also handles overnight trains to Spain and Portugal. The station is undergoing a major renovation as part of the Paris 2024 legacy projects, which can make navigation confusing. Our private transfer service meets you at the main exit on Boulevard de l\'Hopital with a personalized name sign.',
    description2: 'While smaller than Gare du Nord or Gare de Lyon, Austerlitz can be tricky during construction periods with shifting exit points. Your driver stays in contact and adapts to whichever exit is currently in use.',
    description3: 'A gateway to the Loire Valley castles and the southwest. Perfect for travellers heading to Tours (Chateaux de la Loire), Bordeaux via connecting services, or returning from Spain overnight. Fixed prices, no surprises.',
    whyChoose: 'Why Choose Our Gare d\'Austerlitz Transfer?',
    feature1Title: 'Train Monitoring', feature1Desc: 'We track your arrival. Driver adjusts.',
    feature2Title: 'Flexible Meet Point', feature2Desc: 'Driver adapts to construction exit changes. Always finds you.',
    feature3Title: 'Fixed Prices', feature3Desc: 'No hidden fees. Station-to-door.',
    feature4Title: 'Premium Vehicles', feature4Desc: 'Mercedes E, S, V-Class.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class',
    minivan: 'Minivan', minivanDesc: 'Mercedes V-Class, up to 6', minibus: 'Minibus', minibusDesc: 'Up to 8',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive', vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Select Gare d\'Austerlitz.',
    step2: 'Meet Driver', step2Desc: 'Name sign at exit.', step3: 'Transfer', step3Desc: 'Direct comfortable ride.',
    popularRoutesTitle: 'Popular Gare d\'Austerlitz Transfers', fromLabel: 'From',
    routes: [{ name: 'Austerlitz to Paris Hotel', price: 25 }, { name: 'Austerlitz to CDG Airport', price: 65 }, { name: 'Austerlitz to Orly Airport', price: 45 }],
    bookingForm: 'Book Your Gare d\'Austerlitz Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Gare d\'Austerlitz, Paris', otherCitiesTitle: 'All Paris stations', otherCitiesBtn: 'View All',
    rating: '4.5/5 Tripadvisor (29 reviews)',
    meetDriverTitle: 'Where to Meet Your Driver at Gare d\'Austerlitz',
    meetDriverText: 'After your train arrives, follow the signs to the main exit on Boulevard de l\'Hopital. Your chauffeur will be waiting outside with a sign showing your name. Due to ongoing renovations, exit points may vary — your driver stays in contact by phone to ensure a smooth pickup regardless of construction changes.',
  },
  fr: {
    title: 'Transfert Gare d\'Austerlitz - Chauffeur Prive a Paris',
    subtitle: 'Chauffeur prive premium depuis et vers la Gare d\'Austerlitz. Trains d\'Orleans, Limoges, Toulouse et trains de nuit vers l\'Espagne.',
    description: 'La Gare d\'Austerlitz est situee dans le 13e le long de la Seine, desservant le centre et le sud-ouest de la France : Orleans, Tours, Limoges, Toulouse. Elle gere aussi les trains de nuit vers l\'Espagne et le Portugal. En cours de renovation, la navigation peut etre confuse. Notre transfert vous attend Boulevard de l\'Hopital.',
    description2: 'Pendant les travaux, les sorties changent. Votre chauffeur reste en contact et s\'adapte a la sortie en vigueur.',
    description3: 'Porte d\'entree vers les Chateaux de la Loire. Prix fixes des 25 EUR.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Gare d\'Austerlitz ?',
    feature1Title: 'Suivi Train', feature1Desc: 'Surveillance de votre train.',
    feature2Title: 'Point Flexible', feature2Desc: 'Le chauffeur s\'adapte aux changements de sortie.',
    feature3Title: 'Prix Fixes', feature3Desc: 'Pas de frais caches.',
    feature4Title: 'Vehicules Premium', feature4Desc: 'Mercedes E, S, V-Class.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S',
    minivan: 'Monospace', minivanDesc: 'Mercedes Classe V', minibus: 'Minibus', minibusDesc: 'Jusqu\'a 8',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris', vehiclesTitle: 'Choisissez',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez', step1Desc: 'Austerlitz.',
    step2: 'Rencontrez', step2Desc: 'Pancarte a la sortie.', step3: 'Transfert', step3Desc: 'Trajet confortable.',
    popularRoutesTitle: 'Transferts Gare d\'Austerlitz', fromLabel: 'A partir de',
    routes: [{ name: 'Austerlitz vers Hotel', price: 25 }, { name: 'Austerlitz vers CDG', price: 65 }, { name: 'Austerlitz vers Orly', price: 45 }],
    bookingForm: 'Reservez Transfert Austerlitz',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Gare d\'Austerlitz, Paris', otherCitiesTitle: 'Toutes les gares', otherCitiesBtn: 'Toutes les Gares',
    rating: '4.5/5 Tripadvisor (29 avis)',
    meetDriverTitle: 'Ou retrouver votre chauffeur a la Gare d\'Austerlitz',
    meetDriverText: 'Apres l\'arrivee de votre train, suivez les panneaux vers la sortie principale Boulevard de l\'Hopital. Votre chauffeur vous attend dehors avec une pancarte a votre nom. En raison des travaux de renovation, les sorties peuvent varier — votre chauffeur reste en contact par telephone pour assurer une prise en charge fluide.',
  },
  ru: {
    title: 'Трансфер Гар д\'Остерлиц', subtitle: 'Премиум трансфер.',
    description: 'Гар д\'Остерлиц — поезда в Орлеан, Тулузу, ночные в Испанию. Водитель у выхода.',
    description2: 'Из-за ремонта выходы меняются. Водитель на связи.',
    whyChoose: 'Почему?', feature1Title: 'Мониторинг', feature1Desc: '.', feature2Title: 'Гибкая встреча', feature2Desc: 'Водитель адаптируется.',
    feature3Title: 'Фикс.', feature3Desc: 'От 25.', feature4Title: 'Премиум', feature4Desc: 'Mercedes.',
    sedan: 'Седан', sedanDesc: 'E-Class', luxury: 'Люкс', luxuryDesc: 'S-Class', minivan: 'Минивэн', minivanDesc: 'V-Class', minibus: 'Микроавтобус', minibusDesc: '8',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Включено', vehiclesTitle: 'Авто', howItWorks: 'Как',
    step1: 'Бронируйте', step1Desc: '.', step2: 'Встреча', step2Desc: '.', step3: 'Трансфер', step3Desc: '.',
    popularRoutesTitle: 'Популярные', fromLabel: 'От', routes: [{ name: 'Остерлиц → Отель', price: 25 }],
    bookingForm: 'Забронируйте', pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: '', otherCitiesTitle: 'Все', otherCitiesBtn: 'Все', rating: '4.5/5 Tripadvisor',
    meetDriverTitle: 'Где встретить на Остерлиц', meetDriverText: 'Водитель у Boulevard de l\'Hopital с табличкой.',
  },
  hy: {
    title: 'Austerlitz delays', subtitle: 'Delays', description: 'Delays.',
    whyChoose: 'Delays', feature1Title: 'Delays', feature1Desc: '.', feature2Title: 'Delays', feature2Desc: '.',
    feature3Title: 'Delays', feature3Desc: '.', feature4Title: 'Delays', feature4Desc: '.',
    sedan: 'Delays', sedanDesc: '.', luxury: 'Delays', luxuryDesc: '.', minivan: 'Delays', minivanDesc: '.', minibus: 'Delays', minibusDesc: '.',
    passengers: 'Delays', luggage: 'Delays', bookNow: 'Delays', allInclusive: 'Delays', vehiclesTitle: 'Delays', howItWorks: 'Delays',
    step1: 'Delays', step1Desc: '.', step2: 'Delays', step2Desc: '.', step3: 'Delays', step3Desc: '.',
    popularRoutesTitle: 'Delays', fromLabel: 'Delays', bookingForm: 'Delays', pickupLabel: 'Delays', dropoffLabel: 'Delays', dateLabel: 'Delays', timeLabel: 'Delays',
    defaultPickup: '', otherCitiesTitle: 'Delays', otherCitiesBtn: 'Delays', rating: '4.5/5 Tripadvisor',
    meetDriverTitle: 'Delays Austerlitz', meetDriverText: 'Delays.',
  },
};

const vehiclesPrices = { sedan: 25, luxury: 45, minivan: 60, minibus: 90 };
const seoUrls = { en: '/gare-austerlitz-transfer', fr: '/transfert-gare-austerlitz', ru: '/transfer-gar-osterlits', hy: '/gar-osterlits-transfer' };
const GareAusterlitzTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} meetDriverImage="/images/gare-austerlitz-driver.webp" pageId="gare-est" />;
export default GareAusterlitzTransfer;
