import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Gare Montparnasse Transfer - Private Driver in Paris',
    subtitle: 'Premium private chauffeur to and from Gare Montparnasse. TGV arrivals from Bordeaux, Nantes, Rennes, and Brittany.',
    description: 'Gare Montparnasse is the departure and arrival point for TGV trains to southwestern France: Bordeaux, Nantes, Rennes, La Rochelle, and the entire Brittany coast. Located in the 15th arrondissement, the station is a modern complex with multiple levels that can be confusing to navigate with heavy luggage. Our private transfer meets you at the main exit on Place Raoul Dautry and drives you directly to your hotel, apartment, or Paris airport.',
    description2: 'The area around Montparnasse is a busy commercial district. Taxi queues can be long, especially on Friday evenings when TGVs from Bordeaux arrive packed. Our pre-booked chauffeur waits specifically for you — no queuing, no searching.',
    description3: 'Popular with business travellers commuting between Paris and Bordeaux (2h15 by TGV). Book a morning pickup from your hotel for the 7:00 departure and an evening return transfer. Fixed prices, reliable service.',
    whyChoose: 'Why Choose Our Gare Montparnasse Transfer?',
    feature1Title: 'TGV Monitoring', feature1Desc: 'We track your train. Driver adjusts to delays.',
    feature2Title: 'Main Exit Meet', feature2Desc: 'Driver waits at Place Raoul Dautry exit with name sign.',
    feature3Title: 'Fixed Prices', feature3Desc: 'No surge. Price confirmed at booking.',
    feature4Title: 'Premium Vehicles', feature4Desc: 'Mercedes E, S, V-Class.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class or similar',
    minivan: 'Minivan', minivanDesc: 'Mercedes V-Class, up to 6 passengers', minibus: 'Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Select Gare Montparnasse and destination.',
    step2: 'Meet Your Driver', step2Desc: 'Driver at the exit with your name.', step3: 'Direct Transfer', step3Desc: 'Comfortable ride.',
    popularRoutesTitle: 'Popular Gare Montparnasse Transfers', fromLabel: 'From',
    routes: [
      { name: 'Gare Montparnasse to Paris Hotel', price: 25 },
      { name: 'Gare Montparnasse to CDG Airport', price: 70 },
      { name: 'Gare Montparnasse to Orly Airport', price: 40 },
    ],
    bookingForm: 'Book Your Gare Montparnasse Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Gare Montparnasse, Paris',
    otherCitiesTitle: 'Also available from all Paris stations', otherCitiesBtn: 'View All Stations',
    rating: '4.5/5 Tripadvisor (29 reviews)',
    meetDriverTitle: 'Where to Meet Your Driver at Gare Montparnasse',
    meetDriverText: 'After your TGV arrives, follow the signs to the main exit at Place Raoul Dautry. Your chauffeur will be waiting right outside, holding a sign with your name. He will assist with your luggage and escort you to your vehicle parked nearby. Simple, efficient, and stress-free.',
  },
  fr: {
    title: 'Transfert Gare Montparnasse - Chauffeur Prive a Paris',
    subtitle: 'Chauffeur prive premium depuis et vers Gare Montparnasse. TGV de Bordeaux, Nantes, Rennes et Bretagne.',
    description: 'La Gare Montparnasse est le point de depart et d\'arrivee des TGV vers le sud-ouest : Bordeaux, Nantes, Rennes, La Rochelle et toute la cote bretonne. Situee dans le 15e, la gare est un complexe moderne a plusieurs niveaux. Notre transfert prive vous attend a la sortie principale Place Raoul Dautry.',
    description2: 'Les files de taxis peuvent etre longues, surtout le vendredi soir. Notre chauffeur pre-reserve vous attend specifiquement.',
    description3: 'Populaire aupres des voyageurs d\'affaires Paris-Bordeaux (2h15 en TGV). Prix fixes.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Gare Montparnasse ?',
    feature1Title: 'Suivi TGV', feature1Desc: 'Surveillance de votre train.',
    feature2Title: 'Accueil Sortie', feature2Desc: 'Chauffeur Place Raoul Dautry avec pancarte.',
    feature3Title: 'Prix Fixes', feature3Desc: 'Pas de frais caches.',
    feature4Title: 'Vehicules Premium', feature4Desc: 'Mercedes E, S, V-Class.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E, 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S',
    minivan: 'Monospace', minivanDesc: 'Mercedes Classe V, jusqu\'a 6', minibus: 'Minibus', minibusDesc: 'Jusqu\'a 8',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez', step1Desc: 'Selectionnez Montparnasse.',
    step2: 'Rencontrez', step2Desc: 'Chauffeur a la sortie.', step3: 'Transfert', step3Desc: 'Trajet confortable.',
    popularRoutesTitle: 'Transferts Gare Montparnasse', fromLabel: 'A partir de',
    routes: [
      { name: 'Montparnasse vers Hotel Paris', price: 25 },
      { name: 'Montparnasse vers Aeroport CDG', price: 70 },
      { name: 'Montparnasse vers Aeroport Orly', price: 40 },
    ],
    bookingForm: 'Reservez Votre Transfert Montparnasse',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Gare Montparnasse, Paris',
    otherCitiesTitle: 'Toutes les gares de Paris', otherCitiesBtn: 'Toutes les Gares',
    rating: '4.5/5 Tripadvisor (29 avis)',
    meetDriverTitle: 'Ou retrouver votre chauffeur a Gare Montparnasse',
    meetDriverText: 'Apres l\'arrivee de votre TGV, suivez les panneaux vers la sortie principale Place Raoul Dautry. Votre chauffeur vous attend juste dehors avec une pancarte a votre nom. Il prend vos bagages et vous accompagne a votre vehicule. Simple, efficace et sans stress.',
  },
  ru: {
    title: 'Трансфер Гар Монпарнас', subtitle: 'Премиум трансфер.',
    description: 'Гар-Монпарнас — TGV в Бордо, Нант, Ренн. Водитель у выхода с табличкой.',
    description2: 'Такси — длинные очереди. Наш сервис — без ожидания.', description3: 'Фикс. цены.',
    whyChoose: 'Почему?', feature1Title: 'Мониторинг', feature1Desc: 'Отслеживание поезда.',
    feature2Title: 'Встреча', feature2Desc: 'Табличка у выхода.', feature3Title: 'Фикс.', feature3Desc: 'От 25 EUR.',
    feature4Title: 'Премиум', feature4Desc: 'Mercedes.',
    sedan: 'Седан', sedanDesc: 'E-Class', luxury: 'Люкс', luxuryDesc: 'S-Class', minivan: 'Минивэн', minivanDesc: 'V-Class', minibus: 'Микроавтобус', minibusDesc: 'До 8',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Включено', vehiclesTitle: 'Авто', howItWorks: 'Как',
    step1: 'Бронируйте', step1Desc: '.', step2: 'Встреча', step2Desc: '.', step3: 'Трансфер', step3Desc: '.',
    popularRoutesTitle: 'Популярные', fromLabel: 'От', routes: [{ name: 'Монпарнас → Отель', price: 25 }],
    bookingForm: 'Забронируйте', pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: '', otherCitiesTitle: 'Все', otherCitiesBtn: 'Все', rating: '4.5/5 Tripadvisor',
    meetDriverTitle: 'Где встретить водителя на Монпарнас', meetDriverText: 'Водитель ждёт у выхода Place Raoul Dautry с табличкой.',
  },
  hy: {
    title: 'Montparnasse delays', subtitle: 'Delays', description: 'Delays.',
    whyChoose: 'Delays', feature1Title: 'Delays', feature1Desc: 'Delays', feature2Title: 'Delays', feature2Desc: 'Delays',
    feature3Title: 'Delays', feature3Desc: 'Delays', feature4Title: 'Delays', feature4Desc: 'Delays',
    sedan: 'Delays', sedanDesc: 'Delays', luxury: 'Delays', luxuryDesc: 'Delays', minivan: 'Delays', minivanDesc: 'Delays', minibus: 'Delays', minibusDesc: 'Delays',
    passengers: 'Delays', luggage: 'Delays', bookNow: 'Delays', allInclusive: 'Delays', vehiclesTitle: 'Delays', howItWorks: 'Delays',
    step1: 'Delays', step1Desc: '.', step2: 'Delays', step2Desc: '.', step3: 'Delays', step3Desc: '.',
    popularRoutesTitle: 'Delays', fromLabel: 'Delays', bookingForm: 'Delays', pickupLabel: 'Delays', dropoffLabel: 'Delays', dateLabel: 'Delays', timeLabel: 'Delays',
    defaultPickup: '', otherCitiesTitle: 'Delays', otherCitiesBtn: 'Delays', rating: '4.5/5 Tripadvisor',
    meetDriverTitle: 'Delays Montparnasse', meetDriverText: 'Delays.',
  },
};

const vehiclesPrices = { sedan: 25, luxury: 45, minivan: 60, minibus: 90 };
const seoUrls = { en: '/gare-montparnasse-transfer', fr: '/transfert-gare-montparnasse', ru: '/transfer-gar-monparnas', hy: '/gar-monparnas-transfer' };
const GareMontparnasseTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} meetDriverImage="/images/gare-montparnasse-driver.webp" />;
export default GareMontparnasseTransfer;
