import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Milan Airport Transfer - Malpensa, Linate & Bergamo',
    subtitle: 'Private driver service from Milan airports to city center, Duomo area, fashion district and all Milan hotels',
    description: 'Book your Milan airport transfer with professional drivers. Milan has three airports: Malpensa (MXP) at 50 km, the main international hub; Linate (LIN) at 7 km, ideal for domestic and European flights; and Bergamo Orio al Serio (BGY) at 45 km, popular with low-cost carriers. We provide premium private transfers from all three airports to Milan city center, Duomo, Quadrilatero della Moda, Porta Nuova, Fiera Milano, and any destination in Lombardy.',
    description2: 'Milan is Italy\'s fashion and business capital. From the stunning Duomo to the Last Supper, from designer boutiques to world-class restaurants, our professional drivers ensure you arrive refreshed and on time.',
    whyChoose: 'Why Choose Our Milan Airport Transfer?',
    feature1Title: 'Meet & Greet', feature1Desc: 'Driver with name sign at arrivals of MXP, LIN, or BGY. 60 min free waiting.',
    feature2Title: 'All 3 Airports', feature2Desc: 'We serve Malpensa, Linate and Bergamo. Flight tracking included.',
    feature3Title: 'Italian Elegance', feature3Desc: 'Premium vehicles worthy of Milan. Clean, air-conditioned, recent models.',
    feature4Title: 'Fixed Prices', feature4Desc: 'Price confirmed at booking. No surge pricing, tolls included.',
    sedan: 'Premium Sedan', sedanDesc: '1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes E-Class or similar',
    minivan: 'Minivan', minivanDesc: 'Up to 6 passengers', minibus: 'Minibus', minibusDesc: 'Up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter your flight and Milan address. Instant confirmation.',
    step2: 'Meet at Airport', step2Desc: 'Driver waits with name sign at your arrival airport.',
    step3: 'Arrive in Style', step3Desc: 'Direct comfortable transfer to central Milan.',
    popularRoutesTitle: 'Popular Milan Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'Malpensa MXP → Milan City Center', price: 70 },
      { name: 'Linate LIN → Milan Duomo', price: 35 },
      { name: 'Bergamo BGY → Milan City Center', price: 75 },
      { name: 'Malpensa MXP → Lake Como', price: 120 },
    ],
    bookingForm: 'Book Your Milan Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Milan Malpensa Airport (MXP)',
    otherCitiesTitle: 'We serve other European cities too', otherCitiesBtn: 'View All Destinations',
    rating: '4.8/5 (1,650+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Milan - Malpensa, Linate et Bergame',
    subtitle: 'Chauffeur prive depuis les aeroports de Milan vers le centre-ville, le Duomo et le quartier de la mode',
    description: 'Reservez votre transfert aeroport Milan avec des chauffeurs professionnels. Milan dispose de trois aeroports : Malpensa (MXP) a 50 km, le hub international principal ; Linate (LIN) a 7 km, ideal pour les vols domestiques ; et Bergame Orio al Serio (BGY) a 45 km, populaire pour les compagnies low-cost. Transferts prives premium depuis les trois aeroports vers le centre de Milan, le Duomo, le Quadrilatero della Moda, Porta Nuova et la Fiera Milano.',
    description2: 'Milan est la capitale italienne de la mode et des affaires. Du Duomo sublime a la Cene de Leonard de Vinci, nos chauffeurs vous conduisent avec elegance.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Milan ?',
    feature1Title: 'Accueil Personnalise', feature1Desc: 'Chauffeur avec pancarte aux arrivees MXP, LIN ou BGY. 60 min gratuites.',
    feature2Title: '3 Aeroports Desservis', feature2Desc: 'Malpensa, Linate et Bergame. Suivi de vol inclus.',
    feature3Title: 'Elegance Italienne', feature3Desc: 'Vehicules premium dignes de Milan. Propres, climatises.',
    feature4Title: 'Prix Fixes', feature4Desc: 'Prix confirme. Pas de supplement, peages inclus.',
    sedan: 'Berline Premium', sedanDesc: '1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe E ou similaire',
    minivan: 'Monospace', minivanDesc: 'Jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez vol et adresse a Milan.',
    step2: 'Rendez-vous a l\'Aeroport', step2Desc: 'Chauffeur avec pancarte a votre aeroport.',
    step3: 'Arrivez avec Style', step3Desc: 'Transfert direct vers le centre de Milan.',
    popularRoutesTitle: 'Trajets Populaires Transfert Milan', fromLabel: 'A partir de',
    routes: [
      { name: 'Malpensa MXP → Centre de Milan', price: 70 },
      { name: 'Linate LIN → Duomo Milan', price: 35 },
      { name: 'Bergame BGY → Centre de Milan', price: 75 },
      { name: 'Malpensa MXP → Lac de Come', price: 120 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Milan',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Milan Malpensa (MXP)',
    otherCitiesTitle: 'Nous desservons d\'autres villes europeennes', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.8/5 (1 650+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Милана - Мальпенса, Линате и Бергамо',
    subtitle: 'Частный водитель из аэропортов Милана в центр города, Дуомо и модный квартал',
    description: 'Забронируйте трансфер из аэропорта Милана. Три аэропорта: Мальпенса (MXP) - 50 км, Линате (LIN) - 7 км, Бергамо (BGY) - 45 км. Премиум-трансферы в центр Милана, Дуомо, Квадрилатеро делла Мода и все направления Ломбардии.',
    description2: 'Милан - столица итальянской моды и бизнеса. Наши водители доставят вас с элегантностью.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Милана?',
    feature1Title: 'Встреча', feature1Desc: 'Водитель с табличкой в MXP, LIN или BGY. 60 минут бесплатно.',
    feature2Title: '3 Аэропорта', feature2Desc: 'Мальпенса, Линате и Бергамо. Отслеживание рейсов.',
    feature3Title: 'Итальянская Элегантность', feature3Desc: 'Премиум автомобили, достойные Милана.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Без скрытых платежей, дороги включены.',
    sedan: 'Премиум Седан', sedanDesc: '1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes E-Class',
    minivan: 'Минивэн', minivanDesc: 'До 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте', step1Desc: 'Введите рейс и адрес в Милане.',
    step2: 'Встреча', step2Desc: 'Водитель в аэропорту.',
    step3: 'Прибытие', step3Desc: 'Прямой трансфер в центр Милана.',
    popularRoutesTitle: 'Популярные Маршруты из Аэропорта Милана', fromLabel: 'От',
    routes: [
      { name: 'Мальпенса MXP → Центр Милана', price: 70 },
      { name: 'Линате LIN → Дуомо', price: 35 },
      { name: 'Бергамо BGY → Центр Милана', price: 75 },
      { name: 'Мальпенса MXP → Озеро Комо', price: 120 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Милана',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Милан Мальпенса (MXP)',
    otherCitiesTitle: 'Другие города', otherCitiesBtn: 'Все Направления',
    rating: '4.8/5 (1 650+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 70, luxury: 95, minivan: 130, minibus: 190 };

const seoUrls = { en: '/milan-airport-transfer', fr: '/transfert-aeroport-milan', ru: '/taksi-iz-aeroporta-milan' };
const MilanTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default MilanTransfer;
