import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Milan Airport Transfer - Malpensa, Linate & Bergamo',
    subtitle: 'Private driver service from Milan airports to city center, Duomo area, fashion district and all Milan hotels',
    description: 'Milan is where Italian elegance meets global commerce. The city of Leonardo da Vinci\'s Last Supper, the Gothic marvel of the Duomo, and the Quadrilatero della Moda — the four-block fashion district that hosts Prada, Versace, Armani, and Dolce & Gabbana\'s flagship stores — is served by three airports spread across Lombardy. Malpensa (MXP), the main international hub, sits 50 kilometres northwest amid the lakes of Varese. Linate (LIN), the compact city airport, is just 7 kilometres from the Duomo — but its limited connections mean most intercontinental travelers still arrive at Malpensa. Bergamo Orio al Serio (BGY), the Ryanair and easyJet base, lies 45 kilometres northeast. Our private Milan airport transfer covers all three airports, delivering you to your hotel, office, or fashion showroom in Porta Nuova, Brera, Navigli, or the Fiera Milano exhibition complex.',
    description2: 'The Malpensa Express train takes 52 minutes to Milano Centrale station and runs only twice an hour — fine if your hotel happens to be at the station, problematic if it is anywhere else. A taxi from Malpensa charges a flat 105 euros to the city centre with minimal luggage handling. Our premium transfer offers the same journey in 45 to 60 minutes, door to door, with your driver waiting at arrivals and your bags carried to the car. From Linate, the ride to the Duomo takes just 15 minutes; from Bergamo, expect 50 to 70 minutes along the A4 motorway through the industrial heartland of Lombardy.',
    description3: 'Milan is much more than fashion weeks and trade fairs. The city is a gateway to the Italian Lake District — Como (50 minutes north), Maggiore (70 minutes), and Garda (90 minutes east) — where George Clooney, Richard Branson, and generations of European aristocracy have maintained lakeside villas. Many of our clients land at Malpensa and ask to be driven directly to their villa on Lake Como, skipping Milan entirely. Others use our service during Salone del Mobile (the world\'s largest furniture fair), Milan Fashion Week, or Serie A matches at the legendary San Siro stadium. Whatever brings you to Milan, start your Italian experience in the back seat of a Mercedes, not in a crowded regional train.',
    whyChoose: 'Why Choose Our Milan Airport Transfer?',
    feature1Title: 'Meet & Greet', feature1Desc: 'Driver with name sign at arrivals of MXP, LIN, or BGY. 60 min free waiting.',
    feature2Title: 'All 3 Airports', feature2Desc: 'We serve Malpensa, Linate and Bergamo. Flight tracking included.',
    feature3Title: 'Italian Elegance', feature3Desc: 'Premium vehicles worthy of Milan. Clean, air-conditioned, recent models.',
    feature4Title: 'Fixed Prices', feature4Desc: 'Price confirmed at booking. No surge pricing, tolls included.',
    sedan: 'Premium Sedan', sedanDesc: '1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes E-Class or similar',
    minivan: 'Minivan', minivanDesc: 'Up to 6 passengers', minibus: 'Minibus', minibusDesc: 'Up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter your flight and Milan address. Instant confirmation.',
    step2: 'Meet at Airport', step2Desc: 'Driver waits with name sign at your arrival airport.',
    step3: 'Arrive in Style', step3Desc: 'Direct comfortable transfer to central Milan.',
    popularRoutesTitle: 'Popular Milan Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'Malpensa MXP → Milan City Center', price: 70 },
      { name: 'Linate LIN → Milan Duomo', price: 35 },
      { name: 'Bergamo BGY → Milan City Center', price: 75 },
      { name: 'Malpensa MXP → Lake Como', price: 120 },
    ],
    bookingForm: 'Book Your Milan Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Milan Malpensa Airport (MXP)',
    otherCitiesTitle: 'We serve other European cities too', otherCitiesBtn: 'View All Destinations',
    rating: '4.8/5 (1,650+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Milan - Malpensa, Linate et Bergame',
    subtitle: 'Chauffeur prive depuis les aeroports de Milan vers le centre-ville, le Duomo et le quartier de la mode',
    description: 'Reservez votre transfert aeroport Milan avec des chauffeurs professionnels. Milan dispose de trois aeroports : Malpensa (MXP) a 50 km, le hub international principal ; Linate (LIN) a 7 km, ideal pour les vols domestiques ; et Bergame Orio al Serio (BGY) a 45 km, populaire pour les compagnies low-cost. Transferts prives premium depuis les trois aeroports vers le centre de Milan, le Duomo, le Quadrilatero della Moda, Porta Nuova et la Fiera Milano.',
    description2: 'Milan, la ou l\'elegance italienne rencontre le commerce mondial : la Cene de Leonard, le Duomo gothique, le Quadrilatero della Moda avec Prada, Versace et Armani. Trois aeroports : Malpensa (50 km), Linate (7 km) et Bergame (45 km). Le Malpensa Express met 52 minutes et ne part que deux fois par heure. Notre transfert premium fait le meme trajet en 45-60 min, porte a porte. Milan est aussi la porte du lac de Come (50 min), Maggiore (70 min) et Garde (90 min). Beaucoup de clients atterrissent a Malpensa et filent directement vers leur villa sur le lac de Come.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Milan ?',
    feature1Title: 'Accueil Personnalise', feature1Desc: 'Chauffeur avec pancarte aux arrivees MXP, LIN ou BGY. 60 min gratuites.',
    feature2Title: '3 Aeroports Desservis', feature2Desc: 'Malpensa, Linate et Bergame. Suivi de vol inclus.',
    feature3Title: 'Elegance Italienne', feature3Desc: 'Vehicules premium dignes de Milan. Propres, climatises.',
    feature4Title: 'Prix Fixes', feature4Desc: 'Prix confirme. Pas de supplement, peages inclus.',
    sedan: 'Berline Premium', sedanDesc: '1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe E ou similaire',
    minivan: 'Monospace', minivanDesc: 'Jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez vol et adresse a Milan.',
    step2: 'Rendez-vous a l\'Aeroport', step2Desc: 'Chauffeur avec pancarte a votre aeroport.',
    step3: 'Arrivez avec Style', step3Desc: 'Transfert direct vers le centre de Milan.',
    popularRoutesTitle: 'Trajets Populaires Transfert Milan', fromLabel: 'A partir de',
    routes: [
      { name: 'Malpensa MXP → Centre de Milan', price: 70 },
      { name: 'Linate LIN → Duomo Milan', price: 35 },
      { name: 'Bergame BGY → Centre de Milan', price: 75 },
      { name: 'Malpensa MXP → Lac de Come', price: 120 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Milan',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Milan Malpensa (MXP)',
    otherCitiesTitle: 'Nous desservons d\'autres villes europeennes', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.8/5 (1 650+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Милана - Мальпенса, Линате и Бергамо',
    subtitle: 'Частный водитель из аэропортов Милана в центр города, Дуомо и модный квартал',
    description: 'Милан — где итальянская элегантность встречает мировую коммерцию. Город Тайной вечери Леонардо, готического чуда Дуомо и модного квартала Quadrilatero обслуживается тремя аэропортами: Мальпенса (50 км), Линате (7 км) и Бергамо (45 км). Malpensa Express идёт 52 минуты и ходит дважды в час. Наш премиальный трансфер делает тот же путь за 45-60 мин, от двери до двери.',
    description2: 'Милан — ворота к итальянским озёрам: Комо (50 мин), Маджоре (70 мин), Гарда (90 мин), где Джордж Клуни и европейская аристократия держат виллы. Многие клиенты летят в Мальпенсу и едут прямо к вилле на озере Комо. Другие пользуются нашим сервисом во время Salone del Mobile, Недели моды или матчей Серии А на легендарном «Сан-Сиро». Начните итальянский опыт в Mercedes, а не в переполненной электричке.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Милана?',
    feature1Title: 'Встреча', feature1Desc: 'Водитель с табличкой в MXP, LIN или BGY. 60 минут бесплатно.',
    feature2Title: '3 Аэропорта', feature2Desc: 'Мальпенса, Линате и Бергамо. Отслеживание рейсов.',
    feature3Title: 'Итальянская Элегантность', feature3Desc: 'Премиум автомобили, достойные Милана.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Без скрытых платежей, дороги включены.',
    sedan: 'Премиум Седан', sedanDesc: '1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes E-Class',
    minivan: 'Минивэн', minivanDesc: 'До 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте', step1Desc: 'Введите рейс и адрес в Милане.',
    step2: 'Встреча', step2Desc: 'Водитель в аэропорту.',
    step3: 'Прибытие', step3Desc: 'Прямой трансфер в центр Милана.',
    popularRoutesTitle: 'Популярные Маршруты из Аэропорта Милана', fromLabel: 'От',
    routes: [
      { name: 'Мальпенса MXP → Центр Милана', price: 70 },
      { name: 'Линате LIN → Дуомо', price: 35 },
      { name: 'Бергамо BGY → Центр Милана', price: 75 },
      { name: 'Мальпенса MXP → Озеро Комо', price: 120 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Милана',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Милан Мальпенса (MXP)',
    otherCitiesTitle: 'Другие города', otherCitiesBtn: 'Все Направления',
    rating: '4.8/5 (1 650+ отзывов)',
  },
  hy: {
    title: 'Տրանսֆեր Միլանի օդանավայանից',
    subtitle: 'Մասնավոր վարորդ Malpensa, Linate և Bergamo',
    description: 'Միլանը իտալական նրբագեղության և առևտրի մայրաքաղաքն է: Da Vinci-ի Վերջին ընթրիքը՝ Duomo-ն՝ Quadrilatero della Moda: 3 օդանավայան՝ Malpensa (50 կմ)՝ Linate (7 կմ)՝ Bergamo (45 կմ): Como լիճը 50 րոպե՝ Maggiore 70՝ Garda 90: Salone del Mobile՝ նորաձևի շաբաթ՝ San Siro:',
    description2: 'Իտալական լճերի դարպասը:',
    whyChoose: 'Ինչու ընտրել մեր տրանսֆեր միլանի օդանավայանից',
    feature1Title: 'Դիմավորում', feature1Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով: 60 րոպե անվճար սպասման ժամանակ:',
    feature2Title: 'Թռիչքի հետևում', feature2Desc: 'Իրական ժամանակում թռիչքի հետևում: Անվճար:',
    feature3Title: 'Պրեմիում մեքենաներ', feature3Desc: 'Mercedes E-Class, BMW 5: Մաքուր, կլիմատիզացիա:',
    feature4Title: 'Ֆիքս գներ', feature4Desc: 'Գինը հաստատված է ամրագրման ժամանակ: Թաքնված վճարներ չկան:',
    sedan: 'Պրեմիում սեդան', sedanDesc: 'Mercedes E-Class, 1-3 ուղևոր',
    luxury: 'Լյուքս սեդան', luxuryDesc: 'Mercedes S-Class կամ BMW 7',
    minivan: 'Մինիվեն', minivanDesc: 'Mercedes V-Class, մինչև 6 ուղևոր',
    minibus: 'Մինիբուս', minibusDesc: 'Մինչև 8 ուղևոր',
    passengers: 'Ուղևորներ', luggage: 'Ուղեբարան',
    bookNow: 'ԱՄՏԱԳՏՎԵԼ', allInclusive: 'Ամեն ինչ ներառված է',
    vehiclesTitle: 'Ընտրեք մեքենան',
    howItWorks: 'Ինչպես է աշխատում',
    step1: 'Ամրագրեք օնլայն', step1Desc: 'Մուտքագրեք ձեր տվյալները և հասցեն: Ակնթարթ գնի հաստատում:',
    step2: 'Հանդիպեք վարորդին', step2Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով:',
    step3: 'Հանգստացեք', step3Desc: 'Հարմարավետ ուղևորություն պրեմիում մեքենայում:',
    popularRoutesTitle: 'Սկսած', fromLabel: 'Սկսած',
    bookingForm: 'ԱՄՏԱԳՏՎԵԼ',
    pickupLabel: 'Վերցնում', dropoffLabel: 'Իջնում',
    dateLabel: 'Ամսաթիվ', timeLabel: 'Ժամ',
    defaultPickup: '',
    otherCitiesTitle: 'Սպասարկում ենք 120+ քաղաքներ Եվրոպայում',
    otherCitiesBtn: 'Բոլոր ուղղությունները',
    rating: '4.9/5',
  },
};

const vehiclesPrices = { sedan: 70, luxury: 95, minivan: 130, minibus: 190 };

const seoUrls = { en: '/milan-airport-transfer', fr: '/transfert-aeroport-milan', ru: '/taksi-iz-aeroporta-milan', hy: '/milan-odanavakayani-transfer' };
const MilanTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default MilanTransfer;
