import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Monaco Airport Transfer - Private Car Service',
    subtitle: 'Premium private driver from Nice Airport to Monaco, Monte-Carlo and all Monaco destinations',
    description: 'Book your Monaco airport transfer with professional drivers. Monaco does not have its own airport, so the closest is Nice Cote d\'Azur Airport (NCE), just 30 minutes away. We provide luxury private transfers from Nice Airport directly to your hotel in Monaco, Monte-Carlo, Fontvieille, or La Condamine. Fixed prices, no hidden fees, flight monitoring included.',
    description2: 'Whether you are attending the Monaco Grand Prix, visiting the Casino de Monte-Carlo, or on a luxury vacation, our premium transfer service ensures you arrive in style. All our vehicles are high-end Mercedes or BMW, perfect for the elegance that Monaco demands.',
    whyChoose: 'Why Choose Our Monaco Airport Transfer?',
    feature1Title: 'VIP Meet & Greet', feature1Desc: 'Driver waits at Nice Airport arrivals with your name on a personalized sign. Free 60 min waiting time.',
    feature2Title: 'Flight Monitoring', feature2Desc: 'Real-time tracking of your flight. No surcharge for delays.',
    feature3Title: 'Luxury Fleet', feature3Desc: 'Mercedes S-Class, BMW 7 Series and luxury SUVs. Vehicles worthy of Monaco.',
    feature4Title: 'All-Inclusive Pricing', feature4Desc: 'Fixed price confirmed at booking. Tolls, parking, and taxes included.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class or BMW 7 Series',
    minivan: 'Luxury Minivan', minivanDesc: 'Mercedes V-Class, up to 6 passengers', minibus: 'VIP Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter flight details and your Monaco address. Instant confirmation.',
    step2: 'Meet at Nice Airport', step2Desc: 'Your driver greets you at arrivals and assists with luggage.',
    step3: 'Arrive in Style', step3Desc: 'Direct luxury transfer to Monaco in 25-35 minutes.',
    popularRoutesTitle: 'Popular Monaco Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'Nice Airport → Monte-Carlo', price: 65 },
      { name: 'Nice Airport → Monaco Port Hercules', price: 70 },
      { name: 'Nice Airport → Fontvieille', price: 65 },
      { name: 'Monaco → Cannes', price: 95 },
    ],
    bookingForm: 'Book Your Monaco Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Nice Cote d\'Azur Airport (NCE)',
    otherCitiesTitle: 'We also serve other cities in Europe', otherCitiesBtn: 'View All Destinations',
    rating: '4.9/5 (980+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Monaco - Service Voiture Privee',
    subtitle: 'Chauffeur prive premium depuis l\'aeroport de Nice vers Monaco, Monte-Carlo et toutes destinations monegasques',
    description: 'Reservez votre transfert aeroport Monaco avec des chauffeurs professionnels. Monaco ne possede pas d\'aeroport propre, le plus proche est l\'aeroport Nice Cote d\'Azur (NCE), a seulement 30 minutes. Nous assurons des transferts prives de luxe depuis l\'aeroport de Nice directement vers votre hotel a Monaco, Monte-Carlo, Fontvieille ou La Condamine. Prix fixes, pas de frais caches.',
    description2: 'Que vous assistiez au Grand Prix de Monaco, visitiez le Casino de Monte-Carlo ou soyez en vacances de luxe, notre service de transfert premium vous garantit une arrivee en toute elegance.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Monaco ?',
    feature1Title: 'Accueil VIP', feature1Desc: 'Chauffeur avec pancarte nominative aux arrivees de Nice. 60 min d\'attente gratuites.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Suivi en temps reel de votre vol. Aucun supplement pour retard.',
    feature3Title: 'Flotte de Luxe', feature3Desc: 'Mercedes Classe S, BMW Serie 7 et SUV de luxe. Vehicules dignes de Monaco.',
    feature4Title: 'Prix Tout Compris', feature4Desc: 'Prix fixe confirme a la reservation. Peages, parking et taxes inclus.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E, 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S ou BMW Serie 7',
    minivan: 'Monospace de Luxe', minivanDesc: 'Mercedes Classe V, jusqu\'a 6 passagers', minibus: 'Minibus VIP', minibusDesc: 'Pour groupes jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez les details du vol et votre adresse a Monaco. Confirmation immediate.',
    step2: 'Rendez-vous a l\'Aeroport de Nice', step2Desc: 'Votre chauffeur vous accueille aux arrivees et aide avec les bagages.',
    step3: 'Arrivez avec Style', step3Desc: 'Transfert de luxe direct vers Monaco en 25-35 minutes.',
    popularRoutesTitle: 'Trajets Populaires Transfert Monaco', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport Nice → Monte-Carlo', price: 65 },
      { name: 'Aeroport Nice → Port Hercule Monaco', price: 70 },
      { name: 'Aeroport Nice → Fontvieille', price: 65 },
      { name: 'Monaco → Cannes', price: 95 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Monaco',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Nice Cote d\'Azur (NCE)',
    otherCitiesTitle: 'Nous desservons aussi d\'autres villes en Europe', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.9/5 (980+ avis)',
  },
  ru: {
    title: 'Трансфер в Монако из Аэропорта - Частный Автомобиль',
    subtitle: 'Премиум трансфер из аэропорта Ниццы в Монако, Монте-Карло и все направления Монако',
    description: 'Забронируйте трансфер в Монако с профессиональными водителями. В Монако нет собственного аэропорта, ближайший - Ницца Лазурный Берег (NCE), всего 30 минут езды. Мы обеспечиваем люкс-трансферы из аэропорта Ниццы в ваш отель в Монако, Монте-Карло, Фонвьей или Ла-Кондамин.',
    description2: 'Будь то Гран-При Монако, посещение Казино Монте-Карло или роскошный отдых - наш премиум-сервис гарантирует стильное прибытие.',
    whyChoose: 'Почему Выбрать Наш Трансфер в Монако?',
    feature1Title: 'VIP Встреча', feature1Desc: 'Водитель с именной табличкой в зале прилета Ниццы. 60 минут ожидания бесплатно.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мониторинг рейса в реальном времени. Без доплаты за задержку.',
    feature3Title: 'Люкс Автопарк', feature3Desc: 'Mercedes S-Class, BMW 7 серии и люкс SUV.',
    feature4Title: 'Все Включено', feature4Desc: 'Фиксированная цена. Дороги, парковка и налоги включены.',
    sedan: 'Премиум Седан', sedanDesc: 'Mercedes E-Class, 1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes S-Class или BMW 7 серии',
    minivan: 'Люкс Минивэн', minivanDesc: 'Mercedes V-Class, до 6 пассажиров', minibus: 'VIP Микроавтобус', minibusDesc: 'Для групп до 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Введите данные рейса и адрес в Монако.',
    step2: 'Встреча в Аэропорту Ниццы', step2Desc: 'Водитель встречает вас и помогает с багажом.',
    step3: 'Прибытие со Стилем', step3Desc: 'Прямой люкс-трансфер в Монако за 25-35 минут.',
    popularRoutesTitle: 'Популярные Маршруты Трансфера в Монако', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт Ниццы → Монте-Карло', price: 65 },
      { name: 'Аэропорт Ниццы → Порт Эркюль Монако', price: 70 },
      { name: 'Аэропорт Ниццы → Фонвьей', price: 65 },
      { name: 'Монако → Канны', price: 95 },
    ],
    bookingForm: 'Забронируйте Трансфер в Монако',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Ницца Лазурный Берег (NCE)',
    otherCitiesTitle: 'Мы также обслуживаем другие города Европы', otherCitiesBtn: 'Все Направления',
    rating: '4.9/5 (980+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 65, luxury: 95, minivan: 120, minibus: 180 };

const seoUrls = { en: '/monaco-airport-transfer', fr: '/transfert-aeroport-monaco', ru: '/taksi-iz-aeroporta-monako' };
const MonacoTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default MonacoTransfer;
