import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Monaco Airport Transfer - Private Car Service',
    subtitle: 'Premium private driver from Nice Airport to Monaco, Monte-Carlo and all Monaco destinations',
    description: 'Monaco is the second smallest country in the world, yet it concentrates more wealth, prestige and spectacle per square metre than anywhere on Earth. From the legendary Casino de Monte-Carlo to the hairpin turns of the Formula 1 Grand Prix circuit, from the Prince\'s Palace perched above the harbour to the yacht-lined Port Hercules, every corner of this 2-square-kilometre principality radiates exclusivity. Since Monaco has no airport of its own, virtually every visitor arrives via Nice Cote d\'Azur Airport (NCE), just 22 kilometres and 25 to 35 minutes along the spectacular coastal roads. Our premium Monaco transfer meets you at Nice Airport arrivals and whisks you straight to your Monte-Carlo hotel, your business meeting in Fontvieille, or your yacht in Port Hercules.',
    description2: 'The drive from Nice Airport to Monaco is itself an experience. Depending on the route your driver chooses, you may glide along the seafront Basse Corniche through Villefranche-sur-Mer and Cap-Ferrat — two of the most expensive postcodes on the Riviera — or take the breathtaking Moyenne Corniche that inspired Alfred Hitchcock\'s "To Catch a Thief," with sweeping panoramas of the turquoise Mediterranean far below. Arriving by private car allows you to enjoy this scenery in comfort, with a chilled water bottle and a driver who knows exactly which hotel entrance, underground car park, or marina gate to deliver you to.',
    description3: 'Whether you are attending the Monaco Grand Prix in May, the Monte-Carlo Rally in January, the Monaco Yacht Show in September, or simply visiting for a weekend of fine dining at Alain Ducasse\'s Louis XV, the right arrival sets the tone. Our fleet includes luxury sedans and S-Class Mercedes that match Monaco\'s standards. Many clients also book our service for day trips from Monaco to the medieval village of Eze, the perfume workshops of Grasse, or the art galleries of Saint-Paul-de-Vence. And when your stay ends, the same reliable driver takes you back to Nice Airport with time to spare. Reserve your Monaco transfer today.',
    whyChoose: 'Why Choose Our Monaco Airport Transfer?',
    feature1Title: 'VIP Meet & Greet', feature1Desc: 'Driver waits at Nice Airport arrivals with your name on a personalized sign. Free 60 min waiting time.',
    feature2Title: 'Flight Monitoring', feature2Desc: 'Real-time tracking of your flight. No surcharge for delays.',
    feature3Title: 'Luxury Fleet', feature3Desc: 'Mercedes S-Class, BMW 7 Series and luxury SUVs. Vehicles worthy of Monaco.',
    feature4Title: 'All-Inclusive Pricing', feature4Desc: 'Fixed price confirmed at booking. Tolls, parking, and taxes included.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class or BMW 7 Series',
    minivan: 'Luxury Minivan', minivanDesc: 'Mercedes V-Class, up to 6 passengers', minibus: 'VIP Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter flight details and your Monaco address. Instant confirmation.',
    step2: 'Meet at Nice Airport', step2Desc: 'Your driver greets you at arrivals and assists with luggage.',
    step3: 'Arrive in Style', step3Desc: 'Direct luxury transfer to Monaco in 25-35 minutes.',
    popularRoutesTitle: 'Popular Monaco Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'Nice Airport → Monte-Carlo', price: 65 },
      { name: 'Nice Airport → Monaco Port Hercules', price: 70 },
      { name: 'Nice Airport → Fontvieille', price: 65 },
      { name: 'Monaco → Cannes', price: 95 },
    ],
    bookingForm: 'Book Your Monaco Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Nice Cote d\'Azur Airport (NCE)',
    otherCitiesTitle: 'We also serve other cities in Europe', otherCitiesBtn: 'View All Destinations',
    rating: '4.9/5 (980+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Monaco - Service Voiture Privee',
    subtitle: 'Chauffeur prive premium depuis l\'aeroport de Nice vers Monaco, Monte-Carlo et toutes destinations monegasques',
    description: 'Monaco est le deuxieme plus petit pays du monde, mais concentre plus de richesse et de prestige au metre carre que n\'importe ou sur Terre. Du Casino de Monte-Carlo aux virages en epingle du circuit de Formule 1, du Palais Princier aux yachts de Port Hercule, chaque recoin de cette principaute de 2 km2 respire l\'exclusivite. Monaco ne possedant pas d\'aeroport, la quasi-totalite des visiteurs arrivent via Nice Cote d\'Azur (NCE), a 22 km et 25 a 35 minutes par les routes cotieres spectaculaires. Notre transfert premium vous accueille aux arrivees de Nice et vous conduit directement a votre hotel a Monte-Carlo, votre reunion a Fontvieille, ou votre yacht au Port Hercule.',
    description2: 'Le trajet de Nice a Monaco est en lui-meme une experience. Selon l\'itineraire, vous longerez la Basse Corniche a travers Villefranche-sur-Mer et le Cap-Ferrat, ou emprunterez la Moyenne Corniche qui a inspire Hitchcock, avec des panoramas grandioses sur la Mediterranee turquoise. Arriver en voiture privee vous permet de profiter du paysage avec confort, bouteille d\'eau fraiche et chauffeur connaissant chaque entree d\'hotel et porte de marina.',
    description3: 'Que vous assistiez au Grand Prix de Monaco en mai, au Rallye Monte-Carlo en janvier, au Yacht Show en septembre ou veniez pour un week-end au Louis XV d\'Alain Ducasse, notre flotte de berlines luxe et Mercedes Classe S est a la hauteur des standards monegasques. Nombre de clients reservent des excursions vers Eze, Grasse ou Saint-Paul-de-Vence. Quand votre sejour s\'acheve, le meme chauffeur vous ramene a l\'aeroport de Nice. Reservez votre transfert Monaco.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Monaco ?',
    feature1Title: 'Accueil VIP', feature1Desc: 'Chauffeur avec pancarte nominative aux arrivees de Nice. 60 min d\'attente gratuites.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Suivi en temps reel de votre vol. Aucun supplement pour retard.',
    feature3Title: 'Flotte de Luxe', feature3Desc: 'Mercedes Classe S, BMW Serie 7 et SUV de luxe. Vehicules dignes de Monaco.',
    feature4Title: 'Prix Tout Compris', feature4Desc: 'Prix fixe confirme a la reservation. Peages, parking et taxes inclus.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E, 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S ou BMW Serie 7',
    minivan: 'Monospace de Luxe', minivanDesc: 'Mercedes Classe V, jusqu\'a 6 passagers', minibus: 'Minibus VIP', minibusDesc: 'Pour groupes jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez les details du vol et votre adresse a Monaco. Confirmation immediate.',
    step2: 'Rendez-vous a l\'Aeroport de Nice', step2Desc: 'Votre chauffeur vous accueille aux arrivees et aide avec les bagages.',
    step3: 'Arrivez avec Style', step3Desc: 'Transfert de luxe direct vers Monaco en 25-35 minutes.',
    popularRoutesTitle: 'Trajets Populaires Transfert Monaco', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport Nice → Monte-Carlo', price: 65 },
      { name: 'Aeroport Nice → Port Hercule Monaco', price: 70 },
      { name: 'Aeroport Nice → Fontvieille', price: 65 },
      { name: 'Monaco → Cannes', price: 95 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Monaco',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Nice Cote d\'Azur (NCE)',
    otherCitiesTitle: 'Nous desservons aussi d\'autres villes en Europe', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.9/5 (980+ avis)',
  },
  ru: {
    title: 'Трансфер в Монако из Аэропорта - Частный Автомобиль',
    subtitle: 'Премиум трансфер из аэропорта Ниццы в Монако, Монте-Карло и все направления Монако',
    description: 'Монако — вторая по размеру страна мира, но на каждом квадратном метре здесь сосредоточено больше роскоши, чем где-либо. От Казино Монте-Карло до шпилек Формулы-1, от Княжеского дворца до яхт в порту Эркюль — каждый уголок этого княжества дышит эксклюзивностью. Своего аэропорта у Монако нет, поэтому гости прибывают через Ниццу (NCE) — 22 км и 25-35 минут по живописному побережью. Наш премиальный трансфер встречает вас в зале прилёта Ниццы и доставляет прямо к отелю в Монте-Карло, деловой встрече в Фонвьей или яхте в порту Эркюль.',
    description2: 'Путь из аэропорта Ниццы в Монако — само по себе впечатление. Вы проедете по Нижней Корниш через Вильфранш-сюр-Мер и Кап-Ферра или по захватывающей Средней Корниш с панорамами Средиземноморья далеко внизу. Частный автомобиль позволяет наслаждаться пейзажами с комфортом — охлаждённая вода, кондиционер и водитель, знающий каждый вход отеля.',
    description3: 'Гран-при Монако в мае, ралли Монте-Карло в январе, Яхт-шоу в сентябре или уикенд у Алена Дюкасса — правильное прибытие задаёт тон визиту. Наш автопарк включает Mercedes S-Class и люксовые седаны. Многие клиенты заказывают экскурсии в Эз, Грасс или Сен-Поль-де-Ванс. При отъезде тот же водитель доставит вас в аэропорт.',
    whyChoose: 'Почему Выбрать Наш Трансфер в Монако?',
    feature1Title: 'VIP Встреча', feature1Desc: 'Водитель с именной табличкой в зале прилета Ниццы. 60 минут ожидания бесплатно.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мониторинг рейса в реальном времени. Без доплаты за задержку.',
    feature3Title: 'Люкс Автопарк', feature3Desc: 'Mercedes S-Class, BMW 7 серии и люкс SUV.',
    feature4Title: 'Все Включено', feature4Desc: 'Фиксированная цена. Дороги, парковка и налоги включены.',
    sedan: 'Премиум Седан', sedanDesc: 'Mercedes E-Class, 1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes S-Class или BMW 7 серии',
    minivan: 'Люкс Минивэн', minivanDesc: 'Mercedes V-Class, до 6 пассажиров', minibus: 'VIP Микроавтобус', minibusDesc: 'Для групп до 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Введите данные рейса и адрес в Монако.',
    step2: 'Встреча в Аэропорту Ниццы', step2Desc: 'Водитель встречает вас и помогает с багажом.',
    step3: 'Прибытие со Стилем', step3Desc: 'Прямой люкс-трансфер в Монако за 25-35 минут.',
    popularRoutesTitle: 'Популярные Маршруты Трансфера в Монако', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт Ниццы → Монте-Карло', price: 65 },
      { name: 'Аэропорт Ниццы → Порт Эркюль Монако', price: 70 },
      { name: 'Аэропорт Ниццы → Фонвьей', price: 65 },
      { name: 'Монако → Канны', price: 95 },
    ],
    bookingForm: 'Забронируйте Трансфер в Монако',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Ницца Лазурный Берег (NCE)',
    otherCitiesTitle: 'Мы также обслуживаем другие города Европы', otherCitiesBtn: 'Все Направления',
    rating: '4.9/5 (980+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 65, luxury: 95, minivan: 120, minibus: 180 };

const seoUrls = { en: '/monaco-airport-transfer', fr: '/transfert-aeroport-monaco', ru: '/taksi-iz-aeroporta-monako' };
const MonacoTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default MonacoTransfer;
