import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Munich Airport Transfer - Franz Josef Strauss',
    subtitle: 'Professional private driver from Munich Airport to city center, Marienplatz and all Bavaria destinations',
    description: 'Munich Airport (MUC) — officially named after Bavarian politician Franz Josef Strauss — consistently ranks among the top five airports in Europe for service quality, yet it sits a full 37 kilometres northeast of the city centre in the fields of Erdinger Moos. The S-Bahn shuttle takes 45 minutes, stops at every suburban station, and becomes standing-room-only during Oktoberfest season. A taxi from MUC to Marienplatz costs upward of 80 euros with no guarantee your driver speaks English or knows your specific hotel entrance. Our private Munich airport transfer changes this equation entirely: a professional, English-speaking chauffeur greets you at the arrivals gate, loads your bags into a premium Mercedes or BMW, and takes you directly to your hotel, conference venue, or Alpine chalet — in 35 to 50 minutes, with a price confirmed before you even land.',
    description2: 'The drive from MUC to central Munich follows the A92 and A9 motorways through the flat Bavarian countryside, with views of the distant Alps on clear days. Our drivers can drop you at Marienplatz in the historic Altstadt, the BMW Welt visitor centre in Milbertshofen, the Allianz Arena in Freimann, or the Theresienwiese where Oktoberfest unfolds each autumn. For business travelers heading to the Messe Munchen exhibition centre in Riem, the airport is actually closer than the city centre — just 15 minutes east — and our drivers know the dedicated VIP entrance roads.',
    description3: 'Munich is not just a city — it is the gateway to the Bavarian Alps, the fairy-tale castles of Ludwig II, and some of the finest beer culture on the planet. From MUC, our drivers can take you directly to Neuschwanstein Castle (90 minutes), the ski resorts of Garmisch-Partenkirchen (80 minutes), or the crystal-clear waters of Starnberger See (40 minutes). During Oktoberfest, which draws over 6 million visitors in just 16 days, our pre-booked transfers ensure you skip the impossible taxi queues that form outside MUC every evening. Whether you are here for lederhosen, for luxury, or for the Pinakothek museums, your Munich experience starts with a calm, comfortable ride from the airport.',
    whyChoose: 'Why Choose Our Munich Airport Transfer?',
    feature1Title: 'Meet & Greet at MUC', feature1Desc: 'Driver waits with name sign at Munich Airport arrivals. 60 min free waiting.',
    feature2Title: 'Flight Tracking', feature2Desc: 'We track your flight in real-time. No surcharge for delays.',
    feature3Title: 'Premium German Cars', feature3Desc: 'BMW, Mercedes, Audi. Clean, comfortable, less than 3 years old.',
    feature4Title: 'Fixed Prices', feature4Desc: 'Price confirmed at booking. No hidden charges, tolls included.',
    sedan: 'Premium Sedan', sedanDesc: 'BMW 5 Series or similar, 1-3 passengers', luxury: 'Business Sedan', luxuryDesc: 'Mercedes E-Class or BMW 7 Series',
    minivan: 'Minivan', minivanDesc: 'For groups up to 6 passengers', minibus: 'Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter flight details and Munich address. Instant price confirmation.',
    step2: 'Meet Your Driver', step2Desc: 'Professional driver greets you at MUC arrivals.',
    step3: 'Enjoy the Ride', step3Desc: 'Comfortable 35-45 minute ride to central Munich.',
    popularRoutesTitle: 'Popular Munich Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'MUC Airport → Munich Marienplatz', price: 55 },
      { name: 'MUC Airport → Munich Hauptbahnhof', price: 55 },
      { name: 'MUC Airport → BMW World', price: 50 },
      { name: 'MUC Airport → Garmisch-Partenkirchen', price: 180 },
    ],
    bookingForm: 'Book Your Munich Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Munich Airport (MUC)',
    otherCitiesTitle: 'We also serve other cities', otherCitiesBtn: 'View All Destinations',
    rating: '4.9/5 (1,100+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Munich - Franz Josef Strauss',
    subtitle: 'Chauffeur prive professionnel depuis l\'aeroport de Munich vers le centre-ville et toute la Baviere',
    description: 'Reservez votre transfert aeroport Munich avec des chauffeurs professionnels. L\'aeroport de Munich (MUC) est situe a 28 km au nord-est de la ville. Nous offrons des transferts prives premium depuis MUC vers le centre de Munich, Marienplatz, la zone de l\'Oktoberfest, BMW World et toutes les destinations bavaroises. Prix fixes, suivi de vol, service d\'accueil.',
    description2: 'L\'aeroport de Munich (MUC), du nom du politicien bavarois Franz Josef Strauss, se classe regulierement parmi les cinq meilleurs d\'Europe, mais se trouve a 37 km du centre-ville. Le S-Bahn met 45 minutes avec arrets a chaque gare de banlieue. Notre chauffeur vous accueille aux arrivees, charge vos bagages dans une Mercedes premium et vous conduit a Marienplatz, BMW Welt, l\'Allianz Arena ou la Theresienwiese en 35-50 minutes, prix fixe confirme avant meme l\'atterrissage.',
    description3: 'Munich est la porte des Alpes bavaroises, des chateaux feeriques de Louis II et d\'une culture brassicole parmi les plus riches au monde. Depuis MUC, nos chauffeurs vous emmenent directement au chateau de Neuschwanstein (90 min), aux stations de ski de Garmisch-Partenkirchen (80 min) ou au lac Starnberger See (40 min). Pendant l\'Oktoberfest et ses 6 millions de visiteurs en 16 jours, nos transferts pre-reserves vous evitent les files de taxis impossibles devant MUC chaque soir.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Munich ?',
    feature1Title: 'Accueil a MUC', feature1Desc: 'Chauffeur avec pancarte aux arrivees de Munich. 60 min d\'attente gratuites.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Suivi en temps reel. Pas de supplement pour retard.',
    feature3Title: 'Vehicules Allemands Premium', feature3Desc: 'BMW, Mercedes, Audi. Propres, confortables, moins de 3 ans.',
    feature4Title: 'Prix Fixes', feature4Desc: 'Prix confirme a la reservation. Aucun frais cache, peages inclus.',
    sedan: 'Berline Premium', sedanDesc: 'BMW Serie 5 ou similaire, 1-3 passagers', luxury: 'Berline Business', luxuryDesc: 'Mercedes Classe E ou BMW Serie 7',
    minivan: 'Monospace', minivanDesc: 'Pour groupes jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Pour groupes jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez les details du vol et adresse a Munich.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Chauffeur professionnel aux arrivees MUC.',
    step3: 'Profitez du Trajet', step3Desc: 'Trajet confortable de 35-45 minutes vers Munich centre.',
    popularRoutesTitle: 'Trajets Populaires Transfert Munich', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport MUC → Munich Marienplatz', price: 55 },
      { name: 'Aeroport MUC → Gare Centrale Munich', price: 55 },
      { name: 'Aeroport MUC → BMW World', price: 50 },
      { name: 'Aeroport MUC → Garmisch-Partenkirchen', price: 180 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Munich',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport de Munich (MUC)',
    otherCitiesTitle: 'Nous desservons aussi d\'autres villes', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.9/5 (1 100+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Мюнхена - Франц Йозеф Штраус',
    subtitle: 'Профессиональный водитель из аэропорта Мюнхена в центр города и все направления Баварии',
    description: 'Забронируйте трансфер из аэропорта Мюнхена. Аэропорт Мюнхена (MUC) расположен в 28 км к северо-востоку от города. Мы обеспечиваем премиум-трансферы из MUC в центр Мюнхена, Мариенплац, район Октоберфест, BMW World и все направления Баварии.',
    description2: 'Аэропорт Мюнхена (MUC) стабильно входит в пятёрку лучших Европы, но расположен в 37 км от центра. S-Bahn едет 45 минут с остановкой на каждой пригородной станции. Наш водитель встречает в зале прилёта, загружает багаж в премиальный Mercedes и доставляет к Мариенплац, BMW Welt, Allianz Arena или Терезиенвизе за 35-50 минут. Цена фиксирована до посадки.',
    description3: 'Мюнхен — ворота в Баварские Альпы, к сказочным замкам Людвига II и одной из лучших пивных культур планеты. От MUC наши водители везут прямо к замку Нойшванштайн (90 мин), горнолыжному Гармиш-Партенкирхену (80 мин) или озеру Штарнбергер-Зе (40 мин). В Октоберфест, когда 6 млн гостей за 16 дней, наши предзаказанные трансферы спасают от невозможных очередей на такси у MUC каждый вечер.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Мюнхена?',
    feature1Title: 'Встреча в MUC', feature1Desc: 'Водитель с табличкой в зале прилета. 60 минут ожидания бесплатно.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мониторинг в реальном времени. Без доплаты.',
    feature3Title: 'Немецкие Авто Премиум', feature3Desc: 'BMW, Mercedes, Audi. Чистые, комфортные.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Цена при бронировании. Без скрытых платежей.',
    sedan: 'Премиум Седан', sedanDesc: 'BMW 5 серии, 1-3 пассажира', luxury: 'Бизнес Седан', luxuryDesc: 'Mercedes E-Class или BMW 7',
    minivan: 'Минивэн', minivanDesc: 'До 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Введите данные рейса и адрес в Мюнхене.',
    step2: 'Встретьте Водителя', step2Desc: 'Водитель в зале прилета MUC.',
    step3: 'Наслаждайтесь', step3Desc: 'Комфортная поездка 35-45 минут.',
    popularRoutesTitle: 'Популярные Маршруты из Аэропорта Мюнхена', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт MUC → Мариенплац', price: 55 },
      { name: 'Аэропорт MUC → Главный вокзал', price: 55 },
      { name: 'Аэропорт MUC → BMW World', price: 50 },
      { name: 'Аэропорт MUC → Гармиш', price: 180 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Мюнхена',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Мюнхена (MUC)',
    otherCitiesTitle: 'Другие города', otherCitiesBtn: 'Все Направления',
    rating: '4.9/5 (1 100+ отзывов)',
  },
  hy: {
    title: 'Տրանսֆեր Մյունխենի օդանավայանից',
    subtitle: 'Մասնավոր վարորդ MUC-ից Մյունխենի կենտրոն',
    description: 'Մյունխենի օդանավայանը (MUC) Եվրոպայի լավագույններից է՝ բայց 37 կմ կենտրոնից: Oktoberfest-ը յուրաքանչյուր օր 6 միլիոն այցելու է ընդունում: Marienplatz՝ BMW Welt՝ Allianz Arena: Նոյշվանշտայն (90 րոպե)՝ Garmisch-Partenkirchen (80 րոպե)՝ Starnberger See (40 րոպե):',
    description2: 'Բավարական Ալպերի դարպասը:',
    whyChoose: 'Ինչու ընտրել մեր տրանսֆեր մյունխենի օդանավայանից',
    feature1Title: 'Դիմավորում', feature1Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով: 60 րոպե անվճար սպասման ժամանակ:',
    feature2Title: 'Թռիչքի հետևում', feature2Desc: 'Իրական ժամանակում թռիչքի հետևում: Անվճար:',
    feature3Title: 'Պրեմիում մեքենաներ', feature3Desc: 'Mercedes E-Class, BMW 5: Մաքուր, կլիմատիզացիա:',
    feature4Title: 'Ֆիքս գներ', feature4Desc: 'Գինը հաստատված է ամրագրման ժամանակ: Թաքնված վճարներ չկան:',
    sedan: 'Պրեմիում սեդան', sedanDesc: 'Mercedes E-Class, 1-3 ուղևոր',
    luxury: 'Լյուքս սեդան', luxuryDesc: 'Mercedes S-Class կամ BMW 7',
    minivan: 'Մինիվեն', minivanDesc: 'Mercedes V-Class, մինչև 6 ուղևոր',
    minibus: 'Մինիբուս', minibusDesc: 'Մինչև 8 ուղևոր',
    passengers: 'Ուղևորներ', luggage: 'Ուղեբարան',
    bookNow: 'ԱՄՏԱԳՏՎԵԼ', allInclusive: 'Ամեն ինչ ներառված է',
    vehiclesTitle: 'Ընտրեք մեքենան',
    howItWorks: 'Ինչպես է աշխատում',
    step1: 'Ամրագրեք օնլայն', step1Desc: 'Մուտքագրեք ձեր տվյալները և հասցեն: Ակնթարթ գնի հաստատում:',
    step2: 'Հանդիպեք վարորդին', step2Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով:',
    step3: 'Հանգստացեք', step3Desc: 'Հարմարավետ ուղևորություն պրեմիում մեքենայում:',
    popularRoutesTitle: 'Սկսած', fromLabel: 'Սկսած',
    bookingForm: 'ԱՄՏԱԳՏՎԵԼ',
    pickupLabel: 'Վերցնում', dropoffLabel: 'Իջնում',
    dateLabel: 'Ամսաթիվ', timeLabel: 'Ժամ',
    defaultPickup: '',
    otherCitiesTitle: 'Սպասարկում ենք 120+ քաղաքներ Եվրոպայում',
    otherCitiesBtn: 'Բոլոր ուղղությունները',
    rating: '4.9/5',
  },
};

const vehiclesPrices = { sedan: 55, luxury: 80, minivan: 110, minibus: 165 };

const seoUrls = { en: '/munich-airport-transfer', fr: '/transfert-aeroport-munich', ru: '/taksi-iz-aeroporta-munhen' };
const MunichTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default MunichTransfer;
