import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Munich Airport Transfer - Franz Josef Strauss',
    subtitle: 'Professional private driver from Munich Airport to city center, Marienplatz and all Bavaria destinations',
    description: 'Book your Munich airport transfer with professional drivers. Munich Airport (MUC), also known as Franz Josef Strauss Airport, is located 28 km northeast of Munich. We provide premium private transfers from MUC Airport to Munich city center, Marienplatz, Oktoberfest area, BMW World, and all Bavarian destinations. Fixed prices, flight monitoring, meet and greet service.',
    description2: 'Munich is the gateway to Bavaria, famous for Oktoberfest, BMW, world-class museums, and the stunning Bavarian Alps. Our experienced drivers will take you comfortably from the airport to your destination, whether it is a hotel in the Altstadt, a business meeting, or a connection to the Alps.',
    whyChoose: 'Why Choose Our Munich Airport Transfer?',
    feature1Title: 'Meet & Greet at MUC', feature1Desc: 'Driver waits with name sign at Munich Airport arrivals. 60 min free waiting.',
    feature2Title: 'Flight Tracking', feature2Desc: 'We track your flight in real-time. No surcharge for delays.',
    feature3Title: 'Premium German Cars', feature3Desc: 'BMW, Mercedes, Audi. Clean, comfortable, less than 3 years old.',
    feature4Title: 'Fixed Prices', feature4Desc: 'Price confirmed at booking. No hidden charges, tolls included.',
    sedan: 'Premium Sedan', sedanDesc: 'BMW 5 Series or similar, 1-3 passengers', luxury: 'Business Sedan', luxuryDesc: 'Mercedes E-Class or BMW 7 Series',
    minivan: 'Minivan', minivanDesc: 'For groups up to 6 passengers', minibus: 'Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter flight details and Munich address. Instant price confirmation.',
    step2: 'Meet Your Driver', step2Desc: 'Professional driver greets you at MUC arrivals.',
    step3: 'Enjoy the Ride', step3Desc: 'Comfortable 35-45 minute ride to central Munich.',
    popularRoutesTitle: 'Popular Munich Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'MUC Airport → Munich Marienplatz', price: 55 },
      { name: 'MUC Airport → Munich Hauptbahnhof', price: 55 },
      { name: 'MUC Airport → BMW World', price: 50 },
      { name: 'MUC Airport → Garmisch-Partenkirchen', price: 180 },
    ],
    bookingForm: 'Book Your Munich Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Munich Airport (MUC)',
    otherCitiesTitle: 'We also serve other cities', otherCitiesBtn: 'View All Destinations',
    rating: '4.9/5 (1,100+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Munich - Franz Josef Strauss',
    subtitle: 'Chauffeur prive professionnel depuis l\'aeroport de Munich vers le centre-ville et toute la Baviere',
    description: 'Reservez votre transfert aeroport Munich avec des chauffeurs professionnels. L\'aeroport de Munich (MUC) est situe a 28 km au nord-est de la ville. Nous offrons des transferts prives premium depuis MUC vers le centre de Munich, Marienplatz, la zone de l\'Oktoberfest, BMW World et toutes les destinations bavaroises. Prix fixes, suivi de vol, service d\'accueil.',
    description2: 'Munich est la porte de la Baviere, celebre pour l\'Oktoberfest, BMW, les musees de classe mondiale et les Alpes bavaroises. Nos chauffeurs experimentes vous conduisent confortablement a votre destination.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Munich ?',
    feature1Title: 'Accueil a MUC', feature1Desc: 'Chauffeur avec pancarte aux arrivees de Munich. 60 min d\'attente gratuites.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Suivi en temps reel. Pas de supplement pour retard.',
    feature3Title: 'Vehicules Allemands Premium', feature3Desc: 'BMW, Mercedes, Audi. Propres, confortables, moins de 3 ans.',
    feature4Title: 'Prix Fixes', feature4Desc: 'Prix confirme a la reservation. Aucun frais cache, peages inclus.',
    sedan: 'Berline Premium', sedanDesc: 'BMW Serie 5 ou similaire, 1-3 passagers', luxury: 'Berline Business', luxuryDesc: 'Mercedes Classe E ou BMW Serie 7',
    minivan: 'Monospace', minivanDesc: 'Pour groupes jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Pour groupes jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez les details du vol et adresse a Munich.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Chauffeur professionnel aux arrivees MUC.',
    step3: 'Profitez du Trajet', step3Desc: 'Trajet confortable de 35-45 minutes vers Munich centre.',
    popularRoutesTitle: 'Trajets Populaires Transfert Munich', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport MUC → Munich Marienplatz', price: 55 },
      { name: 'Aeroport MUC → Gare Centrale Munich', price: 55 },
      { name: 'Aeroport MUC → BMW World', price: 50 },
      { name: 'Aeroport MUC → Garmisch-Partenkirchen', price: 180 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Munich',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport de Munich (MUC)',
    otherCitiesTitle: 'Nous desservons aussi d\'autres villes', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.9/5 (1 100+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Мюнхена - Франц Йозеф Штраус',
    subtitle: 'Профессиональный водитель из аэропорта Мюнхена в центр города и все направления Баварии',
    description: 'Забронируйте трансфер из аэропорта Мюнхена. Аэропорт Мюнхена (MUC) расположен в 28 км к северо-востоку от города. Мы обеспечиваем премиум-трансферы из MUC в центр Мюнхена, Мариенплац, район Октоберфест, BMW World и все направления Баварии.',
    description2: 'Мюнхен - ворота в Баварию, знаменитый Октоберфестом, BMW и Баварскими Альпами. Наши водители доставят вас комфортно.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Мюнхена?',
    feature1Title: 'Встреча в MUC', feature1Desc: 'Водитель с табличкой в зале прилета. 60 минут ожидания бесплатно.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мониторинг в реальном времени. Без доплаты.',
    feature3Title: 'Немецкие Авто Премиум', feature3Desc: 'BMW, Mercedes, Audi. Чистые, комфортные.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Цена при бронировании. Без скрытых платежей.',
    sedan: 'Премиум Седан', sedanDesc: 'BMW 5 серии, 1-3 пассажира', luxury: 'Бизнес Седан', luxuryDesc: 'Mercedes E-Class или BMW 7',
    minivan: 'Минивэн', minivanDesc: 'До 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Введите данные рейса и адрес в Мюнхене.',
    step2: 'Встретьте Водителя', step2Desc: 'Водитель в зале прилета MUC.',
    step3: 'Наслаждайтесь', step3Desc: 'Комфортная поездка 35-45 минут.',
    popularRoutesTitle: 'Популярные Маршруты из Аэропорта Мюнхена', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт MUC → Мариенплац', price: 55 },
      { name: 'Аэропорт MUC → Главный вокзал', price: 55 },
      { name: 'Аэропорт MUC → BMW World', price: 50 },
      { name: 'Аэропорт MUC → Гармиш', price: 180 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Мюнхена',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Мюнхена (MUC)',
    otherCitiesTitle: 'Другие города', otherCitiesBtn: 'Все Направления',
    rating: '4.9/5 (1 100+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 55, luxury: 80, minivan: 110, minibus: 165 };

const MunichTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} />;
export default MunichTransfer;
