import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Nice Airport Transfer - Cote d\'Azur Airport',
    subtitle: 'Private driver service from Nice Cote d\'Azur Airport to your hotel, city center or anywhere on the French Riviera',
    description: 'The French Riviera begins the moment you step off your flight at Nice Cote d\'Azur Airport, the third busiest in France and the gateway to the most glamorous 100 kilometres of Mediterranean coastline on earth. Each year, over 14 million travelers pass through its two modern terminals — many of them heading to seafront hotels on the Promenade des Anglais, villas perched above the old port of Villefranche-sur-Mer, or hilltop villages like Eze and Saint-Paul-de-Vence. Our private Nice airport transfer puts you in a premium vehicle within minutes of clearing arrivals, with a professional driver who speaks your language and knows every twist of the Basse Corniche, the Moyenne Corniche, and the Grande Corniche roads that hug this legendary coast.',
    description2: 'Nice Airport sits remarkably close to the city — just 6 kilometres from the Promenade des Anglais and 10 minutes from the Cours Saleya flower market in Vieux Nice. But proximity does not mean simplicity: the tramway to the city centre takes 30 minutes with multiple stops, taxis often refuse short rides to nearby hotels, and rental car queues can stretch for an hour in July and August. Our fixed-price transfer bypasses all of this. Whether you are staying at a five-star on the Promenade, a boutique residence in the port district, or a holiday apartment in Cimiez near the Matisse Museum, your driver delivers you directly to the entrance.',
    description3: 'Nice is not just a beach destination — it is a cultural capital with 19 museums, a thriving restaurant scene ranked among the best in southern France, and a microclimate that delivers 300 days of sunshine per year. From Nice, the entire Riviera opens up: Monaco is 30 minutes east, Cannes 35 minutes west, and the perfume town of Grasse sits 40 minutes inland among lavender fields. Many of our clients book a multi-day driver for excursions to the Verdon Gorge, the vineyards of Provence, or the medieval markets of Antibes. But it all starts with that first ride from the airport — and we make sure it sets the tone for an unforgettable stay. Book your Nice airport transfer and let the Cote d\'Azur welcome you in style.',
    whyChoose: 'Why Choose Our Nice Airport Transfer?',
    feature1Title: 'Meet & Greet at NCE', feature1Desc: 'Your driver waits at Nice Airport arrivals with a personalized name sign. 60 minutes free waiting time for flight delays.',
    feature2Title: 'Real-Time Flight Tracking', feature2Desc: 'We monitor your flight status. No extra charge if your flight is delayed.',
    feature3Title: 'Premium Vehicles', feature3Desc: 'Air-conditioned, clean vehicles less than 3 years old. Mercedes, BMW, or similar.',
    feature4Title: 'Fixed Prices', feature4Desc: 'Price confirmed at booking. No hidden fees, no surge pricing. Tolls included.',
    sedan: 'Premium Sedan', sedanDesc: 'Ideal for 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes E-Class or similar',
    minivan: 'Minivan', minivanDesc: 'For groups up to 6 passengers', minibus: 'Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter your flight details and destination. Instant price confirmation.',
    step2: 'Meet Your Driver', step2Desc: 'Driver waits at arrivals with your name sign. Help with luggage included.',
    step3: 'Relax & Enjoy', step3Desc: 'Comfortable ride in a premium vehicle directly to your destination.',
    popularRoutesTitle: 'Popular Nice Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'Nice Airport → Nice City Center', price: 35 },
      { name: 'Nice Airport → Monaco', price: 65 },
      { name: 'Nice Airport → Cannes', price: 75 },
      { name: 'Nice Airport → Saint-Tropez', price: 250 },
    ],
    bookingForm: 'Book Your Nice Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Nice Cote d\'Azur Airport (NCE)',
    otherCitiesTitle: 'We also serve other cities in Europe', otherCitiesBtn: 'View All Destinations',
    rating: '4.5/5 Tripadvisor (29 reviews)',
    meetDriverTitle: 'Where to Meet Your Driver at Nice Airport',
    meetDriverText: 'After your flight lands, follow the airport signs to the Arrivals / Exit area. Your chauffeur will be waiting outside with a sign showing your name. Nice airport has 2 terminals just minutes from the Promenade des Anglais — your driver knows both perfectly and will assist with your luggage for a smooth start to your Riviera experience.',
  },
  fr: {
    title: 'Transfert Aeroport Nice - Cote d\'Azur',
    subtitle: 'Service de chauffeur prive depuis l\'aeroport de Nice vers votre hotel, le centre-ville ou toute la Cote d\'Azur',
    description: 'La Riviera francaise commence des que vous posez le pied a l\'aeroport Nice Cote d\'Azur, troisieme aeroport de France et porte d\'entree des 100 kilometres de littoral mediterraneen les plus glamour au monde. Chaque annee, plus de 14 millions de voyageurs transitent par ses deux terminaux modernes — nombre d\'entre eux rejoignant les hotels en front de mer de la Promenade des Anglais, les villas perchees au-dessus du vieux port de Villefranche-sur-Mer, ou les villages de caractere comme Eze et Saint-Paul-de-Vence. Notre transfert prive depuis Nice vous installe dans un vehicule premium quelques minutes apres les arrivees, avec un chauffeur professionnel qui parle votre langue et connait chaque virage de la Basse Corniche, de la Moyenne Corniche et de la Grande Corniche.',
    description2: 'L\'aeroport de Nice est remarquablement proche de la ville — 6 kilometres de la Promenade des Anglais et 10 minutes du marche aux fleurs du Cours Saleya dans le Vieux Nice. Mais proximite ne signifie pas simplicite : le tramway met 30 minutes avec de multiples arrets, les taxis refusent souvent les courses courtes vers les hotels proches, et les files de location de voiture peuvent s\'etirer pendant une heure en juillet-aout. Notre transfert a prix fixe contourne tout cela. Que vous logiez dans un cinq etoiles sur la Promenade, un boutique-hotel du quartier du port, ou un appartement de vacances a Cimiez pres du Musee Matisse, votre chauffeur vous depose directement a l\'entree.',
    description3: 'Nice n\'est pas qu\'une destination balneaire — c\'est une capitale culturelle avec 19 musees, une scene gastronomique parmi les meilleures du sud de la France, et un microclimat qui offre 300 jours de soleil par an. Depuis Nice, toute la Riviera s\'ouvre a vous : Monaco a 30 minutes a l\'est, Cannes a 35 minutes a l\'ouest, et la ville des parfums de Grasse a 40 minutes dans les terres, au milieu des champs de lavande. Beaucoup de nos clients reservent un chauffeur sur plusieurs jours pour visiter les Gorges du Verdon, les vignobles de Provence ou les marches medievaux d\'Antibes. Tout commence par ce premier trajet depuis l\'aeroport — et nous nous assurons qu\'il donne le ton d\'un sejour inoubliable.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Nice ?',
    feature1Title: 'Accueil Personnalise NCE', feature1Desc: 'Votre chauffeur vous attend aux arrivees de l\'aeroport de Nice avec une pancarte a votre nom. 60 minutes d\'attente gratuites.',
    feature2Title: 'Suivi des Vols en Temps Reel', feature2Desc: 'Nous surveillons votre vol. Aucun supplement en cas de retard.',
    feature3Title: 'Vehicules Premium', feature3Desc: 'Vehicules climatises, propres, de moins de 3 ans. Mercedes, BMW ou similaire.',
    feature4Title: 'Prix Fixes Garantis', feature4Desc: 'Prix confirme a la reservation. Pas de frais caches, peages inclus.',
    sedan: 'Berline Premium', sedanDesc: 'Ideal pour 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe E ou similaire',
    minivan: 'Monospace', minivanDesc: 'Pour groupes jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Pour groupes jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez les details de votre vol et destination. Confirmation du prix immediate.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Le chauffeur vous attend aux arrivees avec pancarte a votre nom.',
    step3: 'Detendez-vous', step3Desc: 'Transfert direct dans un vehicule premium climatise vers votre destination.',
    popularRoutesTitle: 'Trajets Populaires Transfert Aeroport Nice', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport Nice → Centre-ville Nice', price: 35 },
      { name: 'Aeroport Nice → Monaco', price: 65 },
      { name: 'Aeroport Nice → Cannes', price: 75 },
      { name: 'Aeroport Nice → Saint-Tropez', price: 250 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Nice',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Nice Cote d\'Azur (NCE)',
    otherCitiesTitle: 'Nous desservons aussi d\'autres villes en Europe', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.5/5 Tripadvisor (29 avis)',
    meetDriverTitle: 'Ou retrouver votre chauffeur a l\'aeroport de Nice',
    meetDriverText: 'Apres l\'atterrissage, suivez les panneaux vers la zone Arrivees / Sortie. Votre chauffeur vous attend dehors avec une pancarte a votre nom. L\'aeroport de Nice a 2 terminaux a quelques minutes de la Promenade des Anglais — votre chauffeur connait les deux parfaitement et vous aide avec vos bagages pour un debut de sejour sur la Riviera en toute serenite.',
  },
  ru: {
    title: 'Трансфер из Аэропорта Ниццы - Лазурный Берег',
    subtitle: 'Услуги частного водителя из аэропорта Ницца Лазурный Берег в отель, центр города или любую точку Ривьеры',
    description: 'Французская Ривьера начинается в ту секунду, когда вы выходите из самолёта в аэропорту Ницца Лазурный Берег — третьем по загруженности во Франции и воротах к самым роскошным 100 километрам средиземноморского побережья на планете. Ежегодно более 14 миллионов путешественников проходят через два современных терминала, направляясь к отелям на Английской набережной, виллам над старым портом Вильфранш-сюр-Мер или горным деревушкам вроде Эз и Сен-Поль-де-Ванс. Наш частный трансфер из Ниццы усаживает вас в премиальный автомобиль через считанные минуты после прилёта — с профессиональным водителем, который говорит на вашем языке и знает каждый поворот Нижнего, Среднего и Верхнего корнишей.',
    description2: 'Аэропорт Ниццы расположен удивительно близко к городу — всего 6 км от Английской набережной и 10 минут от цветочного рынка Кур-Салея в Старом городе. Но близость не означает простоту: трамвай до центра едет 30 минут с множеством остановок, таксисты часто отказывают в коротких поездках к ближайшим отелям, а очереди на аренду автомобиля в июле-августе растягиваются на час. Наш трансфер с фиксированной ценой обходит всё это стороной. Остановились в пятизвёздочном отеле на Променаде, бутик-отеле в порту или апартаментах в Симье у музея Матисса — водитель доставит вас прямо к входу.',
    description3: 'Ницца — не просто пляжное направление. Это культурная столица с 19 музеями, выдающейся гастрономической сценой и микроклиматом, дарящим 300 солнечных дней в году. Отсюда открывается вся Ривьера: Монако в 30 минутах на восток, Канны в 35 минутах на запад, парфюмерный Грасс в 40 минутах вглубь лавандовых полей Прованса. Многие клиенты заказывают водителя на несколько дней для экскурсий к Вердонскому ущелью, виноградникам Прованса или средневековым рынкам Антиба. Но всё начинается с первой поездки из аэропорта — и мы позаботимся, чтобы она задала тон незабываемому отдыху.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Ниццы?',
    feature1Title: 'Встреча в Аэропорту NCE', feature1Desc: 'Водитель ждет вас в зале прилета с табличкой. 60 минут ожидания бесплатно.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мы следим за вашим рейсом. Без доплаты за задержку.',
    feature3Title: 'Премиум Автомобили', feature3Desc: 'Чистые автомобили с кондиционером, не старше 3 лет. Mercedes, BMW.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Цена подтверждается при бронировании. Без скрытых платежей.',
    sedan: 'Премиум Седан', sedanDesc: 'Для 1-3 пассажиров', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes E-Class или аналогичный',
    minivan: 'Минивэн', minivanDesc: 'Для групп до 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'Для групп до 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Введите данные рейса и направление. Мгновенное подтверждение цены.',
    step2: 'Встретьте Водителя', step2Desc: 'Водитель ждет в зале прилета с табличкой с вашим именем.',
    step3: 'Расслабьтесь', step3Desc: 'Комфортная поездка в премиум автомобиле прямо до места назначения.',
    popularRoutesTitle: 'Популярные Маршруты из Аэропорта Ниццы', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт Ниццы → Центр Ниццы', price: 35 },
      { name: 'Аэропорт Ниццы → Монако', price: 65 },
      { name: 'Аэропорт Ниццы → Канны', price: 75 },
      { name: 'Аэропорт Ниццы → Сен-Тропе', price: 250 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Ниццы',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Ницца Лазурный Берег (NCE)',
    otherCitiesTitle: 'Мы также обслуживаем другие города Европы', otherCitiesBtn: 'Все Направления',
    rating: '4.5/5 Tripadvisor (29 отзывов)',
    meetDriverTitle: 'Где встретить водителя в аэропорту Ниццы',
    meetDriverText: 'После посадки следуйте указателям к зоне Прибытия / Выхода. Ваш водитель ждёт снаружи с табличкой с вашим именем. Аэропорт Ниццы имеет 2 терминала рядом с Английской набережной — водитель знает оба и поможет с багажом.',
  },
  hy: {
    title: 'Տրանսֆեր Նիսի օդանավայանից',
    subtitle: 'Մասնավոր վարորդ Նիսի օդանավայանից',
    description: 'Ֆրանսիական Ռիվիերան սկսվում է Նիսի օդանավայանից՝ Ֆրանսիայի 3-րդ օդանավայանը: 14 միլիոն ուղևոր՝ Promenade des Anglais-ի հյուրանոցային հոտելներ՝ Villefranche-sur-Mer-ի վիլլաներ: 6 կմ քաղաքի կենտրոնից՝ 10 րոպե Cours Saleya ծաղկային շուկայից: Մոնակոն 30 րոպե՝ Կանն 35 րոպե՝ Գրաս 40 րոպե: 19 թանգարան՝ 300 արևային օր:',
    description2: 'Նիսն ոչ միայն լողավայրի տեղ է՝ այլ մշակույթային մայրաքաղաք:',
    whyChoose: 'Ինչու ընտրել մեր տրանսֆեր նիսի օդանավայանից',
    feature1Title: 'Դիմավորում', feature1Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով: 60 րոպե անվճար սպասման ժամանակ:',
    feature2Title: 'Թռիչքի հետևում', feature2Desc: 'Իրական ժամանակում թռիչքի հետևում: Անվճար:',
    feature3Title: 'Պրեմիում մեքենաներ', feature3Desc: 'Mercedes E-Class, BMW 5: Մաքուր, կլիմատիզացիա:',
    feature4Title: 'Ֆիքս գներ', feature4Desc: 'Գինը հաստատված է ամրագրման ժամանակ: Թաքնված վճարներ չկան:',
    sedan: 'Պրեմիում սեդան', sedanDesc: 'Mercedes E-Class, 1-3 ուղևոր',
    luxury: 'Լյուքս սեդան', luxuryDesc: 'Mercedes S-Class կամ BMW 7',
    minivan: 'Մինիվեն', minivanDesc: 'Mercedes V-Class, մինչև 6 ուղևոր',
    minibus: 'Մինիբուս', minibusDesc: 'Մինչև 8 ուղևոր',
    passengers: 'Ուղևորներ', luggage: 'Ուղեբարան',
    bookNow: 'ԱՄՏԱԳՏՎԵԼ', allInclusive: 'Ամեն ինչ ներառված է',
    vehiclesTitle: 'Ընտրեք մեքենան',
    howItWorks: 'Ինչպես է աշխատում',
    step1: 'Ամրագրեք օնլայն', step1Desc: 'Մուտքագրեք ձեր տվյալները և հասցեն: Ակնթարթ գնի հաստատում:',
    step2: 'Հանդիպեք վարորդին', step2Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով:',
    step3: 'Հանգստացեք', step3Desc: 'Հարմարավետ ուղևորություն պրեմիում մեքենայում:',
    popularRoutesTitle: 'Սկսած', fromLabel: 'Սկսած',
    bookingForm: 'ԱՄՏԱԳՏՎԵԼ',
    pickupLabel: 'Վերցնում', dropoffLabel: 'Իջնում',
    dateLabel: 'Ամսաթիվ', timeLabel: 'Ժամ',
    defaultPickup: '',
    otherCitiesTitle: 'Սպասարկում ենք 16 քաղաքներ Եվրոպայում',
    otherCitiesBtn: 'Բոլոր ուղղությունները',
    rating: '4.5/5 Tripadvisor',
    meetDriverTitle: 'Որdelays delays Nice delays delays',
    meetDriverText: 'Delays delays delays delays delays delays delays delays.',
  },
};

const vehiclesPrices = { sedan: 35, luxury: 55, minivan: 85, minibus: 140 };

const seoUrls = { en: '/nice-airport-transfer', fr: '/transfert-aeroport-nice', ru: '/taksi-iz-aeroporta-nitstsa', hy: '/nis-odanavakayani-transfer' };
const NiceTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} meetDriverImage="/images/beauvais-driver-meet.webp" />;
export default NiceTransfer;
