import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Nice Airport Transfer - Cote d\'Azur Airport',
    subtitle: 'Private driver service from Nice Cote d\'Azur Airport to your hotel, city center or anywhere on the French Riviera',
    description: 'Book your Nice airport transfer with professional English-speaking drivers. We offer premium private car service from Nice Cote d\'Azur Airport (NCE) to Nice city center, Promenade des Anglais hotels, Old Town Nice, and all destinations on the French Riviera. Fixed prices, flight tracking, meet and greet with name sign at arrivals.',
    description2: 'Nice Cote d\'Azur is the third busiest airport in France, serving millions of travelers heading to the French Riviera. Our professional drivers know every route and shortcut, ensuring you reach your destination quickly and comfortably. Whether you are visiting Nice for business, leisure, or connecting to Monaco, Cannes or Saint-Tropez, we provide reliable door-to-door service.',
    whyChoose: 'Why Choose Our Nice Airport Transfer?',
    feature1Title: 'Meet & Greet at NCE', feature1Desc: 'Your driver waits at Nice Airport arrivals with a personalized name sign. 60 minutes free waiting time for flight delays.',
    feature2Title: 'Real-Time Flight Tracking', feature2Desc: 'We monitor your flight status. No extra charge if your flight is delayed.',
    feature3Title: 'Premium Vehicles', feature3Desc: 'Air-conditioned, clean vehicles less than 3 years old. Mercedes, BMW, or similar.',
    feature4Title: 'Fixed Prices', feature4Desc: 'Price confirmed at booking. No hidden fees, no surge pricing. Tolls included.',
    sedan: 'Premium Sedan', sedanDesc: 'Ideal for 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes E-Class or similar',
    minivan: 'Minivan', minivanDesc: 'For groups up to 6 passengers', minibus: 'Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter your flight details and destination. Instant price confirmation.',
    step2: 'Meet Your Driver', step2Desc: 'Driver waits at arrivals with your name sign. Help with luggage included.',
    step3: 'Relax & Enjoy', step3Desc: 'Comfortable ride in a premium vehicle directly to your destination.',
    popularRoutesTitle: 'Popular Nice Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'Nice Airport → Nice City Center', price: 35 },
      { name: 'Nice Airport → Monaco', price: 65 },
      { name: 'Nice Airport → Cannes', price: 75 },
      { name: 'Nice Airport → Saint-Tropez', price: 250 },
    ],
    bookingForm: 'Book Your Nice Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Nice Cote d\'Azur Airport (NCE)',
    otherCitiesTitle: 'We also serve other cities in Europe', otherCitiesBtn: 'View All Destinations',
    rating: '4.9/5 (1,850+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Nice - Cote d\'Azur',
    subtitle: 'Service de chauffeur prive depuis l\'aeroport de Nice vers votre hotel, le centre-ville ou toute la Cote d\'Azur',
    description: 'Reservez votre transfert aeroport Nice avec des chauffeurs professionnels francophones. Nous proposons un service de voiture privee premium depuis l\'aeroport Nice Cote d\'Azur (NCE) vers le centre-ville de Nice, les hotels de la Promenade des Anglais, le Vieux Nice et toutes les destinations de la Riviera francaise. Prix fixes, suivi des vols, accueil personnalise avec pancarte nominative.',
    description2: 'Nice Cote d\'Azur est le troisieme aeroport le plus frequente de France, desservant des millions de voyageurs se rendant sur la Cote d\'Azur. Nos chauffeurs professionnels connaissent chaque itineraire et raccourci, garantissant que vous atteignez votre destination rapidement et confortablement.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Nice ?',
    feature1Title: 'Accueil Personnalise NCE', feature1Desc: 'Votre chauffeur vous attend aux arrivees de l\'aeroport de Nice avec une pancarte a votre nom. 60 minutes d\'attente gratuites.',
    feature2Title: 'Suivi des Vols en Temps Reel', feature2Desc: 'Nous surveillons votre vol. Aucun supplement en cas de retard.',
    feature3Title: 'Vehicules Premium', feature3Desc: 'Vehicules climatises, propres, de moins de 3 ans. Mercedes, BMW ou similaire.',
    feature4Title: 'Prix Fixes Garantis', feature4Desc: 'Prix confirme a la reservation. Pas de frais caches, peages inclus.',
    sedan: 'Berline Premium', sedanDesc: 'Ideal pour 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe E ou similaire',
    minivan: 'Monospace', minivanDesc: 'Pour groupes jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Pour groupes jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez les details de votre vol et destination. Confirmation du prix immediate.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Le chauffeur vous attend aux arrivees avec pancarte a votre nom.',
    step3: 'Detendez-vous', step3Desc: 'Transfert direct dans un vehicule premium climatise vers votre destination.',
    popularRoutesTitle: 'Trajets Populaires Transfert Aeroport Nice', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport Nice → Centre-ville Nice', price: 35 },
      { name: 'Aeroport Nice → Monaco', price: 65 },
      { name: 'Aeroport Nice → Cannes', price: 75 },
      { name: 'Aeroport Nice → Saint-Tropez', price: 250 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Nice',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Nice Cote d\'Azur (NCE)',
    otherCitiesTitle: 'Nous desservons aussi d\'autres villes en Europe', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.9/5 (1 850+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Ниццы - Лазурный Берег',
    subtitle: 'Услуги частного водителя из аэропорта Ницца Лазурный Берег в отель, центр города или любую точку Ривьеры',
    description: 'Забронируйте трансфер из аэропорта Ниццы с профессиональными русскоговорящими водителями. Мы предлагаем премиум-сервис частного автомобиля из аэропорта Ницца Лазурный Берег (NCE) в центр Ниццы, отели Английской набережной, Старый город и все направления Французской Ривьеры. Фиксированные цены, отслеживание рейсов, встреча с именной табличкой.',
    description2: 'Ницца Лазурный Берег - третий по загруженности аэропорт Франции. Наши профессиональные водители знают каждый маршрут, обеспечивая быструю и комфортную доставку до места назначения.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Ниццы?',
    feature1Title: 'Встреча в Аэропорту NCE', feature1Desc: 'Водитель ждет вас в зале прилета с табличкой. 60 минут ожидания бесплатно.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мы следим за вашим рейсом. Без доплаты за задержку.',
    feature3Title: 'Премиум Автомобили', feature3Desc: 'Чистые автомобили с кондиционером, не старше 3 лет. Mercedes, BMW.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Цена подтверждается при бронировании. Без скрытых платежей.',
    sedan: 'Премиум Седан', sedanDesc: 'Для 1-3 пассажиров', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes E-Class или аналогичный',
    minivan: 'Минивэн', minivanDesc: 'Для групп до 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'Для групп до 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Введите данные рейса и направление. Мгновенное подтверждение цены.',
    step2: 'Встретьте Водителя', step2Desc: 'Водитель ждет в зале прилета с табличкой с вашим именем.',
    step3: 'Расслабьтесь', step3Desc: 'Комфортная поездка в премиум автомобиле прямо до места назначения.',
    popularRoutesTitle: 'Популярные Маршруты из Аэропорта Ниццы', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт Ниццы → Центр Ниццы', price: 35 },
      { name: 'Аэропорт Ниццы → Монако', price: 65 },
      { name: 'Аэропорт Ниццы → Канны', price: 75 },
      { name: 'Аэропорт Ниццы → Сен-Тропе', price: 250 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Ниццы',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Ницца Лазурный Берег (NCE)',
    otherCitiesTitle: 'Мы также обслуживаем другие города Европы', otherCitiesBtn: 'Все Направления',
    rating: '4.9/5 (1 850+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 35, luxury: 55, minivan: 85, minibus: 140 };

const NiceTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} />;
export default NiceTransfer;
