import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Orly Airport Transfer - Private Driver from 39\u20AC',
    subtitle: 'Affordable private driver from Paris Orly Airport to Paris city center, hotels and all destinations. Fixed prices from 39\u20AC',
    description: 'Paris-Orly is the insider\'s airport. Situated just 13 kilometres south of central Paris, it offers the quickest route to the Left Bank, the Latin Quarter, and Montparnasse — neighbourhoods that can take over an hour to reach from CDG. Yet despite its proximity, getting out of Orly without a private car still means decoding the OrlyVal shuttle to Antony, switching to the RER B, and hoping your Navigo pass works. Our Orly airport transfer eliminates every one of those steps. A professional driver waits at your terminal exit with a name board, takes your bags, and delivers you to any Paris address in 20 to 35 minutes via the A6 motorway or the scenic Route Nationale 7.',
    description2: 'Orly has recently completed a major modernization, merging its former Sud and Ouest terminals into four numbered halls (Orly 1 through 4). The redesigned airport is sleeker but still growing, and signage can be inconsistent. Our drivers stay updated on every construction detour, every temporary pickup zone, and every gate change. If you land at Orly 3 — the busiest hall for European flights — your chauffeur is positioned just beyond the sliding doors. If you arrive at Orly 1 on an intercontinental flight, the dedicated pickup lane is equally straightforward. No guessing, no walking in the rain to a distant parking lot.',
    description3: 'Orly is also the gateway to southern Paris attractions that tourists often overlook: the Rungis wholesale market (the largest fresh food market in the world), the charming village of Sceaux with its Le Notre gardens, and the vibrant Vietnamese neighbourhood of Choisy. For business travelers, the Orly-Rungis business park and the Courtaboeuf technology zone are minutes away. Many families flying budget airlines into Orly also use our service to reach Disneyland Paris (about 45 minutes east) — far more comfortable than two metro changes with toddlers and luggage. Reserve your Orly transfer today and start your Parisian adventure the moment you land.',
    whyChoose: 'Why Choose Our Orly Airport Transfer?',
    feature1Title: 'Orly 1-4 Coverage', feature1Desc: 'Pickup from all four Orly halls. Driver right at your terminal exit with name sign.',
    feature2Title: 'Fastest to Left Bank', feature2Desc: 'Just 20 minutes to Saint-Germain, Latin Quarter, Montparnasse. No RER or shuttle needed.',
    feature3Title: 'Premium Vehicles', feature3Desc: 'Mercedes E-Class, BMW 5 Series. Clean, air-conditioned, less than 3 years old.',
    feature4Title: 'Fixed Prices from 39\u20AC', feature4Desc: 'Price confirmed at booking. Tolls included. No surge pricing. Affordable for everyone.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class or BMW 7 Series',
    minivan: 'Minivan', minivanDesc: 'Mercedes V-Class, up to 6 passengers', minibus: 'Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter your Orly hall number, flight details and destination. Instant price.',
    step2: 'Meet Your Driver', step2Desc: 'Driver waits at your Orly terminal exit with a personalized name sign.',
    step3: 'Relax & Enjoy', step3Desc: 'Comfortable ride to central Paris in just 20-35 minutes.',
    popularRoutesTitle: 'Popular Orly Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'Orly Airport \u2192 Paris City Center', price: 45 },
      { name: 'Orly Airport \u2192 Latin Quarter / Sorbonne', price: 42 },
      { name: 'Orly Airport \u2192 Eiffel Tower / Trocadero', price: 48 },
      { name: 'Orly Airport \u2192 Disneyland Paris', price: 90 },
    ],
    bookingForm: 'Book Your Orly Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Paris Orly Airport',
    otherCitiesTitle: 'Also available from CDG and Beauvais airports', otherCitiesBtn: 'View All Destinations',
    rating: '4.5/5 Tripadvisor (29 reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Orly - Chauffeur Prive des 39\u20AC',
    subtitle: 'Chauffeur prive depuis l\'aeroport Paris-Orly vers Paris centre, hotels et toutes destinations. Prix fixes des 39\u20AC',
    description: 'Paris-Orly est l\'aeroport des inities. Situe a seulement 13 kilometres au sud du centre de Paris, il offre l\'acces le plus rapide a la Rive Gauche, au Quartier Latin et a Montparnasse — des quartiers qui peuvent prendre plus d\'une heure depuis CDG. Pourtant, malgre sa proximite, sortir d\'Orly sans voiture privee implique de dechiffrer la navette OrlyVal jusqu\'a Antony, de changer pour le RER B, et d\'esperer que votre passe Navigo fonctionne. Notre transfert aeroport Orly elimine chacune de ces etapes. Un chauffeur professionnel vous attend a la sortie de votre terminal avec une pancarte nominative, prend vos bagages et vous depose a n\'importe quelle adresse parisienne en 20 a 35 minutes par l\'autoroute A6 ou la pittoresque Nationale 7.',
    description2: 'Orly a recemment acheve une modernisation majeure, fusionnant ses anciens terminaux Sud et Ouest en quatre halls numerotes (Orly 1 a 4). L\'aeroport redesigne est plus elegant mais toujours en evolution, et la signaletique peut etre incoherente. Nos chauffeurs restent informes de chaque deviation de chantier, chaque zone de prise en charge temporaire et chaque changement de porte. Si vous atterrissez a Orly 3 — le hall le plus frequente pour les vols europeens — votre chauffeur est positionne juste apres les portes coulissantes. Si vous arrivez a Orly 1 sur un vol intercontinental, le point de prise en charge est tout aussi simple. Pas de doute, pas de marche sous la pluie vers un parking eloigne.',
    description3: 'Orly est aussi la porte d\'entree vers des attractions du sud parisien souvent meconnues des touristes : le marche de Rungis (le plus grand marche de produits frais au monde), le charmant village de Sceaux avec ses jardins de Le Notre, et le quartier vietnamien anime de Choisy. Pour les voyageurs d\'affaires, le parc d\'activites Orly-Rungis et la zone technologique de Courtaboeuf sont a quelques minutes. De nombreuses familles voyageant en low-cost via Orly utilisent aussi notre service pour rejoindre Disneyland Paris (environ 45 minutes a l\'est) — bien plus confortable que deux changements de metro avec des enfants et des valises. Reservez votre transfert Orly aujourd\'hui et commencez votre aventure parisienne des l\'atterrissage.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Orly ?',
    feature1Title: 'Couverture Orly 1-4', feature1Desc: 'Prise en charge depuis les quatre halls. Chauffeur a la sortie avec pancarte.',
    feature2Title: 'Le Plus Rapide vers la Rive Gauche', feature2Desc: '20 minutes vers Saint-Germain, Quartier Latin, Montparnasse. Sans RER ni navette.',
    feature3Title: 'Vehicules Premium', feature3Desc: 'Mercedes Classe E, BMW Serie 5. Propres, climatises, moins de 3 ans.',
    feature4Title: 'Prix Fixes des 39\u20AC', feature4Desc: 'Prix confirme a la reservation. Peages inclus. Accessible a tous.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E, 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S ou BMW Serie 7',
    minivan: 'Monospace', minivanDesc: 'Mercedes Classe V, jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Pour groupes jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez votre hall Orly, vol et destination. Prix instantane.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Le chauffeur vous attend a la sortie de votre terminal Orly.',
    step3: 'Detendez-vous', step3Desc: 'Trajet confortable vers Paris centre en 20-35 minutes seulement.',
    popularRoutesTitle: 'Trajets Populaires depuis Orly', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport Orly \u2192 Centre de Paris', price: 45 },
      { name: 'Aeroport Orly \u2192 Quartier Latin / Sorbonne', price: 42 },
      { name: 'Aeroport Orly \u2192 Tour Eiffel / Trocadero', price: 48 },
      { name: 'Aeroport Orly \u2192 Disneyland Paris', price: 90 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Orly',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Paris Orly',
    otherCitiesTitle: 'Egalement depuis CDG et Beauvais', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.5/5 Tripadvisor (29 avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Орли - Частный Автомобиль с Водителем',
    subtitle: 'Премиум трансфер из аэропорта Париж-Орли в центр Парижа, отели и все направления',
    description: 'Париж-Орли — аэропорт для знающих. Расположенный всего в 13 километрах к югу от центра Парижа, он обеспечивает самый быстрый путь на Левый берег, в Латинский квартал и к Монпарнасу — районы, до которых из CDG можно добираться больше часа. Однако несмотря на близость, выбраться из Орли без частного автомобиля означает разбираться в шаттле OrlyVal до Антони, пересаживаться на RER B и надеяться, что ваш проездной Навиго сработает. Наш трансфер из Орли устраняет все эти шаги. Профессиональный водитель ждёт вас на выходе из терминала с именной табличкой, забирает багаж и доставляет по любому парижскому адресу за 20-35 минут по автомагистрали A6.',
    description2: 'Орли недавно завершил масштабную модернизацию, объединив бывшие терминалы Сюд и Уэст в четыре пронумерованных зала (Орли 1-4). Обновлённый аэропорт стал современнее, но навигация может быть непоследовательной. Наши водители в курсе каждого строительного объезда, каждой временной зоны посадки и каждого изменения выхода. Приземлились в Орли 3 — самом загруженном зале для европейских рейсов? Ваш шофёр стоит сразу за раздвижными дверями. Прилетели в Орли 1 на межконтинентальном рейсе? Точка посадки столь же удобна.',
    description3: 'Орли — ворота к достопримечательностям южного Парижа, часто упускаемым туристами: рынок Ранжис (крупнейший продовольственный рынок в мире), очаровательный Со с садами Ле Нотра, оживлённый вьетнамский квартал Шуази. Для деловых путешественников бизнес-парк Орли-Ранжис и технопарк Куртабёф в нескольких минутах. Семьи, прилетающие лоукостерами, используют наш сервис для поездки в Диснейленд (45 минут на восток) — куда комфортнее, чем две пересадки в метро с детьми и чемоданами. Забронируйте трансфер из Орли и начните парижское приключение с момента посадки.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Орли?',
    feature1Title: 'Орли 1-4', feature1Desc: 'Встреча у всех четырёх залов. Водитель на выходе с табличкой.',
    feature2Title: 'Быстрее Всего до Левого Берега', feature2Desc: '20 минут до Сен-Жермен, Латинского квартала, Монпарнаса. Без RER.',
    feature3Title: 'Премиум Автомобили', feature3Desc: 'Mercedes E-Class, BMW 5 серии. Чистые, с кондиционером.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Цена при бронировании. Включая дорожные сборы.',
    sedan: 'Премиум Седан', sedanDesc: 'Mercedes E-Class, 1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes S-Class или BMW 7',
    minivan: 'Минивэн', minivanDesc: 'Mercedes V-Class, до 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Укажите зал Орли, рейс и адрес. Мгновенная цена.',
    step2: 'Встретьте Водителя', step2Desc: 'Водитель ждёт на выходе из вашего терминала.',
    step3: 'Расслабьтесь', step3Desc: 'Комфортная поездка в центр Парижа за 20-35 минут.',
    popularRoutesTitle: 'Популярные Маршруты из Орли', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт Орли \u2192 Центр Парижа', price: 45 },
      { name: 'Аэропорт Орли \u2192 Латинский квартал', price: 42 },
      { name: 'Аэропорт Орли \u2192 Эйфелева башня', price: 48 },
      { name: 'Аэропорт Орли \u2192 Диснейленд', price: 90 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Орли',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Париж Орли',
    otherCitiesTitle: 'Также из CDG и Бове', otherCitiesBtn: 'Все Направления',
    rating: '4.5/5 Tripadvisor (29 отзывов)',
  },
  hy: {
    title: 'Տրանսֆեր Orly օդանավայանից',
    subtitle: 'Մասնավոր վարորդ Orly-ից Փարիզի կենտրոն',
    description: 'Orly-ն ընդամենը 13 կմ է Փարիզի կենտրոնից՝ ամենաարագ ճանապարհը Ձախ ափ՝ Լատինական թաղամաս և Մոնպարնաս: 4 սրահներից (Orly 1-4) վերցնում ձեր վարորդը սպասում է ելքին: Rungis-ի շուկան (աշխարհի ամենամեծ սննդի շուկան)՝ Sceaux-ի այգիները և Վիետնամական թաղամասը մոտակա են: Դիսնեյլենդը 45 րոպե է:',
    description2: '20 րոպեում տանում ենք Փարիզի կենտրոն A6 մագիստրալով:',
    whyChoose: 'Ինչու ընտրել մեր տրանսֆեր orly օդանավայանից',
    feature1Title: 'Դիմավորում', feature1Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով: 60 րոպե անվճար սպասման ժամանակ:',
    feature2Title: 'Թռիչքի հետևում', feature2Desc: 'Իրական ժամանակում թռիչքի հետևում: Անվճար:',
    feature3Title: 'Պրեմիում մեքենաներ', feature3Desc: 'Mercedes E-Class, BMW 5: Մաքուր, կլիմատիզացիա:',
    feature4Title: 'Ֆիքս գներ', feature4Desc: 'Գինը հաստատված է ամրագրման ժամանակ: Թաքնված վճարներ չկան:',
    sedan: 'Պրեմիում սեդան', sedanDesc: 'Mercedes E-Class, 1-3 ուղևոր',
    luxury: 'Լյուքս սեդան', luxuryDesc: 'Mercedes S-Class կամ BMW 7',
    minivan: 'Մինիվեն', minivanDesc: 'Mercedes V-Class, մինչև 6 ուղևոր',
    minibus: 'Մինիբուս', minibusDesc: 'Մինչև 8 ուղևոր',
    passengers: 'Ուղևորներ', luggage: 'Ուղեբարան',
    bookNow: 'ԱՄՏԱԳՏՎԵԼ', allInclusive: 'Ամեն ինչ ներառված է',
    vehiclesTitle: 'Ընտրեք մեքենան',
    howItWorks: 'Ինչպես է աշխատում',
    step1: 'Ամրագրեք օնլայն', step1Desc: 'Մուտքագրեք ձեր տվյալները և հասցեն: Ակնթարթ գնի հաստատում:',
    step2: 'Հանդիպեք վարորդին', step2Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով:',
    step3: 'Հանգստացեք', step3Desc: 'Հարմարավետ ուղևորություն պրեմիում մեքենայում:',
    popularRoutesTitle: 'Սկսած', fromLabel: 'Սկսած',
    bookingForm: 'ԱՄՏԱԳՏՎԵԼ',
    pickupLabel: 'Վերցնում', dropoffLabel: 'Իջնում',
    dateLabel: 'Ամսաթիվ', timeLabel: 'Ժամ',
    defaultPickup: '',
    otherCitiesTitle: 'Սպասարկում ենք 16 քաղաքներ Եվրոպայում',
    otherCitiesBtn: 'Բոլոր ուղղությունները',
    rating: '4.5/5 Tripadvisor',
  },
};

const vehiclesPrices = { sedan: 45, luxury: 70, minivan: 100, minibus: 160 };

const seoUrls = { en: '/orly-airport-transfer', fr: '/transfert-aeroport-orly', ru: '/taksi-iz-aeroporta-orli', hy: '/orli-odanavakayani-transfer' };
const OrlyTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default OrlyTransfer;
