import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Orly Airport Transfer - Private Car Service',
    subtitle: 'Premium private driver from Paris Orly Airport to Paris city center, hotels and all destinations',
    description: 'Book your Orly airport transfer with professional English-speaking drivers. Paris Orly Airport (ORY) is the second largest airport in the Paris region, located just 13 km south of the city center. We provide premium private car transfers from Orly Terminals 1-4 to central Paris, the Latin Quarter, Montparnasse, Saint-Germain-des-Pres, and any destination in the Ile-de-France region. Fixed prices, flight monitoring, meet and greet at arrivals.',
    description2: 'Orly Airport is perfectly positioned for quick access to the Left Bank of Paris. With our private transfer, you can reach central Paris in just 20-30 minutes, avoiding the hassle of public transport or expensive metered taxis. Our drivers know every route and shortcut, ensuring a fast and comfortable journey to your hotel or meeting.',
    whyChoose: 'Why Choose Our Orly Airport Transfer?',
    feature1Title: 'All Orly Terminals', feature1Desc: 'Service from Terminals 1, 2, 3 and 4. Driver meets you at arrivals with name sign.',
    feature2Title: 'Flight Monitoring', feature2Desc: 'Real-time flight tracking. No surcharge for delays. 60 minutes free waiting.',
    feature3Title: 'Quick to Paris', feature3Desc: 'Only 20-30 minutes to central Paris. Premium vehicles with air conditioning.',
    feature4Title: 'Fixed Prices', feature4Desc: 'Price confirmed at booking. No hidden fees, tolls and parking included.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class or BMW 7 Series',
    minivan: 'Minivan', minivanDesc: 'Mercedes V-Class, up to 6 passengers', minibus: 'Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter your Orly terminal, flight number, and Paris address.',
    step2: 'Meet Your Driver', step2Desc: 'Driver waits at your Orly terminal arrivals with personalized name sign.',
    step3: 'Fast to Paris', step3Desc: 'Comfortable 20-30 minute ride directly to your Paris destination.',
    popularRoutesTitle: 'Popular Orly Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'Orly Airport → Paris City Center', price: 45 },
      { name: 'Orly Airport → Montparnasse / Saint-Germain', price: 42 },
      { name: 'Orly Airport → Tour Eiffel / Trocadero', price: 45 },
      { name: 'Orly Airport → Gare de Lyon', price: 48 },
    ],
    bookingForm: 'Book Your Orly Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Paris Orly Airport (ORY)',
    otherCitiesTitle: 'Also available from other Paris airports', otherCitiesBtn: 'View All Destinations',
    rating: '4.9/5 (2,100+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Orly - Voiture Privee',
    subtitle: 'Chauffeur prive premium depuis l\'aeroport Paris-Orly vers Paris centre, hotels et toutes destinations',
    description: 'Reservez votre transfert aeroport Orly avec des chauffeurs professionnels francophones. L\'aeroport Paris-Orly (ORY) est le deuxieme aeroport de la region parisienne, situe a seulement 13 km au sud du centre-ville. Nous proposons des transferts en voiture privee premium depuis les Terminaux 1-4 d\'Orly vers Paris centre, le Quartier Latin, Montparnasse, Saint-Germain-des-Pres et toute destination en Ile-de-France. Prix fixes, suivi de vol, accueil aux arrivees.',
    description2: 'L\'aeroport d\'Orly est idealement situe pour un acces rapide a la Rive Gauche de Paris. Avec notre transfert prive, rejoignez le centre de Paris en seulement 20-30 minutes, sans les desagrements des transports en commun ou les taxis au compteur.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Orly ?',
    feature1Title: 'Tous les Terminaux Orly', feature1Desc: 'Service depuis Terminaux 1, 2, 3 et 4. Chauffeur aux arrivees avec pancarte.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Suivi en temps reel. Aucun supplement pour retard. 60 min d\'attente gratuites.',
    feature3Title: 'Rapide vers Paris', feature3Desc: 'Seulement 20-30 minutes vers le centre. Vehicules premium climatises.',
    feature4Title: 'Prix Fixes', feature4Desc: 'Prix confirme a la reservation. Pas de frais caches, peages et parking inclus.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E, 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S ou BMW Serie 7',
    minivan: 'Monospace', minivanDesc: 'Mercedes Classe V, jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Pour groupes jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez votre terminal Orly, numero de vol et adresse a Paris.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Chauffeur aux arrivees de votre terminal Orly avec pancarte nominative.',
    step3: 'Rapide vers Paris', step3Desc: 'Trajet confortable de 20-30 minutes vers votre destination parisienne.',
    popularRoutesTitle: 'Trajets Populaires depuis Orly', fromLabel: 'A partir de',
    routes: [
      { name: 'Aeroport Orly → Paris Centre', price: 45 },
      { name: 'Aeroport Orly → Montparnasse / Saint-Germain', price: 42 },
      { name: 'Aeroport Orly → Tour Eiffel / Trocadero', price: 45 },
      { name: 'Aeroport Orly → Gare de Lyon', price: 48 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Orly',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Paris-Orly (ORY)',
    otherCitiesTitle: 'Egalement disponible depuis les autres aeroports parisiens', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.9/5 (2 100+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Орли - Частный Автомобиль',
    subtitle: 'Премиум трансфер из аэропорта Париж-Орли в центр Парижа, отели и все направления',
    description: 'Забронируйте трансфер из аэропорта Орли с профессиональными русскоговорящими водителями. Аэропорт Париж-Орли (ORY) - второй по величине аэропорт парижского региона, расположенный всего в 13 км к югу от центра города. Премиум-трансферы из терминалов 1-4 Орли в центр Парижа, Латинский квартал, Монпарнас, Сен-Жермен-де-Пре и любой адрес в Иль-де-Франс.',
    description2: 'Аэропорт Орли идеально расположен для быстрого доступа к Левому берегу Парижа. Доберитесь до центра за 20-30 минут без проблем с общественным транспортом.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Орли?',
    feature1Title: 'Все Терминалы Орли', feature1Desc: 'Терминалы 1, 2, 3 и 4. Водитель встречает с табличкой.',
    feature2Title: 'Отслеживание Рейсов', feature2Desc: 'Мониторинг в реальном времени. 60 минут ожидания бесплатно.',
    feature3Title: 'Быстро в Париж', feature3Desc: 'Всего 20-30 минут до центра. Премиум авто с кондиционером.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Цена при бронировании. Без скрытых платежей.',
    sedan: 'Премиум Седан', sedanDesc: 'Mercedes E-Class, 1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes S-Class или BMW 7',
    minivan: 'Минивэн', minivanDesc: 'Mercedes V-Class, до 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Введите терминал Орли, номер рейса и адрес.',
    step2: 'Встретьте Водителя', step2Desc: 'Водитель ждет в зале прилета вашего терминала.',
    step3: 'Быстро в Париж', step3Desc: 'Комфортная поездка 20-30 минут.',
    popularRoutesTitle: 'Популярные Маршруты из Орли', fromLabel: 'От',
    routes: [
      { name: 'Аэропорт Орли → Центр Парижа', price: 45 },
      { name: 'Аэропорт Орли → Монпарнас / Сен-Жермен', price: 42 },
      { name: 'Аэропорт Орли → Эйфелева Башня', price: 45 },
      { name: 'Аэропорт Орли → Лионский Вокзал', price: 48 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Орли',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Париж-Орли (ORY)',
    otherCitiesTitle: 'Также из других парижских аэропортов', otherCitiesBtn: 'Все Направления',
    rating: '4.9/5 (2 100+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 45, luxury: 70, minivan: 100, minibus: 155 };

const OrlyTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} />;
export default OrlyTransfer;
