import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Paris Train Station Transfer - Private Car Service',
    subtitle: 'Premium private driver to and from all Paris train stations: Gare du Nord, Gare de Lyon, Gare Montparnasse, Gare de l\'Est, Gare Saint-Lazare',
    description: 'Book your Paris train station transfer with professional English-speaking drivers. Paris is home to six major train stations, each serving different destinations across France and Europe. We provide premium private car transfers to and from Gare du Nord (Eurostar, Thalys), Gare de Lyon (TGV South), Gare Montparnasse (TGV West), Gare de l\'Est (TGV East), Gare Saint-Lazare (Normandy), and Gare d\'Austerlitz. Door-to-door service between any train station and your hotel, airport, or Paris address.',
    description2: 'Arriving in Paris by train can be overwhelming, especially with heavy luggage. Our private transfer service eliminates the stress of navigating the metro or finding a taxi. Whether you are arriving from London via Eurostar at Gare du Nord, from Lyon at Gare de Lyon, or connecting between stations, our drivers are waiting for you right at the station exit. We also offer inter-station transfers for travelers with tight connections.',
    whyChoose: 'Why Choose Our Paris Train Station Transfer?',
    feature1Title: 'All 6 Stations', feature1Desc: 'Gare du Nord, Gare de Lyon, Montparnasse, Gare de l\'Est, Saint-Lazare, Austerlitz.',
    feature2Title: 'Train Monitoring', feature2Desc: 'We track your train arrival. Driver adjusts to delays automatically.',
    feature3Title: 'Meet at Station', feature3Desc: 'Driver waits near the platform exit with your name sign. Help with luggage.',
    feature4Title: 'Fixed Prices', feature4Desc: 'Price confirmed at booking. No hidden fees. Station-to-hotel or station-to-airport.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class or similar',
    minivan: 'Minivan', minivanDesc: 'Mercedes V-Class, up to 6 passengers', minibus: 'Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Select your train station, train number, and destination address.',
    step2: 'Meet Your Driver', step2Desc: 'Driver waits at the station exit with personalized name sign.',
    step3: 'Direct Transfer', step3Desc: 'Comfortable ride to your hotel, airport, or any Paris destination.',
    popularRoutesTitle: 'Popular Paris Train Station Transfers', fromLabel: 'From',
    routes: [
      { name: 'Gare du Nord → Paris Hotel / Apartment', price: 25 },
      { name: 'Gare de Lyon → Paris Hotel / Apartment', price: 25 },
      { name: 'Gare du Nord → CDG Airport', price: 65 },
      { name: 'Gare Montparnasse → Orly Airport', price: 50 },
    ],
    bookingForm: 'Book Your Paris Train Station Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Gare du Nord, Paris',
    otherCitiesTitle: 'Also available for Paris airports', otherCitiesBtn: 'View All Destinations',
    rating: '4.9/5 (1,800+ reviews)',
  },
  fr: {
    title: 'Transfert Gare de Paris - Voiture Privee avec Chauffeur',
    subtitle: 'Chauffeur prive premium depuis et vers toutes les gares parisiennes : Gare du Nord, Gare de Lyon, Gare Montparnasse, Gare de l\'Est, Gare Saint-Lazare',
    description: 'Reservez votre transfert gare de Paris avec des chauffeurs professionnels francophones. Paris compte six grandes gares, chacune desservant differentes destinations en France et en Europe. Nous proposons des transferts en voiture privee premium depuis et vers la Gare du Nord (Eurostar, Thalys), la Gare de Lyon (TGV Sud), la Gare Montparnasse (TGV Ouest), la Gare de l\'Est (TGV Est), la Gare Saint-Lazare (Normandie) et la Gare d\'Austerlitz. Service porte-a-porte entre toute gare et votre hotel, aeroport ou adresse parisienne.',
    description2: 'Arriver a Paris en train peut etre stressant, surtout avec des bagages lourds. Notre service de transfert prive elimine le stress du metro ou de la recherche d\'un taxi. Que vous arriviez de Londres par l\'Eurostar a la Gare du Nord, de Lyon a la Gare de Lyon, ou que vous ayez une correspondance entre gares, nos chauffeurs vous attendent a la sortie des quais.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Gare de Paris ?',
    feature1Title: 'Les 6 Gares', feature1Desc: 'Gare du Nord, Gare de Lyon, Montparnasse, Gare de l\'Est, Saint-Lazare, Austerlitz.',
    feature2Title: 'Suivi du Train', feature2Desc: 'Nous suivons l\'arrivee de votre train. Le chauffeur s\'adapte aux retards.',
    feature3Title: 'Accueil en Gare', feature3Desc: 'Chauffeur a la sortie des quais avec pancarte nominative. Aide aux bagages.',
    feature4Title: 'Prix Fixes', feature4Desc: 'Prix confirme a la reservation. Pas de frais caches. Gare-hotel ou gare-aeroport.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E, 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S ou similaire',
    minivan: 'Monospace', minivanDesc: 'Mercedes Classe V, jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Pour groupes jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Selectionnez votre gare, numero de train et adresse de destination.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Chauffeur a la sortie de la gare avec pancarte personnalisee.',
    step3: 'Transfert Direct', step3Desc: 'Trajet confortable vers votre hotel, aeroport ou toute destination parisienne.',
    popularRoutesTitle: 'Transferts Gare de Paris Populaires', fromLabel: 'A partir de',
    routes: [
      { name: 'Gare du Nord → Hotel / Appartement Paris', price: 25 },
      { name: 'Gare de Lyon → Hotel / Appartement Paris', price: 25 },
      { name: 'Gare du Nord → Aeroport CDG', price: 65 },
      { name: 'Gare Montparnasse → Aeroport Orly', price: 50 },
    ],
    bookingForm: 'Reservez Votre Transfert Gare de Paris',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Gare du Nord, Paris',
    otherCitiesTitle: 'Egalement disponible pour les aeroports parisiens', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.9/5 (1 800+ avis)',
  },
  ru: {
    title: 'Трансфер с Вокзалов Парижа - Частный Автомобиль',
    subtitle: 'Премиум трансфер со всех вокзалов Парижа: Гар дю Нор, Гар де Лион, Монпарнас, Гар де л\'Эст, Сен-Лазар',
    description: 'Забронируйте трансфер с вокзала Парижа с профессиональными русскоговорящими водителями. В Париже шесть крупных вокзалов. Мы обеспечиваем премиум-трансферы с Гар дю Нор (Eurostar, Thalys), Гар де Лион (TGV Юг), Монпарнас (TGV Запад), Гар де л\'Эст (TGV Восток), Сен-Лазар (Нормандия) и Аустерлиц. Сервис от двери до двери между вокзалом и отелем, аэропортом или любым адресом.',
    description2: 'Прибытие в Париж поездом может быть стрессовым, особенно с тяжелым багажом. Наш водитель ждет вас у выхода с платформы с именной табличкой.',
    whyChoose: 'Почему Выбрать Наш Трансфер с Вокзалов Парижа?',
    feature1Title: 'Все 6 Вокзалов', feature1Desc: 'Гар дю Нор, Гар де Лион, Монпарнас, Гар де л\'Эст, Сен-Лазар, Аустерлиц.',
    feature2Title: 'Отслеживание Поезда', feature2Desc: 'Мониторинг прибытия. Водитель адаптируется к задержкам.',
    feature3Title: 'Встреча на Вокзале', feature3Desc: 'Водитель у выхода с платформы с табличкой. Помощь с багажом.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Цена при бронировании. Вокзал-отель или вокзал-аэропорт.',
    sedan: 'Премиум Седан', sedanDesc: 'Mercedes E-Class, 1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes S-Class',
    minivan: 'Минивэн', minivanDesc: 'Mercedes V-Class, до 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Выберите вокзал, номер поезда и адрес.',
    step2: 'Встретьте Водителя', step2Desc: 'Водитель ждет у выхода с табличкой.',
    step3: 'Прямой Трансфер', step3Desc: 'Комфортная поездка до отеля или аэропорта.',
    popularRoutesTitle: 'Популярные Трансферы с Вокзалов Парижа', fromLabel: 'От',
    routes: [
      { name: 'Гар дю Нор → Отель в Париже', price: 25 },
      { name: 'Гар де Лион → Отель в Париже', price: 25 },
      { name: 'Гар дю Нор → Аэропорт CDG', price: 65 },
      { name: 'Монпарнас → Аэропорт Орли', price: 50 },
    ],
    bookingForm: 'Забронируйте Трансфер с Вокзала Парижа',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Гар дю Нор, Париж',
    otherCitiesTitle: 'Также из аэропортов Парижа', otherCitiesBtn: 'Все Направления',
    rating: '4.9/5 (1 800+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 25, luxury: 45, minivan: 60, minibus: 90 };

const ParisTrainStationTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} />;
export default ParisTrainStationTransfer;
