import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Paris Train Station Transfer - Private Car Service',
    subtitle: 'Premium private driver to and from all Paris train stations: Gare du Nord, Gare de Lyon, Gare Montparnasse, Gare de l\'Est, Gare Saint-Lazare',
    description: 'Paris has six major train stations, each a gateway to a different corner of Europe, and none of them are easy to navigate with suitcases, children, or jet-lagged colleagues. Gare du Nord — the busiest station in Europe — handles Eurostar arrivals from London, Thalys from Brussels, and ICE trains from Amsterdam, depositing over 700,000 passengers per day into a neighbourhood that can feel chaotic to first-time visitors. Gare de Lyon sends TGVs racing south to Lyon, Marseille, and the Cote d\'Azur. Gare Montparnasse connects to Bordeaux and Brittany. Our private Paris train station transfer meets you at the platform exit with a name sign, handles your luggage, and drives you straight to your hotel, apartment, business meeting, or airport — in a clean, air-conditioned premium vehicle.',
    description2: 'What makes train stations particularly stressful is that they sit in different parts of Paris, and switching between them involves taxi queues or multiple metro lines with stairs and no lifts. A connection from Gare du Nord (10th arrondissement) to Gare Montparnasse (15th) takes over 40 minutes on public transport and requires hauling bags through the crowded Chatelet interchange — the labyrinthine metro junction that even Parisians avoid with heavy luggage. Our door-to-door service makes the same trip in 20 minutes by car, with your bags safely in the trunk. We also specialize in hotel pickups for departures: your driver arrives 15 minutes early, loads your suitcases, and ensures you reach the correct terminal at Gare de Lyon or the right platform at Gare du Nord.',
    description3: 'Many of our clients use train station transfers as part of a larger Paris itinerary. Arriving from London on the Eurostar? We take you from Gare du Nord to your Saint-Germain hotel. After three days exploring Montmartre, the Louvre, and the Marais, we pick you up and drive you to CDG Airport for your return flight. Business travelers often book a series of rides: morning pickup at the hotel, drive to Gare de Lyon for a day trip to Lyon, return pickup at Gare de Lyon in the evening, and back to the hotel. With fixed prices per route and no surge pricing, budgeting your Paris transport is finally simple. Book your Paris station transfer now.',
    whyChoose: 'Why Choose Our Paris Train Station Transfer?',
    feature1Title: 'All 6 Stations', feature1Desc: 'Gare du Nord, Gare de Lyon, Montparnasse, Gare de l\'Est, Saint-Lazare, Austerlitz.',
    feature2Title: 'Train Monitoring', feature2Desc: 'We track your train arrival. Driver adjusts to delays automatically.',
    feature3Title: 'Meet at Station', feature3Desc: 'Driver waits near the platform exit with your name sign. Help with luggage.',
    feature4Title: 'Fixed Prices', feature4Desc: 'Price confirmed at booking. No hidden fees. Station-to-hotel or station-to-airport.',
    sedan: 'Premium Sedan', sedanDesc: 'Mercedes E-Class, 1-3 passengers', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes S-Class or similar',
    minivan: 'Minivan', minivanDesc: 'Mercedes V-Class, up to 6 passengers', minibus: 'Minibus', minibusDesc: 'For groups up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Select your train station, train number, and destination address.',
    step2: 'Meet Your Driver', step2Desc: 'Driver waits at the station exit with personalized name sign.',
    step3: 'Direct Transfer', step3Desc: 'Comfortable ride to your hotel, airport, or any Paris destination.',
    popularRoutesTitle: 'Popular Paris Train Station Transfers', fromLabel: 'From',
    routes: [
      { name: 'Gare du Nord → Paris Hotel / Apartment', price: 25 },
      { name: 'Gare de Lyon → Paris Hotel / Apartment', price: 25 },
      { name: 'Gare du Nord → CDG Airport', price: 65 },
      { name: 'Gare Montparnasse → Orly Airport', price: 50 },
    ],
    bookingForm: 'Book Your Paris Train Station Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Gare du Nord, Paris',
    otherCitiesTitle: 'Also available for Paris airports', otherCitiesBtn: 'View All Destinations',
    rating: '4.9/5 (1,800+ reviews)',
  },
  fr: {
    title: 'Transfert Gare de Paris - Voiture Privee avec Chauffeur',
    subtitle: 'Chauffeur prive premium depuis et vers toutes les gares parisiennes : Gare du Nord, Gare de Lyon, Gare Montparnasse, Gare de l\'Est, Gare Saint-Lazare',
    description: 'Paris possede six grandes gares, chacune porte d\'entree vers un coin different de l\'Europe, et aucune n\'est facile a naviguer avec des valises, des enfants ou des collegues fatigues. La Gare du Nord — la plus frequentee d\'Europe — accueille les Eurostar de Londres, les Thalys de Bruxelles et les ICE d\'Amsterdam, deversant plus de 700 000 passagers par jour dans un quartier qui peut paraitre chaotique aux primo-visiteurs. La Gare de Lyon lance des TGV vers Lyon, Marseille et la Cote d\'Azur. Gare Montparnasse dessert Bordeaux et la Bretagne. Notre transfert prive vous attend a la sortie du quai avec une pancarte, prend vos bagages et vous conduit directement a votre hotel, appartement, reunion ou aeroport.',
    description2: 'Ce qui rend les gares particulierement stressantes, c\'est qu\'elles sont eparpillees dans Paris, et passer de l\'une a l\'autre implique des files de taxis ou plusieurs lignes de metro avec escaliers sans ascenseurs. Une correspondance de la Gare du Nord (10e) a Montparnasse (15e) prend 40 minutes en transport et necessite de trainer des valises dans le labyrinthe de Chatelet — le noeud metro que meme les Parisiens evitent avec des bagages. Notre service fait le meme trajet en 20 minutes en voiture, bagages en securite dans le coffre. Nous proposons aussi la prise en charge a l\'hotel pour les departs : votre chauffeur arrive 15 minutes en avance et vous depose au bon terminal ou quai.',
    description3: 'Beaucoup de clients integrent les transferts de gare dans un itineraire parisien complet. Arrivee de Londres par Eurostar ? Nous vous conduisons de la Gare du Nord a votre hotel a Saint-Germain. Apres trois jours a explorer Montmartre, le Louvre et le Marais, nous vous emmenons a CDG pour votre vol retour. Les voyageurs d\'affaires reservent souvent une serie de trajets : matin a l\'hotel, Gare de Lyon pour un aller-retour a Lyon, puis retour a l\'hotel le soir. Avec des prix fixes par trajet et sans majoration, budgeter vos transports parisiens devient enfin simple.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Gare de Paris ?',
    feature1Title: 'Les 6 Gares', feature1Desc: 'Gare du Nord, Gare de Lyon, Montparnasse, Gare de l\'Est, Saint-Lazare, Austerlitz.',
    feature2Title: 'Suivi du Train', feature2Desc: 'Nous suivons l\'arrivee de votre train. Le chauffeur s\'adapte aux retards.',
    feature3Title: 'Accueil en Gare', feature3Desc: 'Chauffeur a la sortie des quais avec pancarte nominative. Aide aux bagages.',
    feature4Title: 'Prix Fixes', feature4Desc: 'Prix confirme a la reservation. Pas de frais caches. Gare-hotel ou gare-aeroport.',
    sedan: 'Berline Premium', sedanDesc: 'Mercedes Classe E, 1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe S ou similaire',
    minivan: 'Monospace', minivanDesc: 'Mercedes Classe V, jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Pour groupes jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Selectionnez votre gare, numero de train et adresse de destination.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Chauffeur a la sortie de la gare avec pancarte personnalisee.',
    step3: 'Transfert Direct', step3Desc: 'Trajet confortable vers votre hotel, aeroport ou toute destination parisienne.',
    popularRoutesTitle: 'Transferts Gare de Paris Populaires', fromLabel: 'A partir de',
    routes: [
      { name: 'Gare du Nord → Hotel / Appartement Paris', price: 25 },
      { name: 'Gare de Lyon → Hotel / Appartement Paris', price: 25 },
      { name: 'Gare du Nord → Aeroport CDG', price: 65 },
      { name: 'Gare Montparnasse → Aeroport Orly', price: 50 },
    ],
    bookingForm: 'Reservez Votre Transfert Gare de Paris',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Gare du Nord, Paris',
    otherCitiesTitle: 'Egalement disponible pour les aeroports parisiens', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.9/5 (1 800+ avis)',
  },
  ru: {
    title: 'Трансфер с Вокзалов Парижа - Частный Автомобиль',
    subtitle: 'Премиум трансфер со всех вокзалов Парижа: Гар дю Нор, Гар де Лион, Монпарнас, Гар де л\'Эст, Сен-Лазар',
    description: 'В Париже шесть крупных вокзалов — каждый ведёт в свой уголок Европы, и ни на одном не просто ориентироваться с чемоданами, детьми или уставшими коллегами. Гар-дю-Нор — самый загруженный вокзал Европы — принимает Eurostar из Лондона, Thalys из Брюсселя и ICE из Амстердама, ежедневно выпуская 700 000 пассажиров в район, который может показаться хаотичным. Гар-де-Лион отправляет TGV на юг к Лиону, Марселю и Лазурному Берегу. Гар-Монпарнас связывает с Бордо и Бретанью. Наш частный трансфер встречает вас у выхода с платформы, забирает багаж и везёт прямо к отелю, апартаментам, встрече или аэропорту.',
    description2: 'Вокзалы Парижа разбросаны по городу, а пересадка между ними означает очереди на такси или несколько линий метро с лестницами без лифтов. Переезд с Гар-дю-Нор (10-й округ) до Монпарнаса (15-й) занимает 40 минут общественным транспортом через лабиринт Шатле — пересадочный узел, которого избегают даже парижане. Наш сервис делает тот же маршрут за 20 минут на автомобиле, багаж надёжно в багажнике.',
    description3: 'Многие клиенты используют вокзальные трансферы в рамках полного парижского маршрута: прибытие из Лондона на Eurostar — доставка с Гар-дю-Нор в отель Сен-Жермен. Через три дня — трансфер в аэропорт CDG на обратный рейс. Бизнес-путешественники заказывают серию поездок: утренний трансфер, Гар-де-Лион на дневную встречу в Лионе, вечерний возврат в отель. Фиксированные цены без накруток — планировать парижский транспорт теперь просто.',
    whyChoose: 'Почему Выбрать Наш Трансфер с Вокзалов Парижа?',
    feature1Title: 'Все 6 Вокзалов', feature1Desc: 'Гар дю Нор, Гар де Лион, Монпарнас, Гар де л\'Эст, Сен-Лазар, Аустерлиц.',
    feature2Title: 'Отслеживание Поезда', feature2Desc: 'Мониторинг прибытия. Водитель адаптируется к задержкам.',
    feature3Title: 'Встреча на Вокзале', feature3Desc: 'Водитель у выхода с платформы с табличкой. Помощь с багажом.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Цена при бронировании. Вокзал-отель или вокзал-аэропорт.',
    sedan: 'Премиум Седан', sedanDesc: 'Mercedes E-Class, 1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes S-Class',
    minivan: 'Минивэн', minivanDesc: 'Mercedes V-Class, до 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте Онлайн', step1Desc: 'Выберите вокзал, номер поезда и адрес.',
    step2: 'Встретьте Водителя', step2Desc: 'Водитель ждет у выхода с табличкой.',
    step3: 'Прямой Трансфер', step3Desc: 'Комфортная поездка до отеля или аэропорта.',
    popularRoutesTitle: 'Популярные Трансферы с Вокзалов Парижа', fromLabel: 'От',
    routes: [
      { name: 'Гар дю Нор → Отель в Париже', price: 25 },
      { name: 'Гар де Лион → Отель в Париже', price: 25 },
      { name: 'Гар дю Нор → Аэропорт CDG', price: 65 },
      { name: 'Монпарнас → Аэропорт Орли', price: 50 },
    ],
    bookingForm: 'Забронируйте Трансфер с Вокзала Парижа',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Гар дю Нор, Париж',
    otherCitiesTitle: 'Также из аэропортов Парижа', otherCitiesBtn: 'Все Направления',
    rating: '4.9/5 (1 800+ отзывов)',
  },
  hy: {
    title: 'Փարիզի կայարանների տրանսֆեր',
    subtitle: 'Մասնավոր վարորդ Փարիզի բոլոր կայարաններից',
    description: 'Փարիզն ունի 6 մեծ կայարան: Gare du Nord-ը Eurostar-ից Լոնդոնից՝ Gare de Lyon-ը TGV-ով հարավ: Մեր վարորդը սպասում է հարթակի ելքին և տանում է ձեր հյուրանոցին: Կայարանների միջև անցումը մետրով 40 րոպե է՝ մեր մեքենայով 20 րոպե:',
    description2: 'Շատ հաճախորդները օգտագործում են կայարանների տրանսֆերները Փարիզի լիարժեք երթուղու մասը:',
    whyChoose: 'Ինչու ընտրել մեր փարիզի կայարանների տրանսֆեր',
    feature1Title: 'Դիմավորում', feature1Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով: 60 րոպե անվճար սպասման ժամանակ:',
    feature2Title: 'Թռիչքի հետևում', feature2Desc: 'Իրական ժամանակում թռիչքի հետևում: Անվճար:',
    feature3Title: 'Պրեմիում մեքենաներ', feature3Desc: 'Mercedes E-Class, BMW 5: Մաքուր, կլիմատիզացիա:',
    feature4Title: 'Ֆիքս գներ', feature4Desc: 'Գինը հաստատված է ամրագրման ժամանակ: Թաքնված վճարներ չկան:',
    sedan: 'Պրեմիում սեդան', sedanDesc: 'Mercedes E-Class, 1-3 ուղևոր',
    luxury: 'Լյուքս սեդան', luxuryDesc: 'Mercedes S-Class կամ BMW 7',
    minivan: 'Մինիվեն', minivanDesc: 'Mercedes V-Class, մինչև 6 ուղևոր',
    minibus: 'Մինիբուս', minibusDesc: 'Մինչև 8 ուղևոր',
    passengers: 'Ուղևորներ', luggage: 'Ուղեբարան',
    bookNow: 'ԱՄՏԱԳՏՎԵԼ', allInclusive: 'Ամեն ինչ ներառված է',
    vehiclesTitle: 'Ընտրեք մեքենան',
    howItWorks: 'Ինչպես է աշխատում',
    step1: 'Ամրագրեք օնլայն', step1Desc: 'Մուտքագրեք ձեր տվյալները և հասցեն: Ակնթարթ գնի հաստատում:',
    step2: 'Հանդիպեք վարորդին', step2Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով:',
    step3: 'Հանգստացեք', step3Desc: 'Հարմարավետ ուղևորություն պրեմիում մեքենայում:',
    popularRoutesTitle: 'Սկսած', fromLabel: 'Սկսած',
    bookingForm: 'ԱՄՏԱԳՏՎԵԼ',
    pickupLabel: 'Վերցնում', dropoffLabel: 'Իջնում',
    dateLabel: 'Ամսաթիվ', timeLabel: 'Ժամ',
    defaultPickup: '',
    otherCitiesTitle: 'Սպասարկում ենք 120+ քաղաքներ Եվրոպայում',
    otherCitiesBtn: 'Բոլոր ուղղությունները',
    rating: '4.9/5',
  },
};

const vehiclesPrices = { sedan: 25, luxury: 45, minivan: 60, minibus: 90 };

const seoUrls = { en: '/paris-train-station-transfer', fr: '/transfert-gare-paris', ru: '/transfer-vokzal-parizh' };
const ParisTrainStationTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default ParisTrainStationTransfer;
