import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Rome Airport Transfer - Fiumicino & Ciampino',
    subtitle: 'Private driver service from Rome airports to city center, Vatican, Colosseum area and all Rome hotels',
    description: 'Book your Rome airport transfer with professional drivers. Rome has two airports: Leonardo da Vinci-Fiumicino (FCO), the main international airport located 32 km from the city center, and Ciampino (CIA), a smaller airport 15 km south. We provide premium private transfers from both airports to your hotel, the Vatican, Trastevere, the Colosseum area, Termini Station, and any Rome address. Fixed prices, flight tracking, meet and greet.',
    description2: 'Rome, the Eternal City, welcomes millions of visitors every year. Navigate the city like a VIP with our professional transfer service. No haggling with taxi drivers, no crowded trains - just a comfortable, direct ride from the airport to your Roman adventure.',
    whyChoose: 'Why Choose Our Rome Airport Transfer?',
    feature1Title: 'Meet & Greet', feature1Desc: 'Driver with name sign at FCO or CIA arrivals. 60 minutes free waiting.',
    feature2Title: 'Flight Monitoring', feature2Desc: 'We track both Fiumicino and Ciampino flights. No delay surcharges.',
    feature3Title: 'Comfortable Vehicles', feature3Desc: 'Mercedes, BMW. Clean, air-conditioned, less than 3 years old.',
    feature4Title: 'Fixed Prices', feature4Desc: 'Price confirmed at booking. No hidden fees, tolls included.',
    sedan: 'Premium Sedan', sedanDesc: '1-3 passengers, perfect for couples', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes E-Class or similar',
    minivan: 'Minivan', minivanDesc: 'Up to 6 passengers', minibus: 'Minibus', minibusDesc: 'Up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter flight details and Rome address. Instant price.',
    step2: 'Meet Your Driver', step2Desc: 'Driver greets you at arrivals with name sign.',
    step3: 'Enjoy Rome', step3Desc: 'Direct comfortable transfer to your destination.',
    popularRoutesTitle: 'Popular Rome Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'Fiumicino FCO → Rome City Center', price: 50 },
      { name: 'Fiumicino FCO → Vatican Area', price: 50 },
      { name: 'Ciampino CIA → Rome City Center', price: 40 },
      { name: 'Fiumicino FCO → Termini Station', price: 48 },
    ],
    bookingForm: 'Book Your Rome Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Rome Fiumicino Airport (FCO)',
    otherCitiesTitle: 'We also serve other European cities', otherCitiesBtn: 'View All Destinations',
    rating: '4.8/5 (2,100+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Rome - Fiumicino et Ciampino',
    subtitle: 'Service de chauffeur prive depuis les aeroports de Rome vers le centre-ville, le Vatican et tous les hotels',
    description: 'Reservez votre transfert aeroport Rome avec des chauffeurs professionnels. Rome possede deux aeroports : Leonardo da Vinci-Fiumicino (FCO), l\'aeroport international principal a 32 km du centre, et Ciampino (CIA), un plus petit aeroport a 15 km au sud. Nous offrons des transferts prives premium depuis les deux aeroports vers votre hotel, le Vatican, le Trastevere, le Colisee, la Gare Termini et toute adresse romaine. Prix fixes, suivi de vol.',
    description2: 'Rome, la Ville Eternelle, accueille des millions de visiteurs chaque annee. Naviguez comme un VIP avec notre service de transfert professionnel.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Rome ?',
    feature1Title: 'Accueil Personnalise', feature1Desc: 'Chauffeur avec pancarte aux arrivees FCO ou CIA. 60 min d\'attente gratuites.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Nous suivons les vols Fiumicino et Ciampino. Pas de supplement pour retard.',
    feature3Title: 'Vehicules Confortables', feature3Desc: 'Mercedes, BMW. Propres, climatises, moins de 3 ans.',
    feature4Title: 'Prix Fixes', feature4Desc: 'Prix confirme. Pas de frais caches, peages inclus.',
    sedan: 'Berline Premium', sedanDesc: '1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe E ou similaire',
    minivan: 'Monospace', minivanDesc: 'Jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez les details du vol et adresse a Rome.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Chauffeur aux arrivees avec pancarte.',
    step3: 'Profitez de Rome', step3Desc: 'Transfert direct et confortable.',
    popularRoutesTitle: 'Trajets Populaires Transfert Rome', fromLabel: 'A partir de',
    routes: [
      { name: 'Fiumicino FCO → Centre de Rome', price: 50 },
      { name: 'Fiumicino FCO → Quartier Vatican', price: 50 },
      { name: 'Ciampino CIA → Centre de Rome', price: 40 },
      { name: 'Fiumicino FCO → Gare Termini', price: 48 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Rome',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Rome Fiumicino (FCO)',
    otherCitiesTitle: 'Nous desservons aussi d\'autres villes', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.8/5 (2 100+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Рима - Фьюмичино и Чампино',
    subtitle: 'Частный водитель из аэропортов Рима в центр города, Ватикан, Колизей и все отели',
    description: 'Забронируйте трансфер из аэропорта Рима. Рим имеет два аэропорта: Леонардо да Винчи-Фьюмичино (FCO) - главный международный аэропорт в 32 км от центра, и Чампино (CIA) - небольшой аэропорт в 15 км. Мы обеспечиваем премиум-трансферы из обоих аэропортов.',
    description2: 'Рим - Вечный город, принимающий миллионы гостей ежегодно. Прибудьте как VIP с нашим сервисом.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Рима?',
    feature1Title: 'Встреча', feature1Desc: 'Водитель с табличкой в FCO или CIA. 60 минут бесплатно.',
    feature2Title: 'Отслеживание', feature2Desc: 'Мониторинг рейсов. Без доплаты за задержку.',
    feature3Title: 'Комфортные Авто', feature3Desc: 'Mercedes, BMW. Чистые, с кондиционером.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Цена при бронировании. Без скрытых платежей.',
    sedan: 'Премиум Седан', sedanDesc: '1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes E-Class',
    minivan: 'Минивэн', minivanDesc: 'До 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте', step1Desc: 'Введите данные рейса и адрес в Риме.',
    step2: 'Встреча', step2Desc: 'Водитель встречает вас.',
    step3: 'Наслаждайтесь Римом', step3Desc: 'Прямой комфортный трансфер.',
    popularRoutesTitle: 'Популярные Маршруты из Аэропорта Рима', fromLabel: 'От',
    routes: [
      { name: 'Фьюмичино FCO → Центр Рима', price: 50 },
      { name: 'Фьюмичино FCO → Ватикан', price: 50 },
      { name: 'Чампино CIA → Центр Рима', price: 40 },
      { name: 'Фьюмичино FCO → Вокзал Термини', price: 48 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Рима',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Рим Фьюмичино (FCO)',
    otherCitiesTitle: 'Другие города', otherCitiesBtn: 'Все Направления',
    rating: '4.8/5 (2 100+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 50, luxury: 75, minivan: 100, minibus: 160 };

const seoUrls = { en: '/rome-airport-transfer', fr: '/transfert-aeroport-rome', ru: '/taksi-iz-aeroporta-rim' };
const RomeTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default RomeTransfer;
