import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Rome Airport Transfer - Fiumicino & Ciampino',
    subtitle: 'Private driver service from Rome airports to city center, Vatican, Colosseum area and all Rome hotels',
    description: 'Rome, the Eternal City, has been drawing travelers for over two thousand years — from ancient pilgrims and Renaissance scholars to today\'s 15 million annual tourists who come to stand before the Colosseum, throw coins into the Trevi Fountain, and gaze at the Sistine Chapel ceiling. Rome is served by two airports: Leonardo da Vinci-Fiumicino (FCO), the main international hub 32 kilometres southwest, and Ciampino (CIA), the smaller budget-airline base 15 kilometres south. The Leonardo Express train from Fiumicino costs 14 euros but only goes to Termini Station — useless if your hotel is in Trastevere, near the Vatican, or in the historic Piazza Navona area. Our private Rome airport transfer delivers you from either airport directly to your exact address, in a comfortable air-conditioned vehicle, with a driver who speaks your language and will not take you on the infamous "scenic route" that adds 20 euros to a meter.',
    description2: 'Driving in Rome is an art form that locals have perfected and visitors should avoid. The ZTL (Zona Traffico Limitato) restricted zones in the historic centre trap unwary rental-car drivers with 100-euro fines, one-way streets change direction without notice, and parking near the Pantheon is practically mythological. Our professional drivers hold Italian VTC licences and navigate the city\'s organized chaos with practised calm. From Fiumicino, the standard route follows the Roma-Fiumicino motorway and enters the city via the Grande Raccordo Anulare ring road — about 40 to 60 minutes depending on traffic. From Ciampino, you can be in the centre in just 25 minutes via the Via Appia Nuova, the ancient Roman road still in daily use.',
    description3: 'Beyond the Colosseum and Vatican, Rome rewards exploration: the ochre-walled alleys of Trastevere where artisan gelato shops outnumber banks, the Sunday morning flea market at Porta Portese, the panoramic terrace of Pincian Hill overlooking Piazza del Popolo, and the Appian Way where you can walk on the same basalt stones that Roman legions marched 2,000 years ago. Many of our clients use their airport transfer as the start of a multi-day driver service — Fiumicino to hotel, then day trips to Pompeii and the Amalfi Coast (3 hours south), Orvieto and its underground caves (90 minutes north), or the vineyards of Frascati in the Castelli Romani (30 minutes). Book your Rome transfer and let the Eternal City reveal itself in comfort.',
    whyChoose: 'Why Choose Our Rome Airport Transfer?',
    feature1Title: 'Meet & Greet', feature1Desc: 'Driver with name sign at FCO or CIA arrivals. 60 minutes free waiting.',
    feature2Title: 'Flight Monitoring', feature2Desc: 'We track both Fiumicino and Ciampino flights. No delay surcharges.',
    feature3Title: 'Comfortable Vehicles', feature3Desc: 'Mercedes, BMW. Clean, air-conditioned, less than 3 years old.',
    feature4Title: 'Fixed Prices', feature4Desc: 'Price confirmed at booking. No hidden fees, tolls included.',
    sedan: 'Premium Sedan', sedanDesc: '1-3 passengers, perfect for couples', luxury: 'Luxury Sedan', luxuryDesc: 'Mercedes E-Class or similar',
    minivan: 'Minivan', minivanDesc: 'Up to 6 passengers', minibus: 'Minibus', minibusDesc: 'Up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter flight details and Rome address. Instant price.',
    step2: 'Meet Your Driver', step2Desc: 'Driver greets you at arrivals with name sign.',
    step3: 'Enjoy Rome', step3Desc: 'Direct comfortable transfer to your destination.',
    popularRoutesTitle: 'Popular Rome Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'Fiumicino FCO → Rome City Center', price: 50 },
      { name: 'Fiumicino FCO → Vatican Area', price: 50 },
      { name: 'Ciampino CIA → Rome City Center', price: 40 },
      { name: 'Fiumicino FCO → Termini Station', price: 48 },
    ],
    bookingForm: 'Book Your Rome Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Rome Fiumicino Airport (FCO)',
    otherCitiesTitle: 'We also serve other European cities', otherCitiesBtn: 'View All Destinations',
    rating: '4.8/5 (2,100+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Rome - Fiumicino et Ciampino',
    subtitle: 'Service de chauffeur prive depuis les aeroports de Rome vers le centre-ville, le Vatican et tous les hotels',
    description: 'Rome, la Ville Eternelle, attire les voyageurs depuis plus de deux millenaires. Ses 15 millions de visiteurs annuels viennent contempler le Colisee, jeter des pieces dans la fontaine de Trevi et lever les yeux vers le plafond de la Chapelle Sixtine. Rome est desservie par Fiumicino (FCO), a 32 km au sud-ouest, et Ciampino (CIA), base low-cost a 15 km. Le Leonardo Express ne va qu\'a Termini — inutile si votre hotel est au Trastevere, pres du Vatican ou sur la Piazza Navona. Notre transfert prive vous depose depuis chaque aeroport directement a votre adresse exacte, dans un vehicule climatise, avec un chauffeur qui ne vous fera pas le fameux "detour touristique" a 20 euros de plus.',
    description2: 'Conduire a Rome est un art que les locaux maitrisent et que les visiteurs devraient eviter. Les zones ZTL du centre historique piegent les loueurs avec des amendes de 100 euros. Nos chauffeurs VTC licencies naviguent dans le chaos organise avec un calme experimente. Depuis Fiumicino, 40-60 minutes par le Raccordo Anulare. Depuis Ciampino, 25 minutes par la Via Appia Nuova — la route romaine antique toujours en service. Au-dela du Colisee : les ruelles ocres du Trastevere, le marche de Porta Portese, la terrasse du Pincio, et des excursions vers Pompei (3h), Orvieto (90 min) ou les vignobles de Frascati (30 min).',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Rome ?',
    feature1Title: 'Accueil Personnalise', feature1Desc: 'Chauffeur avec pancarte aux arrivees FCO ou CIA. 60 min d\'attente gratuites.',
    feature2Title: 'Suivi des Vols', feature2Desc: 'Nous suivons les vols Fiumicino et Ciampino. Pas de supplement pour retard.',
    feature3Title: 'Vehicules Confortables', feature3Desc: 'Mercedes, BMW. Propres, climatises, moins de 3 ans.',
    feature4Title: 'Prix Fixes', feature4Desc: 'Prix confirme. Pas de frais caches, peages inclus.',
    sedan: 'Berline Premium', sedanDesc: '1-3 passagers', luxury: 'Berline de Luxe', luxuryDesc: 'Mercedes Classe E ou similaire',
    minivan: 'Monospace', minivanDesc: 'Jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez les details du vol et adresse a Rome.',
    step2: 'Rencontrez Votre Chauffeur', step2Desc: 'Chauffeur aux arrivees avec pancarte.',
    step3: 'Profitez de Rome', step3Desc: 'Transfert direct et confortable.',
    popularRoutesTitle: 'Trajets Populaires Transfert Rome', fromLabel: 'A partir de',
    routes: [
      { name: 'Fiumicino FCO → Centre de Rome', price: 50 },
      { name: 'Fiumicino FCO → Quartier Vatican', price: 50 },
      { name: 'Ciampino CIA → Centre de Rome', price: 40 },
      { name: 'Fiumicino FCO → Gare Termini', price: 48 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Rome',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport Rome Fiumicino (FCO)',
    otherCitiesTitle: 'Nous desservons aussi d\'autres villes', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.8/5 (2 100+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Рима - Фьюмичино и Чампино',
    subtitle: 'Частный водитель из аэропортов Рима в центр города, Ватикан, Колизей и все отели',
    description: 'Забронируйте трансфер из аэропорта Рима. Рим имеет два аэропорта: Леонардо да Винчи-Фьюмичино (FCO) - главный международный аэропорт в 32 км от центра, и Чампино (CIA) - небольшой аэропорт в 15 км. Мы обеспечиваем премиум-трансферы из обоих аэропортов.',
    description2: 'Рим, Вечный город, привлекает 15 млн туристов в год. Два аэропорта: Фьюмичино (FCO, 32 км) и Чампино (CIA, 15 км). Leonardo Express идёт только до Термини — бесполезно, если отель в Трастевере или у Ватикана. Наш частный трансфер доставляет от любого аэропорта прямо к вашему адресу. Водители VTC знают римский хаос: зоны ZTL, односторонние улицы, мифическую парковку у Пантеона. От Фьюмичино — 40-60 минут, от Чампино — 25 минут по Via Appia Nuova, древнеримской дороге, работающей и сегодня.',
    description3: 'Помимо Колизея и Ватикана, Рим вознаграждает исследователей: охряные переулки Трастевере с ремесленным джелато, воскресный рынок Порта-Портезе, панорамная терраса холма Пинчо и Аппиева дорога, где можно пройти по тем же базальтовым камням, что и римские легионы 2000 лет назад. Многие клиенты заказывают экскурсии: Помпеи и Амальфитанское побережье (3 часа), Орвието (90 мин), виноградники Фраскати (30 мин). Забронируйте трансфер из аэропорта Рима.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Рима?',
    feature1Title: 'Встреча', feature1Desc: 'Водитель с табличкой в FCO или CIA. 60 минут бесплатно.',
    feature2Title: 'Отслеживание', feature2Desc: 'Мониторинг рейсов. Без доплаты за задержку.',
    feature3Title: 'Комфортные Авто', feature3Desc: 'Mercedes, BMW. Чистые, с кондиционером.',
    feature4Title: 'Фиксированные Цены', feature4Desc: 'Цена при бронировании. Без скрытых платежей.',
    sedan: 'Премиум Седан', sedanDesc: '1-3 пассажира', luxury: 'Люкс Седан', luxuryDesc: 'Mercedes E-Class',
    minivan: 'Минивэн', minivanDesc: 'До 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте', step1Desc: 'Введите данные рейса и адрес в Риме.',
    step2: 'Встреча', step2Desc: 'Водитель встречает вас.',
    step3: 'Наслаждайтесь Римом', step3Desc: 'Прямой комфортный трансфер.',
    popularRoutesTitle: 'Популярные Маршруты из Аэропорта Рима', fromLabel: 'От',
    routes: [
      { name: 'Фьюмичино FCO → Центр Рима', price: 50 },
      { name: 'Фьюмичино FCO → Ватикан', price: 50 },
      { name: 'Чампино CIA → Центр Рима', price: 40 },
      { name: 'Фьюмичино FCO → Вокзал Термини', price: 48 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Рима',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Рим Фьюмичино (FCO)',
    otherCitiesTitle: 'Другие города', otherCitiesBtn: 'Все Направления',
    rating: '4.8/5 (2 100+ отзывов)',
  },
  hy: {
    title: 'Տրանսֆեր Ռոմի օդանավայանից',
    subtitle: 'Մասնավոր վարորդ FCO և CIA օդանավայաններից',
    description: 'Ռոմը՝ Հավերժական քաղաքը՝ 2000 տարվա ճանապարհորդներ է գրավում: Կոլիզեյ՝ Trevi շատրևան՝ Սիստինյան կապելլա: Երկու օդանավայան՝ Fiumicino (32 կմ) և Ciampino (15 կմ): ZTL գոտիները՝ միակողմանի փողոցները: Պոմպեյ (3 ժամ)՝ Orvieto (90 րոպե)՝ Frascati (30 րոպե): Trastevere-ի նեղ փողոցները՝ Porta Portese շուկան՝ Pincio տերասը:',
    description2: 'Ռոմին պարգևում է նրանց՝ ովքեր հանգստացած են գալիս:',
    whyChoose: 'Ինչու ընտրել մեր տրանսֆեր ռոմի օդանավայանից',
    feature1Title: 'Դիմավորում', feature1Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով: 60 րոպե անվճար սպասման ժամանակ:',
    feature2Title: 'Թռիչքի հետևում', feature2Desc: 'Իրական ժամանակում թռիչքի հետևում: Անվճար:',
    feature3Title: 'Պրեմիում մեքենաներ', feature3Desc: 'Mercedes E-Class, BMW 5: Մաքուր, կլիմատիզացիա:',
    feature4Title: 'Ֆիքս գներ', feature4Desc: 'Գինը հաստատված է ամրագրման ժամանակ: Թաքնված վճարներ չկան:',
    sedan: 'Պրեմիում սեդան', sedanDesc: 'Mercedes E-Class, 1-3 ուղևոր',
    luxury: 'Լյուքս սեդան', luxuryDesc: 'Mercedes S-Class կամ BMW 7',
    minivan: 'Մինիվեն', minivanDesc: 'Mercedes V-Class, մինչև 6 ուղևոր',
    minibus: 'Մինիբուս', minibusDesc: 'Մինչև 8 ուղևոր',
    passengers: 'Ուղևորներ', luggage: 'Ուղեբարան',
    bookNow: 'ԱՄՏԱԳՏՎԵԼ', allInclusive: 'Ամեն ինչ ներառված է',
    vehiclesTitle: 'Ընտրեք մեքենան',
    howItWorks: 'Ինչպես է աշխատում',
    step1: 'Ամրագրեք օնլայն', step1Desc: 'Մուտքագրեք ձեր տվյալները և հասցեն: Ակնթարթ գնի հաստատում:',
    step2: 'Հանդիպեք վարորդին', step2Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով:',
    step3: 'Հանգստացեք', step3Desc: 'Հարմարավետ ուղևորություն պրեմիում մեքենայում:',
    popularRoutesTitle: 'Սկսած', fromLabel: 'Սկսած',
    bookingForm: 'ԱՄՏԱԳՏՎԵԼ',
    pickupLabel: 'Վերցնում', dropoffLabel: 'Իջնում',
    dateLabel: 'Ամսաթիվ', timeLabel: 'Ժամ',
    defaultPickup: '',
    otherCitiesTitle: 'Սպասարկում ենք 120+ քաղաքներ Եվրոպայում',
    otherCitiesBtn: 'Բոլոր ուղղությունները',
    rating: '4.9/5',
  },
};

const vehiclesPrices = { sedan: 50, luxury: 75, minivan: 100, minibus: 160 };

const seoUrls = { en: '/rome-airport-transfer', fr: '/transfert-aeroport-rome', ru: '/taksi-iz-aeroporta-rim', hy: '/hrom-odanavakayani-transfer' };
const RomeTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default RomeTransfer;
