import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Yerevan Airport Transfer - Zvartnots International',
    subtitle: 'Professional driver from Zvartnots Airport to Yerevan city center, hotels and all Armenia destinations',
    description: 'Yerevan is one of the world\'s oldest continuously inhabited cities — 29 centuries of history etched into pink tufa stone buildings that glow amber at sunset, with the twin peaks of Mount Ararat floating on the horizon like a biblical painting. Zvartnots International Airport (EVN) sits just 12 kilometres west of the city centre, a 15-minute drive on a modern highway that passes the ruins of the 7th-century Zvartnots Cathedral (a UNESCO World Heritage Site visible from the road). Yet despite the short distance, arriving late at night to an unfamiliar airport in a country with limited English signage can be daunting. Our private Yerevan airport transfer ensures a seamless arrival: a professional driver — fluent in Armenian, Russian, French, and English — waits at the arrivals hall with a name board, helps with your luggage, and drives you directly to Republic Square, Northern Avenue, the Cascade Complex, or your hotel anywhere in the city.',
    description2: 'Armenia is experiencing a remarkable tourism renaissance. The country\'s ancient monasteries — Geghard carved into a clifftop, Tatev perched on a canyon edge reachable by the world\'s longest cable car, Khor Virap sitting in the shadow of Mount Ararat — draw architecture lovers and pilgrims alike. Yerevan itself buzzes with an energy that belies its ancient roots: the cafe-lined terraces of Northern Avenue, the contemporary art at the Cafesjian Center inside the Cascade, the craft beer bars of Saryan Street, and the brandy distilleries that have been producing Armenia\'s national drink since 1887.',
    description3: 'Many of our clients use the airport transfer as the first leg of a broader Armenian journey. From Yerevan, our drivers can take you to Lake Sevan (60 minutes east), the wine region of Areni with its 6,000-year-old winery (two hours south), the ski resort of Tsaghkadzor (50 minutes northeast), or the stunning gorge of Garni with its Greco-Roman temple (30 minutes). Armenia\'s compact size means you can visit three UNESCO sites in a single day trip and be back in Yerevan for dinner at a rooftop restaurant overlooking Ararat. With prices starting at a fraction of Western European rates, a private driver in Armenia is not a luxury — it is the smartest way to explore. Book your Yerevan transfer today.',
    whyChoose: 'Why Choose Our Yerevan Airport Transfer?',
    feature1Title: 'Meet & Greet at EVN', feature1Desc: 'Driver with name sign at Zvartnots arrivals. Free waiting time for flight delays.',
    feature2Title: 'Local Knowledge', feature2Desc: 'Drivers speak Armenian, Russian, English and French. Expert local knowledge.',
    feature3Title: 'Comfortable Cars', feature3Desc: 'Clean, air-conditioned vehicles. Mercedes, Toyota, or similar.',
    feature4Title: 'Best Prices', feature4Desc: 'Competitive fixed prices. No hidden fees.',
    sedan: 'Comfort Sedan', sedanDesc: '1-3 passengers', luxury: 'Business Sedan', luxuryDesc: 'Mercedes E-Class or similar',
    minivan: 'Minivan', minivanDesc: 'Up to 6 passengers', minibus: 'Minibus', minibusDesc: 'Up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter flight details and Yerevan address.',
    step2: 'Meet at Zvartnots', step2Desc: 'Driver greets you at arrivals with name sign.',
    step3: 'Welcome to Yerevan', step3Desc: 'Comfortable 15-20 minute ride to Yerevan center.',
    popularRoutesTitle: 'Popular Yerevan Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'Zvartnots EVN → Republic Square', price: 15 },
      { name: 'Zvartnots EVN → Northern Avenue', price: 15 },
      { name: 'Zvartnots EVN → Cascade Complex', price: 15 },
      { name: 'Zvartnots EVN → Lake Sevan', price: 55 },
    ],
    bookingForm: 'Book Your Yerevan Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Zvartnots International Airport (EVN)',
    otherCitiesTitle: 'We also serve European cities', otherCitiesBtn: 'View All Destinations',
    rating: '4.9/5 (2,300+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Erevan - Zvartnots International',
    subtitle: 'Chauffeur professionnel depuis l\'aeroport de Zvartnots vers Erevan centre, hotels et toute l\'Armenie',
    description: 'Reservez votre transfert aeroport Erevan avec des chauffeurs professionnels. L\'aeroport international de Zvartnots (EVN) est situe a 12 km a l\'ouest d\'Erevan, capitale de l\'Armenie. Transferts prives fiables depuis Zvartnots vers le centre d\'Erevan, la Place de la Republique, l\'Avenue du Nord, le Complexe Cascade et toutes les destinations en Armenie. Prix fixes abordables, suivi de vol, accueil avec pancarte.',
    description2: 'Erevan est l\'une des plus anciennes villes habitees au monde — 29 siecles d\'histoire graves dans la pierre de tuf rose qui rougeoie au coucher du soleil, avec les pics jumeaux du Mont Ararat flottant a l\'horizon. L\'aeroport Zvartnots (EVN) est a 12 km, 15 minutes de route passant devant les ruines de la cathedrale UNESCO de Zvartnots. L\'Armenie connait une renaissance touristique : monasteres millénaires de Geghard, Tatev et Khor Virap, les terrasses de l\'avenue du Nord, l\'art contemporain du Cascade, les bars de la rue Saryan et les distilleries de cognac depuis 1887. Nos chauffeurs parlent armenien, russe, francais et anglais. Depuis Erevan : lac Sevan (1h), vignobles d\'Areni (2h), ski a Tsaghkadzor (50 min), temple greco-romain de Garni (30 min). Reservez votre transfert Erevan.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Erevan ?',
    feature1Title: 'Accueil a EVN', feature1Desc: 'Chauffeur avec pancarte aux arrivees de Zvartnots. Attente gratuite.',
    feature2Title: 'Connaissance Locale', feature2Desc: 'Chauffeurs parlant armenien, russe, anglais et francais.',
    feature3Title: 'Vehicules Confortables', feature3Desc: 'Propres, climatises. Mercedes, Toyota ou similaire.',
    feature4Title: 'Meilleurs Prix', feature4Desc: 'Prix fixes competitifs. Pas de frais caches.',
    sedan: 'Berline Confort', sedanDesc: '1-3 passagers', luxury: 'Berline Business', luxuryDesc: 'Mercedes Classe E ou similaire',
    minivan: 'Monospace', minivanDesc: 'Jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez vol et adresse a Erevan.',
    step2: 'Rendez-vous a Zvartnots', step2Desc: 'Chauffeur aux arrivees avec pancarte.',
    step3: 'Bienvenue a Erevan', step3Desc: 'Trajet confortable de 15-20 minutes vers le centre.',
    popularRoutesTitle: 'Trajets Populaires Transfert Erevan', fromLabel: 'A partir de',
    routes: [
      { name: 'Zvartnots EVN → Place de la Republique', price: 15 },
      { name: 'Zvartnots EVN → Avenue du Nord', price: 15 },
      { name: 'Zvartnots EVN → Complexe Cascade', price: 15 },
      { name: 'Zvartnots EVN → Lac Sevan', price: 55 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Erevan',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport International Zvartnots (EVN)',
    otherCitiesTitle: 'Nous desservons aussi les villes europeennes', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.9/5 (2 300+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Еревана - Звартноц',
    subtitle: 'Профессиональный водитель из аэропорта Звартноц в центр Еревана, отели и все направления Армении',
    description: 'Забронируйте трансфер из аэропорта Еревана с профессиональными водителями. Международный аэропорт Звартноц (EVN) расположен в 12 км к западу от Еревана. Мы обеспечиваем надежные трансферы из Звартноц в центр Еревана, площадь Республики, Северный проспект, Каскад и все направления Армении. Доступные фиксированные цены.',
    description2: 'Ереван — один из древнейших городов мира: 29 веков истории в зданиях из розового туфа, алеющих на закате, с двуглавым Араратом на горизонте. Аэропорт Звартноц (EVN) в 12 км, 15 минут по современному шоссе мимо руин храма VII века (ЮНЕСКО). Армения переживает туристический ренессанс: скальный Гегард, Татев на краю каньона, Хор Вирап в тени Арарата. Сам Ереван бурлит энергией: террасы Северного проспекта, Каскад с современным искусством, бары улицы Сарян и коньячные заводы с 1887 года. Озеро Севан (1 ч), винодельни Арени (2 ч), горнолыжный Цахкадзор (50 мин), храм Гарни (30 мин). Частный водитель в Армении — не роскошь, а лучший способ путешествовать.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Еревана?',
    feature1Title: 'Встреча в EVN', feature1Desc: 'Водитель с табличкой в Звартноц. Бесплатное ожидание.',
    feature2Title: 'Местные Знания', feature2Desc: 'Водители говорят на армянском, русском, английском и французском.',
    feature3Title: 'Комфортные Авто', feature3Desc: 'Чистые, с кондиционером. Mercedes, Toyota.',
    feature4Title: 'Лучшие Цены', feature4Desc: 'Конкурентные фиксированные цены.',
    sedan: 'Комфорт Седан', sedanDesc: '1-3 пассажира', luxury: 'Бизнес Седан', luxuryDesc: 'Mercedes E-Class',
    minivan: 'Минивэн', minivanDesc: 'До 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте', step1Desc: 'Введите рейс и адрес в Ереване.',
    step2: 'Встреча в Звартноц', step2Desc: 'Водитель в зале прилета.',
    step3: 'Добро Пожаловать в Ереван', step3Desc: 'Комфортная поездка 15-20 минут.',
    popularRoutesTitle: 'Популярные Маршруты из Аэропорта Еревана', fromLabel: 'От',
    routes: [
      { name: 'Звартноц EVN → Площадь Республики', price: 15 },
      { name: 'Звартноц EVN → Северный Проспект', price: 15 },
      { name: 'Звартноц EVN → Каскад', price: 15 },
      { name: 'Звартноц EVN → Озеро Севан', price: 55 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Еревана',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Звартноц (EVN)',
    otherCitiesTitle: 'Другие города', otherCitiesBtn: 'Все Направления',
    rating: '4.9/5 (2 300+ отзывов)',
  },
  hy: {
    title: 'Տրանսֆեր Երևանի օդանավայանից',
    subtitle: 'Մասնավոր վարորդ Զվարթնոցից Երևան',
    description: 'Երևանը աշխարհի հնագույն անընդհատ բնակեցված քաղաքներից է — 29 դարի պատմություն: Զվարթնոց օդանավայանը 12 կմ է քաղաքի կենտրոնից: Արարատ լեռան հորիզոնին: Գեղարդ (ժայրի)՝ Տաթև (կանյոնի եզրին)՝ Խոր Վիրապ (Արարատի ստվերում): Սևան լիճ (1 ժամ)՝ Արենիի գինեգործարաններ (2 ժամ)՝ Ծաղկաձոր (50 րոպե)՝ Գառնի (30 րոպե): Հյուսի անելի ճանապարհ հայկական յուրահատկությամբ:',
    description2: 'Հայաստանի հյուրասիրությունը:',
    whyChoose: 'Ինչու ընտրել մեր տրանսֆեր երևանի օդանավայանից',
    feature1Title: 'Դիմավորում', feature1Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով: 60 րոպե անվճար սպասման ժամանակ:',
    feature2Title: 'Թռիչքի հետևում', feature2Desc: 'Իրական ժամանակում թռիչքի հետևում: Անվճար:',
    feature3Title: 'Պրեմիում մեքենաներ', feature3Desc: 'Mercedes E-Class, BMW 5: Մաքուր, կլիմատիզացիա:',
    feature4Title: 'Ֆիքս գներ', feature4Desc: 'Գինը հաստատված է ամրագրման ժամանակ: Թաքնված վճարներ չկան:',
    sedan: 'Պրեմիում սեդան', sedanDesc: 'Mercedes E-Class, 1-3 ուղևոր',
    luxury: 'Լյուքս սեդան', luxuryDesc: 'Mercedes S-Class կամ BMW 7',
    minivan: 'Մինիվեն', minivanDesc: 'Mercedes V-Class, մինչև 6 ուղևոր',
    minibus: 'Մինիբուս', minibusDesc: 'Մինչև 8 ուղևոր',
    passengers: 'Ուղևորներ', luggage: 'Ուղեբարան',
    bookNow: 'ԱՄՏԱԳՏՎԵԼ', allInclusive: 'Ամեն ինչ ներառված է',
    vehiclesTitle: 'Ընտրեք մեքենան',
    howItWorks: 'Ինչպես է աշխատում',
    step1: 'Ամրագրեք օնլայն', step1Desc: 'Մուտքագրեք ձեր տվյալները և հասցեն: Ակնթարթ գնի հաստատում:',
    step2: 'Հանդիպեք վարորդին', step2Desc: 'Վարորդը սպասում է ձեզ անունային ցուցանակով:',
    step3: 'Հանգստացեք', step3Desc: 'Հարմարավետ ուղևորություն պրեմիում մեքենայում:',
    popularRoutesTitle: 'Սկսած', fromLabel: 'Սկսած',
    bookingForm: 'ԱՄՏԱԳՏՎԵԼ',
    pickupLabel: 'Վերցնում', dropoffLabel: 'Իջնում',
    dateLabel: 'Ամսաթիվ', timeLabel: 'Ժամ',
    defaultPickup: '',
    otherCitiesTitle: 'Սպասարկում ենք 120+ քաղաքներ Եվրոպայում',
    otherCitiesBtn: 'Բոլոր ուղղությունները',
    rating: '4.9/5',
  },
};

const vehiclesPrices = { sedan: 15, luxury: 25, minivan: 35, minibus: 55 };

const seoUrls = { en: '/yerevan-airport-transfer', fr: '/transfert-aeroport-erevan', ru: '/taksi-iz-aeroporta-erevan', hy: '/erevan-odanavakayani-transfer' };
const YerevanTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} seoUrls={seoUrls} />;
export default YerevanTransfer;
