import React from 'react';
import CityTransferPage from '@/components/CityTransferPage';

const content = {
  en: {
    title: 'Yerevan Airport Transfer - Zvartnots International',
    subtitle: 'Professional driver from Zvartnots Airport to Yerevan city center, hotels and all Armenia destinations',
    description: 'Book your Yerevan airport transfer with professional drivers. Zvartnots International Airport (EVN) is located 12 km west of Yerevan, the capital of Armenia. We provide reliable private transfers from Zvartnots to Yerevan city center, Republic Square, Northern Avenue, Cascade Complex, and all destinations in Armenia. Affordable fixed prices, flight monitoring, meet and greet with name sign.',
    description2: 'Yerevan is one of the oldest continuously inhabited cities in the world, with a history spanning over 2,800 years. From the stunning views of Mount Ararat to the vibrant cafe culture, from ancient monasteries to modern art galleries, Armenia welcomes you. Our local drivers speak Russian, Armenian, English and French, ensuring a warm welcome from the moment you land.',
    whyChoose: 'Why Choose Our Yerevan Airport Transfer?',
    feature1Title: 'Meet & Greet at EVN', feature1Desc: 'Driver with name sign at Zvartnots arrivals. Free waiting time for flight delays.',
    feature2Title: 'Local Knowledge', feature2Desc: 'Drivers speak Armenian, Russian, English and French. Expert local knowledge.',
    feature3Title: 'Comfortable Cars', feature3Desc: 'Clean, air-conditioned vehicles. Mercedes, Toyota, or similar.',
    feature4Title: 'Best Prices', feature4Desc: 'Competitive fixed prices. No hidden fees.',
    sedan: 'Comfort Sedan', sedanDesc: '1-3 passengers', luxury: 'Business Sedan', luxuryDesc: 'Mercedes E-Class or similar',
    minivan: 'Minivan', minivanDesc: 'Up to 6 passengers', minibus: 'Minibus', minibusDesc: 'Up to 8 passengers',
    passengers: 'Passengers', luggage: 'Luggage', bookNow: 'BOOK NOW', allInclusive: 'All inclusive',
    vehiclesTitle: 'Choose Your Vehicle',
    howItWorks: 'How It Works', step1: 'Book Online', step1Desc: 'Enter flight details and Yerevan address.',
    step2: 'Meet at Zvartnots', step2Desc: 'Driver greets you at arrivals with name sign.',
    step3: 'Welcome to Yerevan', step3Desc: 'Comfortable 15-20 minute ride to Yerevan center.',
    popularRoutesTitle: 'Popular Yerevan Airport Transfer Routes', fromLabel: 'From',
    routes: [
      { name: 'Zvartnots EVN → Republic Square', price: 15 },
      { name: 'Zvartnots EVN → Northern Avenue', price: 15 },
      { name: 'Zvartnots EVN → Cascade Complex', price: 15 },
      { name: 'Zvartnots EVN → Lake Sevan', price: 55 },
    ],
    bookingForm: 'Book Your Yerevan Airport Transfer',
    pickupLabel: 'Pick up', dropoffLabel: 'Drop off', dateLabel: 'Date', timeLabel: 'Time',
    defaultPickup: 'Zvartnots International Airport (EVN)',
    otherCitiesTitle: 'We also serve European cities', otherCitiesBtn: 'View All Destinations',
    rating: '4.9/5 (2,300+ reviews)',
  },
  fr: {
    title: 'Transfert Aeroport Erevan - Zvartnots International',
    subtitle: 'Chauffeur professionnel depuis l\'aeroport de Zvartnots vers Erevan centre, hotels et toute l\'Armenie',
    description: 'Reservez votre transfert aeroport Erevan avec des chauffeurs professionnels. L\'aeroport international de Zvartnots (EVN) est situe a 12 km a l\'ouest d\'Erevan, capitale de l\'Armenie. Transferts prives fiables depuis Zvartnots vers le centre d\'Erevan, la Place de la Republique, l\'Avenue du Nord, le Complexe Cascade et toutes les destinations en Armenie. Prix fixes abordables, suivi de vol, accueil avec pancarte.',
    description2: 'Erevan est l\'une des plus anciennes villes continuellement habitees au monde, avec une histoire de plus de 2 800 ans. Du Mont Ararat a la culture des cafes, nos chauffeurs locaux parlent russe, armenien, anglais et francais.',
    whyChoose: 'Pourquoi Choisir Notre Transfert Aeroport Erevan ?',
    feature1Title: 'Accueil a EVN', feature1Desc: 'Chauffeur avec pancarte aux arrivees de Zvartnots. Attente gratuite.',
    feature2Title: 'Connaissance Locale', feature2Desc: 'Chauffeurs parlant armenien, russe, anglais et francais.',
    feature3Title: 'Vehicules Confortables', feature3Desc: 'Propres, climatises. Mercedes, Toyota ou similaire.',
    feature4Title: 'Meilleurs Prix', feature4Desc: 'Prix fixes competitifs. Pas de frais caches.',
    sedan: 'Berline Confort', sedanDesc: '1-3 passagers', luxury: 'Berline Business', luxuryDesc: 'Mercedes Classe E ou similaire',
    minivan: 'Monospace', minivanDesc: 'Jusqu\'a 6 passagers', minibus: 'Minibus', minibusDesc: 'Jusqu\'a 8 passagers',
    passengers: 'Passagers', luggage: 'Bagages', bookNow: 'RESERVER', allInclusive: 'Tout compris',
    vehiclesTitle: 'Choisissez Votre Vehicule',
    howItWorks: 'Comment Ca Marche', step1: 'Reservez en Ligne', step1Desc: 'Entrez vol et adresse a Erevan.',
    step2: 'Rendez-vous a Zvartnots', step2Desc: 'Chauffeur aux arrivees avec pancarte.',
    step3: 'Bienvenue a Erevan', step3Desc: 'Trajet confortable de 15-20 minutes vers le centre.',
    popularRoutesTitle: 'Trajets Populaires Transfert Erevan', fromLabel: 'A partir de',
    routes: [
      { name: 'Zvartnots EVN → Place de la Republique', price: 15 },
      { name: 'Zvartnots EVN → Avenue du Nord', price: 15 },
      { name: 'Zvartnots EVN → Complexe Cascade', price: 15 },
      { name: 'Zvartnots EVN → Lac Sevan', price: 55 },
    ],
    bookingForm: 'Reservez Votre Transfert Aeroport Erevan',
    pickupLabel: 'Depart', dropoffLabel: 'Destination', dateLabel: 'Date', timeLabel: 'Heure',
    defaultPickup: 'Aeroport International Zvartnots (EVN)',
    otherCitiesTitle: 'Nous desservons aussi les villes europeennes', otherCitiesBtn: 'Voir Toutes les Destinations',
    rating: '4.9/5 (2 300+ avis)',
  },
  ru: {
    title: 'Трансфер из Аэропорта Еревана - Звартноц',
    subtitle: 'Профессиональный водитель из аэропорта Звартноц в центр Еревана, отели и все направления Армении',
    description: 'Забронируйте трансфер из аэропорта Еревана с профессиональными водителями. Международный аэропорт Звартноц (EVN) расположен в 12 км к западу от Еревана. Мы обеспечиваем надежные трансферы из Звартноц в центр Еревана, площадь Республики, Северный проспект, Каскад и все направления Армении. Доступные фиксированные цены.',
    description2: 'Ереван - один из древнейших непрерывно населенных городов мира с историей более 2 800 лет. Наши водители говорят на русском, армянском, английском и французском.',
    whyChoose: 'Почему Выбрать Наш Трансфер из Аэропорта Еревана?',
    feature1Title: 'Встреча в EVN', feature1Desc: 'Водитель с табличкой в Звартноц. Бесплатное ожидание.',
    feature2Title: 'Местные Знания', feature2Desc: 'Водители говорят на армянском, русском, английском и французском.',
    feature3Title: 'Комфортные Авто', feature3Desc: 'Чистые, с кондиционером. Mercedes, Toyota.',
    feature4Title: 'Лучшие Цены', feature4Desc: 'Конкурентные фиксированные цены.',
    sedan: 'Комфорт Седан', sedanDesc: '1-3 пассажира', luxury: 'Бизнес Седан', luxuryDesc: 'Mercedes E-Class',
    minivan: 'Минивэн', minivanDesc: 'До 6 пассажиров', minibus: 'Микроавтобус', minibusDesc: 'До 8 пассажиров',
    passengers: 'Пассажиры', luggage: 'Багаж', bookNow: 'ЗАБРОНИРОВАТЬ', allInclusive: 'Все включено',
    vehiclesTitle: 'Выберите Автомобиль',
    howItWorks: 'Как Это Работает', step1: 'Бронируйте', step1Desc: 'Введите рейс и адрес в Ереване.',
    step2: 'Встреча в Звартноц', step2Desc: 'Водитель в зале прилета.',
    step3: 'Добро Пожаловать в Ереван', step3Desc: 'Комфортная поездка 15-20 минут.',
    popularRoutesTitle: 'Популярные Маршруты из Аэропорта Еревана', fromLabel: 'От',
    routes: [
      { name: 'Звартноц EVN → Площадь Республики', price: 15 },
      { name: 'Звартноц EVN → Северный Проспект', price: 15 },
      { name: 'Звартноц EVN → Каскад', price: 15 },
      { name: 'Звартноц EVN → Озеро Севан', price: 55 },
    ],
    bookingForm: 'Забронируйте Трансфер из Аэропорта Еревана',
    pickupLabel: 'Откуда', dropoffLabel: 'Куда', dateLabel: 'Дата', timeLabel: 'Время',
    defaultPickup: 'Аэропорт Звартноц (EVN)',
    otherCitiesTitle: 'Другие города', otherCitiesBtn: 'Все Направления',
    rating: '4.9/5 (2 300+ отзывов)',
  },
};

const vehiclesPrices = { sedan: 15, luxury: 25, minivan: 35, minibus: 55 };

const YerevanTransfer = () => <CityTransferPage content={content} vehicles={vehiclesPrices} />;
export default YerevanTransfer;
